CREATE TABLE IF NOT EXISTS image (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename VARCHAR(255),
  url VARCHAR(255),
  classification VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS image_entity_context (
  image_entity_id BIGINT NOT NULL,
  context VARCHAR(255),
  CONSTRAINT fk_image_entity_context_image FOREIGN KEY (image_entity_id) REFERENCES image(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_image_entity_context_image_entity_id ON image_entity_context (image_entity_id);