-- pos-image: Flyway baseline (flattened 2026-09-09 from the previous migration history) with the
-- ADR-0062 tenancy schema folded in. Generated by scripts/db/tenancy/flatten.py from a pg_dump of a
-- database migrated with the retired scripts; the tenancy additions are mechanical and are listed in
-- docs/TENANCY_SCHEMA.md. Global (unscoped) tables: src/main/resources/db/tenancy-global-tables.txt.
--
-- Tenant context: app_current_tenant() reads the session setting app.current_tenant, which the
-- TenantAwareDataSource (pos-tenancy-common, plan WS1) binds per checkout. Until then the owner role
-- carries a transitional default (postgres/init-tenancy.sh) and tests set it per connection.
-- With nothing bound: NULL -> every scoped table reads as empty and refuses inserts (fail closed).

-- Functions are emitted before the tables they reference (pg_dump order); do not validate bodies.
SET check_function_bodies = false;

CREATE OR REPLACE FUNCTION public.app_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$ SELECT NULLIF(current_setting('app.current_tenant', true), '')::uuid $$;

CREATE TABLE public.image (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id bigint NOT NULL,
    filename character varying(255),
    url character varying(255),
    classification character varying(255),
    content_hash character varying(64),
    content_type character varying(255),
    byte_size bigint,
    source_uri character varying(2000),
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

CREATE TABLE public.image_content (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    content_hash character varying(64) NOT NULL,
    content_type character varying(255) NOT NULL,
    byte_size bigint NOT NULL,
    content bytea NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT ck_image_content_size CHECK ((byte_size > 0))
);

CREATE TABLE public.image_entity_context (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    image_entity_id bigint NOT NULL,
    context character varying(255)
);

ALTER TABLE public.image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Tenant-led, unlike every other primary key in these baselines, and deliberately so.
-- content_hash is a business key derived from the bytes rather than a UUID v7 surrogate, so two
-- tenants storing the same picture derive it identically. Primary and unique constraints are
-- enforced across every row of a table whatever row-level security hides, so keying on the hash
-- alone made the second tenant's insert collide with a row it could not see; the collision was
-- swallowed as a concurrent store and left that tenant's image pointing at bytes it can never read.
-- See docs/TENANCY_SCHEMA.md, "Business-key primary keys". A re-flatten preserves this shape
-- through scripts/db/tenancy/flatten.py's TENANT_LED_PK set. The image_content_tenant_key side
-- constraint the generator normally adds beside a primary key is absent on purpose: this key
-- already covers exactly those columns, and a second identical index on a table holding image
-- bytes would be paid for on every write.
ALTER TABLE ONLY public.image_content
    ADD CONSTRAINT image_content_pkey PRIMARY KEY (tenant_id, content_hash);

ALTER TABLE ONLY public.image
    ADD CONSTRAINT image_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.image
    ADD CONSTRAINT image_tenant_key UNIQUE (tenant_id, id);

CREATE INDEX idx_image_entity_context_image_entity_id ON public.image_entity_context USING btree (image_entity_id);

CREATE INDEX ix_image_content_hash ON public.image USING btree (content_hash);

CREATE INDEX ix_image_source_uri ON public.image USING btree (source_uri);

ALTER TABLE ONLY public.image_entity_context
    ADD CONSTRAINT fk_image_entity_context_image FOREIGN KEY (tenant_id, image_entity_id) REFERENCES public.image(tenant_id, id) ON DELETE CASCADE;

CREATE INDEX image_tenant_idx ON public.image USING btree (tenant_id);

CREATE INDEX image_content_tenant_idx ON public.image_content USING btree (tenant_id);

CREATE INDEX image_entity_context_tenant_idx ON public.image_entity_context USING btree (tenant_id);

ALTER TABLE public.image ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.image FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.image
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.image_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.image_content FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.image_content
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.image_entity_context ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.image_entity_context FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.image_entity_context
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());
