openapi: 3.1.0
info:
  contact:
    email: louis.burroughs@gmail.com
    name: Durion Support Services
  description: API documentation for the Inquiry service
  title: Positivity Inquiry API
  version: v1
servers:
- description: Generated server url
  url: http://localhost:8086
paths: {}
components:
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
