-- pos-mcp-server: Flyway baseline (flattened 2026-09-09 from the previous migration history) with the
-- ADR-0062 tenancy schema folded in. Generated by scripts/db/tenancy/flatten.py from a pg_dump of a
-- database migrated with the retired scripts; the tenancy additions are mechanical and are listed in
-- docs/TENANCY_SCHEMA.md. Global (unscoped) tables: src/main/resources/db/tenancy-global-tables.txt.
--
-- Tenant context: app_current_tenant() reads the session setting app.current_tenant, which the
-- TenantAwareDataSource (pos-tenancy-common, plan WS1) binds per checkout. Until then the owner role
-- carries a transitional default (postgres/init-tenancy.sh) and tests set it per connection.
-- With nothing bound: NULL -> every scoped table reads as empty and refuses inserts (fail closed).

-- Functions are emitted before the tables they reference (pg_dump order); do not validate bodies.
SET check_function_bodies = false;

CREATE OR REPLACE FUNCTION public.app_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$ SELECT NULLIF(current_setting('app.current_tenant', true), '')::uuid $$;

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

CREATE TABLE public.llm_api_config (
    id uuid NOT NULL,
    api_id character varying(120) NOT NULL,
    model character varying(120) NOT NULL,
    base_url character varying(255) NOT NULL,
    api_key character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.llm_api_config_headers (
    llm_api_config_id uuid NOT NULL,
    headers_key character varying(255) NOT NULL,
    header_value character varying(255)
);

CREATE TABLE public.mcp_document_embedding (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    content text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp without time zone DEFAULT now(),
    content_tsv tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, COALESCE(content, ''::text))) STORED,
    embedding public.vector(1024)
);

CREATE TABLE public.mcp_document_ingestion_job (
    id uuid NOT NULL,
    document_id character varying(255) NOT NULL,
    status character varying(32) NOT NULL,
    content text NOT NULL,
    metadata_json text NOT NULL,
    chunk_count integer,
    error_message text,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.mcp_eval_turn_trace (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    turn_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    trace_payload jsonb NOT NULL
);

CREATE TABLE public.mcp_rag_preload_record (
    id uuid NOT NULL,
    document_id character varying(120) NOT NULL,
    content_hash character varying(64) NOT NULL,
    source_path character varying(255) NOT NULL,
    status character varying(20) NOT NULL,
    loaded_at timestamp with time zone NOT NULL,
    job_id uuid,
    rag_scope character varying(80) NOT NULL
);

CREATE TABLE public.mcp_screen_registry (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    screen_key character varying(120) NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    domain character varying(80) NOT NULL,
    url_template text NOT NULL,
    required_perm character varying(120),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    embedding public.vector(1024)
);

CREATE TABLE public.mcp_simple_chat_rule (
    id uuid NOT NULL,
    rule_type character varying(64) NOT NULL,
    phrase character varying(255) NOT NULL,
    language_code character varying(16) NOT NULL,
    priority integer NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.mcp_tool (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(100) NOT NULL,
    display_name character varying(150) NOT NULL,
    description text NOT NULL,
    domain character varying(80) NOT NULL,
    priority double precision DEFAULT 1.0 NOT NULL,
    cost_level character varying(20) DEFAULT 'low'::character varying NOT NULL,
    avg_latency_ms integer DEFAULT 200 NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    handler_bean character varying(150),
    source character varying(20) DEFAULT 'facade'::character varying NOT NULL,
    http_method character varying(10),
    path_template character varying(500),
    operation_id character varying(150),
    http_path character varying(512),
    service_id character varying(128),
    input_schema text,
    embedding public.vector(1024)
);

CREATE TABLE public.mcp_tool_invocation_log (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tool_id uuid,
    user_id character varying(100),
    session_id character varying(100),
    intent character varying(200),
    workflow_state character varying(100),
    semantic_rank integer,
    final_score numeric(8,4),
    selected boolean DEFAULT false NOT NULL,
    success boolean DEFAULT false NOT NULL,
    fallback_invoked boolean DEFAULT false NOT NULL,
    execution_time_ms integer,
    error_type character varying(200),
    created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE public.mcp_tool_permission (
    tool_id uuid NOT NULL,
    permission_code character varying(150) NOT NULL,
    permission_group text NOT NULL
);

CREATE TABLE public.mcp_tool_prerequisite (
    tool_name character varying(150) NOT NULL,
    required_param character varying(120) NOT NULL,
    producing_tool character varying(150) NOT NULL,
    producing_field character varying(120) NOT NULL
);

-- ADR-0062 plan WS6: per-tenant tool-priority overlay. mcp_tool.priority stays the global row (the
-- catalog is a global, code-first table); a tenant's overlay row, tuned from that tenant's own
-- mcp_tool_invocation_log, wins for that tool and the global row serves every tool without one.
-- The primary key leads with tenant_id, so no separate tenant index is needed.
CREATE TABLE public.mcp_tool_priority (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    tool_id uuid NOT NULL,
    priority double precision NOT NULL,
    avg_latency_ms integer NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.mcp_tool_workflow (
    tool_id uuid NOT NULL,
    workflow_state_id uuid NOT NULL
);

CREATE TABLE public.mcp_workflow_state (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(80) NOT NULL
);

CREATE TABLE public.nlti_audit_event (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    correlation_id uuid NOT NULL,
    session_id uuid,
    request_id uuid,
    event_type character varying(255) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    actor_subject_id character varying(255),
    payload_ref character varying(255),
    payload_hash character varying(255),
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.nlti_intent (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    request_id uuid,
    session_id uuid NOT NULL,
    correlation_id uuid NOT NULL,
    intent_type character varying(255),
    status character varying(255),
    risk_level character varying(255),
    slots_json text,
    clarification_questions_json text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.nlti_request (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    correlation_id uuid NOT NULL,
    session_id uuid NOT NULL,
    status character varying(255) NOT NULL,
    prompt_hash character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.nlti_session (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    subject_id character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    workflow_state character varying(32) DEFAULT 'IDLE'::character varying NOT NULL
);

CREATE TABLE public.nlti_write_plan (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    request_id uuid NOT NULL,
    session_id uuid NOT NULL,
    idempotency_key character varying(128) NOT NULL,
    target_tool character varying(255) NOT NULL,
    args_json text NOT NULL,
    arg_provenance_json text NOT NULL,
    risk_level character varying(16) NOT NULL,
    source_entity_versions_json text,
    summary_text text NOT NULL,
    status character varying(32) DEFAULT 'PENDING_CONFIRMATION'::character varying NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    executed_at timestamp with time zone,
    execution_result text
);

CREATE TABLE public.system_prompt (
    id uuid NOT NULL,
    name character varying(120) NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

ALTER TABLE ONLY public.llm_api_config
    ADD CONSTRAINT llm_api_config_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mcp_document_embedding
    ADD CONSTRAINT mcp_document_embedding_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mcp_document_ingestion_job
    ADD CONSTRAINT mcp_document_ingestion_job_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mcp_eval_turn_trace
    ADD CONSTRAINT mcp_eval_turn_trace_pkey PRIMARY KEY (turn_id);

ALTER TABLE ONLY public.mcp_eval_turn_trace
    ADD CONSTRAINT mcp_eval_turn_trace_tenant_key UNIQUE (tenant_id, turn_id);

ALTER TABLE ONLY public.mcp_screen_registry
    ADD CONSTRAINT mcp_screen_registry_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mcp_screen_registry
    ADD CONSTRAINT mcp_screen_registry_screen_key_key UNIQUE (screen_key);

ALTER TABLE ONLY public.mcp_simple_chat_rule
    ADD CONSTRAINT mcp_simple_chat_rule_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mcp_tool_invocation_log
    ADD CONSTRAINT mcp_tool_invocation_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mcp_tool_invocation_log
    ADD CONSTRAINT mcp_tool_invocation_log_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.mcp_tool_permission
    ADD CONSTRAINT mcp_tool_permission_pkey PRIMARY KEY (tool_id, permission_group, permission_code);

ALTER TABLE ONLY public.mcp_tool
    ADD CONSTRAINT mcp_tool_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mcp_tool_prerequisite
    ADD CONSTRAINT mcp_tool_prerequisite_pkey PRIMARY KEY (tool_name, required_param);

ALTER TABLE ONLY public.mcp_tool_priority
    ADD CONSTRAINT mcp_tool_priority_pkey PRIMARY KEY (tenant_id, tool_id);

ALTER TABLE ONLY public.mcp_tool_workflow
    ADD CONSTRAINT mcp_tool_workflow_pkey PRIMARY KEY (tool_id, workflow_state_id);

ALTER TABLE ONLY public.mcp_workflow_state
    ADD CONSTRAINT mcp_workflow_state_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.nlti_audit_event
    ADD CONSTRAINT nlti_audit_event_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.nlti_audit_event
    ADD CONSTRAINT nlti_audit_event_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.nlti_intent
    ADD CONSTRAINT nlti_intent_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.nlti_intent
    ADD CONSTRAINT nlti_intent_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.nlti_request
    ADD CONSTRAINT nlti_request_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.nlti_request
    ADD CONSTRAINT nlti_request_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.nlti_session
    ADD CONSTRAINT nlti_session_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.nlti_session
    ADD CONSTRAINT nlti_session_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.nlti_write_plan
    ADD CONSTRAINT nlti_write_plan_idempotency_key_key UNIQUE (tenant_id, idempotency_key);

ALTER TABLE ONLY public.nlti_write_plan
    ADD CONSTRAINT nlti_write_plan_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.nlti_write_plan
    ADD CONSTRAINT nlti_write_plan_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.mcp_rag_preload_record
    ADD CONSTRAINT pk_rag_preload_record PRIMARY KEY (id);

ALTER TABLE ONLY public.system_prompt
    ADD CONSTRAINT system_prompt_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.llm_api_config
    ADD CONSTRAINT uk_llm_api_config_api_id UNIQUE (api_id);

ALTER TABLE ONLY public.mcp_simple_chat_rule
    ADD CONSTRAINT uk_mcp_simple_chat_rule_type_phrase UNIQUE (rule_type, phrase);

ALTER TABLE ONLY public.mcp_tool
    ADD CONSTRAINT uk_mcp_tool_name UNIQUE (name);

ALTER TABLE ONLY public.mcp_workflow_state
    ADD CONSTRAINT uk_mcp_workflow_state_name UNIQUE (name);

ALTER TABLE ONLY public.system_prompt
    ADD CONSTRAINT uk_system_prompt_name UNIQUE (name);

CREATE INDEX idx_llm_api_config_headers_config_id ON public.llm_api_config_headers USING btree (llm_api_config_id);

CREATE INDEX idx_mcp_document_ingestion_job_created_at ON public.mcp_document_ingestion_job USING btree (created_at);

CREATE INDEX idx_mcp_document_ingestion_job_document_id ON public.mcp_document_ingestion_job USING btree (document_id);

CREATE INDEX idx_mcp_document_ingestion_job_status ON public.mcp_document_ingestion_job USING btree (status);

CREATE INDEX idx_mcp_eval_turn_trace_expires_at ON public.mcp_eval_turn_trace USING btree (expires_at);

CREATE INDEX idx_mcp_screen_registry_domain ON public.mcp_screen_registry USING btree (domain);

CREATE INDEX idx_mcp_simple_chat_rule_enabled_priority ON public.mcp_simple_chat_rule USING btree (enabled, priority);

CREATE INDEX idx_mcp_tool_embedding ON public.mcp_tool USING hnsw (embedding public.vector_cosine_ops);

CREATE INDEX idx_mcp_tool_invocation_log_created_at ON public.mcp_tool_invocation_log USING btree (created_at);

CREATE INDEX idx_mcp_tool_invocation_log_tool_id ON public.mcp_tool_invocation_log USING btree (tool_id);

CREATE INDEX idx_mcp_tool_permission_code ON public.mcp_tool_permission USING btree (permission_code);

CREATE INDEX idx_mcp_tool_workflow_tool_id ON public.mcp_tool_workflow USING btree (tool_id);

CREATE INDEX idx_nlti_audit_event_correlation_id ON public.nlti_audit_event USING btree (correlation_id);

CREATE INDEX idx_nlti_intent_request_id ON public.nlti_intent USING btree (request_id);

CREATE INDEX idx_nlti_intent_session_id ON public.nlti_intent USING btree (session_id);

CREATE INDEX idx_nlti_request_session_id ON public.nlti_request USING btree (session_id);

CREATE INDEX idx_nlti_write_plan_session_status ON public.nlti_write_plan USING btree (session_id, status);

CREATE INDEX idx_rag_preload_document_id ON public.mcp_rag_preload_record USING btree (document_id, rag_scope, status, loaded_at DESC);

CREATE INDEX mcp_doc_content_tsv_idx ON public.mcp_document_embedding USING gin (content_tsv);

CREATE INDEX mcp_doc_embedding_idx ON public.mcp_document_embedding USING hnsw (embedding public.vector_cosine_ops);

CREATE UNIQUE INDEX uq_nlti_write_plan_one_pending ON public.nlti_write_plan USING btree (tenant_id, session_id) WHERE ((status)::text = 'PENDING_CONFIRMATION'::text);

ALTER TABLE ONLY public.llm_api_config_headers
    ADD CONSTRAINT fk_llm_api_config_headers_config FOREIGN KEY (llm_api_config_id) REFERENCES public.llm_api_config(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.mcp_tool_invocation_log
    ADD CONSTRAINT mcp_tool_invocation_log_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.mcp_tool(id);

ALTER TABLE ONLY public.mcp_tool_permission
    ADD CONSTRAINT mcp_tool_permission_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.mcp_tool(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.mcp_tool_priority
    ADD CONSTRAINT mcp_tool_priority_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.mcp_tool(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.mcp_tool_workflow
    ADD CONSTRAINT mcp_tool_workflow_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.mcp_tool(id);

ALTER TABLE ONLY public.mcp_tool_workflow
    ADD CONSTRAINT mcp_tool_workflow_workflow_state_id_fkey FOREIGN KEY (workflow_state_id) REFERENCES public.mcp_workflow_state(id);

CREATE INDEX mcp_eval_turn_trace_tenant_idx ON public.mcp_eval_turn_trace USING btree (tenant_id);

CREATE INDEX mcp_tool_invocation_log_tenant_idx ON public.mcp_tool_invocation_log USING btree (tenant_id);

CREATE INDEX nlti_audit_event_tenant_idx ON public.nlti_audit_event USING btree (tenant_id);

CREATE INDEX nlti_intent_tenant_idx ON public.nlti_intent USING btree (tenant_id);

CREATE INDEX nlti_request_tenant_idx ON public.nlti_request USING btree (tenant_id);

CREATE INDEX nlti_session_tenant_idx ON public.nlti_session USING btree (tenant_id);

ALTER TABLE public.mcp_eval_turn_trace ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mcp_eval_turn_trace FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.mcp_eval_turn_trace
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.mcp_tool_invocation_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mcp_tool_invocation_log FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.mcp_tool_invocation_log
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.mcp_tool_priority ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mcp_tool_priority FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.mcp_tool_priority
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.nlti_audit_event ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nlti_audit_event FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.nlti_audit_event
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.nlti_intent ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nlti_intent FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.nlti_intent
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.nlti_request ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nlti_request FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.nlti_request
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.nlti_session ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nlti_session FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.nlti_session
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.nlti_write_plan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nlti_write_plan FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.nlti_write_plan
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());
