-- pos-people: Flyway baseline (flattened 2026-09-09 from the previous migration history) with the
-- ADR-0062 tenancy schema folded in. Generated by scripts/db/tenancy/flatten.py from a pg_dump of a
-- database migrated with the retired scripts; the tenancy additions are mechanical and are listed in
-- docs/TENANCY_SCHEMA.md. Global (unscoped) tables: src/main/resources/db/tenancy-global-tables.txt.
--
-- Tenant context: app_current_tenant() reads the session setting app.current_tenant, which the
-- TenantAwareDataSource (pos-tenancy-common, plan WS1) binds per checkout. Until then the owner role
-- carries a transitional default (postgres/init-tenancy.sh) and tests set it per connection.
-- With nothing bound: NULL -> every scoped table reads as empty and refuses inserts (fail closed).

-- Functions are emitted before the tables they reference (pg_dump order); do not validate bodies.
SET check_function_bodies = false;

CREATE OR REPLACE FUNCTION public.app_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$ SELECT NULLIF(current_setting('app.current_tenant', true), '')::uuid $$;

CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public;

CREATE TABLE public.employee (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    person_id uuid NOT NULL,
    employee_number character varying(255),
    status character varying(255),
    hire_date date,
    termination_date date,
    status_effective_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    CONSTRAINT employee_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'ON_LEAVE'::character varying, 'SUSPENDED'::character varying, 'TERMINATED'::character varying, 'DISABLED'::character varying])::text[])))
);

CREATE TABLE public.employee_location_assignment (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    employee_id uuid NOT NULL,
    location_id uuid NOT NULL,
    role character varying(255) NOT NULL,
    is_primary boolean NOT NULL,
    effective_from date NOT NULL,
    effective_to date,
    status character varying(255) NOT NULL,
    created_by character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    CONSTRAINT employee_location_assignment_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'ENDED'::character varying])::text[])))
);

CREATE TABLE public.employee_offboarding_retry_queue (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    employee_id uuid NOT NULL,
    assignment_policy character varying(255) NOT NULL,
    disable_reason character varying(255),
    actor_id character varying(255) NOT NULL,
    failure_reason character varying(255) NOT NULL,
    attempts integer NOT NULL,
    next_attempt_at timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    CONSTRAINT employee_offboarding_retry_queue_assignment_policy_check CHECK (((assignment_policy)::text = ANY ((ARRAY['IMMEDIATE'::character varying, 'GRACE_PERIOD'::character varying])::text[])))
);

CREATE TABLE public.event_outbox (
    id uuid NOT NULL,
    topic character varying(255) NOT NULL,
    record_key character varying(255) NOT NULL,
    payload text NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    published_at timestamp(6) with time zone,
    attempts integer DEFAULT 0 NOT NULL,
    last_error text
);

CREATE TABLE public.ext_location (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    location_id uuid NOT NULL,
    name character varying(255),
    status character varying(64),
    active boolean DEFAULT false NOT NULL,
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    financial_ancestor_ids text DEFAULT ''::text NOT NULL,
    other_ancestor_ids text DEFAULT ''::text NOT NULL
);

CREATE TABLE public.ext_location_parent (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    child_id uuid NOT NULL,
    parent_type character varying(64) NOT NULL,
    parent_id uuid NOT NULL
);

CREATE TABLE public.ext_people_contact_person (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    person_id uuid NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    preferred_name character varying(255),
    primary_email character varying(255),
    secondary_email character varying(255),
    primary_phone character varying(255),
    secondary_phone character varying(255),
    person_created_at timestamp(6) with time zone,
    person_updated_at timestamp(6) with time zone,
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.ext_people_contact_user_link (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    link_id uuid NOT NULL,
    person_id uuid NOT NULL,
    username character varying(255) NOT NULL,
    status character varying(20) NOT NULL,
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.ext_workorder_job_time (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    labor_entry_id uuid NOT NULL,
    work_order_id uuid NOT NULL,
    technician_id uuid NOT NULL,
    location_id uuid,
    end_at_utc timestamp(6) with time zone NOT NULL,
    minutes integer NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.processed_events (
    event_id character varying(36) NOT NULL,
    tenant_id uuid,
    owner character varying(64) NOT NULL,
    processed_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.time_entry (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    time_entry_id uuid NOT NULL,
    person_id uuid,
    location_id uuid,
    timesheet_id character varying(255),
    status character varying(255),
    attendance_start_at timestamp(6) with time zone,
    attendance_end_at timestamp(6) with time zone,
    approved_at timestamp(6) with time zone,
    approved_by character varying(255),
    rejected_at timestamp(6) with time zone,
    rejected_by character varying(255),
    rejection_reason character varying(500),
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    work_session_id uuid,
    break_minutes integer,
    submitted_at timestamp(6) with time zone,
    CONSTRAINT time_entry_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SUBMITTED'::character varying, 'PENDING_APPROVAL'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);

CREATE TABLE public.time_entry_adjustment (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    adjustment_id uuid NOT NULL,
    time_entry_id uuid NOT NULL,
    status character varying(50),
    reason_code character varying(200),
    minutes_delta integer,
    proposed_start_at timestamp(6) with time zone,
    proposed_end_at timestamp(6) with time zone,
    notes text,
    created_by character varying(255),
    created_at timestamp(6) with time zone,
    decided_by character varying(255),
    decided_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    CONSTRAINT time_entry_adjustment_status_check CHECK (((status)::text = ANY ((ARRAY['PROPOSED'::character varying, 'PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);

CREATE TABLE public.time_entry_audit (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    audit_id uuid NOT NULL,
    time_entry_id character varying(255) NOT NULL,
    action character varying(100) NOT NULL,
    actor_id character varying(255),
    correlation_id character varying(100),
    details text,
    "timestamp" timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

CREATE TABLE public.time_entry_exception (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    exception_id uuid NOT NULL,
    employee_id character varying(255) NOT NULL,
    time_entry_id character varying(255),
    exception_code character varying(200),
    severity character varying(50),
    status character varying(50),
    work_date date,
    detected_at timestamp(6) with time zone,
    resolved_at timestamp(6) with time zone,
    resolved_by character varying(255),
    resolution_notes text,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    CONSTRAINT time_entry_exception_severity_check CHECK (((severity)::text = ANY ((ARRAY['WARNING'::character varying, 'BLOCKING'::character varying])::text[]))),
    CONSTRAINT time_entry_exception_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'ACKNOWLEDGED'::character varying, 'RESOLVED'::character varying, 'WAIVED'::character varying])::text[])))
);

CREATE TABLE public.time_period (
    time_period_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    status character varying(50) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT time_period_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'SUBMISSION_CLOSED'::character varying, 'PAYROLL_CLOSED'::character varying])::text[])))
);

CREATE TABLE public.timekeeping_entry (
    timekeeping_entry_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    employee_id uuid NOT NULL,
    source_system character varying(50) NOT NULL,
    source_session_id uuid NOT NULL,
    original_source_session_id uuid,
    associated_work_order_id uuid,
    session_start_time timestamp(6) with time zone NOT NULL,
    session_end_time timestamp(6) with time zone NOT NULL,
    approval_status character varying(50) NOT NULL,
    correction_id uuid,
    correction_reason text,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT timekeeping_entry_approval_status_check CHECK (((approval_status)::text = ANY ((ARRAY['PENDING_APPROVAL'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);

CREATE TABLE public.timekeeping_policy (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    timekeeping_policy_id uuid NOT NULL,
    scope_type character varying(16) NOT NULL,
    scope_id uuid,
    job_time_discrepancy_threshold_minutes integer NOT NULL,
    effective_start_at timestamp(6) with time zone,
    effective_end_at timestamp(6) with time zone,
    updated_by character varying(255),
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT timekeeping_policy_scope_type_check CHECK (((scope_type)::text = ANY ((ARRAY['GLOBAL'::character varying, 'LOCATION'::character varying])::text[])))
);

CREATE TABLE public.work_session (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    session_id uuid NOT NULL,
    person_id uuid NOT NULL,
    status character varying(32) NOT NULL,
    actor character varying(128),
    started_at timestamp(6) with time zone NOT NULL,
    ended_at timestamp(6) with time zone,
    submitted_at timestamp(6) with time zone,
    billable_minutes integer,
    break_minutes integer,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

CREATE TABLE public.work_session_break (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    break_id uuid NOT NULL,
    session_id uuid NOT NULL,
    actor character varying(128),
    started_at timestamp(6) with time zone NOT NULL,
    ended_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

ALTER TABLE ONLY public.employee_location_assignment
    ADD CONSTRAINT employee_location_assignment_employee_id_location_id_role_e_key UNIQUE (tenant_id, employee_id, location_id, role, effective_from);

ALTER TABLE ONLY public.employee_location_assignment
    ADD CONSTRAINT employee_location_assignment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.employee_location_assignment
    ADD CONSTRAINT employee_location_assignment_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.employee_offboarding_retry_queue
    ADD CONSTRAINT employee_offboarding_retry_queue_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.employee_offboarding_retry_queue
    ADD CONSTRAINT employee_offboarding_retry_queue_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_person_id_key UNIQUE (tenant_id, person_id);

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.event_outbox
    ADD CONSTRAINT event_outbox_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.time_period
    ADD CONSTRAINT ex_time_period_tenant_no_overlap EXCLUDE USING gist (tenant_id WITH =, daterange(start_date, end_date, '[]'::text) WITH &&);

ALTER TABLE ONLY public.ext_location_parent
    ADD CONSTRAINT ext_location_parent_pkey PRIMARY KEY (child_id, parent_type);

ALTER TABLE ONLY public.ext_location_parent
    ADD CONSTRAINT ext_location_parent_tenant_key UNIQUE (tenant_id, child_id, parent_type);

ALTER TABLE ONLY public.ext_location
    ADD CONSTRAINT ext_location_pkey PRIMARY KEY (location_id);

ALTER TABLE ONLY public.ext_location
    ADD CONSTRAINT ext_location_tenant_key UNIQUE (tenant_id, location_id);

ALTER TABLE ONLY public.ext_people_contact_person
    ADD CONSTRAINT ext_people_contact_person_pkey PRIMARY KEY (person_id);

ALTER TABLE ONLY public.ext_people_contact_person
    ADD CONSTRAINT ext_people_contact_person_tenant_key UNIQUE (tenant_id, person_id);

ALTER TABLE ONLY public.ext_people_contact_user_link
    ADD CONSTRAINT ext_people_contact_user_link_pkey PRIMARY KEY (link_id);

ALTER TABLE ONLY public.ext_people_contact_user_link
    ADD CONSTRAINT ext_people_contact_user_link_tenant_key UNIQUE (tenant_id, link_id);

ALTER TABLE ONLY public.ext_workorder_job_time
    ADD CONSTRAINT ext_workorder_job_time_pkey PRIMARY KEY (labor_entry_id);

ALTER TABLE ONLY public.ext_workorder_job_time
    ADD CONSTRAINT ext_workorder_job_time_tenant_key UNIQUE (tenant_id, labor_entry_id);

ALTER TABLE ONLY public.processed_events
    ADD CONSTRAINT processed_events_pkey PRIMARY KEY (event_id);

ALTER TABLE ONLY public.time_entry_adjustment
    ADD CONSTRAINT time_entry_adjustment_pkey PRIMARY KEY (adjustment_id);

ALTER TABLE ONLY public.time_entry_adjustment
    ADD CONSTRAINT time_entry_adjustment_tenant_key UNIQUE (tenant_id, adjustment_id);

ALTER TABLE ONLY public.time_entry_audit
    ADD CONSTRAINT time_entry_audit_pkey PRIMARY KEY (audit_id);

ALTER TABLE ONLY public.time_entry_audit
    ADD CONSTRAINT time_entry_audit_tenant_key UNIQUE (tenant_id, audit_id);

ALTER TABLE ONLY public.time_entry_exception
    ADD CONSTRAINT time_entry_exception_pkey PRIMARY KEY (exception_id);

ALTER TABLE ONLY public.time_entry_exception
    ADD CONSTRAINT time_entry_exception_tenant_key UNIQUE (tenant_id, exception_id);

ALTER TABLE ONLY public.time_entry
    ADD CONSTRAINT time_entry_pkey PRIMARY KEY (time_entry_id);

ALTER TABLE ONLY public.time_entry
    ADD CONSTRAINT time_entry_tenant_key UNIQUE (tenant_id, time_entry_id);

ALTER TABLE ONLY public.time_period
    ADD CONSTRAINT time_period_pkey PRIMARY KEY (time_period_id);

ALTER TABLE ONLY public.time_period
    ADD CONSTRAINT time_period_tenant_key UNIQUE (tenant_id, time_period_id);

ALTER TABLE ONLY public.timekeeping_entry
    ADD CONSTRAINT timekeeping_entry_pkey PRIMARY KEY (timekeeping_entry_id);

ALTER TABLE ONLY public.timekeeping_entry
    ADD CONSTRAINT timekeeping_entry_tenant_key UNIQUE (tenant_id, timekeeping_entry_id);

ALTER TABLE ONLY public.timekeeping_entry
    ADD CONSTRAINT timekeeping_entry_tenant_id_source_system_source_session_id_key UNIQUE (tenant_id, source_system, source_session_id);

ALTER TABLE ONLY public.timekeeping_policy
    ADD CONSTRAINT timekeeping_policy_pkey PRIMARY KEY (timekeeping_policy_id);

ALTER TABLE ONLY public.timekeeping_policy
    ADD CONSTRAINT timekeeping_policy_tenant_key UNIQUE (tenant_id, timekeeping_policy_id);

ALTER TABLE ONLY public.time_entry
    ADD CONSTRAINT uq_time_entry_work_session UNIQUE (tenant_id, work_session_id);

ALTER TABLE ONLY public.time_period
    ADD CONSTRAINT uq_time_period_tenant_start UNIQUE (tenant_id, start_date);

ALTER TABLE ONLY public.work_session_break
    ADD CONSTRAINT work_session_break_pkey PRIMARY KEY (break_id);

ALTER TABLE ONLY public.work_session_break
    ADD CONSTRAINT work_session_break_tenant_key UNIQUE (tenant_id, break_id);

ALTER TABLE ONLY public.work_session
    ADD CONSTRAINT work_session_pkey PRIMARY KEY (session_id);

ALTER TABLE ONLY public.work_session
    ADD CONSTRAINT work_session_tenant_key UNIQUE (tenant_id, session_id);

CREATE INDEX idx_employee_status ON public.employee USING btree (status);

CREATE INDEX idx_event_outbox_published_window ON public.event_outbox USING btree (topic, created_at) WHERE (published_at IS NOT NULL);

CREATE INDEX idx_event_outbox_unpublished ON public.event_outbox USING btree (id) WHERE (published_at IS NULL);

CREATE INDEX idx_ext_job_time_end_at ON public.ext_workorder_job_time USING btree (end_at_utc);

CREATE INDEX idx_ext_job_time_technician ON public.ext_workorder_job_time USING btree (technician_id, end_at_utc);

CREATE INDEX idx_ext_location_parent_parent ON public.ext_location_parent USING btree (parent_id, parent_type);

CREATE INDEX idx_ext_person_last_name ON public.ext_people_contact_person USING btree (last_name);

CREATE INDEX idx_ext_person_primary_email ON public.ext_people_contact_person USING btree (primary_email);

CREATE INDEX idx_ext_user_link_person ON public.ext_people_contact_user_link USING btree (person_id);

CREATE INDEX idx_ext_user_link_username ON public.ext_people_contact_user_link USING btree (username);

CREATE INDEX idx_processed_events_owner_tenant_event ON public.processed_events USING btree (owner, tenant_id, event_id);

CREATE INDEX idx_time_entry_attendance_window ON public.time_entry USING btree (attendance_start_at, attendance_end_at);

CREATE INDEX idx_time_entry_location_start ON public.time_entry USING btree (location_id, attendance_start_at);

CREATE INDEX idx_time_entry_person_start ON public.time_entry USING btree (person_id, attendance_start_at);

CREATE INDEX idx_time_entry_status_start ON public.time_entry USING btree (status, attendance_start_at);

CREATE INDEX idx_time_period_dates ON public.time_period USING btree (start_date, end_date);

CREATE INDEX idx_time_period_tenant_status ON public.time_period USING btree (tenant_id, status);

CREATE INDEX idx_timekeeping_policy_scope ON public.timekeeping_policy USING btree (scope_type, scope_id);

CREATE INDEX idx_timekeeping_policy_scope_effective_updated ON public.timekeeping_policy USING btree (scope_type, scope_id, effective_start_at, effective_end_at, updated_at);

ALTER TABLE ONLY public.employee_location_assignment
    ADD CONSTRAINT fk_employee_location_assignment_employee FOREIGN KEY (tenant_id, employee_id) REFERENCES public.employee(tenant_id, id);

ALTER TABLE ONLY public.time_entry_adjustment
    ADD CONSTRAINT fk_time_entry_adjustment_entry FOREIGN KEY (tenant_id, time_entry_id) REFERENCES public.time_entry(tenant_id, time_entry_id);

ALTER TABLE ONLY public.work_session_break
    ADD CONSTRAINT fk_work_session_break_session FOREIGN KEY (tenant_id, session_id) REFERENCES public.work_session(tenant_id, session_id);

ALTER TABLE public.time_period ALTER COLUMN tenant_id SET DEFAULT public.app_current_tenant();

ALTER TABLE public.time_period ALTER COLUMN tenant_id SET NOT NULL;

ALTER TABLE public.timekeeping_entry ALTER COLUMN tenant_id SET DEFAULT public.app_current_tenant();

ALTER TABLE public.timekeeping_entry ALTER COLUMN tenant_id SET NOT NULL;

CREATE INDEX employee_tenant_idx ON public.employee USING btree (tenant_id);

CREATE INDEX employee_location_assignment_tenant_idx ON public.employee_location_assignment USING btree (tenant_id);

CREATE INDEX employee_offboarding_retry_queue_tenant_idx ON public.employee_offboarding_retry_queue USING btree (tenant_id);

CREATE INDEX ext_location_tenant_idx ON public.ext_location USING btree (tenant_id);

CREATE INDEX ext_location_parent_tenant_idx ON public.ext_location_parent USING btree (tenant_id);

CREATE INDEX ext_people_contact_person_tenant_idx ON public.ext_people_contact_person USING btree (tenant_id);

CREATE INDEX ext_people_contact_user_link_tenant_idx ON public.ext_people_contact_user_link USING btree (tenant_id);

CREATE INDEX ext_workorder_job_time_tenant_idx ON public.ext_workorder_job_time USING btree (tenant_id);

CREATE INDEX time_entry_tenant_idx ON public.time_entry USING btree (tenant_id);

CREATE INDEX time_entry_adjustment_tenant_idx ON public.time_entry_adjustment USING btree (tenant_id);

CREATE INDEX time_entry_audit_tenant_idx ON public.time_entry_audit USING btree (tenant_id);

CREATE INDEX time_entry_exception_tenant_idx ON public.time_entry_exception USING btree (tenant_id);

CREATE INDEX timekeeping_entry_tenant_idx ON public.timekeeping_entry USING btree (tenant_id);

CREATE INDEX timekeeping_policy_tenant_idx ON public.timekeeping_policy USING btree (tenant_id);

CREATE INDEX work_session_tenant_idx ON public.work_session USING btree (tenant_id);

CREATE INDEX work_session_break_tenant_idx ON public.work_session_break USING btree (tenant_id);

ALTER TABLE public.employee ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.employee
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.employee_location_assignment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_location_assignment FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.employee_location_assignment
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.employee_offboarding_retry_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_offboarding_retry_queue FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.employee_offboarding_retry_queue
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_location ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_location FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_location
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_location_parent ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_location_parent FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_location_parent
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_people_contact_person ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_people_contact_person FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_people_contact_person
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_people_contact_user_link ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_people_contact_user_link FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_people_contact_user_link
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_workorder_job_time ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_workorder_job_time FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_workorder_job_time
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.time_entry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.time_entry FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.time_entry
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.time_entry_adjustment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.time_entry_adjustment FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.time_entry_adjustment
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.time_entry_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.time_entry_audit FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.time_entry_audit
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.time_entry_exception ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.time_entry_exception FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.time_entry_exception
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.time_period ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.time_period FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.time_period
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.timekeeping_entry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timekeeping_entry FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.timekeeping_entry
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.timekeeping_policy ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timekeeping_policy FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.timekeeping_policy
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.work_session ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_session FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.work_session
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.work_session_break ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_session_break FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.work_session_break
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());
