-- pos-vehicle-reference-nhtsa: Flyway baseline (flattened 2026-09-09 from the previous migration history) with the
-- ADR-0062 tenancy schema folded in. Generated by scripts/db/tenancy/flatten.py from a pg_dump of a
-- database migrated with the retired scripts; the tenancy additions are mechanical and are listed in
-- docs/TENANCY_SCHEMA.md. Global (unscoped) tables: src/main/resources/db/tenancy-global-tables.txt.
--
-- Tenant context: app_current_tenant() reads the session setting app.current_tenant, which the
-- TenantAwareDataSource (pos-tenancy-common, plan WS1) binds per checkout. Until then the owner role
-- carries a transitional default (postgres/init-tenancy.sh) and tests set it per connection.
-- With nothing bound: NULL -> every scoped table reads as empty and refuses inserts (fail closed).

-- Functions are emitted before the tables they reference (pg_dump order); do not validate bodies.
SET check_function_bodies = false;

CREATE OR REPLACE FUNCTION public.app_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$ SELECT NULLIF(current_setting('app.current_tenant', true), '')::uuid $$;

CREATE TABLE public.make (
    id uuid NOT NULL,
    name character varying(255),
    manufacturer_id uuid,
    cache_timestamp timestamp without time zone
);

CREATE TABLE public.manufacturer (
    id uuid NOT NULL,
    name character varying(255),
    cache_timestamp timestamp without time zone
);

CREATE TABLE public.model (
    id uuid NOT NULL,
    name character varying(255),
    make_id uuid,
    cache_timestamp timestamp without time zone
);

CREATE TABLE public.vehicle_type (
    id uuid NOT NULL,
    make_id uuid,
    vehicle_type_name character varying(255),
    vehicle_type_id character varying(255),
    cache_timestamp timestamp without time zone
);

CREATE TABLE public.vehicle_variable (
    id uuid NOT NULL,
    name character varying(255),
    description character varying(255),
    cache_timestamp timestamp without time zone
);

CREATE TABLE public.vehicle_variable_value (
    id uuid NOT NULL,
    variable_id uuid,
    value character varying(255),
    value_id character varying(255),
    cache_timestamp timestamp without time zone
);

ALTER TABLE ONLY public.make
    ADD CONSTRAINT make_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.manufacturer
    ADD CONSTRAINT manufacturer_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.model
    ADD CONSTRAINT model_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vehicle_type
    ADD CONSTRAINT vehicle_type_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vehicle_variable
    ADD CONSTRAINT vehicle_variable_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vehicle_variable_value
    ADD CONSTRAINT vehicle_variable_value_pkey PRIMARY KEY (id);

CREATE INDEX idx_make_manufacturer_id ON public.make USING btree (manufacturer_id);

CREATE INDEX idx_model_make_id ON public.model USING btree (make_id);

CREATE INDEX idx_vehicle_type_make_id ON public.vehicle_type USING btree (make_id);

CREATE INDEX idx_vehicle_variable_value_variable_id ON public.vehicle_variable_value USING btree (variable_id);

ALTER TABLE ONLY public.make
    ADD CONSTRAINT fk_make_manufacturer FOREIGN KEY (manufacturer_id) REFERENCES public.manufacturer(id);

ALTER TABLE ONLY public.model
    ADD CONSTRAINT fk_model_make FOREIGN KEY (make_id) REFERENCES public.make(id);

ALTER TABLE ONLY public.vehicle_type
    ADD CONSTRAINT fk_vehicle_type_make FOREIGN KEY (make_id) REFERENCES public.make(id);

ALTER TABLE ONLY public.vehicle_variable_value
    ADD CONSTRAINT fk_vehicle_variable_value_variable FOREIGN KEY (variable_id) REFERENCES public.vehicle_variable(id);
