-- Repeatable seed: canonical role -> permission baseline (role_permissions).
--
-- WHY THIS FILE EXISTS
-- Authorities carried in a JWT are resolved from this table at login:
--     users -> user_roles -> roles -> role_permissions -> permissions
-- RoleAuthorityServiceImpl reads these rows; it no longer hardcodes role
-- expansion in Java. An empty role_permissions therefore means "no authority",
-- so this baseline must stay complete.
--
-- POLICY
-- * Least privilege for operational roles. Domain grants mirror a capability the
--   role already exercised through the retired hardcoded expansion, or (for
--   SYSTEM_ADMINISTRATOR and DISPATCHER, which the hardcoded switch never
--   covered) the role's documented job function.
-- * Assistant baseline: every role listed in section 3 receives mcp:chat:execute,
--   mcp:chat:stream, nlti:request:submit and nlti:request:read. These are the
--   conversational entrypoints. MCP now gates the order, pricing and catalog
--   facades on explicit domain permission codes rather than the synthetic
--   AUTHENTICATED tier; only domains that still lack a real permission code for
--   MCP to mirror remain on that floor.
--   NOTE this includes the customer-facing CUSTOMER and SELF_SERVICE_CUSTOMER
--   roles, which previously held nothing at all.
--   These are explicit grants, not a rule the database enforces: a role created
--   later through the role-permission admin API starts with NO grants, assistant
--   entrypoints included, until something grants them. To make a new role part of
--   the baseline, add it to section 3 here.
-- * SYSTEM_ADMINISTRATOR is deliberately NOT a superuser. It holds the
--   security/admin surface plus MCP administration (system prompts, LLM API
--   configuration, tool management, document ingest) and no accounting, catalog,
--   workorder, inventory or shop authority. ADMIN remains the all-domain role
--   and is a strict superset.
-- * The retired switch also expanded ACCOUNTANT, AP_CLERK, CONTROLLER, CSR,
--   FLEET_MANAGER and GL_ANALYST. Those are NOT reproduced here: no migration
--   and no runtime initializer creates them, and both user_roles and
--   role_assignments are foreign-keyed to roles(id), so no user could hold one.
--   To make a persona real, create the role first, then grant it here.
-- * invoice:finalize:override (#1374) gates manager-approval elevation for
--   invoice finalization above the service-advisor cap. It is held by ADMIN
--   and the manager roles only — ACCOUNT_MANAGER, GENERAL_MANAGER,
--   LOCATION_MANAGER, MANAGER and SHOP_MANAGER — per the product decision on
--   that issue. Do not widen it: the permission exists specifically to cap
--   what a service advisor can finalize by naming an absent manager.
-- * workorder:workorder:delete (#1432) is a hard delete that destroys history,
--   so it is held by ADMIN and the manager roles only — GENERAL_MANAGER,
--   LOCATION_MANAGER, MANAGER and SHOP_MANAGER — mirroring the
--   invoice:finalize:override precedent. Advisors create workorders
--   (workorder:workorder:create) but cannot destroy them.
-- * SERVICE_ADVISOR holds the CRM onboarding surface (#1435, #1437):
--   crm:party:view/search/create, crm:person:read/create and
--   crm:vehicle:create (alongside its existing crm:vehicle:search/view), so a
--   walk-in customer can be looked up, duplicate-checked, onboarded and have
--   their vehicle registered at the counter. Deliberately NOT
--   crm:party:edit/deactivate/merge — corrections and destructive party
--   operations stay manager-and-above.
-- * INVENTORY_LEAD is the parts-receiving persona (#1439): it holds the
--   receiving surface (ASN, receiving sessions, goods receipts, cross-dock
--   issue, putaway, shortages, on-hand visibility) plus purchase-order
--   create/view. The elevated escape hatches stay out: goods_receipt:override
--   and the putaway capacity/compatibility overrides are not granted here.
-- * The inventory:availability:* and inventory:on_hand:* families answer two
--   different questions and neither implies the other (ADR-0057, #1494).
--   on_hand:* reads the stock record itself — counted quantity, lot and serial
--   detail, location contents, rollups. availability:* reads the derived
--   projection: on-hand net of prior commitments (allocations, reservations,
--   expired lots) plus the incoming/outgoing forecast, i.e. what can be
--   promised. Each family splits again on cross-location disclosure:
--   availability:read is the scope-limited answer, availability:search the
--   per-location breakdown that enumerates every location holding the SKU.
--   TECHNICIAN and SERVICE_ADVISOR hold :read so they can tell whether a part
--   can be committed to the job in front of them; they deliberately do NOT hold
--   :search or any on_hand code. Before #1494, availability:read was granted
--   here and enforced by no endpoint, so it granted nothing.
-- * order:purchase_order:approve and :transmit (#1438) are held by ADMIN and
--   the PO-approver personas LOCATION_MANAGER and INVENTORY_MANAGER only.
--   Note the legacy inventory:purchase_order:* family remains seeded
--   (ADMIN-only) although no controller enforces it — pos-order enforces
--   order:purchase_order:*; retiring the legacy family needs a versioned
--   migration and is tracked on #1438.
-- * The inventory adjustment roles (#1373) carry the documented model:
--   INVENTORY_LEAD creates and views adjustment requests;
--   INVENTORY_MANAGER and INVENTORY_CONTROLLER additionally approve them. The two
--   approver roles hold an identical permission set on purpose — location versus
--   global reach is a property of role_assignments.scope_type, not of
--   role_permissions, so it cannot be expressed by granting different rows here.
--   INVENTORY_CONTROLLER alone also holds inventory:adjustment:override, the
--   negative-stock escape hatch ScrapServiceImpl checks, because only a
--   globally scoped approver should drive on-hand below zero.
-- * SHOP_MANAGER holds the shop surface its V3 description names (locations,
--   bays, schedules, technicians) plus invoice:finalize:override (#1374). It has
--   no audit grant because the shop domain defines no audit permission; add one
--   to pos-shop-manager's manifest first if that capability is wanted.
-- * SECURITY_ADMIN and READ_ONLY_SCHEDULER are NOT granted here and no longer
--   exist: V3 created them as unratified "Candidate Roles v0", nothing in the
--   codebase ever referenced them, and V23 deletes them (#1373).
--   SECURITY_ADMIN's described scope is covered by SYSTEM_ADMINISTRATOR.
-- * CUSTOMER and SELF_SERVICE_CUSTOMER hold the assistant entrypoints and nothing
--   else, confirmed deliberate on #1373. They are external-facing; any domain
--   grant to them is a new product decision, not a gap to be filled.
-- * Grants are additive. Nothing here deletes a row, so permissions an operator
--   granted through the role-permission admin API survive re-runs. Revoking a
--   grant therefore needs a versioned migration, which is what V23 does for the
--   two deleted candidate roles.
--
-- IDEMPOTENCY
-- Every statement below is ON CONFLICT DO NOTHING, and role/permission ids are
-- resolved by NAME rather than hardcoded UUIDs, so re-running this repeatable
-- migration against a populated database is a no-op.

SET TIME ZONE 'UTC';

-- ---------------------------------------------------------------------------
-- 1. Role creation.
--
-- Roles are created by SQL migrations only (#1440): every role this baseline
-- grants to is inserted with a pinned UUID by R__seed_reference_security.sql,
-- which Flyway runs before this file (repeatables run in filename order), or by
-- a versioned migration (V3). No runtime code creates roles any more — the
-- retired RoleInitializer bean ran @PostConstruct, i.e. AFTER Flyway, which is
-- why this section used to re-create its roles defensively. Granting to a role
-- no migration creates still aborts the migration via the assertion in
-- section 4.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- 2. Ensure a permissions row exists for every permission this baseline grants.
--
-- Most rows already exist (SQL-seeded, or registered at startup by the owning
-- module). Some are registered only by services that may not have booted yet on
-- a fresh database, and role_permissions has a foreign key to permissions, so a
-- missing row would silently drop the grant. Names and bit indexes come from the
-- PermissionCode catalog -- the same compiled catalog pos-api-gateway decodes
-- perm_bits against -- so nothing here is invented. The placeholder description
-- is overwritten when the owning module registers the permission at startup.
--
-- ON CONFLICT DO NOTHING (no conflict target) so an existing row is preserved
-- untouched, whatever unique constraint it collides on.
-- ---------------------------------------------------------------------------
INSERT INTO permissions (
    id, name, description, domain, resource, action,
    registered_at, registered_by_service, version, bit_index)
SELECT gen_random_uuid(), c.name, c.name, c.domain, c.resource, c.action,
       NOW(), 'pos-security-service', '1.0', c.bit_index
FROM (VALUES
    ('accounting:ap:approve', 'accounting', 'ap', 'approve', 262),
    ('accounting:ap:pay', 'accounting', 'ap', 'pay', 4),
    ('accounting:ap:reject', 'accounting', 'ap', 'reject', 263),
    ('accounting:ap:view', 'accounting', 'ap', 'view', 3),
    ('accounting:coa:create', 'accounting', 'coa', 'create', 6),
    ('accounting:coa:deactivate', 'accounting', 'coa', 'deactivate', 264),
    ('accounting:coa:edit', 'accounting', 'coa', 'edit', 7),
    ('accounting:coa:view', 'accounting', 'coa', 'view', 5),
    ('accounting:credit-memo:create', 'accounting', 'credit-memo', 'create', 285),
    ('accounting:credit-memo:read', 'accounting', 'credit-memo', 'read', 286),
    ('accounting:default-mapping:create', 'accounting', 'default-mapping', 'create', 287),
    ('accounting:default-mapping:delete', 'accounting', 'default-mapping', 'delete', 288),
    ('accounting:default-mapping:edit', 'accounting', 'default-mapping', 'edit', 289),
    ('accounting:default-mapping:view', 'accounting', 'default-mapping', 'view', 290),
    ('accounting:events:reprocess', 'accounting', 'events', 'reprocess', 241),
    ('accounting:events:retry', 'accounting', 'events', 'retry', 10),
    ('accounting:events:submit', 'accounting', 'events', 'submit', 9),
    ('accounting:events:view', 'accounting', 'events', 'view', 8),
    ('accounting:export:request', 'accounting', 'export', 'request', 242),
    ('accounting:export:view', 'accounting', 'export', 'view', 243),
    ('accounting:gl-mapping:create', 'accounting', 'gl-mapping', 'create', 291),
    ('accounting:gl-mapping:resolve', 'accounting', 'gl-mapping', 'resolve', 292),
    ('accounting:je:create', 'accounting', 'je', 'create', 1),
    ('accounting:je:post', 'accounting', 'je', 'post', 2),
    ('accounting:je:reverse', 'accounting', 'je', 'reverse', 265),
    ('accounting:je:view', 'accounting', 'je', 'view', 0),
    ('accounting:mapping-key:create', 'accounting', 'mapping-key', 'create', 293),
    ('accounting:mapping-key:deactivate', 'accounting', 'mapping-key', 'deactivate', 294),
    ('accounting:mapping-key:edit', 'accounting', 'mapping-key', 'edit', 295),
    ('accounting:mapping-key:view', 'accounting', 'mapping-key', 'view', 296),
    ('accounting:mapping:create', 'accounting', 'mapping', 'create', 267),
    ('accounting:mapping:deactivate', 'accounting', 'mapping', 'deactivate', 269),
    ('accounting:mapping:edit', 'accounting', 'mapping', 'edit', 268),
    ('accounting:mapping:view', 'accounting', 'mapping', 'view', 266),
    ('accounting:payment:apply', 'accounting', 'payment', 'apply', 297),
    ('accounting:payment:reverse', 'accounting', 'payment', 'reverse', 298),
    ('accounting:posting-category:create', 'accounting', 'posting-category', 'create', 299),
    ('accounting:posting-category:deactivate', 'accounting', 'posting-category', 'deactivate', 300),
    ('accounting:posting-category:edit', 'accounting', 'posting-category', 'edit', 301),
    ('accounting:posting-category:view', 'accounting', 'posting-category', 'view', 302),
    ('accounting:posting_rules:archive', 'accounting', 'posting_rules', 'archive', 273),
    ('accounting:posting_rules:create', 'accounting', 'posting_rules', 'create', 271),
    ('accounting:posting_rules:publish', 'accounting', 'posting_rules', 'publish', 272),
    ('accounting:posting_rules:view', 'accounting', 'posting_rules', 'view', 270),
    ('accounting:report:export', 'accounting', 'report', 'export', 303),
    ('accounting:time:export', 'accounting', 'time', 'export', 304),
    ('appointments:cancel', 'appointments', '', 'cancel', 162),
    ('appointments:create', 'appointments', '', 'create', 159),
    ('appointments:reschedule', 'appointments', '', 'reschedule', 161),
    ('appointments:view', 'appointments', '', 'view', 160),
    ('bulkImport:status:read', 'bulkImport', 'status', 'read', 240),
    ('bulkImport:upload:execute', 'bulkImport', 'upload', 'execute', 239),
    ('catalog:category:create', 'catalog', 'category', 'create', 18),
    ('catalog:category:delete', 'catalog', 'category', 'delete', 20),
    ('catalog:category:edit', 'catalog', 'category', 'edit', 19),
    ('catalog:category:view', 'catalog', 'category', 'view', 17),
    ('catalog:msrp:read', 'catalog', 'msrp', 'read', 229),
    ('catalog:msrp:write', 'catalog', 'msrp', 'write', 230),
    ('catalog:price_book:read', 'catalog', 'price_book', 'read', 231),
    ('catalog:price_book:write', 'catalog', 'price_book', 'write', 232),
    ('catalog:product:create', 'catalog', 'product', 'create', 12),
    ('catalog:product:delete', 'catalog', 'product', 'delete', 14),
    ('catalog:product:edit', 'catalog', 'product', 'edit', 13),
    ('catalog:product:view', 'catalog', 'product', 'view', 11),
    ('catalog:service_type:create', 'catalog', 'service_type', 'create', 22),
    ('catalog:service_type:edit', 'catalog', 'service_type', 'edit', 23),
    ('catalog:service_type:view', 'catalog', 'service_type', 'view', 21),
    ('catalog:supplier_cost:read', 'catalog', 'supplier_cost', 'read', 227),
    ('catalog:supplier_cost:write', 'catalog', 'supplier_cost', 'write', 228),
    ('catalog:variant:create', 'catalog', 'variant', 'create', 25),
    ('catalog:variant:edit', 'catalog', 'variant', 'edit', 26),
    ('catalog:variant:view', 'catalog', 'variant', 'view', 24),
    ('crm:billing_rules:edit', 'crm', 'billing_rules', 'edit', 244),
    ('crm:contact:create', 'crm', 'contact', 'create', 34),
    ('crm:contact:delete', 'crm', 'contact', 'delete', 36),
    ('crm:contact:edit', 'crm', 'contact', 'edit', 35),
    ('crm:contact:view', 'crm', 'contact', 'view', 33),
    ('crm:contact_preference:edit', 'crm', 'contact_preference', 'edit', 41),
    ('crm:contact_preference:view', 'crm', 'contact_preference', 'view', 40),
    ('crm:contact_role:assign', 'crm', 'contact_role', 'assign', 38),
    ('crm:contact_role:revoke', 'crm', 'contact_role', 'revoke', 39),
    ('crm:contact_role:view', 'crm', 'contact_role', 'view', 37),
    ('crm:integration:audit', 'crm', 'integration', 'audit', 54),
    ('crm:party:create', 'crm', 'party', 'create', 29),
    ('crm:party:deactivate', 'crm', 'party', 'deactivate', 31),
    ('crm:party:edit', 'crm', 'party', 'edit', 30),
    ('crm:party:merge', 'crm', 'party', 'merge', 32),
    ('crm:party:search', 'crm', 'party', 'search', 28),
    ('crm:party:view', 'crm', 'party', 'view', 27),
    ('crm:person:create', 'crm', 'person', 'create', 305),
    ('crm:person:read', 'crm', 'person', 'read', 306),
    ('crm:processing_log:view', 'crm', 'processing_log', 'view', 52),
    ('crm:promotion_redemption:record', 'crm', 'promotion_redemption', 'record', 338),
    ('crm:promotion_redemption:view', 'crm', 'promotion_redemption', 'view', 339),
    ('crm:relationship:create', 'crm', 'relationship', 'create', 307),
    ('crm:relationship:delete', 'crm', 'relationship', 'delete', 308),
    ('crm:relationship:read', 'crm', 'relationship', 'read', 309),
    ('crm:relationship:update', 'crm', 'relationship', 'update', 310),
    ('crm:suspense:view', 'crm', 'suspense', 'view', 53),
    ('crm:vehicle:create', 'crm', 'vehicle', 'create', 44),
    ('crm:vehicle:search', 'crm', 'vehicle', 'search', 43),
    ('crm:vehicle:view', 'crm', 'vehicle', 'view', 42),
    ('crm:vehicle_party_association:create', 'crm', 'vehicle_party_association', 'create', 47),
    ('crm:vehicle_party_association:edit', 'crm', 'vehicle_party_association', 'edit', 49),
    ('crm:vehicle_party_association:view', 'crm', 'vehicle_party_association', 'view', 48),
    ('crm:vehicle_preference:edit', 'crm', 'vehicle_preference', 'edit', 51),
    ('crm:vehicle_preference:view', 'crm', 'vehicle_preference', 'view', 50),
    ('documents:render', 'documents', '', 'render', 55),
    ('inventory:adjustment:approve', 'inventory', 'adjustment', 'approve', 57),
    ('inventory:adjustment:create', 'inventory', 'adjustment', 'create', 56),
    ('inventory:adjustment:override', 'inventory', 'adjustment', 'override', 468),
    ('inventory:adjustment:view', 'inventory', 'adjustment', 'view', 58),
    ('inventory:allocations:reallocate', 'inventory', 'allocations', 'reallocate', 80),
    ('inventory:asn:create', 'inventory', 'asn', 'create', 75),
    ('inventory:asn:view', 'inventory', 'asn', 'view', 76),
    ('inventory:availability:read', 'inventory', 'availability', 'read', 311),
    ('inventory:availability:search', 'inventory', 'availability', 'search', 470),
    ('inventory:cycle_count:complete', 'inventory', 'cycle_count', 'complete', 63),
    ('inventory:cycle_count:initiate', 'inventory', 'cycle_count', 'initiate', 61),
    ('inventory:cycle_count:view', 'inventory', 'cycle_count', 'view', 62),
    ('inventory:goods_receipt:create', 'inventory', 'goods_receipt', 'create', 77),
    ('inventory:goods_receipt:override', 'inventory', 'goods_receipt', 'override', 79),
    ('inventory:goods_receipt:view', 'inventory', 'goods_receipt', 'view', 78),
    ('inventory:issue:parts', 'inventory', 'issue', 'parts', 69),
    ('inventory:ledger:view', 'inventory', 'ledger', 'view', 246),
    ('inventory:location:admin', 'inventory', 'location', 'admin', 247),
    ('inventory:location:view', 'inventory', 'location', 'view', 248),
    ('inventory:on_hand:search', 'inventory', 'on_hand', 'search', 65),
    ('inventory:on_hand:view', 'inventory', 'on_hand', 'view', 64),
    ('inventory:override:part-match', 'inventory', 'override', 'part-match', 70),
    ('inventory:pick_list:create', 'inventory', 'pick_list', 'create', 249),
    ('inventory:pick_list:execute', 'inventory', 'pick_list', 'execute', 250),
    ('inventory:pick_list:view', 'inventory', 'pick_list', 'view', 251),
    ('inventory:purchase_order:approve', 'inventory', 'purchase_order', 'approve', 73),
    ('inventory:purchase_order:create', 'inventory', 'purchase_order', 'create', 71),
    ('inventory:purchase_order:receive', 'inventory', 'purchase_order', 'receive', 74),
    ('inventory:purchase_order:view', 'inventory', 'purchase_order', 'view', 72),
    ('inventory:putaway:claim', 'inventory', 'putaway', 'claim', 252),
    ('inventory:putaway:execute', 'inventory', 'putaway', 'execute', 253),
    ('inventory:putaway:generate', 'inventory', 'putaway', 'generate', 254),
    ('inventory:putaway:override_location_capacity', 'inventory', 'putaway', 'override_location_capacity', 60),
    ('inventory:putaway:override_location_compatibility', 'inventory', 'putaway', 'override_location_compatibility', 59),
    ('inventory:putaway:view', 'inventory', 'putaway', 'view', 255),
    ('inventory:receiving:complete', 'inventory', 'receiving', 'complete', 68),
    ('inventory:receiving:create', 'inventory', 'receiving', 'create', 66),
    ('inventory:receiving:view', 'inventory', 'receiving', 'view', 67),
    ('inventory:return:view', 'inventory', 'return', 'view', 256),
    ('inventory:return:write', 'inventory', 'return', 'write', 257),
    ('inventory:shortage:resolve', 'inventory', 'shortage', 'resolve', 258),
    ('inventory:shortage:view', 'inventory', 'shortage', 'view', 259),
    ('inventory:stock_movement:create', 'inventory', 'stock_movement', 'create', 260),
    ('invoice:billing-rules', 'invoice', '', 'billing-rules', 83),
    ('invoice:finalize', 'invoice', '', 'finalize', 84),
    ('invoice:finalize:override', 'invoice', 'finalize', 'override', 346),
    ('invoice:manage', 'invoice', '', 'manage', 82),
    ('location:bay:manage', 'location', 'bay', 'manage', 88),
    ('location:bay:read', 'location', 'bay', 'read', 87),
    ('location:mobile-unit:manage', 'location', 'mobile-unit', 'manage', 90),
    ('location:mobile-unit:read', 'location', 'mobile-unit', 'read', 89),
    ('location:read', 'location', '', 'read', 85),
    ('location:service-area:manage', 'location', 'service-area', 'manage', 92),
    ('location:service-area:read', 'location', 'service-area', 'read', 91),
    ('location:travel-buffer-policy:manage', 'location', 'travel-buffer-policy', 'manage', 94),
    ('location:travel-buffer-policy:read', 'location', 'travel-buffer-policy', 'read', 93),
    ('location:write', 'location', '', 'write', 86),
    ('mcp:chat:execute', 'mcp', 'chat', 'execute', 226),
    ('mcp:chat:stream', 'mcp', 'chat', 'stream', 225),
    ('mcp:document:ingest', 'mcp', 'document', 'ingest', 224),
    ('mcp:llm_api:create', 'mcp', 'llm_api', 'create', 96),
    ('mcp:llm_api:delete', 'mcp', 'llm_api', 'delete', 98),
    ('mcp:llm_api:update', 'mcp', 'llm_api', 'update', 97),
    ('mcp:llm_api:view', 'mcp', 'llm_api', 'view', 95),
    ('mcp:system_prompt:create', 'mcp', 'system_prompt', 'create', 100),
    ('mcp:system_prompt:delete', 'mcp', 'system_prompt', 'delete', 102),
    ('mcp:system_prompt:update', 'mcp', 'system_prompt', 'update', 101),
    ('mcp:system_prompt:view', 'mcp', 'system_prompt', 'view', 99),
    ('mcp:tool:manage', 'mcp', 'tool', 'manage', 347),
    ('mcp:tool:view', 'mcp', 'tool', 'view', 348),
    ('nlti:audit:read', 'nlti', 'audit', 'read', 223),
    ('nlti:request:read', 'nlti', 'request', 'read', 222),
    ('nlti:request:submit', 'nlti', 'request', 'submit', 221),
    ('order:line:create', 'order', 'line', 'create', 108),
    ('order:line:delete', 'order', 'line', 'delete', 110),
    ('order:line:edit', 'order', 'line', 'edit', 109),
    ('order:line:enter_manual_price', 'order', 'line', 'enter_manual_price', 111),
    ('order:line:view', 'order', 'line', 'view', 107),
    ('order:order:cancel', 'order', 'order', 'cancel', 106),
    ('order:order:create', 'order', 'order', 'create', 104),
    ('order:order:edit', 'order', 'order', 'edit', 105),
    ('order:order:view', 'order', 'order', 'view', 103),
    ('order:price_override:apply', 'order', 'price_override', 'apply', 113),
    ('order:price_override:approve', 'order', 'price_override', 'approve', 114),
    ('order:price_override:reject', 'order', 'price_override', 'reject', 115),
    ('order:price_override:view', 'order', 'price_override', 'view', 112),
    ('order:purchase_order:approve', 'order', 'purchase_order', 'approve', 456),
    ('order:purchase_order:availability_view', 'order', 'purchase_order', 'availability_view', 460),
    ('order:purchase_order:create', 'order', 'purchase_order', 'create', 457),
    ('order:purchase_order:transmit', 'order', 'purchase_order', 'transmit', 459),
    ('order:purchase_order:view', 'order', 'purchase_order', 'view', 458),
    ('people-contact:person:create', 'people-contact', 'person', 'create', 352),
    ('people-contact:person:delete', 'people-contact', 'person', 'delete', 354),
    ('people-contact:person:edit', 'people-contact', 'person', 'edit', 353),
    ('people-contact:person:view', 'people-contact', 'person', 'view', 351),
    ('people-contact:role:assign', 'people-contact', 'role', 'assign', 356),
    ('people-contact:role:revoke', 'people-contact', 'role', 'revoke', 357),
    ('people-contact:role:view', 'people-contact', 'role', 'view', 355),
    ('people-contact:userLink:view', 'people-contact', 'userLink', 'view', 358),
    ('people-contact:userLink:write', 'people-contact', 'userLink', 'write', 359),
    ('people:availability:view', 'people', 'availability', 'view', 312),
    ('people:employee:create', 'people', 'employee', 'create', 117),
    ('people:employee:deactivate', 'people', 'employee', 'deactivate', 119),
    ('people:employee:edit', 'people', 'employee', 'edit', 118),
    ('people:employee:view', 'people', 'employee', 'view', 116),
    ('people:skill:assign', 'people', 'skill', 'assign', 124),
    ('people:skill:edit', 'people', 'skill', 'edit', 125),
    ('people:skill:view', 'people', 'skill', 'view', 123),
    ('people:timeAdjustment:approve', 'people', 'timeAdjustment', 'approve', 318),
    ('people:timeAdjustment:create', 'people', 'timeAdjustment', 'create', 319),
    ('people:timeAdjustment:view', 'people', 'timeAdjustment', 'view', 320),
    ('people:timeEntry:approve', 'people', 'timeEntry', 'approve', 321),
    ('people:timeEntry:reject', 'people', 'timeEntry', 'reject', 322),
    ('people:timeException:acknowledge', 'people', 'timeException', 'acknowledge', 323),
    ('people:timeException:create', 'people', 'timeException', 'create', 324),
    ('people:timeException:resolve', 'people', 'timeException', 'resolve', 325),
    ('people:timeException:view', 'people', 'timeException', 'view', 326),
    ('people:timekeeping:approve', 'people', 'timekeeping', 'approve', 328),
    ('people:timekeeping:reject', 'people', 'timekeeping', 'reject', 329),
    ('people:timekeeping:view', 'people', 'timekeeping', 'view', 330),
    ('pricing:base_price:create', 'pricing', 'base_price', 'create', 245),
    ('pricing:normalization:edit', 'pricing', 'normalization', 'edit', 131),
    ('pricing:normalization:view', 'pricing', 'normalization', 'view', 130),
    ('pricing:override:approve', 'pricing', 'override', 'approve', 313),
    ('pricing:price_book:create', 'pricing', 'price_book', 'create', 127),
    ('pricing:price_book:delete', 'pricing', 'price_book', 'delete', 129),
    ('pricing:price_book:edit', 'pricing', 'price_book', 'edit', 128),
    ('pricing:price_book:view', 'pricing', 'price_book', 'view', 126),
    ('pricing:promotion:apply', 'pricing', 'promotion', 'apply', 340),
    ('pricing:promotion:manage', 'pricing', 'promotion', 'manage', 341),
    ('pricing:promotion:view', 'pricing', 'promotion', 'view', 342),
    ('pricing:restriction:manage', 'pricing', 'restriction', 'manage', 314),
    ('pricing:restriction:override', 'pricing', 'restriction', 'override', 315),
    ('pricing:restrictions:edit', 'pricing', 'restrictions', 'edit', 133),
    ('pricing:restrictions:view', 'pricing', 'restrictions', 'view', 132),
    ('pricing:rule:create', 'pricing', 'rule', 'create', 135),
    ('pricing:rule:delete', 'pricing', 'rule', 'delete', 137),
    ('pricing:rule:edit', 'pricing', 'rule', 'edit', 136),
    ('pricing:rule:view', 'pricing', 'rule', 'view', 134),
    ('product:lifecycle:override_discontinued', 'product', 'lifecycle', 'override_discontinued', 16),
    ('product:lifecycle:update', 'product', 'lifecycle', 'update', 15),
    ('reporting:view:financial-statements', 'reporting', 'view', 'financial-statements', 316),
    ('security:audit:create', 'security', 'audit', 'create', 218),
    ('security:audit:export', 'security', 'audit', 'export', 317),
    ('security:audit:view', 'security', 'audit', 'view', 217),
    ('security:authorization:decide', 'security', 'authorization', 'decide', 219),
    ('security:permission:register', 'security', 'permission', 'register', 144),
    ('security:permission:view', 'security', 'permission', 'view', 143),
    ('security:role:assign', 'security', 'role', 'assign', 142),
    ('security:role:create', 'security', 'role', 'create', 139),
    ('security:role:delete', 'security', 'role', 'delete', 141),
    ('security:role:edit', 'security', 'role', 'edit', 140),
    ('security:role:view', 'security', 'role', 'view', 138),
    ('security:token:issue_internal', 'security', 'token', 'issue_internal', 220),
    ('security:user:create', 'security', 'user', 'create', 146),
    ('security:user:delete', 'security', 'user', 'delete', 148),
    ('security:user:edit', 'security', 'user', 'edit', 147),
    ('security:user:view', 'security', 'user', 'view', 145),
    ('security:user_account_state:manage', 'security', 'user_account_state', 'manage', 216),
    ('security:user_account_state:view', 'security', 'user_account_state', 'view', 215),
    ('shop:bay:assign', 'shop', 'bay', 'assign', 156),
    ('shop:bay:create', 'shop', 'bay', 'create', 154),
    ('shop:bay:edit', 'shop', 'bay', 'edit', 155),
    ('shop:bay:view', 'shop', 'bay', 'view', 153),
    ('shop:location:create', 'shop', 'location', 'create', 150),
    ('shop:location:deactivate', 'shop', 'location', 'deactivate', 152),
    ('shop:location:edit', 'shop', 'location', 'edit', 151),
    ('shop:location:view', 'shop', 'location', 'view', 149),
    ('shop:schedule:edit', 'shop', 'schedule', 'edit', 158),
    ('shop:schedule:view', 'shop', 'schedule', 'view', 157),
    ('shop:technician:view', 'shop', 'technician', 'view', 361),
    ('tax:calculate', 'tax', '', 'calculate', 163),
    ('tax:mode:view', 'tax', 'mode', 'view', 164),
    ('timekeeping:overlap_override', 'timekeeping', '', 'overlap_override', 278),
    ('timekeeping:work_session:break_start', 'timekeeping', 'work_session', 'break_start', 276),
    ('timekeeping:work_session:break_stop', 'timekeeping', 'work_session', 'break_stop', 277),
    ('timekeeping:work_session:create', 'timekeeping', 'work_session', 'create', 274),
    ('timekeeping:work_session:stop', 'timekeeping', 'work_session', 'stop', 275),
    ('vehicle-fitment:catalog:view', 'vehicle-fitment', 'catalog', 'view', 169),
    ('vehicle-fitment:hint:create', 'vehicle-fitment', 'hint', 'create', 166),
    ('vehicle-fitment:hint:delete', 'vehicle-fitment', 'hint', 'delete', 168),
    ('vehicle-fitment:hint:update', 'vehicle-fitment', 'hint', 'update', 167),
    ('vehicle-fitment:hint:view', 'vehicle-fitment', 'hint', 'view', 165),
    ('vehicle-inventory:preferences:manage', 'vehicle-inventory', 'preferences', 'manage', 174),
    ('vehicle-inventory:registry:create', 'vehicle-inventory', 'registry', 'create', 171),
    ('vehicle-inventory:registry:delete', 'vehicle-inventory', 'registry', 'delete', 173),
    ('vehicle-inventory:registry:update', 'vehicle-inventory', 'registry', 'update', 172),
    ('vehicle-inventory:registry:view', 'vehicle-inventory', 'registry', 'view', 170),
    ('vehicle-inventory:search:view', 'vehicle-inventory', 'search', 'view', 175),
    ('workorder:approval_config:create', 'workorder', 'approval_config', 'create', 204),
    ('workorder:approval_config:delete', 'workorder', 'approval_config', 'delete', 206),
    ('workorder:approval_config:edit', 'workorder', 'approval_config', 'edit', 205),
    ('workorder:approval_config:view', 'workorder', 'approval_config', 'view', 203),
    ('workorder:change_request:approve', 'workorder', 'change_request', 'approve', 200),
    ('workorder:change_request:create', 'workorder', 'change_request', 'create', 199),
    ('workorder:change_request:decline', 'workorder', 'change_request', 'decline', 201),
    ('workorder:change_request:emergency_override', 'workorder', 'change_request', 'emergency_override', 202),
    ('workorder:change_request:view', 'workorder', 'change_request', 'view', 198),
    ('workorder:dashboard:view', 'workorder', 'dashboard', 'view', 279),
    ('workorder:estimate:approve', 'workorder', 'estimate', 'approve', 188),
    ('workorder:estimate:calculate', 'workorder', 'estimate', 'calculate', 191),
    ('workorder:estimate:create', 'workorder', 'estimate', 'create', 185),
    ('workorder:estimate:decline', 'workorder', 'estimate', 'decline', 189),
    ('workorder:estimate:delete', 'workorder', 'estimate', 'delete', 187),
    ('workorder:estimate:edit', 'workorder', 'estimate', 'edit', 186),
    ('workorder:estimate:promote', 'workorder', 'estimate', 'promote', 281),
    ('workorder:estimate:reopen', 'workorder', 'estimate', 'reopen', 190),
    ('workorder:estimate:submit', 'workorder', 'estimate', 'submit', 280),
    ('workorder:estimate:view', 'workorder', 'estimate', 'view', 184),
    ('workorder:estimate_item:add', 'workorder', 'estimate_item', 'add', 193),
    ('workorder:estimate_item:delete', 'workorder', 'estimate_item', 'delete', 195),
    ('workorder:estimate_item:edit', 'workorder', 'estimate_item', 'edit', 194),
    ('workorder:estimate_item:view', 'workorder', 'estimate_item', 'view', 192),
    ('workorder:estimate_snapshot:create', 'workorder', 'estimate_snapshot', 'create', 196),
    ('workorder:estimate_snapshot:view', 'workorder', 'estimate_snapshot', 'view', 197),
    ('workorder:invoice:create', 'workorder', 'invoice', 'create', 208),
    ('workorder:invoice:view', 'workorder', 'invoice', 'view', 207),
    ('workorder:labor:add', 'workorder', 'labor', 'add', 210),
    ('workorder:labor:view', 'workorder', 'labor', 'view', 209),
    ('workorder:operationalContext:override', 'workorder', 'operationalContext', 'override', 327),
    ('workorder:parts:add', 'workorder', 'parts', 'add', 212),
    ('workorder:parts:consume', 'workorder', 'parts', 'consume', 261),
    ('workorder:parts:view', 'workorder', 'parts', 'view', 211),
    ('workorder:start', 'workorder', '', 'start', 284),
    ('workorder:timeEntry:approve', 'workorder', 'timeEntry', 'approve', 343),
    ('workorder:timeEntry:reject', 'workorder', 'timeEntry', 'reject', 344),
    ('workorder:wip:view', 'workorder', 'wip', 'view', 213),
    ('workorder:wip:view_all_locations', 'workorder', 'wip', 'view_all_locations', 214),
    ('workorder:workorder:approve', 'workorder', 'workorder', 'approve', 183),
    ('workorder:workorder:assign-technician', 'workorder', 'workorder', 'assign-technician', 282),
    ('workorder:workorder:complete', 'workorder', 'workorder', 'complete', 181),
    ('workorder:workorder:create', 'workorder', 'workorder', 'create', 177),
    ('workorder:workorder:delete', 'workorder', 'workorder', 'delete', 179),
    ('workorder:workorder:edit', 'workorder', 'workorder', 'edit', 178),
    ('workorder:workorder:generate_invoice', 'workorder', 'workorder', 'generate_invoice', 283),
    ('workorder:workorder:reopen_completed', 'workorder', 'workorder', 'reopen_completed', 182),
    ('workorder:workorder:start', 'workorder', 'workorder', 'start', 180),
    ('workorder:workorder:view', 'workorder', 'workorder', 'view', 176)
) AS c(name, domain, resource, action, bit_index)
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3. Role -> permission grants, resolved by name.
-- ---------------------------------------------------------------------------
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM (VALUES
    ('ACCOUNTING_ASSOCIATE', 'accounting:ap:approve'),
    ('ACCOUNTING_ASSOCIATE', 'accounting:ap:pay'),
    ('ACCOUNTING_ASSOCIATE', 'accounting:ap:reject'),
    ('ACCOUNTING_ASSOCIATE', 'accounting:ap:view'),
    ('ACCOUNTING_ASSOCIATE', 'accounting:coa:view'),
    ('ACCOUNTING_ASSOCIATE', 'accounting:events:view'),
    ('ACCOUNTING_ASSOCIATE', 'accounting:export:view'),
    ('ACCOUNTING_ASSOCIATE', 'accounting:je:view'),
    ('ACCOUNTING_ASSOCIATE', 'accounting:mapping:view'),
    ('ACCOUNTING_ASSOCIATE', 'accounting:posting_rules:view'),
    ('ACCOUNTING_ASSOCIATE', 'mcp:chat:execute'),
    ('ACCOUNTING_ASSOCIATE', 'mcp:chat:stream'),
    ('ACCOUNTING_ASSOCIATE', 'nlti:request:read'),
    ('ACCOUNTING_ASSOCIATE', 'nlti:request:submit'),
    ('ACCOUNT_MANAGER', 'accounting:ap:approve'),
    ('ACCOUNT_MANAGER', 'accounting:ap:pay'),
    ('ACCOUNT_MANAGER', 'accounting:ap:reject'),
    ('ACCOUNT_MANAGER', 'accounting:ap:view'),
    ('ACCOUNT_MANAGER', 'accounting:coa:create'),
    ('ACCOUNT_MANAGER', 'accounting:coa:deactivate'),
    ('ACCOUNT_MANAGER', 'accounting:coa:edit'),
    ('ACCOUNT_MANAGER', 'accounting:coa:view'),
    ('ACCOUNT_MANAGER', 'accounting:credit-memo:create'),
    ('ACCOUNT_MANAGER', 'accounting:credit-memo:read'),
    ('ACCOUNT_MANAGER', 'accounting:default-mapping:create'),
    ('ACCOUNT_MANAGER', 'accounting:default-mapping:delete'),
    ('ACCOUNT_MANAGER', 'accounting:default-mapping:edit'),
    ('ACCOUNT_MANAGER', 'accounting:default-mapping:view'),
    ('ACCOUNT_MANAGER', 'accounting:events:reprocess'),
    ('ACCOUNT_MANAGER', 'accounting:events:retry'),
    ('ACCOUNT_MANAGER', 'accounting:events:submit'),
    ('ACCOUNT_MANAGER', 'accounting:events:view'),
    ('ACCOUNT_MANAGER', 'accounting:export:view'),
    ('ACCOUNT_MANAGER', 'accounting:gl-mapping:create'),
    ('ACCOUNT_MANAGER', 'accounting:gl-mapping:resolve'),
    ('ACCOUNT_MANAGER', 'accounting:je:create'),
    ('ACCOUNT_MANAGER', 'accounting:je:post'),
    ('ACCOUNT_MANAGER', 'accounting:je:reverse'),
    ('ACCOUNT_MANAGER', 'accounting:je:view'),
    ('ACCOUNT_MANAGER', 'accounting:mapping-key:create'),
    ('ACCOUNT_MANAGER', 'accounting:mapping-key:deactivate'),
    ('ACCOUNT_MANAGER', 'accounting:mapping-key:edit'),
    ('ACCOUNT_MANAGER', 'accounting:mapping-key:view'),
    ('ACCOUNT_MANAGER', 'accounting:mapping:create'),
    ('ACCOUNT_MANAGER', 'accounting:mapping:deactivate'),
    ('ACCOUNT_MANAGER', 'accounting:mapping:edit'),
    ('ACCOUNT_MANAGER', 'accounting:mapping:view'),
    ('ACCOUNT_MANAGER', 'accounting:payment:apply'),
    ('ACCOUNT_MANAGER', 'accounting:payment:reverse'),
    ('ACCOUNT_MANAGER', 'accounting:posting-category:create'),
    ('ACCOUNT_MANAGER', 'accounting:posting-category:deactivate'),
    ('ACCOUNT_MANAGER', 'accounting:posting-category:edit'),
    ('ACCOUNT_MANAGER', 'accounting:posting-category:view'),
    ('ACCOUNT_MANAGER', 'accounting:posting_rules:create'),
    ('ACCOUNT_MANAGER', 'accounting:posting_rules:publish'),
    ('ACCOUNT_MANAGER', 'accounting:posting_rules:view'),
    ('ACCOUNT_MANAGER', 'invoice:billing-rules'),
    ('ACCOUNT_MANAGER', 'invoice:finalize:override'),
    ('ACCOUNT_MANAGER', 'invoice:manage'),
    ('ACCOUNT_MANAGER', 'mcp:chat:execute'),
    ('ACCOUNT_MANAGER', 'mcp:chat:stream'),
    ('ACCOUNT_MANAGER', 'nlti:request:read'),
    ('ACCOUNT_MANAGER', 'nlti:request:submit'),
    ('ACCOUNT_MANAGER', 'reporting:view:financial-statements'),
    ('ADMIN', 'accounting:ap:approve'),
    ('ADMIN', 'accounting:ap:pay'),
    ('ADMIN', 'accounting:ap:reject'),
    ('ADMIN', 'accounting:ap:view'),
    ('ADMIN', 'accounting:coa:create'),
    ('ADMIN', 'accounting:coa:deactivate'),
    ('ADMIN', 'accounting:coa:edit'),
    ('ADMIN', 'accounting:coa:view'),
    ('ADMIN', 'accounting:credit-memo:create'),
    ('ADMIN', 'accounting:credit-memo:read'),
    ('ADMIN', 'accounting:default-mapping:create'),
    ('ADMIN', 'accounting:default-mapping:delete'),
    ('ADMIN', 'accounting:default-mapping:edit'),
    ('ADMIN', 'accounting:default-mapping:view'),
    ('ADMIN', 'accounting:events:reprocess'),
    ('ADMIN', 'accounting:events:retry'),
    ('ADMIN', 'accounting:events:submit'),
    ('ADMIN', 'accounting:events:view'),
    ('ADMIN', 'accounting:export:request'),
    ('ADMIN', 'accounting:export:view'),
    ('ADMIN', 'accounting:gl-mapping:create'),
    ('ADMIN', 'accounting:gl-mapping:resolve'),
    ('ADMIN', 'accounting:je:create'),
    ('ADMIN', 'accounting:je:post'),
    ('ADMIN', 'accounting:je:reverse'),
    ('ADMIN', 'accounting:je:view'),
    ('ADMIN', 'accounting:mapping-key:create'),
    ('ADMIN', 'accounting:mapping-key:deactivate'),
    ('ADMIN', 'accounting:mapping-key:edit'),
    ('ADMIN', 'accounting:mapping-key:view'),
    ('ADMIN', 'accounting:mapping:create'),
    ('ADMIN', 'accounting:mapping:deactivate'),
    ('ADMIN', 'accounting:mapping:edit'),
    ('ADMIN', 'accounting:mapping:view'),
    ('ADMIN', 'accounting:payment:apply'),
    ('ADMIN', 'accounting:payment:reverse'),
    ('ADMIN', 'accounting:posting-category:create'),
    ('ADMIN', 'accounting:posting-category:deactivate'),
    ('ADMIN', 'accounting:posting-category:edit'),
    ('ADMIN', 'accounting:posting-category:view'),
    ('ADMIN', 'accounting:posting_rules:archive'),
    ('ADMIN', 'accounting:posting_rules:create'),
    ('ADMIN', 'accounting:posting_rules:publish'),
    ('ADMIN', 'accounting:posting_rules:view'),
    ('ADMIN', 'accounting:report:export'),
    ('ADMIN', 'accounting:time:export'),
    ('ADMIN', 'appointments:cancel'),
    ('ADMIN', 'appointments:create'),
    ('ADMIN', 'appointments:reschedule'),
    ('ADMIN', 'appointments:view'),
    ('ADMIN', 'bulkImport:status:read'),
    ('ADMIN', 'bulkImport:upload:execute'),
    ('ADMIN', 'catalog:category:create'),
    ('ADMIN', 'catalog:category:delete'),
    ('ADMIN', 'catalog:category:edit'),
    ('ADMIN', 'catalog:category:view'),
    ('ADMIN', 'catalog:msrp:read'),
    ('ADMIN', 'catalog:msrp:write'),
    ('ADMIN', 'catalog:price_book:read'),
    ('ADMIN', 'catalog:price_book:write'),
    ('ADMIN', 'catalog:product:create'),
    ('ADMIN', 'catalog:product:delete'),
    ('ADMIN', 'catalog:product:edit'),
    ('ADMIN', 'catalog:product:view'),
    ('ADMIN', 'catalog:service_type:create'),
    ('ADMIN', 'catalog:service_type:edit'),
    ('ADMIN', 'catalog:service_type:view'),
    ('ADMIN', 'catalog:supplier_cost:read'),
    ('ADMIN', 'catalog:supplier_cost:write'),
    ('ADMIN', 'catalog:variant:create'),
    ('ADMIN', 'catalog:variant:edit'),
    ('ADMIN', 'catalog:variant:view'),
    ('ADMIN', 'crm:billing_rules:edit'),
    ('ADMIN', 'crm:contact:create'),
    ('ADMIN', 'crm:contact:delete'),
    ('ADMIN', 'crm:contact:edit'),
    ('ADMIN', 'crm:contact:view'),
    ('ADMIN', 'crm:contact_preference:edit'),
    ('ADMIN', 'crm:contact_preference:view'),
    ('ADMIN', 'crm:contact_role:assign'),
    ('ADMIN', 'crm:contact_role:revoke'),
    ('ADMIN', 'crm:contact_role:view'),
    ('ADMIN', 'crm:integration:audit'),
    ('ADMIN', 'crm:party:create'),
    ('ADMIN', 'crm:party:deactivate'),
    ('ADMIN', 'crm:party:edit'),
    ('ADMIN', 'crm:party:merge'),
    ('ADMIN', 'crm:party:search'),
    ('ADMIN', 'crm:party:view'),
    ('ADMIN', 'crm:person:create'),
    ('ADMIN', 'crm:person:read'),
    ('ADMIN', 'crm:processing_log:view'),
    ('ADMIN', 'crm:promotion_redemption:record'),
    ('ADMIN', 'crm:promotion_redemption:view'),
    ('ADMIN', 'crm:relationship:create'),
    ('ADMIN', 'crm:relationship:delete'),
    ('ADMIN', 'crm:relationship:read'),
    ('ADMIN', 'crm:relationship:update'),
    ('ADMIN', 'crm:suspense:view'),
    ('ADMIN', 'crm:vehicle:create'),
    ('ADMIN', 'crm:vehicle:search'),
    ('ADMIN', 'crm:vehicle:view'),
    ('ADMIN', 'crm:vehicle_party_association:create'),
    ('ADMIN', 'crm:vehicle_party_association:edit'),
    ('ADMIN', 'crm:vehicle_party_association:view'),
    ('ADMIN', 'crm:vehicle_preference:edit'),
    ('ADMIN', 'crm:vehicle_preference:view'),
    ('ADMIN', 'documents:render'),
    ('ADMIN', 'inventory:adjustment:approve'),
    ('ADMIN', 'inventory:adjustment:create'),
    ('ADMIN', 'inventory:adjustment:override'),
    ('ADMIN', 'inventory:adjustment:view'),
    ('ADMIN', 'inventory:allocations:reallocate'),
    ('ADMIN', 'inventory:asn:create'),
    ('ADMIN', 'inventory:asn:view'),
    ('ADMIN', 'inventory:availability:read'),
    ('ADMIN', 'inventory:availability:search'),
    ('ADMIN', 'inventory:cycle_count:complete'),
    ('ADMIN', 'inventory:cycle_count:initiate'),
    ('ADMIN', 'inventory:cycle_count:view'),
    ('ADMIN', 'inventory:goods_receipt:create'),
    ('ADMIN', 'inventory:goods_receipt:override'),
    ('ADMIN', 'inventory:goods_receipt:view'),
    ('ADMIN', 'inventory:issue:parts'),
    ('ADMIN', 'inventory:ledger:view'),
    ('ADMIN', 'inventory:location:admin'),
    ('ADMIN', 'inventory:location:view'),
    ('ADMIN', 'inventory:on_hand:search'),
    ('ADMIN', 'inventory:on_hand:view'),
    ('ADMIN', 'inventory:override:part-match'),
    ('ADMIN', 'inventory:pick_list:create'),
    ('ADMIN', 'inventory:pick_list:execute'),
    ('ADMIN', 'inventory:pick_list:view'),
    ('ADMIN', 'inventory:purchase_order:approve'),
    ('ADMIN', 'inventory:purchase_order:create'),
    ('ADMIN', 'inventory:purchase_order:receive'),
    ('ADMIN', 'inventory:purchase_order:view'),
    ('ADMIN', 'inventory:putaway:claim'),
    ('ADMIN', 'inventory:putaway:execute'),
    ('ADMIN', 'inventory:putaway:generate'),
    ('ADMIN', 'inventory:putaway:override_location_capacity'),
    ('ADMIN', 'inventory:putaway:override_location_compatibility'),
    ('ADMIN', 'inventory:putaway:view'),
    ('ADMIN', 'inventory:receiving:complete'),
    ('ADMIN', 'inventory:receiving:create'),
    ('ADMIN', 'inventory:receiving:view'),
    ('ADMIN', 'inventory:return:view'),
    ('ADMIN', 'inventory:return:write'),
    ('ADMIN', 'inventory:shortage:resolve'),
    ('ADMIN', 'inventory:shortage:view'),
    ('ADMIN', 'inventory:stock_movement:create'),
    ('ADMIN', 'invoice:billing-rules'),
    ('ADMIN', 'invoice:finalize'),
    ('ADMIN', 'invoice:finalize:override'),
    ('ADMIN', 'invoice:manage'),
    ('ADMIN', 'location:bay:manage'),
    ('ADMIN', 'location:bay:read'),
    ('ADMIN', 'location:mobile-unit:manage'),
    ('ADMIN', 'location:mobile-unit:read'),
    ('ADMIN', 'location:read'),
    ('ADMIN', 'location:service-area:manage'),
    ('ADMIN', 'location:service-area:read'),
    ('ADMIN', 'location:travel-buffer-policy:manage'),
    ('ADMIN', 'location:travel-buffer-policy:read'),
    ('ADMIN', 'location:write'),
    ('ADMIN', 'mcp:chat:execute'),
    ('ADMIN', 'mcp:chat:stream'),
    ('ADMIN', 'mcp:document:ingest'),
    ('ADMIN', 'mcp:llm_api:create'),
    ('ADMIN', 'mcp:llm_api:delete'),
    ('ADMIN', 'mcp:llm_api:update'),
    ('ADMIN', 'mcp:llm_api:view'),
    ('ADMIN', 'mcp:system_prompt:create'),
    ('ADMIN', 'mcp:system_prompt:delete'),
    ('ADMIN', 'mcp:system_prompt:update'),
    ('ADMIN', 'mcp:system_prompt:view'),
    ('ADMIN', 'mcp:tool:manage'),
    ('ADMIN', 'mcp:tool:view'),
    ('ADMIN', 'nlti:audit:read'),
    ('ADMIN', 'nlti:request:read'),
    ('ADMIN', 'nlti:request:submit'),
    ('ADMIN', 'order:line:create'),
    ('ADMIN', 'order:line:delete'),
    ('ADMIN', 'order:line:edit'),
    ('ADMIN', 'order:line:enter_manual_price'),
    ('ADMIN', 'order:line:view'),
    ('ADMIN', 'order:order:cancel'),
    ('ADMIN', 'order:order:create'),
    ('ADMIN', 'order:order:edit'),
    ('ADMIN', 'order:order:view'),
    ('ADMIN', 'order:price_override:apply'),
    ('ADMIN', 'order:price_override:approve'),
    ('ADMIN', 'order:price_override:reject'),
    ('ADMIN', 'order:price_override:view'),
    ('ADMIN', 'order:purchase_order:approve'),
    ('ADMIN', 'order:purchase_order:availability_view'),
    ('ADMIN', 'order:purchase_order:create'),
    ('ADMIN', 'order:purchase_order:transmit'),
    ('ADMIN', 'order:purchase_order:view'),
    ('ADMIN', 'people-contact:person:create'),
    ('ADMIN', 'people-contact:person:delete'),
    ('ADMIN', 'people-contact:person:edit'),
    ('ADMIN', 'people-contact:person:view'),
    ('ADMIN', 'people-contact:role:assign'),
    ('ADMIN', 'people-contact:role:revoke'),
    ('ADMIN', 'people-contact:role:view'),
    ('ADMIN', 'people-contact:userLink:view'),
    ('ADMIN', 'people-contact:userLink:write'),
    ('ADMIN', 'people:availability:view'),
    ('ADMIN', 'people:employee:create'),
    ('ADMIN', 'people:employee:deactivate'),
    ('ADMIN', 'people:employee:edit'),
    ('ADMIN', 'people:employee:view'),
    ('ADMIN', 'people:skill:assign'),
    ('ADMIN', 'people:skill:edit'),
    ('ADMIN', 'people:skill:view'),
    ('ADMIN', 'people:timeAdjustment:approve'),
    ('ADMIN', 'people:timeAdjustment:create'),
    ('ADMIN', 'people:timeAdjustment:view'),
    ('ADMIN', 'people:timeEntry:approve'),
    ('ADMIN', 'people:timeEntry:reject'),
    ('ADMIN', 'people:timeException:acknowledge'),
    ('ADMIN', 'people:timeException:create'),
    ('ADMIN', 'people:timeException:resolve'),
    ('ADMIN', 'people:timeException:view'),
    ('ADMIN', 'people:timekeeping:approve'),
    ('ADMIN', 'people:timekeeping:reject'),
    ('ADMIN', 'people:timekeeping:view'),
    ('ADMIN', 'pricing:base_price:create'),
    ('ADMIN', 'pricing:normalization:edit'),
    ('ADMIN', 'pricing:normalization:view'),
    ('ADMIN', 'pricing:override:approve'),
    ('ADMIN', 'pricing:price_book:create'),
    ('ADMIN', 'pricing:price_book:delete'),
    ('ADMIN', 'pricing:price_book:edit'),
    ('ADMIN', 'pricing:price_book:view'),
    ('ADMIN', 'pricing:promotion:apply'),
    ('ADMIN', 'pricing:promotion:manage'),
    ('ADMIN', 'pricing:promotion:view'),
    ('ADMIN', 'pricing:restriction:manage'),
    ('ADMIN', 'pricing:restriction:override'),
    ('ADMIN', 'pricing:restrictions:edit'),
    ('ADMIN', 'pricing:restrictions:view'),
    ('ADMIN', 'pricing:rule:create'),
    ('ADMIN', 'pricing:rule:delete'),
    ('ADMIN', 'pricing:rule:edit'),
    ('ADMIN', 'pricing:rule:view'),
    ('ADMIN', 'product:lifecycle:override_discontinued'),
    ('ADMIN', 'product:lifecycle:update'),
    ('ADMIN', 'reporting:view:financial-statements'),
    ('ADMIN', 'security:audit:create'),
    ('ADMIN', 'security:audit:export'),
    ('ADMIN', 'security:audit:view'),
    ('ADMIN', 'security:authorization:decide'),
    ('ADMIN', 'security:permission:register'),
    ('ADMIN', 'security:permission:view'),
    ('ADMIN', 'security:role:assign'),
    ('ADMIN', 'security:role:create'),
    ('ADMIN', 'security:role:delete'),
    ('ADMIN', 'security:role:edit'),
    ('ADMIN', 'security:role:view'),
    ('ADMIN', 'security:token:issue_internal'),
    ('ADMIN', 'security:user:create'),
    ('ADMIN', 'security:user:delete'),
    ('ADMIN', 'security:user:edit'),
    ('ADMIN', 'security:user:view'),
    ('ADMIN', 'security:user_account_state:manage'),
    ('ADMIN', 'security:user_account_state:view'),
    ('ADMIN', 'shop:bay:assign'),
    ('ADMIN', 'shop:bay:create'),
    ('ADMIN', 'shop:bay:edit'),
    ('ADMIN', 'shop:bay:view'),
    ('ADMIN', 'shop:location:create'),
    ('ADMIN', 'shop:location:deactivate'),
    ('ADMIN', 'shop:location:edit'),
    ('ADMIN', 'shop:location:view'),
    ('ADMIN', 'shop:schedule:edit'),
    ('ADMIN', 'shop:schedule:view'),
    ('ADMIN', 'tax:calculate'),
    ('ADMIN', 'tax:mode:view'),
    ('ADMIN', 'timekeeping:overlap_override'),
    ('ADMIN', 'timekeeping:work_session:break_start'),
    ('ADMIN', 'timekeeping:work_session:break_stop'),
    ('ADMIN', 'timekeeping:work_session:create'),
    ('ADMIN', 'timekeeping:work_session:stop'),
    ('ADMIN', 'vehicle-fitment:catalog:view'),
    ('ADMIN', 'vehicle-fitment:hint:create'),
    ('ADMIN', 'vehicle-fitment:hint:delete'),
    ('ADMIN', 'vehicle-fitment:hint:update'),
    ('ADMIN', 'vehicle-fitment:hint:view'),
    ('ADMIN', 'vehicle-inventory:preferences:manage'),
    ('ADMIN', 'vehicle-inventory:registry:create'),
    ('ADMIN', 'vehicle-inventory:registry:delete'),
    ('ADMIN', 'vehicle-inventory:registry:update'),
    ('ADMIN', 'vehicle-inventory:registry:view'),
    ('ADMIN', 'vehicle-inventory:search:view'),
    ('ADMIN', 'workorder:approval_config:create'),
    ('ADMIN', 'workorder:approval_config:delete'),
    ('ADMIN', 'workorder:approval_config:edit'),
    ('ADMIN', 'workorder:approval_config:view'),
    ('ADMIN', 'workorder:change_request:approve'),
    ('ADMIN', 'workorder:change_request:create'),
    ('ADMIN', 'workorder:change_request:decline'),
    ('ADMIN', 'workorder:change_request:emergency_override'),
    ('ADMIN', 'workorder:change_request:view'),
    ('ADMIN', 'workorder:dashboard:view'),
    ('ADMIN', 'workorder:estimate:approve'),
    ('ADMIN', 'workorder:estimate:calculate'),
    ('ADMIN', 'workorder:estimate:create'),
    ('ADMIN', 'workorder:estimate:decline'),
    ('ADMIN', 'workorder:estimate:delete'),
    ('ADMIN', 'workorder:estimate:edit'),
    ('ADMIN', 'workorder:estimate:promote'),
    ('ADMIN', 'workorder:estimate:reopen'),
    ('ADMIN', 'workorder:estimate:submit'),
    ('ADMIN', 'workorder:estimate:view'),
    ('ADMIN', 'workorder:estimate_item:add'),
    ('ADMIN', 'workorder:estimate_item:delete'),
    ('ADMIN', 'workorder:estimate_item:edit'),
    ('ADMIN', 'workorder:estimate_item:view'),
    ('ADMIN', 'workorder:estimate_snapshot:create'),
    ('ADMIN', 'workorder:estimate_snapshot:view'),
    ('ADMIN', 'workorder:invoice:create'),
    ('ADMIN', 'workorder:invoice:view'),
    ('ADMIN', 'workorder:labor:add'),
    ('ADMIN', 'workorder:labor:view'),
    ('ADMIN', 'workorder:operationalContext:override'),
    ('ADMIN', 'workorder:parts:add'),
    ('ADMIN', 'workorder:parts:consume'),
    ('ADMIN', 'workorder:parts:view'),
    ('ADMIN', 'workorder:start'),
    ('ADMIN', 'workorder:timeEntry:approve'),
    ('ADMIN', 'workorder:timeEntry:reject'),
    ('ADMIN', 'workorder:wip:view'),
    ('ADMIN', 'workorder:wip:view_all_locations'),
    ('ADMIN', 'workorder:workorder:approve'),
    ('ADMIN', 'workorder:workorder:assign-technician'),
    ('ADMIN', 'workorder:workorder:complete'),
    ('ADMIN', 'workorder:workorder:create'),
    ('ADMIN', 'workorder:workorder:delete'),
    ('ADMIN', 'workorder:workorder:edit'),
    ('ADMIN', 'workorder:workorder:generate_invoice'),
    ('ADMIN', 'workorder:workorder:reopen_completed'),
    ('ADMIN', 'workorder:workorder:start'),
    ('ADMIN', 'workorder:workorder:view'),
    ('CUSTOMER', 'mcp:chat:execute'),
    ('CUSTOMER', 'mcp:chat:stream'),
    ('CUSTOMER', 'nlti:request:read'),
    ('CUSTOMER', 'nlti:request:submit'),
    ('DISPATCHER', 'appointments:cancel'),
    ('DISPATCHER', 'appointments:create'),
    ('DISPATCHER', 'appointments:reschedule'),
    ('DISPATCHER', 'appointments:view'),
    ('DISPATCHER', 'mcp:chat:execute'),
    ('DISPATCHER', 'mcp:chat:stream'),
    ('DISPATCHER', 'nlti:request:read'),
    ('DISPATCHER', 'nlti:request:submit'),
    ('DISPATCHER', 'people:availability:view'),
    ('DISPATCHER', 'shop:bay:assign'),
    ('DISPATCHER', 'shop:bay:view'),
    ('DISPATCHER', 'shop:location:view'),
    ('DISPATCHER', 'shop:schedule:edit'),
    ('DISPATCHER', 'shop:schedule:view'),
    ('DISPATCHER', 'shop:technician:view'),
    ('DISPATCHER', 'workorder:workorder:assign-technician'),
    ('DISPATCHER', 'workorder:workorder:view'),
    ('GENERAL_MANAGER', 'catalog:category:view'),
    ('GENERAL_MANAGER', 'catalog:product:view'),
    ('GENERAL_MANAGER', 'invoice:finalize:override'),
    ('GENERAL_MANAGER', 'mcp:chat:execute'),
    ('GENERAL_MANAGER', 'mcp:chat:stream'),
    ('GENERAL_MANAGER', 'nlti:request:read'),
    ('GENERAL_MANAGER', 'nlti:request:submit'),
    ('GENERAL_MANAGER', 'order:order:view'),
    ('GENERAL_MANAGER', 'people:timekeeping:approve'),
    ('GENERAL_MANAGER', 'people:timekeeping:reject'),
    ('GENERAL_MANAGER', 'people:timekeeping:view'),
    ('GENERAL_MANAGER', 'pricing:price_book:view'),
    ('GENERAL_MANAGER', 'pricing:promotion:apply'),
    ('GENERAL_MANAGER', 'pricing:promotion:manage'),
    ('GENERAL_MANAGER', 'pricing:promotion:view'),
    ('GENERAL_MANAGER', 'pricing:rule:view'),
    ('GENERAL_MANAGER', 'security:permission:view'),
    ('GENERAL_MANAGER', 'security:role:assign'),
    ('GENERAL_MANAGER', 'security:role:view'),
    ('GENERAL_MANAGER', 'workorder:timeEntry:approve'),
    ('GENERAL_MANAGER', 'workorder:timeEntry:reject'),
    ('GENERAL_MANAGER', 'workorder:workorder:delete'),
    ('INVENTORY_CONTROLLER', 'catalog:category:view'),
    ('INVENTORY_CONTROLLER', 'catalog:product:view'),
    ('INVENTORY_CONTROLLER', 'inventory:adjustment:approve'),
    ('INVENTORY_CONTROLLER', 'inventory:adjustment:create'),
    ('INVENTORY_CONTROLLER', 'inventory:adjustment:override'),
    ('INVENTORY_CONTROLLER', 'inventory:adjustment:view'),
    ('INVENTORY_CONTROLLER', 'mcp:chat:execute'),
    ('INVENTORY_CONTROLLER', 'mcp:chat:stream'),
    ('INVENTORY_CONTROLLER', 'nlti:request:read'),
    ('INVENTORY_CONTROLLER', 'nlti:request:submit'),
    ('INVENTORY_CONTROLLER', 'order:order:view'),
    ('INVENTORY_CONTROLLER', 'pricing:price_book:view'),
    ('INVENTORY_CONTROLLER', 'pricing:rule:view'),
    ('INVENTORY_LEAD', 'catalog:category:view'),
    ('INVENTORY_LEAD', 'catalog:product:view'),
    ('INVENTORY_LEAD', 'inventory:adjustment:create'),
    ('INVENTORY_LEAD', 'inventory:adjustment:view'),
    ('INVENTORY_LEAD', 'inventory:asn:create'),
    ('INVENTORY_LEAD', 'inventory:asn:view'),
    ('INVENTORY_LEAD', 'inventory:availability:read'),
    ('INVENTORY_LEAD', 'inventory:availability:search'),
    ('INVENTORY_LEAD', 'inventory:goods_receipt:create'),
    ('INVENTORY_LEAD', 'inventory:goods_receipt:view'),
    ('INVENTORY_LEAD', 'inventory:issue:parts'),
    ('INVENTORY_LEAD', 'inventory:on_hand:search'),
    ('INVENTORY_LEAD', 'inventory:on_hand:view'),
    ('INVENTORY_LEAD', 'inventory:putaway:claim'),
    ('INVENTORY_LEAD', 'inventory:putaway:execute'),
    ('INVENTORY_LEAD', 'inventory:putaway:generate'),
    ('INVENTORY_LEAD', 'inventory:putaway:view'),
    ('INVENTORY_LEAD', 'inventory:receiving:complete'),
    ('INVENTORY_LEAD', 'inventory:receiving:create'),
    ('INVENTORY_LEAD', 'inventory:receiving:view'),
    ('INVENTORY_LEAD', 'inventory:shortage:resolve'),
    ('INVENTORY_LEAD', 'inventory:shortage:view'),
    ('INVENTORY_LEAD', 'mcp:chat:execute'),
    ('INVENTORY_LEAD', 'mcp:chat:stream'),
    ('INVENTORY_LEAD', 'nlti:request:read'),
    ('INVENTORY_LEAD', 'nlti:request:submit'),
    ('INVENTORY_LEAD', 'order:order:view'),
    ('INVENTORY_LEAD', 'order:purchase_order:availability_view'),
    ('INVENTORY_LEAD', 'order:purchase_order:create'),
    ('INVENTORY_LEAD', 'order:purchase_order:view'),
    ('INVENTORY_LEAD', 'pricing:price_book:view'),
    ('INVENTORY_LEAD', 'pricing:rule:view'),
    ('INVENTORY_MANAGER', 'catalog:category:view'),
    ('INVENTORY_MANAGER', 'catalog:product:view'),
    ('INVENTORY_MANAGER', 'inventory:adjustment:approve'),
    ('INVENTORY_MANAGER', 'inventory:adjustment:create'),
    ('INVENTORY_MANAGER', 'inventory:adjustment:view'),
    ('INVENTORY_MANAGER', 'mcp:chat:execute'),
    ('INVENTORY_MANAGER', 'mcp:chat:stream'),
    ('INVENTORY_MANAGER', 'nlti:request:read'),
    ('INVENTORY_MANAGER', 'nlti:request:submit'),
    ('INVENTORY_MANAGER', 'order:order:view'),
    ('INVENTORY_MANAGER', 'order:purchase_order:approve'),
    ('INVENTORY_MANAGER', 'order:purchase_order:availability_view'),
    ('INVENTORY_MANAGER', 'order:purchase_order:transmit'),
    ('INVENTORY_MANAGER', 'order:purchase_order:view'),
    ('INVENTORY_MANAGER', 'pricing:price_book:view'),
    ('INVENTORY_MANAGER', 'pricing:rule:view'),
    ('LOCATION_MANAGER', 'appointments:cancel'),
    ('LOCATION_MANAGER', 'appointments:create'),
    ('LOCATION_MANAGER', 'appointments:reschedule'),
    ('LOCATION_MANAGER', 'appointments:view'),
    ('LOCATION_MANAGER', 'catalog:category:view'),
    ('LOCATION_MANAGER', 'catalog:product:view'),
    ('LOCATION_MANAGER', 'crm:vehicle:search'),
    ('LOCATION_MANAGER', 'crm:vehicle:view'),
    ('LOCATION_MANAGER', 'inventory:availability:read'),
    ('LOCATION_MANAGER', 'inventory:pick_list:create'),
    ('LOCATION_MANAGER', 'inventory:pick_list:execute'),
    ('LOCATION_MANAGER', 'inventory:pick_list:view'),
    ('LOCATION_MANAGER', 'invoice:finalize'),
    ('LOCATION_MANAGER', 'invoice:finalize:override'),
    ('LOCATION_MANAGER', 'invoice:manage'),
    ('LOCATION_MANAGER', 'mcp:chat:execute'),
    ('LOCATION_MANAGER', 'mcp:chat:stream'),
    ('LOCATION_MANAGER', 'nlti:request:read'),
    ('LOCATION_MANAGER', 'nlti:request:submit'),
    ('LOCATION_MANAGER', 'order:order:view'),
    ('LOCATION_MANAGER', 'order:purchase_order:approve'),
    ('LOCATION_MANAGER', 'order:purchase_order:availability_view'),
    ('LOCATION_MANAGER', 'order:purchase_order:transmit'),
    ('LOCATION_MANAGER', 'order:purchase_order:view'),
    ('LOCATION_MANAGER', 'people:availability:view'),
    ('LOCATION_MANAGER', 'people:timeAdjustment:approve'),
    ('LOCATION_MANAGER', 'people:timeAdjustment:create'),
    ('LOCATION_MANAGER', 'people:timeAdjustment:view'),
    ('LOCATION_MANAGER', 'people:timeEntry:approve'),
    ('LOCATION_MANAGER', 'people:timeEntry:reject'),
    ('LOCATION_MANAGER', 'people:timeException:acknowledge'),
    ('LOCATION_MANAGER', 'people:timeException:create'),
    ('LOCATION_MANAGER', 'people:timeException:resolve'),
    ('LOCATION_MANAGER', 'people:timeException:view'),
    ('LOCATION_MANAGER', 'people:timekeeping:approve'),
    ('LOCATION_MANAGER', 'people:timekeeping:reject'),
    ('LOCATION_MANAGER', 'people:timekeeping:view'),
    ('LOCATION_MANAGER', 'pricing:price_book:view'),
    ('LOCATION_MANAGER', 'pricing:promotion:apply'),
    ('LOCATION_MANAGER', 'pricing:promotion:manage'),
    ('LOCATION_MANAGER', 'pricing:promotion:view'),
    ('LOCATION_MANAGER', 'pricing:rule:view'),
    ('LOCATION_MANAGER', 'shop:bay:assign'),
    ('LOCATION_MANAGER', 'shop:bay:create'),
    ('LOCATION_MANAGER', 'shop:bay:edit'),
    ('LOCATION_MANAGER', 'shop:bay:view'),
    ('LOCATION_MANAGER', 'shop:location:create'),
    ('LOCATION_MANAGER', 'shop:location:edit'),
    ('LOCATION_MANAGER', 'shop:location:view'),
    ('LOCATION_MANAGER', 'shop:schedule:edit'),
    ('LOCATION_MANAGER', 'shop:schedule:view'),
    ('LOCATION_MANAGER', 'timekeeping:overlap_override'),
    ('LOCATION_MANAGER', 'vehicle-inventory:registry:create'),
    ('LOCATION_MANAGER', 'vehicle-inventory:registry:view'),
    ('LOCATION_MANAGER', 'workorder:approval_config:create'),
    ('LOCATION_MANAGER', 'workorder:approval_config:edit'),
    ('LOCATION_MANAGER', 'workorder:approval_config:view'),
    ('LOCATION_MANAGER', 'workorder:change_request:approve'),
    ('LOCATION_MANAGER', 'workorder:change_request:create'),
    ('LOCATION_MANAGER', 'workorder:change_request:decline'),
    ('LOCATION_MANAGER', 'workorder:change_request:emergency_override'),
    ('LOCATION_MANAGER', 'workorder:change_request:view'),
    ('LOCATION_MANAGER', 'workorder:dashboard:view'),
    ('LOCATION_MANAGER', 'workorder:estimate:approve'),
    ('LOCATION_MANAGER', 'workorder:estimate:calculate'),
    ('LOCATION_MANAGER', 'workorder:estimate:create'),
    ('LOCATION_MANAGER', 'workorder:estimate:decline'),
    ('LOCATION_MANAGER', 'workorder:estimate:edit'),
    ('LOCATION_MANAGER', 'workorder:estimate:promote'),
    ('LOCATION_MANAGER', 'workorder:estimate:reopen'),
    ('LOCATION_MANAGER', 'workorder:estimate:submit'),
    ('LOCATION_MANAGER', 'workorder:estimate:view'),
    ('LOCATION_MANAGER', 'workorder:estimate_item:add'),
    ('LOCATION_MANAGER', 'workorder:estimate_item:delete'),
    ('LOCATION_MANAGER', 'workorder:estimate_item:edit'),
    ('LOCATION_MANAGER', 'workorder:estimate_item:view'),
    ('LOCATION_MANAGER', 'workorder:estimate_snapshot:create'),
    ('LOCATION_MANAGER', 'workorder:estimate_snapshot:view'),
    ('LOCATION_MANAGER', 'workorder:invoice:create'),
    ('LOCATION_MANAGER', 'workorder:invoice:view'),
    ('LOCATION_MANAGER', 'workorder:labor:view'),
    ('LOCATION_MANAGER', 'workorder:operationalContext:override'),
    ('LOCATION_MANAGER', 'workorder:parts:add'),
    ('LOCATION_MANAGER', 'workorder:parts:consume'),
    ('LOCATION_MANAGER', 'workorder:parts:view'),
    ('LOCATION_MANAGER', 'workorder:start'),
    ('LOCATION_MANAGER', 'workorder:timeEntry:approve'),
    ('LOCATION_MANAGER', 'workorder:timeEntry:reject'),
    ('LOCATION_MANAGER', 'workorder:wip:view'),
    ('LOCATION_MANAGER', 'workorder:workorder:approve'),
    ('LOCATION_MANAGER', 'workorder:workorder:assign-technician'),
    ('LOCATION_MANAGER', 'workorder:workorder:complete'),
    ('LOCATION_MANAGER', 'workorder:workorder:create'),
    ('LOCATION_MANAGER', 'workorder:workorder:delete'),
    ('LOCATION_MANAGER', 'workorder:workorder:edit'),
    ('LOCATION_MANAGER', 'workorder:workorder:generate_invoice'),
    ('LOCATION_MANAGER', 'workorder:workorder:reopen_completed'),
    ('LOCATION_MANAGER', 'workorder:workorder:view'),
    ('MANAGER', 'invoice:finalize:override'),
    ('MANAGER', 'mcp:chat:execute'),
    ('MANAGER', 'mcp:chat:stream'),
    ('MANAGER', 'nlti:request:read'),
    ('MANAGER', 'nlti:request:submit'),
    ('MANAGER', 'people:timekeeping:approve'),
    ('MANAGER', 'people:timekeeping:reject'),
    ('MANAGER', 'people:timekeeping:view'),
    ('MANAGER', 'pricing:promotion:apply'),
    ('MANAGER', 'pricing:promotion:manage'),
    ('MANAGER', 'pricing:promotion:view'),
    ('MANAGER', 'security:permission:view'),
    ('MANAGER', 'security:role:assign'),
    ('MANAGER', 'security:role:view'),
    ('MANAGER', 'workorder:timeEntry:approve'),
    ('MANAGER', 'workorder:timeEntry:reject'),
    ('MANAGER', 'workorder:workorder:delete'),
    ('SELF_SERVICE_CUSTOMER', 'mcp:chat:execute'),
    ('SELF_SERVICE_CUSTOMER', 'mcp:chat:stream'),
    ('SELF_SERVICE_CUSTOMER', 'nlti:request:read'),
    ('SELF_SERVICE_CUSTOMER', 'nlti:request:submit'),
    ('SERVICE_ADVISOR', 'appointments:cancel'),
    ('SERVICE_ADVISOR', 'appointments:create'),
    ('SERVICE_ADVISOR', 'appointments:reschedule'),
    ('SERVICE_ADVISOR', 'appointments:view'),
    ('SERVICE_ADVISOR', 'crm:party:create'),
    ('SERVICE_ADVISOR', 'crm:party:search'),
    ('SERVICE_ADVISOR', 'crm:party:view'),
    ('SERVICE_ADVISOR', 'crm:person:create'),
    ('SERVICE_ADVISOR', 'crm:person:read'),
    ('SERVICE_ADVISOR', 'crm:vehicle:create'),
    ('SERVICE_ADVISOR', 'crm:vehicle:search'),
    ('SERVICE_ADVISOR', 'crm:vehicle:view'),
    ('SERVICE_ADVISOR', 'inventory:availability:read'),
    ('SERVICE_ADVISOR', 'invoice:finalize'),
    ('SERVICE_ADVISOR', 'invoice:manage'),
    ('SERVICE_ADVISOR', 'mcp:chat:execute'),
    ('SERVICE_ADVISOR', 'mcp:chat:stream'),
    ('SERVICE_ADVISOR', 'nlti:request:read'),
    ('SERVICE_ADVISOR', 'nlti:request:submit'),
    ('SERVICE_ADVISOR', 'pricing:promotion:view'),
    ('SERVICE_ADVISOR', 'shop:bay:view'),
    ('SERVICE_ADVISOR', 'shop:location:view'),
    ('SERVICE_ADVISOR', 'shop:schedule:view'),
    ('SERVICE_ADVISOR', 'vehicle-inventory:registry:create'),
    ('SERVICE_ADVISOR', 'vehicle-inventory:registry:view'),
    ('SERVICE_ADVISOR', 'workorder:change_request:approve'),
    ('SERVICE_ADVISOR', 'workorder:change_request:create'),
    ('SERVICE_ADVISOR', 'workorder:change_request:decline'),
    ('SERVICE_ADVISOR', 'workorder:change_request:view'),
    ('SERVICE_ADVISOR', 'workorder:estimate:approve'),
    ('SERVICE_ADVISOR', 'workorder:estimate:calculate'),
    ('SERVICE_ADVISOR', 'workorder:estimate:create'),
    ('SERVICE_ADVISOR', 'workorder:estimate:decline'),
    ('SERVICE_ADVISOR', 'workorder:estimate:edit'),
    ('SERVICE_ADVISOR', 'workorder:estimate:promote'),
    ('SERVICE_ADVISOR', 'workorder:estimate:reopen'),
    ('SERVICE_ADVISOR', 'workorder:estimate:submit'),
    ('SERVICE_ADVISOR', 'workorder:estimate:view'),
    ('SERVICE_ADVISOR', 'workorder:estimate_item:add'),
    ('SERVICE_ADVISOR', 'workorder:estimate_item:delete'),
    ('SERVICE_ADVISOR', 'workorder:estimate_item:edit'),
    ('SERVICE_ADVISOR', 'workorder:estimate_item:view'),
    ('SERVICE_ADVISOR', 'workorder:estimate_snapshot:create'),
    ('SERVICE_ADVISOR', 'workorder:estimate_snapshot:view'),
    ('SERVICE_ADVISOR', 'workorder:invoice:create'),
    ('SERVICE_ADVISOR', 'workorder:invoice:view'),
    ('SERVICE_ADVISOR', 'workorder:labor:view'),
    ('SERVICE_ADVISOR', 'workorder:parts:view'),
    ('SERVICE_ADVISOR', 'workorder:timeEntry:approve'),
    ('SERVICE_ADVISOR', 'workorder:timeEntry:reject'),
    ('SERVICE_ADVISOR', 'workorder:wip:view'),
    ('SERVICE_ADVISOR', 'workorder:workorder:approve'),
    ('SERVICE_ADVISOR', 'workorder:workorder:complete'),
    ('SERVICE_ADVISOR', 'workorder:workorder:create'),
    ('SERVICE_ADVISOR', 'workorder:workorder:generate_invoice'),
    ('SERVICE_ADVISOR', 'workorder:workorder:view'),
    ('SHOP_MANAGER', 'invoice:finalize:override'),
    ('SHOP_MANAGER', 'mcp:chat:execute'),
    ('SHOP_MANAGER', 'mcp:chat:stream'),
    ('SHOP_MANAGER', 'nlti:request:read'),
    ('SHOP_MANAGER', 'nlti:request:submit'),
    ('SHOP_MANAGER', 'shop:bay:assign'),
    ('SHOP_MANAGER', 'shop:bay:view'),
    ('SHOP_MANAGER', 'shop:location:view'),
    ('SHOP_MANAGER', 'shop:schedule:edit'),
    ('SHOP_MANAGER', 'shop:schedule:view'),
    ('SHOP_MANAGER', 'shop:technician:view'),
    ('SHOP_MANAGER', 'workorder:workorder:delete'),
    ('SYSTEM_ADMINISTRATOR', 'mcp:chat:execute'),
    ('SYSTEM_ADMINISTRATOR', 'mcp:chat:stream'),
    ('SYSTEM_ADMINISTRATOR', 'mcp:document:ingest'),
    ('SYSTEM_ADMINISTRATOR', 'mcp:llm_api:create'),
    ('SYSTEM_ADMINISTRATOR', 'mcp:llm_api:delete'),
    ('SYSTEM_ADMINISTRATOR', 'mcp:llm_api:update'),
    ('SYSTEM_ADMINISTRATOR', 'mcp:llm_api:view'),
    ('SYSTEM_ADMINISTRATOR', 'mcp:system_prompt:create'),
    ('SYSTEM_ADMINISTRATOR', 'mcp:system_prompt:delete'),
    ('SYSTEM_ADMINISTRATOR', 'mcp:system_prompt:update'),
    ('SYSTEM_ADMINISTRATOR', 'mcp:system_prompt:view'),
    ('SYSTEM_ADMINISTRATOR', 'mcp:tool:manage'),
    ('SYSTEM_ADMINISTRATOR', 'mcp:tool:view'),
    ('SYSTEM_ADMINISTRATOR', 'nlti:audit:read'),
    ('SYSTEM_ADMINISTRATOR', 'nlti:request:read'),
    ('SYSTEM_ADMINISTRATOR', 'nlti:request:submit'),
    ('SYSTEM_ADMINISTRATOR', 'security:audit:create'),
    ('SYSTEM_ADMINISTRATOR', 'security:audit:export'),
    ('SYSTEM_ADMINISTRATOR', 'security:audit:view'),
    ('SYSTEM_ADMINISTRATOR', 'security:authorization:decide'),
    ('SYSTEM_ADMINISTRATOR', 'security:permission:register'),
    ('SYSTEM_ADMINISTRATOR', 'security:permission:view'),
    ('SYSTEM_ADMINISTRATOR', 'security:role:assign'),
    ('SYSTEM_ADMINISTRATOR', 'security:role:create'),
    ('SYSTEM_ADMINISTRATOR', 'security:role:delete'),
    ('SYSTEM_ADMINISTRATOR', 'security:role:edit'),
    ('SYSTEM_ADMINISTRATOR', 'security:role:view'),
    ('SYSTEM_ADMINISTRATOR', 'security:token:issue_internal'),
    ('SYSTEM_ADMINISTRATOR', 'security:user:create'),
    ('SYSTEM_ADMINISTRATOR', 'security:user:delete'),
    ('SYSTEM_ADMINISTRATOR', 'security:user:edit'),
    ('SYSTEM_ADMINISTRATOR', 'security:user:view'),
    ('SYSTEM_ADMINISTRATOR', 'security:user_account_state:manage'),
    ('SYSTEM_ADMINISTRATOR', 'security:user_account_state:view'),
    ('TECHNICIAN', 'inventory:availability:read'),
    ('TECHNICIAN', 'inventory:pick_list:execute'),
    ('TECHNICIAN', 'inventory:pick_list:view'),
    ('TECHNICIAN', 'mcp:chat:execute'),
    ('TECHNICIAN', 'mcp:chat:stream'),
    ('TECHNICIAN', 'nlti:request:read'),
    ('TECHNICIAN', 'nlti:request:submit'),
    ('TECHNICIAN', 'people:timeAdjustment:create'),
    ('TECHNICIAN', 'people:timeAdjustment:view'),
    ('TECHNICIAN', 'people:timeException:acknowledge'),
    ('TECHNICIAN', 'people:timeException:create'),
    ('TECHNICIAN', 'people:timeException:view'),
    ('TECHNICIAN', 'shop:schedule:view'),
    ('TECHNICIAN', 'timekeeping:work_session:break_start'),
    ('TECHNICIAN', 'timekeeping:work_session:break_stop'),
    ('TECHNICIAN', 'timekeeping:work_session:create'),
    ('TECHNICIAN', 'timekeeping:work_session:stop'),
    ('TECHNICIAN', 'workorder:change_request:create'),
    ('TECHNICIAN', 'workorder:change_request:view'),
    ('TECHNICIAN', 'workorder:estimate:view'),
    ('TECHNICIAN', 'workorder:estimate_snapshot:view'),
    ('TECHNICIAN', 'workorder:labor:add'),
    ('TECHNICIAN', 'workorder:labor:view'),
    ('TECHNICIAN', 'workorder:parts:add'),
    ('TECHNICIAN', 'workorder:parts:consume'),
    ('TECHNICIAN', 'workorder:parts:view'),
    ('TECHNICIAN', 'workorder:start'),
    ('TECHNICIAN', 'workorder:workorder:view')
) AS g(role_name, permission_name)
JOIN roles r ON r.name = g.role_name
JOIN permissions p ON p.name = g.permission_name
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 4. Fail loudly if any baseline name did not resolve.
--
-- The JOINs above drop unmatched rows silently, which would under-grant
-- authority with no signal. Assert every baseline role and permission resolved,
-- and abort the migration naming what is missing if not.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    missing_roles TEXT;
    missing_permissions TEXT;
BEGIN
    SELECT string_agg(DISTINCT g.role_name, ', ' ORDER BY g.role_name)
      INTO missing_roles
      FROM (VALUES
        ('ACCOUNTING_ASSOCIATE'),
        ('ACCOUNT_MANAGER'),
        ('ADMIN'),
        ('CUSTOMER'),
        ('DISPATCHER'),
        ('GENERAL_MANAGER'),
        ('INVENTORY_CONTROLLER'),
        ('INVENTORY_LEAD'),
        ('INVENTORY_MANAGER'),
        ('LOCATION_MANAGER'),
        ('MANAGER'),
        ('SELF_SERVICE_CUSTOMER'),
        ('SERVICE_ADVISOR'),
        ('SHOP_MANAGER'),
        ('SYSTEM_ADMINISTRATOR'),
        ('TECHNICIAN')
      ) AS g(role_name)
     WHERE NOT EXISTS (SELECT 1 FROM roles r WHERE r.name = g.role_name);

    SELECT string_agg(DISTINCT g.permission_name, ', ' ORDER BY g.permission_name)
      INTO missing_permissions
      FROM (VALUES
        ('accounting:ap:approve'),
        ('accounting:ap:pay'),
        ('accounting:ap:reject'),
        ('accounting:ap:view'),
        ('accounting:coa:create'),
        ('accounting:coa:deactivate'),
        ('accounting:coa:edit'),
        ('accounting:coa:view'),
        ('accounting:credit-memo:create'),
        ('accounting:credit-memo:read'),
        ('accounting:default-mapping:create'),
        ('accounting:default-mapping:delete'),
        ('accounting:default-mapping:edit'),
        ('accounting:default-mapping:view'),
        ('accounting:events:reprocess'),
        ('accounting:events:retry'),
        ('accounting:events:submit'),
        ('accounting:events:view'),
        ('accounting:export:request'),
        ('accounting:export:view'),
        ('accounting:gl-mapping:create'),
        ('accounting:gl-mapping:resolve'),
        ('accounting:je:create'),
        ('accounting:je:post'),
        ('accounting:je:reverse'),
        ('accounting:je:view'),
        ('accounting:mapping-key:create'),
        ('accounting:mapping-key:deactivate'),
        ('accounting:mapping-key:edit'),
        ('accounting:mapping-key:view'),
        ('accounting:mapping:create'),
        ('accounting:mapping:deactivate'),
        ('accounting:mapping:edit'),
        ('accounting:mapping:view'),
        ('accounting:payment:apply'),
        ('accounting:payment:reverse'),
        ('accounting:posting-category:create'),
        ('accounting:posting-category:deactivate'),
        ('accounting:posting-category:edit'),
        ('accounting:posting-category:view'),
        ('accounting:posting_rules:archive'),
        ('accounting:posting_rules:create'),
        ('accounting:posting_rules:publish'),
        ('accounting:posting_rules:view'),
        ('accounting:report:export'),
        ('accounting:time:export'),
        ('appointments:cancel'),
        ('appointments:create'),
        ('appointments:reschedule'),
        ('appointments:view'),
        ('bulkImport:status:read'),
        ('bulkImport:upload:execute'),
        ('catalog:category:create'),
        ('catalog:category:delete'),
        ('catalog:category:edit'),
        ('catalog:category:view'),
        ('catalog:msrp:read'),
        ('catalog:msrp:write'),
        ('catalog:price_book:read'),
        ('catalog:price_book:write'),
        ('catalog:product:create'),
        ('catalog:product:delete'),
        ('catalog:product:edit'),
        ('catalog:product:view'),
        ('catalog:service_type:create'),
        ('catalog:service_type:edit'),
        ('catalog:service_type:view'),
        ('catalog:supplier_cost:read'),
        ('catalog:supplier_cost:write'),
        ('catalog:variant:create'),
        ('catalog:variant:edit'),
        ('catalog:variant:view'),
        ('crm:billing_rules:edit'),
        ('crm:contact:create'),
        ('crm:contact:delete'),
        ('crm:contact:edit'),
        ('crm:contact:view'),
        ('crm:contact_preference:edit'),
        ('crm:contact_preference:view'),
        ('crm:contact_role:assign'),
        ('crm:contact_role:revoke'),
        ('crm:contact_role:view'),
        ('crm:integration:audit'),
        ('crm:party:create'),
        ('crm:party:deactivate'),
        ('crm:party:edit'),
        ('crm:party:merge'),
        ('crm:party:search'),
        ('crm:party:view'),
        ('crm:person:create'),
        ('crm:person:read'),
        ('crm:processing_log:view'),
        ('crm:promotion_redemption:record'),
        ('crm:promotion_redemption:view'),
        ('crm:relationship:create'),
        ('crm:relationship:delete'),
        ('crm:relationship:read'),
        ('crm:relationship:update'),
        ('crm:suspense:view'),
        ('crm:vehicle:create'),
        ('crm:vehicle:search'),
        ('crm:vehicle:view'),
        ('crm:vehicle_party_association:create'),
        ('crm:vehicle_party_association:edit'),
        ('crm:vehicle_party_association:view'),
        ('crm:vehicle_preference:edit'),
        ('crm:vehicle_preference:view'),
        ('documents:render'),
        ('inventory:adjustment:approve'),
        ('inventory:adjustment:create'),
        ('inventory:adjustment:override'),
        ('inventory:adjustment:view'),
        ('inventory:allocations:reallocate'),
        ('inventory:asn:create'),
        ('inventory:asn:view'),
        ('inventory:availability:read'),
        ('inventory:availability:search'),
        ('inventory:cycle_count:complete'),
        ('inventory:cycle_count:initiate'),
        ('inventory:cycle_count:view'),
        ('inventory:goods_receipt:create'),
        ('inventory:goods_receipt:override'),
        ('inventory:goods_receipt:view'),
        ('inventory:issue:parts'),
        ('inventory:ledger:view'),
        ('inventory:location:admin'),
        ('inventory:location:view'),
        ('inventory:on_hand:search'),
        ('inventory:on_hand:view'),
        ('inventory:override:part-match'),
        ('inventory:pick_list:create'),
        ('inventory:pick_list:execute'),
        ('inventory:pick_list:view'),
        ('inventory:purchase_order:approve'),
        ('inventory:purchase_order:create'),
        ('inventory:purchase_order:receive'),
        ('inventory:purchase_order:view'),
        ('inventory:putaway:claim'),
        ('inventory:putaway:execute'),
        ('inventory:putaway:generate'),
        ('inventory:putaway:override_location_capacity'),
        ('inventory:putaway:override_location_compatibility'),
        ('inventory:putaway:view'),
        ('inventory:receiving:complete'),
        ('inventory:receiving:create'),
        ('inventory:receiving:view'),
        ('inventory:return:view'),
        ('inventory:return:write'),
        ('inventory:shortage:resolve'),
        ('inventory:shortage:view'),
        ('inventory:stock_movement:create'),
        ('invoice:billing-rules'),
        ('invoice:finalize'),
        ('invoice:finalize:override'),
        ('invoice:manage'),
        ('location:bay:manage'),
        ('location:bay:read'),
        ('location:mobile-unit:manage'),
        ('location:mobile-unit:read'),
        ('location:read'),
        ('location:service-area:manage'),
        ('location:service-area:read'),
        ('location:travel-buffer-policy:manage'),
        ('location:travel-buffer-policy:read'),
        ('location:write'),
        ('mcp:chat:execute'),
        ('mcp:chat:stream'),
        ('mcp:document:ingest'),
        ('mcp:llm_api:create'),
        ('mcp:llm_api:delete'),
        ('mcp:llm_api:update'),
        ('mcp:llm_api:view'),
        ('mcp:system_prompt:create'),
        ('mcp:system_prompt:delete'),
        ('mcp:system_prompt:update'),
        ('mcp:system_prompt:view'),
        ('mcp:tool:manage'),
        ('mcp:tool:view'),
        ('nlti:audit:read'),
        ('nlti:request:read'),
        ('nlti:request:submit'),
        ('order:line:create'),
        ('order:line:delete'),
        ('order:line:edit'),
        ('order:line:enter_manual_price'),
        ('order:line:view'),
        ('order:order:cancel'),
        ('order:order:create'),
        ('order:order:edit'),
        ('order:order:view'),
        ('order:price_override:apply'),
        ('order:price_override:approve'),
        ('order:price_override:reject'),
        ('order:price_override:view'),
        ('order:purchase_order:approve'),
        ('order:purchase_order:availability_view'),
        ('order:purchase_order:create'),
        ('order:purchase_order:transmit'),
        ('order:purchase_order:view'),
        ('people-contact:person:create'),
        ('people-contact:person:delete'),
        ('people-contact:person:edit'),
        ('people-contact:person:view'),
        ('people-contact:role:assign'),
        ('people-contact:role:revoke'),
        ('people-contact:role:view'),
        ('people-contact:userLink:view'),
        ('people-contact:userLink:write'),
        ('people:availability:view'),
        ('people:employee:create'),
        ('people:employee:deactivate'),
        ('people:employee:edit'),
        ('people:employee:view'),
        ('people:skill:assign'),
        ('people:skill:edit'),
        ('people:skill:view'),
        ('people:timeAdjustment:approve'),
        ('people:timeAdjustment:create'),
        ('people:timeAdjustment:view'),
        ('people:timeEntry:approve'),
        ('people:timeEntry:reject'),
        ('people:timeException:acknowledge'),
        ('people:timeException:create'),
        ('people:timeException:resolve'),
        ('people:timeException:view'),
        ('people:timekeeping:approve'),
        ('people:timekeeping:reject'),
        ('people:timekeeping:view'),
        ('pricing:base_price:create'),
        ('pricing:normalization:edit'),
        ('pricing:normalization:view'),
        ('pricing:override:approve'),
        ('pricing:price_book:create'),
        ('pricing:price_book:delete'),
        ('pricing:price_book:edit'),
        ('pricing:price_book:view'),
        ('pricing:promotion:apply'),
        ('pricing:promotion:manage'),
        ('pricing:promotion:view'),
        ('pricing:restriction:manage'),
        ('pricing:restriction:override'),
        ('pricing:restrictions:edit'),
        ('pricing:restrictions:view'),
        ('pricing:rule:create'),
        ('pricing:rule:delete'),
        ('pricing:rule:edit'),
        ('pricing:rule:view'),
        ('product:lifecycle:override_discontinued'),
        ('product:lifecycle:update'),
        ('reporting:view:financial-statements'),
        ('security:audit:create'),
        ('security:audit:export'),
        ('security:audit:view'),
        ('security:authorization:decide'),
        ('security:permission:register'),
        ('security:permission:view'),
        ('security:role:assign'),
        ('security:role:create'),
        ('security:role:delete'),
        ('security:role:edit'),
        ('security:role:view'),
        ('security:token:issue_internal'),
        ('security:user:create'),
        ('security:user:delete'),
        ('security:user:edit'),
        ('security:user:view'),
        ('security:user_account_state:manage'),
        ('security:user_account_state:view'),
        ('shop:bay:assign'),
        ('shop:bay:create'),
        ('shop:bay:edit'),
        ('shop:bay:view'),
        ('shop:location:create'),
        ('shop:location:deactivate'),
        ('shop:location:edit'),
        ('shop:location:view'),
        ('shop:schedule:edit'),
        ('shop:schedule:view'),
        ('shop:technician:view'),
        ('tax:calculate'),
        ('tax:mode:view'),
        ('timekeeping:overlap_override'),
        ('timekeeping:work_session:break_start'),
        ('timekeeping:work_session:break_stop'),
        ('timekeeping:work_session:create'),
        ('timekeeping:work_session:stop'),
        ('vehicle-fitment:catalog:view'),
        ('vehicle-fitment:hint:create'),
        ('vehicle-fitment:hint:delete'),
        ('vehicle-fitment:hint:update'),
        ('vehicle-fitment:hint:view'),
        ('vehicle-inventory:preferences:manage'),
        ('vehicle-inventory:registry:create'),
        ('vehicle-inventory:registry:delete'),
        ('vehicle-inventory:registry:update'),
        ('vehicle-inventory:registry:view'),
        ('vehicle-inventory:search:view'),
        ('workorder:approval_config:create'),
        ('workorder:approval_config:delete'),
        ('workorder:approval_config:edit'),
        ('workorder:approval_config:view'),
        ('workorder:change_request:approve'),
        ('workorder:change_request:create'),
        ('workorder:change_request:decline'),
        ('workorder:change_request:emergency_override'),
        ('workorder:change_request:view'),
        ('workorder:dashboard:view'),
        ('workorder:estimate:approve'),
        ('workorder:estimate:calculate'),
        ('workorder:estimate:create'),
        ('workorder:estimate:decline'),
        ('workorder:estimate:delete'),
        ('workorder:estimate:edit'),
        ('workorder:estimate:promote'),
        ('workorder:estimate:reopen'),
        ('workorder:estimate:submit'),
        ('workorder:estimate:view'),
        ('workorder:estimate_item:add'),
        ('workorder:estimate_item:delete'),
        ('workorder:estimate_item:edit'),
        ('workorder:estimate_item:view'),
        ('workorder:estimate_snapshot:create'),
        ('workorder:estimate_snapshot:view'),
        ('workorder:invoice:create'),
        ('workorder:invoice:view'),
        ('workorder:labor:add'),
        ('workorder:labor:view'),
        ('workorder:operationalContext:override'),
        ('workorder:parts:add'),
        ('workorder:parts:consume'),
        ('workorder:parts:view'),
        ('workorder:start'),
        ('workorder:timeEntry:approve'),
        ('workorder:timeEntry:reject'),
        ('workorder:wip:view'),
        ('workorder:wip:view_all_locations'),
        ('workorder:workorder:approve'),
        ('workorder:workorder:assign-technician'),
        ('workorder:workorder:complete'),
        ('workorder:workorder:create'),
        ('workorder:workorder:delete'),
        ('workorder:workorder:edit'),
        ('workorder:workorder:generate_invoice'),
        ('workorder:workorder:reopen_completed'),
        ('workorder:workorder:start'),
        ('workorder:workorder:view')
      ) AS g(permission_name)
     WHERE NOT EXISTS (SELECT 1 FROM permissions p WHERE p.name = g.permission_name);

    IF missing_roles IS NOT NULL THEN
        RAISE EXCEPTION 'role_permissions baseline references unknown roles: %', missing_roles;
    END IF;

    IF missing_permissions IS NOT NULL THEN
        RAISE EXCEPTION 'role_permissions baseline references unknown permissions: %', missing_permissions;
    END IF;
END $$;
