-- pos-security-service: Flyway baseline (flattened 2026-09-09 from the previous migration history) with the
-- ADR-0062 tenancy schema folded in. Generated by scripts/db/tenancy/flatten.py from a pg_dump of a
-- database migrated with the retired scripts; the tenancy additions are mechanical and are listed in
-- docs/TENANCY_SCHEMA.md. Global (unscoped) tables: src/main/resources/db/tenancy-global-tables.txt.
--
-- Tenant context: app_current_tenant() reads the session setting app.current_tenant, which the
-- TenantAwareDataSource (pos-tenancy-common, plan WS1) binds per checkout. Until then the owner role
-- carries a transitional default (postgres/init-tenancy.sh) and tests set it per connection.
-- With nothing bound: NULL -> every scoped table reads as empty and refuses inserts (fail closed).

-- Functions are emitted before the tables they reference (pg_dump order); do not validate bodies.
SET check_function_bodies = false;

CREATE OR REPLACE FUNCTION public.app_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$ SELECT NULLIF(current_setting('app.current_tenant', true), '')::uuid $$;

CREATE TABLE public.audit_log_events (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    event_id uuid NOT NULL,
    "timestamp" timestamp with time zone,
    event_type character varying(100),
    actor_id character varying(255),
    entity_id character varying(255),
    entity_type character varying(255),
    old_value text,
    new_value text,
    context text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

CREATE TABLE public.event_outbox (
    id uuid NOT NULL,
    topic character varying(255) NOT NULL,
    record_key character varying(255) NOT NULL,
    payload text NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    published_at timestamp(6) with time zone,
    attempts integer DEFAULT 0 NOT NULL,
    last_error text
);

CREATE TABLE public.ext_customer_person_identity (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    person_id uuid NOT NULL,
    person_party_id uuid,
    individual_customer boolean DEFAULT false NOT NULL,
    commercial_contact boolean DEFAULT false NOT NULL,
    commercial_account_count integer DEFAULT 0 NOT NULL,
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.ext_people_contact_person (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    person_id uuid NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    preferred_name character varying(255),
    primary_email character varying(255),
    secondary_email character varying(255),
    primary_phone character varying(255),
    secondary_phone character varying(255),
    person_created_at timestamp(6) with time zone,
    person_updated_at timestamp(6) with time zone,
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.ext_people_staffing_assignment (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    assignment_id uuid NOT NULL,
    person_id uuid NOT NULL,
    location_id uuid NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    status character varying(20) NOT NULL,
    effective_from date,
    effective_to date,
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

-- refresh_token and refresh_expires_at are nullable (ADR-0062 section 7, plan WS2b-4): an
-- impersonation token is stored here like any access token, so validation and revocation reach
-- it, but it has no refresh half — it is never refreshable. Every login pair still carries both.
CREATE TABLE public.jwt_token (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    token text NOT NULL,
    refresh_token text,
    issued_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    refresh_expires_at timestamp with time zone,
    subject character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    version bigint,
    -- The platform operator behind an impersonation token (ADR-0062 section 7, WS2b-4). NULL on
    -- every ordinary token: its subject already names its user. An impersonation row lives in the
    -- target tenant under a synthetic subject, so this is the only link back to the operator and
    -- the only key a tenant-independent revocation can use.
    impersonated_by_user_id uuid
);

CREATE TABLE public.permissions (
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(500),
    domain character varying(50) NOT NULL,
    resource character varying(100) NOT NULL,
    action character varying(50) NOT NULL,
    registered_at timestamp with time zone NOT NULL,
    registered_by_service character varying(100) NOT NULL,
    version character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    bit_index integer,
    deprecated boolean DEFAULT false NOT NULL,
    superseded_by character varying(255)
);

CREATE TABLE public.pricing_rule_trace_entries (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    snapshot_id uuid,
    rule_id character varying(255),
    status character varying(32),
    inputs text,
    outputs text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

CREATE TABLE public.pricing_snapshots (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    snapshot_id uuid NOT NULL,
    "timestamp" timestamp with time zone,
    quote_context text,
    final_price numeric(19,4),
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

CREATE TABLE public.processed_events (
    event_id character varying(36) NOT NULL,
    owner character varying(64) NOT NULL,
    processed_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.role_assignments (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    effective_start_date timestamp with time zone NOT NULL,
    effective_end_date timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    last_modified_at timestamp with time zone,
    last_modified_by character varying(255),
    revoked_at timestamp with time zone,
    updated_at timestamp with time zone
);

CREATE TABLE public.role_permissions (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    role_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    granted_at timestamp with time zone DEFAULT now(),
    granted_by character varying(255)
);

COMMENT ON COLUMN public.role_permissions.granted_at IS 'When the grant was written. NULL for rows predating V30.';

COMMENT ON COLUMN public.role_permissions.granted_by IS 'Actor that granted the permission via the admin API. NULL when written by a seed, direct SQL, or an out-of-band script; ''pre-v30-unattributed'' for rows predating V30.';

CREATE TABLE public.roles (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(500),
    created_at timestamp with time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    last_modified_at timestamp with time zone,
    last_modified_by character varying(255),
    updated_at timestamp with time zone,
    persona_title character varying(60),
    persona_focus character varying(200),
    persona_tone character varying(120),
    mcp_persona_rank smallint,
    mcp_persona_eligible boolean DEFAULT true NOT NULL,
    location_scope character varying(16) DEFAULT 'ALL'::character varying NOT NULL,
    location_hierarchy character varying(16) DEFAULT 'OTHER'::character varying NOT NULL,
    CONSTRAINT chk_roles_location_hierarchy CHECK (((location_hierarchy)::text = ANY ((ARRAY['FINANCIAL'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT chk_roles_location_scope CHECK (((location_scope)::text = ANY ((ARRAY['ALL'::character varying, 'LOCATION'::character varying])::text[])))
);

CREATE TABLE public.self_registration_attempts (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    idempotency_key character varying(255) NOT NULL,
    request_fingerprint character varying(128) NOT NULL,
    email character varying(255) NOT NULL,
    username character varying(255),
    status character varying(20) NOT NULL,
    user_id uuid,
    person_id uuid,
    link_status character varying(50),
    matched_existing_person boolean DEFAULT false NOT NULL,
    issued_tokens boolean DEFAULT false NOT NULL,
    crm_candidate_count integer,
    crm_any_matches boolean,
    crm_individual_customer_candidate_count integer,
    crm_commercial_contact_candidate_count integer,
    crm_shared_identity_candidate_count integer,
    crm_exact_email_match boolean,
    crm_exact_phone_match boolean,
    crm_exact_name_match boolean,
    crm_review_required boolean,
    conflict_code character varying(100),
    conflict_message character varying(1000),
    reference_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.self_registration_review_cases (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    case_type character varying(40) NOT NULL,
    status character varying(20) NOT NULL,
    reason_code character varying(100) NOT NULL,
    reason_message character varying(1000) NOT NULL,
    email character varying(255) NOT NULL,
    requested_username character varying(255),
    person_id uuid,
    linked_user_id uuid,
    crm_candidate_count integer,
    crm_shared_identity_candidate_count integer,
    crm_exact_email_match boolean,
    crm_exact_phone_match boolean,
    crm_exact_name_match boolean,
    notes character varying(1000),
    resolved_at timestamp with time zone,
    resolved_by character varying(255),
    resolution_notes character varying(1000),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.users (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    account_non_locked boolean DEFAULT true NOT NULL,
    account_non_expired boolean DEFAULT true NOT NULL,
    credentials_non_expired boolean DEFAULT true NOT NULL,
    awaiting_activation boolean DEFAULT false NOT NULL,
    failed_login_attempts integer DEFAULT 0 NOT NULL,
    last_failed_login_at timestamp with time zone,
    last_successful_login_at timestamp with time zone,
    locked_at timestamp with time zone,
    locked_until timestamp with time zone,
    disabled_at timestamp with time zone,
    disabled_by character varying(255),
    account_expires_at timestamp with time zone,
    credentials_expire_at timestamp with time zone,
    last_login_ip character varying(255),
    last_login_user_agent character varying(512),
    person_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- ADR-0062 section 7 (plan WS2b-3, decided 2026-09-10): one-time activation tokens for a tenant's
-- first administrator. Global table (db/tenancy-global-tables.txt): POST /v1/auth/activate is
-- unauthenticated and binds no tenant, so the row must be findable by hash without one; tenant_id
-- is carried as data and the service binds it before touching users. Only the SHA-256 of the token
-- is stored, never the token.
CREATE TABLE public.user_activation_tokens (
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    user_id uuid NOT NULL,
    token_hash character varying(64) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_by character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON COLUMN public.users.awaiting_activation IS
    'ADR-0062 section 7 (WS2b-3): true only for the first administrator provisioning created and nobody has activated; the one state an activation token may set a password for. Cleared by activation and by any ordinary password set.';

COMMENT ON COLUMN public.user_activation_tokens.tenant_id IS
    'ADR-0062: the user''s tenant, carried as data (global table, no policy); bound by the activation service before the user is updated.';
COMMENT ON COLUMN public.user_activation_tokens.token_hash IS
    'Lower-case hex SHA-256 of the URL-safe base64 token handed to the operator; the token itself is never stored.';

ALTER TABLE ONLY public.audit_log_events
    ADD CONSTRAINT audit_log_events_pkey PRIMARY KEY (event_id);

ALTER TABLE ONLY public.audit_log_events
    ADD CONSTRAINT audit_log_events_tenant_key UNIQUE (tenant_id, event_id);

ALTER TABLE ONLY public.event_outbox
    ADD CONSTRAINT event_outbox_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ext_customer_person_identity
    ADD CONSTRAINT ext_customer_person_identity_pkey PRIMARY KEY (person_id);

ALTER TABLE ONLY public.ext_customer_person_identity
    ADD CONSTRAINT ext_customer_person_identity_tenant_key UNIQUE (tenant_id, person_id);

ALTER TABLE ONLY public.ext_people_contact_person
    ADD CONSTRAINT ext_people_contact_person_pkey PRIMARY KEY (person_id);

ALTER TABLE ONLY public.ext_people_contact_person
    ADD CONSTRAINT ext_people_contact_person_tenant_key UNIQUE (tenant_id, person_id);

ALTER TABLE ONLY public.ext_people_staffing_assignment
    ADD CONSTRAINT ext_people_staffing_assignment_pkey PRIMARY KEY (assignment_id);

ALTER TABLE ONLY public.ext_people_staffing_assignment
    ADD CONSTRAINT ext_people_staffing_assignment_tenant_key UNIQUE (tenant_id, assignment_id);

ALTER TABLE ONLY public.jwt_token
    ADD CONSTRAINT jwt_token_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.jwt_token
    ADD CONSTRAINT jwt_token_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.jwt_token
    ADD CONSTRAINT jwt_token_refresh_token_key UNIQUE (tenant_id, refresh_token);

ALTER TABLE ONLY public.jwt_token
    ADD CONSTRAINT jwt_token_token_key UNIQUE (tenant_id, token);

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_name_key UNIQUE (name);

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pricing_rule_trace_entries
    ADD CONSTRAINT pricing_rule_trace_entries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pricing_rule_trace_entries
    ADD CONSTRAINT pricing_rule_trace_entries_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.pricing_snapshots
    ADD CONSTRAINT pricing_snapshots_pkey PRIMARY KEY (snapshot_id);

ALTER TABLE ONLY public.pricing_snapshots
    ADD CONSTRAINT pricing_snapshots_tenant_key UNIQUE (tenant_id, snapshot_id);

ALTER TABLE ONLY public.processed_events
    ADD CONSTRAINT processed_events_pkey PRIMARY KEY (event_id);

ALTER TABLE ONLY public.role_assignments
    ADD CONSTRAINT role_assignments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.role_assignments
    ADD CONSTRAINT role_assignments_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id);

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_tenant_key UNIQUE (tenant_id, role_id, permission_id);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_name_key UNIQUE (tenant_id, name);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.self_registration_attempts
    ADD CONSTRAINT self_registration_attempts_idempotency_key_key UNIQUE (tenant_id, idempotency_key);

ALTER TABLE ONLY public.self_registration_attempts
    ADD CONSTRAINT self_registration_attempts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.self_registration_attempts
    ADD CONSTRAINT self_registration_attempts_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.self_registration_review_cases
    ADD CONSTRAINT self_registration_review_cases_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.self_registration_review_cases
    ADD CONSTRAINT self_registration_review_cases_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (tenant_id, username);

ALTER TABLE ONLY public.user_activation_tokens
    ADD CONSTRAINT user_activation_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_activation_tokens
    ADD CONSTRAINT user_activation_tokens_token_hash_key UNIQUE (token_hash);

-- Composite: foreign-key checks bypass row-level security, so the key names the tenant too.
ALTER TABLE ONLY public.user_activation_tokens
    ADD CONSTRAINT user_activation_tokens_user_fkey
    FOREIGN KEY (tenant_id, user_id) REFERENCES public.users (tenant_id, id) ON DELETE CASCADE;

CREATE INDEX idx_audit_log_events_actor_id ON public.audit_log_events USING btree (actor_id);

CREATE INDEX idx_audit_log_events_entity_id ON public.audit_log_events USING btree (entity_id);

CREATE INDEX idx_audit_log_events_timestamp ON public.audit_log_events USING btree ("timestamp");

CREATE INDEX idx_event_outbox_published_window ON public.event_outbox USING btree (topic, created_at) WHERE (published_at IS NOT NULL);

CREATE INDEX idx_event_outbox_unpublished ON public.event_outbox USING btree (id) WHERE (published_at IS NULL);

CREATE UNIQUE INDEX idx_permissions_bit_index ON public.permissions USING btree (bit_index) WHERE (bit_index IS NOT NULL);

CREATE INDEX idx_processed_events_owner_event ON public.processed_events USING btree (owner, event_id);

CREATE INDEX idx_role_assignments_effective_dates ON public.role_assignments USING btree (effective_start_date, effective_end_date);

CREATE INDEX idx_role_assignments_revoked_at ON public.role_assignments USING btree (revoked_at);

CREATE INDEX idx_role_assignments_role_id ON public.role_assignments USING btree (role_id);

CREATE INDEX idx_role_assignments_user_id ON public.role_assignments USING btree (user_id);

CREATE INDEX idx_roles_persona_rank ON public.roles USING btree (mcp_persona_rank, name) WHERE mcp_persona_eligible;

CREATE INDEX idx_sec_ext_person_last_name ON public.ext_people_contact_person USING btree (last_name);

CREATE INDEX idx_sec_ext_person_primary_email ON public.ext_people_contact_person USING btree (primary_email);

CREATE INDEX idx_sec_ext_staffing_person ON public.ext_people_staffing_assignment USING btree (person_id);

CREATE INDEX idx_self_registration_attempts_email ON public.self_registration_attempts USING btree (email);

CREATE INDEX idx_self_registration_review_cases_case_type_status ON public.self_registration_review_cases USING btree (case_type, status);

CREATE INDEX idx_self_registration_review_cases_status ON public.self_registration_review_cases USING btree (status);

ALTER TABLE ONLY public.pricing_rule_trace_entries
    ADD CONSTRAINT fk_pricing_rule_trace_entries_snapshot FOREIGN KEY (tenant_id, snapshot_id) REFERENCES public.pricing_snapshots(tenant_id, snapshot_id);

ALTER TABLE ONLY public.role_assignments
    ADD CONSTRAINT fk_role_assignments_role FOREIGN KEY (tenant_id, role_id) REFERENCES public.roles(tenant_id, id);

ALTER TABLE ONLY public.role_assignments
    ADD CONSTRAINT fk_role_assignments_user FOREIGN KEY (tenant_id, user_id) REFERENCES public.users(tenant_id, id);

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES public.permissions(id);

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fk_role_permissions_role FOREIGN KEY (tenant_id, role_id) REFERENCES public.roles(tenant_id, id);

CREATE INDEX audit_log_events_tenant_idx ON public.audit_log_events USING btree (tenant_id);

CREATE INDEX ext_customer_person_identity_tenant_idx ON public.ext_customer_person_identity USING btree (tenant_id);

CREATE INDEX ext_people_contact_person_tenant_idx ON public.ext_people_contact_person USING btree (tenant_id);

CREATE INDEX ext_people_staffing_assignment_tenant_idx ON public.ext_people_staffing_assignment USING btree (tenant_id);

CREATE INDEX jwt_token_tenant_idx ON public.jwt_token USING btree (tenant_id);

-- Revocation of a platform operator's impersonation tokens sweeps every tenant by operator id
-- (ADR-0062 section 7, WS2b-4); partial, because the column is NULL on every ordinary token.
CREATE INDEX jwt_token_impersonated_by_user_idx ON public.jwt_token USING btree (impersonated_by_user_id)
    WHERE impersonated_by_user_id IS NOT NULL;

CREATE INDEX pricing_rule_trace_entries_tenant_idx ON public.pricing_rule_trace_entries USING btree (tenant_id);

CREATE INDEX pricing_snapshots_tenant_idx ON public.pricing_snapshots USING btree (tenant_id);

CREATE INDEX role_assignments_tenant_idx ON public.role_assignments USING btree (tenant_id);

CREATE INDEX role_permissions_tenant_idx ON public.role_permissions USING btree (tenant_id);

CREATE INDEX roles_tenant_idx ON public.roles USING btree (tenant_id);

CREATE INDEX self_registration_attempts_tenant_idx ON public.self_registration_attempts USING btree (tenant_id);

CREATE INDEX self_registration_review_cases_tenant_idx ON public.self_registration_review_cases USING btree (tenant_id);

CREATE INDEX users_tenant_idx ON public.users USING btree (tenant_id);

CREATE INDEX idx_user_activation_tokens_open ON public.user_activation_tokens USING btree (tenant_id, user_id) WHERE (used_at IS NULL);

ALTER TABLE public.audit_log_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log_events FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.audit_log_events
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_customer_person_identity ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_customer_person_identity FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_customer_person_identity
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_people_contact_person ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_people_contact_person FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_people_contact_person
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_people_staffing_assignment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_people_staffing_assignment FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_people_staffing_assignment
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.jwt_token ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jwt_token FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.jwt_token
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.pricing_rule_trace_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_rule_trace_entries FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.pricing_rule_trace_entries
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.pricing_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_snapshots FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.pricing_snapshots
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.role_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_assignments FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.role_assignments
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.role_permissions
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.roles
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.self_registration_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.self_registration_attempts FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.self_registration_attempts
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.self_registration_review_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.self_registration_review_cases FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.self_registration_review_cases
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.users
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());
