-- AUTH-002: Add account-state columns to users table
ALTER TABLE users ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN account_non_locked BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN account_non_expired BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN credentials_non_expired BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN failed_login_attempts INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN last_failed_login_at TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE users ADD COLUMN last_successful_login_at TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE users ADD COLUMN locked_at TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE users ADD COLUMN locked_until TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE users ADD COLUMN disabled_at TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE users ADD COLUMN disabled_by VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN account_expires_at TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE users ADD COLUMN credentials_expire_at TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE users ADD COLUMN last_login_ip VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN last_login_user_agent VARCHAR(512) NULL;
