-- pos-supplier: Flyway baseline (flattened 2026-09-09 from the previous migration history) with the
-- ADR-0062 tenancy schema folded in. Generated by scripts/db/tenancy/flatten.py from a pg_dump of a
-- database migrated with the retired scripts; the tenancy additions are mechanical and are listed in
-- docs/TENANCY_SCHEMA.md. Global (unscoped) tables: src/main/resources/db/tenancy-global-tables.txt.
--
-- Tenant context: app_current_tenant() reads the session setting app.current_tenant, which the
-- TenantAwareDataSource (pos-tenancy-common, plan WS1) binds per checkout. Until then the owner role
-- carries a transitional default (postgres/init-tenancy.sh) and tests set it per connection.
-- With nothing bound: NULL -> every scoped table reads as empty and refuses inserts (fail closed).

-- Functions are emitted before the tables they reference (pg_dump order); do not validate bodies.
SET check_function_bodies = false;

CREATE OR REPLACE FUNCTION public.app_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$ SELECT NULLIF(current_setting('app.current_tenant', true), '')::uuid $$;

CREATE TABLE public.ext_product_code (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    product_id uuid NOT NULL,
    code_type character varying(16),
    code character varying(64),
    aggregate_version bigint DEFAULT 0 NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    sku character varying(64),
    CONSTRAINT ck_ext_product_code_type CHECK (((code_type IS NULL) OR ((code_type)::text = ANY ((ARRAY['EAN'::character varying, 'UPC'::character varying])::text[]))))
);

CREATE TABLE public.processed_events (
    event_id character varying(36) NOT NULL,
    tenant_id uuid,
    owner character varying(64) NOT NULL,
    processed_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.supplier_account (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    role character varying(16) NOT NULL,
    account_number character varying(100) NOT NULL,
    agency_code character varying(50),
    delivery_location_id uuid,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_by character varying(255),
    version bigint NOT NULL,
    CONSTRAINT chk_saccount_role CHECK (((role)::text = ANY ((ARRAY['BILLING'::character varying, 'DELIVERY'::character varying])::text[]))),
    CONSTRAINT chk_saccount_role_location CHECK (((((role)::text = 'DELIVERY'::text) AND (delivery_location_id IS NOT NULL)) OR (((role)::text = 'BILLING'::text) AND (delivery_location_id IS NULL))))
);

CREATE TABLE public.supplier_audit_access (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    audit_access_id uuid NOT NULL,
    exchange_audit_id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    capability character varying(64) NOT NULL,
    accessed_by character varying(255) NOT NULL,
    accessed_at timestamp(6) with time zone NOT NULL,
    access_kind character varying(32) NOT NULL,
    payload_outcome character varying(32) NOT NULL,
    correlation_id character varying(100),
    CONSTRAINT chk_saccess_kind CHECK (((access_kind)::text = 'PAYLOAD_READ'::text)),
    CONSTRAINT chk_saccess_payload_outcome CHECK (((payload_outcome)::text = ANY ((ARRAY['DECRYPTED'::character varying, 'UNREADABLE'::character varying, 'NOT_CAPTURED'::character varying])::text[])))
);

CREATE TABLE public.supplier_auth_config (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    name character varying(100) NOT NULL,
    type character varying(64) NOT NULL,
    username_ref character varying(512),
    password_ref character varying(512),
    api_key_ref character varying(512),
    api_key_header character varying(100),
    token_url_ref character varying(512),
    client_id_ref character varying(512),
    client_secret_ref character varying(512),
    bearer_token_ref character varying(512),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_by character varying(255),
    version bigint NOT NULL,
    CONSTRAINT chk_sauth_type CHECK (((type)::text = ANY ((ARRAY['BASIC_PLUS_APIKEY'::character varying, 'OAUTH2_CLIENT_CREDENTIALS'::character varying, 'BEARER'::character varying])::text[])))
);

CREATE TABLE public.supplier_endpoint_binding (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    capability character varying(64) NOT NULL,
    protocol_family character varying(64) NOT NULL,
    protocol_version character varying(64) NOT NULL,
    base_url character varying(1024) NOT NULL,
    path character varying(512) NOT NULL,
    auth_config_name character varying(100) NOT NULL,
    schedule_cron character varying(100),
    enabled boolean NOT NULL,
    capture_level character varying(32),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_by character varying(255),
    version bigint NOT NULL,
    event_chunk_size integer,
    CONSTRAINT chk_sbinding_capability CHECK (((capability)::text = ANY ((ARRAY['ORDER_CREATE'::character varying, 'ORDER_STATUS'::character varying, 'STOCK_INQUIRY'::character varying, 'STOCK_REPORT'::character varying, 'PRICE_CATALOG'::character varying, 'INVOICE_FETCH'::character varying, 'WORKORDER_AUTHORIZATION'::character varying, 'MARKETING_CATALOG'::character varying, 'TIRE_IDENTIFICATION'::character varying])::text[]))),
    CONSTRAINT chk_sbinding_capture_level CHECK (((capture_level IS NULL) OR ((capture_level)::text = ANY ((ARRAY['FULL'::character varying, 'REDACTED'::character varying, 'METADATA_ONLY'::character varying])::text[])))),
    CONSTRAINT chk_sbinding_family CHECK (((protocol_family)::text = ANY ((ARRAY['EDIWHEEL_A25'::character varying, 'EDIWHEEL_C1'::character varying, 'EDIWHEEL_B'::character varying, 'EDIWHEEL_JSON'::character varying, 'MICHELIN_S2S'::character varying, 'TEST'::character varying])::text[])))
);

CREATE TABLE public.supplier_endpoint_binding_redaction (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    binding_id uuid NOT NULL,
    classification character varying(64) NOT NULL,
    CONSTRAINT chk_sbinding_redaction_classification CHECK (((classification)::text = ANY ((ARRAY['CUSTOMER_IDENTIFIER'::character varying, 'COMMERCIAL_PRICING'::character varying])::text[])))
);

CREATE TABLE public.supplier_event_outbox (
    id uuid NOT NULL,
    topic character varying(255) NOT NULL,
    record_key character varying(255) NOT NULL,
    event_type character varying(128) NOT NULL,
    payload text NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    published_at timestamp(6) with time zone,
    attempts integer DEFAULT 0 NOT NULL,
    last_error text
);

CREATE TABLE public.supplier_exchange_audit (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    exchange_audit_id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    supplier_ref character varying(100) NOT NULL,
    binding_id uuid,
    capability character varying(64) NOT NULL,
    protocol_family character varying(64) NOT NULL,
    protocol_version character varying(64) NOT NULL,
    http_method character varying(16) NOT NULL,
    endpoint_uri character varying(2048) NOT NULL,
    attempt integer NOT NULL,
    correlation_id character varying(100) NOT NULL,
    outcome character varying(32) NOT NULL,
    http_status integer,
    started_at timestamp(6) with time zone NOT NULL,
    duration_ms bigint NOT NULL,
    failure_detail character varying(2048),
    capture_level character varying(16) NOT NULL,
    request_payload bytea,
    response_payload bytea,
    payloads_purged_at timestamp(6) with time zone,
    unmapped_fields character varying(4000),
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    CONSTRAINT chk_saudit_attempt CHECK ((attempt >= 1)),
    CONSTRAINT chk_saudit_capture_level CHECK (((capture_level)::text = ANY ((ARRAY['FULL'::character varying, 'REDACTED'::character varying, 'METADATA_ONLY'::character varying])::text[]))),
    CONSTRAINT chk_saudit_duration CHECK ((duration_ms >= 0)),
    CONSTRAINT chk_saudit_metadata_only_has_no_payload CHECK ((((capture_level)::text <> 'METADATA_ONLY'::text) OR ((request_payload IS NULL) AND (response_payload IS NULL)))),
    CONSTRAINT chk_saudit_outcome CHECK (((outcome)::text = ANY ((ARRAY['OK'::character varying, 'PRE_SEND_FAILURE'::character varying, 'POST_SEND_AMBIGUOUS'::character varying, 'DEFINITIVE_REJECTION'::character varying, 'CONFIGURATION_ERROR'::character varying])::text[])))
);

CREATE TABLE public.supplier_invoice (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    supplier_invoice_id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    supplier_ref character varying(100) NOT NULL,
    vendor_invoice_number character varying(70) NOT NULL,
    invoice_date date NOT NULL,
    invoice_type character varying(16) NOT NULL,
    currency character varying(3) NOT NULL,
    total_net_amount numeric(19,4),
    total_tax_amount numeric(19,4),
    total_gross_amount numeric(19,4),
    vendor_order_reference character varying(70),
    fetched_at timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT supplier_invoice_type_check CHECK (((invoice_type)::text = ANY ((ARRAY['INVOICE'::character varying, 'CREDIT_NOTE'::character varying])::text[])))
);

CREATE TABLE public.supplier_invoice_line (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    supplier_invoice_line_id uuid NOT NULL,
    supplier_invoice_id uuid NOT NULL,
    line_number integer NOT NULL,
    article_ean character varying(64),
    supplier_article_code character varying(64),
    quantity integer,
    unit_price numeric(19,4),
    line_amount numeric(19,4),
    vendor_order_reference character varying(70),
    created_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.supplier_mktcat_subscription (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    supplier_mktcat_subscription_id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    supplier_ref character varying(100) NOT NULL,
    event_name character varying(100) NOT NULL,
    callback_url character varying(1000) NOT NULL,
    status character varying(20) NOT NULL,
    failure_detail character varying(1000),
    subscribed_at timestamp(6) with time zone,
    last_callback_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT ck_mktcat_sub_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])))
);

CREATE TABLE public.supplier_mktcat_variant (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    supplier_mktcat_variant_id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    supplier_ref character varying(100) NOT NULL,
    vendor_variant_id character varying(100) NOT NULL,
    brand character varying(200),
    tread_design character varying(200),
    tread_design_2 character varying(200),
    product_name character varying(300),
    vehicle_type character varying(100),
    seasonality character varying(100),
    content_hash character varying(64) NOT NULL,
    texts_json text NOT NULL,
    images_json text NOT NULL,
    has_unresolved_images boolean DEFAULT false NOT NULL,
    first_seen_at timestamp(6) with time zone NOT NULL,
    last_seen_at timestamp(6) with time zone NOT NULL,
    last_published_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.supplier_pricat_entry (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    entry_id uuid NOT NULL,
    import_manifest_id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    position_number integer,
    article_ean character varying(64),
    supplier_article_code character varying(64),
    x_reference_code character varying(64),
    matched_product_id uuid,
    match_method character varying(32) NOT NULL,
    suggested_retail_price numeric(19,4),
    gross_price numeric(19,4),
    net_price numeric(19,4),
    tax_rate numeric(9,4),
    recycling_fee numeric(19,4),
    effective_from date NOT NULL,
    buyer_account_number character varying(64) NOT NULL,
    country_code character varying(8) NOT NULL,
    currency character varying(8) NOT NULL,
    source_document_id character varying(255),
    source_document_date date,
    fetched_at timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    chunk_sequence integer NOT NULL,
    CONSTRAINT ck_spricat_entry_match_method CHECK (((match_method)::text = ANY ((ARRAY['EAN'::character varying, 'UPC_XREFERENCE'::character varying, 'UNMATCHED'::character varying])::text[])))
);

COMMENT ON COLUMN public.supplier_pricat_entry.chunk_sequence IS 'The 1-based chunk event this line was published in. Fixed at staging so a re-emit reproduces the original chunk boundaries the consumer deduplicates on.';

CREATE TABLE public.supplier_pricat_import (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    import_manifest_id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    supplier_ref character varying(100) NOT NULL,
    protocol_family character varying(64) NOT NULL,
    protocol_version character varying(64) NOT NULL,
    status character varying(32) NOT NULL,
    source_document_id character varying(255),
    source_document_date date,
    buyer_account_number character varying(64) NOT NULL,
    buyer_agency_code character varying(16),
    country_code character varying(8),
    currency character varying(8),
    fetched_at timestamp(6) with time zone NOT NULL,
    completed_at timestamp(6) with time zone,
    lines_fetched integer DEFAULT 0 NOT NULL,
    lines_matched integer DEFAULT 0 NOT NULL,
    lines_unmatched integer DEFAULT 0 NOT NULL,
    lines_duplicate integer DEFAULT 0 NOT NULL,
    chunk_count integer DEFAULT 0 NOT NULL,
    chunk_size integer DEFAULT 0 NOT NULL,
    content_checksum character varying(64),
    exchange_audit_id uuid,
    correlation_id character varying(100) NOT NULL,
    failure_detail character varying(2000),
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(100),
    reapplied_from_import_id uuid,
    republish_count integer DEFAULT 0 NOT NULL,
    last_republished_at timestamp(6) with time zone,
    binding_id uuid,
    window_from timestamp(6) with time zone,
    window_to timestamp(6) with time zone,
    checkpoint_state text,
    checkpoint_at timestamp(6) with time zone,
    error_code character varying(64),
    CONSTRAINT ck_spricat_import_counts CHECK (((lines_fetched >= 0) AND (lines_matched >= 0) AND (lines_unmatched >= 0) AND (lines_duplicate >= 0))),
    CONSTRAINT ck_spricat_import_error_code CHECK (((error_code IS NULL) OR ((error_code)::text = ANY ((ARRAY['FETCH_FAILED'::character varying, 'DECODE_FAILED'::character varying])::text[])))),
    CONSTRAINT ck_spricat_import_status CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'EMPTY'::character varying, 'FAILED'::character varying])::text[])))
);

COMMENT ON COLUMN public.supplier_pricat_import.reapplied_from_import_id IS 'Set when this manifest re-applied quarantined lines of an earlier import (#1310); null for a vendor fetch.';

COMMENT ON COLUMN public.supplier_pricat_import.republish_count IS 'How many times this import has been re-emitted on consumer request; bounded by pos.supplier.pricat.republish-max-attempts.';

CREATE TABLE public.supplier_pricat_unmatched_line (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    unmatched_line_id uuid NOT NULL,
    import_manifest_id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    position_number integer,
    article_ean character varying(64),
    supplier_article_code character varying(64),
    x_reference_code character varying(64),
    reason character varying(48) NOT NULL,
    reason_detail character varying(1000),
    suggested_retail_price numeric(19,4),
    gross_price numeric(19,4),
    net_price numeric(19,4),
    tax_rate numeric(9,4),
    recycling_fee numeric(19,4),
    effective_from date,
    buyer_account_number character varying(64) NOT NULL,
    country_code character varying(8),
    currency character varying(8),
    source_document_id character varying(255),
    source_document_date date,
    fetched_at timestamp(6) with time zone NOT NULL,
    resolved_at timestamp(6) with time zone,
    resolved_product_id uuid,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT ck_spricat_unmatched_reason CHECK (((reason)::text = ANY ((ARRAY['NO_IDENTIFIER'::character varying, 'NO_CATALOG_MATCH'::character varying, 'AMBIGUOUS_CATALOG_MATCH'::character varying, 'CATALOG_UNAVAILABLE'::character varying, 'DUPLICATE_LINE'::character varying, 'MALFORMED_LINE'::character varying])::text[])))
);

CREATE TABLE public.supplier_profile (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    vendor_profile_id uuid NOT NULL,
    supplier_ref character varying(100) NOT NULL,
    display_name character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    sandbox boolean DEFAULT false NOT NULL,
    sandbox_base_url_override character varying(1024),
    connect_timeout_ms integer,
    read_timeout_ms integer,
    retry_max_attempts integer,
    retry_backoff character varying(32),
    source_of_truth character varying(16) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_by character varying(255),
    version bigint NOT NULL,
    CONSTRAINT chk_sprofile_connect_timeout CHECK (((connect_timeout_ms IS NULL) OR (connect_timeout_ms > 0))),
    CONSTRAINT chk_sprofile_read_timeout CHECK (((read_timeout_ms IS NULL) OR (read_timeout_ms > 0))),
    CONSTRAINT chk_sprofile_retry_backoff CHECK (((retry_backoff IS NULL) OR ((retry_backoff)::text = ANY ((ARRAY['FIXED'::character varying, 'EXPONENTIAL'::character varying])::text[])))),
    CONSTRAINT chk_sprofile_retry_max CHECK (((retry_max_attempts IS NULL) OR (retry_max_attempts >= 0))),
    CONSTRAINT chk_sprofile_source_of_truth CHECK (((source_of_truth)::text = ANY ((ARRAY['YAML'::character varying, 'ADMIN'::character varying])::text[])))
);

CREATE TABLE public.supplier_schedule_lease (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    binding_id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    capability character varying(64) NOT NULL,
    owner_token character varying(100),
    leased_until timestamp(6) with time zone,
    last_heartbeat_at timestamp(6) with time zone,
    checkpoint_at timestamp(6) with time zone,
    last_run_started_at timestamp(6) with time zone,
    last_run_outcome character varying(32),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint NOT NULL,
    CONSTRAINT chk_slease_claim_consistent CHECK ((((owner_token IS NULL) AND (leased_until IS NULL)) OR ((owner_token IS NOT NULL) AND (leased_until IS NOT NULL))))
);

CREATE TABLE public.supplier_stock_snapshot (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    snapshot_id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    supplier_ref character varying(100) NOT NULL,
    protocol_version character varying(64) NOT NULL,
    status character varying(32) NOT NULL,
    document_id character varying(255),
    issued_on date,
    snapshot_as_of timestamp(6) with time zone,
    buyer_account_number character varying(64) NOT NULL,
    country_code character varying(8),
    fetched_at timestamp(6) with time zone NOT NULL,
    completed_at timestamp(6) with time zone,
    lines_reported integer DEFAULT 0 NOT NULL,
    lines_rejected integer DEFAULT 0 NOT NULL,
    chunk_count integer DEFAULT 0 NOT NULL,
    chunk_size integer DEFAULT 0 NOT NULL,
    exchange_audit_id uuid,
    correlation_id character varying(100) NOT NULL,
    failure_detail character varying(2000),
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(100),
    CONSTRAINT ck_sstock_snapshot_status CHECK (((status)::text = ANY ((ARRAY['COMPLETED'::character varying, 'EMPTY'::character varying, 'REJECTED'::character varying, 'FAILED'::character varying])::text[])))
);

CREATE TABLE public.supplier_stock_snapshot_line (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    line_id uuid NOT NULL,
    snapshot_id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    vendor_line_id character varying(64),
    article_ean character varying(64),
    supplier_article_code character varying(64),
    buyers_article_id character varying(64),
    description character varying(512),
    available_quantity integer,
    created_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.supplier_transmission_intent (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    transmission_intent_id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    supplier_ref character varying(100) NOT NULL,
    purchase_order_id uuid NOT NULL,
    purchase_order_number character varying(64),
    intent_type character varying(32) NOT NULL,
    revision integer DEFAULT 0 NOT NULL,
    document_id character varying(35) NOT NULL,
    active_intent_key character varying(255),
    attempt_state character varying(32) NOT NULL,
    delivery_location_id uuid,
    billing_account_number character varying(64),
    protocol_version character varying(64),
    supplier_order_number character varying(64),
    vendor_error_code character varying(16),
    vendor_reason character varying(2000),
    dispatch_attempts integer DEFAULT 0 NOT NULL,
    dispatched_at timestamp(6) with time zone,
    result_at timestamp(6) with time zone,
    last_status_fingerprint character varying(64),
    last_status_at timestamp(6) with time zone,
    last_polled_at timestamp(6) with time zone,
    last_status_state character varying(32),
    event_sequence bigint DEFAULT 0 NOT NULL,
    latest_scheduled_delivery_date date,
    status_polling_active boolean DEFAULT false NOT NULL,
    polling_stopped_reason character varying(64),
    resolution_action character varying(32),
    resolved_by character varying(100),
    resolved_at timestamp(6) with time zone,
    resolution_evidence character varying(2000),
    correlation_id character varying(100),
    last_error character varying(2000),
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(100),
    updated_at timestamp(6) with time zone,
    CONSTRAINT ck_stintent_attempt_state CHECK (((attempt_state)::text = ANY ((ARRAY['PENDING'::character varying, 'DISPATCHING'::character varying, 'SENT_AWAITING_RESULT'::character varying, 'CONFIRMED'::character varying, 'REJECTED'::character varying, 'MANUAL_REVIEW'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT ck_stintent_intent_type CHECK (((intent_type)::text = ANY ((ARRAY['INITIAL'::character varying, 'REVISION'::character varying, 'REPLACEMENT'::character varying, 'SPLIT'::character varying])::text[]))),
    CONSTRAINT ck_stintent_revision CHECK ((revision >= 0))
);

CREATE TABLE public.supplier_transmission_line (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    line_id uuid NOT NULL,
    transmission_intent_id uuid NOT NULL,
    line_number integer NOT NULL,
    article_ean character varying(64),
    supplier_article_code character varying(64),
    quantity integer NOT NULL,
    requested_delivery_date date,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT ck_stline_line_number CHECK ((line_number >= 1)),
    CONSTRAINT ck_stline_quantity CHECK ((quantity >= 1))
);

CREATE TABLE public.supplier_workorder_authorization (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    supplier_workorder_authorization_id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    supplier_ref character varying(100) NOT NULL,
    workorder_id uuid NOT NULL,
    status character varying(20) NOT NULL,
    vendor_authorization_id character varying(100),
    poll_location character varying(1000),
    contract_reference character varying(100),
    authorized_amount numeric(19,4),
    currency character varying(3),
    reason_code character varying(50),
    reason_text character varying(1000),
    review_reason character varying(1000),
    approval_status character varying(20) DEFAULT 'NOT_REQUESTED'::character varying NOT NULL,
    approval_attempts integer DEFAULT 0 NOT NULL,
    approved_at timestamp(6) with time zone,
    requested_at timestamp(6) with time zone NOT NULL,
    decided_at timestamp(6) with time zone,
    last_polled_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT ck_swa_amount_currency CHECK (((authorized_amount IS NULL) OR (currency IS NOT NULL))),
    CONSTRAINT ck_swa_approval_status CHECK (((approval_status)::text = ANY ((ARRAY['NOT_REQUESTED'::character varying, 'PENDING'::character varying, 'APPROVED'::character varying, 'MANUAL_REVIEW'::character varying])::text[]))),
    CONSTRAINT ck_swa_status CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'GRANTED'::character varying, 'DENIED'::character varying, 'NOT_FOUND'::character varying, 'MANUAL_REVIEW'::character varying])::text[])))
);

ALTER TABLE ONLY public.ext_product_code
    ADD CONSTRAINT pk_ext_product_code PRIMARY KEY (product_id);

ALTER TABLE ONLY public.ext_product_code
    ADD CONSTRAINT ext_product_code_tenant_key UNIQUE (tenant_id, product_id);

ALTER TABLE ONLY public.supplier_event_outbox
    ADD CONSTRAINT pk_supplier_event_outbox PRIMARY KEY (id);

ALTER TABLE ONLY public.supplier_pricat_entry
    ADD CONSTRAINT pk_supplier_pricat_entry PRIMARY KEY (entry_id);

ALTER TABLE ONLY public.supplier_pricat_entry
    ADD CONSTRAINT supplier_pricat_entry_tenant_key UNIQUE (tenant_id, entry_id);

ALTER TABLE ONLY public.supplier_pricat_import
    ADD CONSTRAINT pk_supplier_pricat_import PRIMARY KEY (import_manifest_id);

ALTER TABLE ONLY public.supplier_pricat_import
    ADD CONSTRAINT supplier_pricat_import_tenant_key UNIQUE (tenant_id, import_manifest_id);

ALTER TABLE ONLY public.supplier_pricat_unmatched_line
    ADD CONSTRAINT pk_supplier_pricat_unmatched_line PRIMARY KEY (unmatched_line_id);

ALTER TABLE ONLY public.supplier_pricat_unmatched_line
    ADD CONSTRAINT supplier_pricat_unmatched_line_tenant_key UNIQUE (tenant_id, unmatched_line_id);

ALTER TABLE ONLY public.supplier_stock_snapshot
    ADD CONSTRAINT pk_supplier_stock_snapshot PRIMARY KEY (snapshot_id);

ALTER TABLE ONLY public.supplier_stock_snapshot
    ADD CONSTRAINT supplier_stock_snapshot_tenant_key UNIQUE (tenant_id, snapshot_id);

ALTER TABLE ONLY public.supplier_stock_snapshot_line
    ADD CONSTRAINT pk_supplier_stock_snapshot_line PRIMARY KEY (line_id);

ALTER TABLE ONLY public.supplier_stock_snapshot_line
    ADD CONSTRAINT supplier_stock_snapshot_line_tenant_key UNIQUE (tenant_id, line_id);

ALTER TABLE ONLY public.supplier_transmission_intent
    ADD CONSTRAINT pk_supplier_transmission_intent PRIMARY KEY (transmission_intent_id);

ALTER TABLE ONLY public.supplier_transmission_intent
    ADD CONSTRAINT supplier_transmission_intent_tenant_key UNIQUE (tenant_id, transmission_intent_id);

ALTER TABLE ONLY public.supplier_transmission_line
    ADD CONSTRAINT pk_supplier_transmission_line PRIMARY KEY (line_id);

ALTER TABLE ONLY public.supplier_transmission_line
    ADD CONSTRAINT supplier_transmission_line_tenant_key UNIQUE (tenant_id, line_id);

ALTER TABLE ONLY public.processed_events
    ADD CONSTRAINT processed_events_pkey PRIMARY KEY (event_id);

ALTER TABLE ONLY public.supplier_account
    ADD CONSTRAINT supplier_account_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.supplier_account
    ADD CONSTRAINT supplier_account_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.supplier_account
    ADD CONSTRAINT supplier_account_profile_role_location_key UNIQUE NULLS NOT DISTINCT (tenant_id, vendor_profile_id, role, delivery_location_id);

ALTER TABLE ONLY public.supplier_audit_access
    ADD CONSTRAINT supplier_audit_access_pkey PRIMARY KEY (audit_access_id);

ALTER TABLE ONLY public.supplier_audit_access
    ADD CONSTRAINT supplier_audit_access_tenant_key UNIQUE (tenant_id, audit_access_id);

ALTER TABLE ONLY public.supplier_auth_config
    ADD CONSTRAINT supplier_auth_config_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.supplier_auth_config
    ADD CONSTRAINT supplier_auth_config_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.supplier_auth_config
    ADD CONSTRAINT supplier_auth_config_profile_name_key UNIQUE (tenant_id, vendor_profile_id, name);

ALTER TABLE ONLY public.supplier_endpoint_binding
    ADD CONSTRAINT supplier_endpoint_binding_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.supplier_endpoint_binding
    ADD CONSTRAINT supplier_endpoint_binding_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.supplier_endpoint_binding
    ADD CONSTRAINT supplier_endpoint_binding_profile_capability_key UNIQUE (tenant_id, vendor_profile_id, capability);

ALTER TABLE ONLY public.supplier_endpoint_binding_redaction
    ADD CONSTRAINT supplier_endpoint_binding_redaction_pkey PRIMARY KEY (binding_id, classification);

ALTER TABLE ONLY public.supplier_endpoint_binding_redaction
    ADD CONSTRAINT supplier_endpoint_binding_redaction_tenant_key UNIQUE (tenant_id, binding_id, classification);

ALTER TABLE ONLY public.supplier_exchange_audit
    ADD CONSTRAINT supplier_exchange_audit_pkey PRIMARY KEY (exchange_audit_id);

ALTER TABLE ONLY public.supplier_exchange_audit
    ADD CONSTRAINT supplier_exchange_audit_tenant_key UNIQUE (tenant_id, exchange_audit_id);

ALTER TABLE ONLY public.supplier_invoice
    ADD CONSTRAINT supplier_invoice_identity UNIQUE (tenant_id, vendor_profile_id, vendor_invoice_number, invoice_date);

ALTER TABLE ONLY public.supplier_invoice_line
    ADD CONSTRAINT supplier_invoice_line_pkey PRIMARY KEY (supplier_invoice_line_id);

ALTER TABLE ONLY public.supplier_invoice_line
    ADD CONSTRAINT supplier_invoice_line_tenant_key UNIQUE (tenant_id, supplier_invoice_line_id);

ALTER TABLE ONLY public.supplier_invoice
    ADD CONSTRAINT supplier_invoice_pkey PRIMARY KEY (supplier_invoice_id);

ALTER TABLE ONLY public.supplier_invoice
    ADD CONSTRAINT supplier_invoice_tenant_key UNIQUE (tenant_id, supplier_invoice_id);

ALTER TABLE ONLY public.supplier_mktcat_subscription
    ADD CONSTRAINT supplier_mktcat_subscription_pkey PRIMARY KEY (supplier_mktcat_subscription_id);

ALTER TABLE ONLY public.supplier_mktcat_subscription
    ADD CONSTRAINT supplier_mktcat_subscription_tenant_key UNIQUE (tenant_id, supplier_mktcat_subscription_id);

ALTER TABLE ONLY public.supplier_mktcat_variant
    ADD CONSTRAINT supplier_mktcat_variant_pkey PRIMARY KEY (supplier_mktcat_variant_id);

ALTER TABLE ONLY public.supplier_mktcat_variant
    ADD CONSTRAINT supplier_mktcat_variant_tenant_key UNIQUE (tenant_id, supplier_mktcat_variant_id);

ALTER TABLE ONLY public.supplier_profile
    ADD CONSTRAINT supplier_profile_pkey PRIMARY KEY (vendor_profile_id);

ALTER TABLE ONLY public.supplier_profile
    ADD CONSTRAINT supplier_profile_tenant_key UNIQUE (tenant_id, vendor_profile_id);

ALTER TABLE ONLY public.supplier_profile
    ADD CONSTRAINT supplier_profile_supplier_ref_key UNIQUE (tenant_id, supplier_ref);

ALTER TABLE ONLY public.supplier_schedule_lease
    ADD CONSTRAINT supplier_schedule_lease_pkey PRIMARY KEY (binding_id);

ALTER TABLE ONLY public.supplier_schedule_lease
    ADD CONSTRAINT supplier_schedule_lease_tenant_key UNIQUE (tenant_id, binding_id);

ALTER TABLE ONLY public.supplier_workorder_authorization
    ADD CONSTRAINT supplier_workorder_authorization_pkey PRIMARY KEY (supplier_workorder_authorization_id);

ALTER TABLE ONLY public.supplier_workorder_authorization
    ADD CONSTRAINT supplier_workorder_authorization_tenant_key UNIQUE (tenant_id, supplier_workorder_authorization_id);

ALTER TABLE ONLY public.supplier_transmission_intent
    ADD CONSTRAINT uq_stintent_active_key UNIQUE (tenant_id, active_intent_key);

ALTER TABLE ONLY public.supplier_transmission_intent
    ADD CONSTRAINT uq_stintent_document_id UNIQUE (tenant_id, document_id);

CREATE INDEX idx_ext_product_code_lookup ON public.ext_product_code USING btree (code_type, code);

CREATE INDEX idx_ext_product_code_sku ON public.ext_product_code USING btree (sku);

CREATE INDEX idx_processed_events_owner_tenant_event ON public.processed_events USING btree (owner, tenant_id, event_id);

CREATE INDEX idx_saccess_accessed_at ON public.supplier_audit_access USING btree (accessed_at);

CREATE INDEX idx_saccess_actor_time ON public.supplier_audit_access USING btree (accessed_by, accessed_at);

CREATE INDEX idx_saccess_correlation ON public.supplier_audit_access USING btree (correlation_id);

CREATE INDEX idx_saccess_exchange ON public.supplier_audit_access USING btree (exchange_audit_id);

CREATE INDEX idx_saccount_profile ON public.supplier_account USING btree (vendor_profile_id);

CREATE INDEX idx_saudit_correlation ON public.supplier_exchange_audit USING btree (correlation_id);

CREATE INDEX idx_saudit_profile_capability_started ON public.supplier_exchange_audit USING btree (vendor_profile_id, capability, started_at);

CREATE INDEX idx_saudit_profile_started ON public.supplier_exchange_audit USING btree (vendor_profile_id, started_at);

CREATE INDEX idx_saudit_started_at ON public.supplier_exchange_audit USING btree (started_at);

CREATE INDEX idx_sauth_profile ON public.supplier_auth_config USING btree (vendor_profile_id);

CREATE INDEX idx_sbinding_profile ON public.supplier_endpoint_binding USING btree (vendor_profile_id);

CREATE INDEX idx_slease_leased_until ON public.supplier_schedule_lease USING btree (leased_until);

CREATE INDEX idx_soutbox_unpublished ON public.supplier_event_outbox USING btree (published_at, id);

CREATE INDEX idx_spricat_entry_chunk ON public.supplier_pricat_entry USING btree (import_manifest_id, chunk_sequence);

CREATE INDEX idx_spricat_entry_ean ON public.supplier_pricat_entry USING btree (vendor_profile_id, article_ean);

CREATE INDEX idx_spricat_entry_import ON public.supplier_pricat_entry USING btree (import_manifest_id);

CREATE INDEX idx_spricat_entry_latest ON public.supplier_pricat_entry USING btree (vendor_profile_id, matched_product_id, country_code, currency, effective_from);

CREATE INDEX idx_spricat_import_binding ON public.supplier_pricat_import USING btree (vendor_profile_id, binding_id);

CREATE INDEX idx_spricat_import_correlation ON public.supplier_pricat_import USING btree (correlation_id);

CREATE INDEX idx_spricat_import_profile_fetched ON public.supplier_pricat_import USING btree (vendor_profile_id, fetched_at);

CREATE INDEX idx_spricat_import_reapplied_from ON public.supplier_pricat_import USING btree (reapplied_from_import_id);

CREATE INDEX idx_spricat_import_status ON public.supplier_pricat_import USING btree (status);

CREATE INDEX idx_spricat_unmatched_import ON public.supplier_pricat_unmatched_line USING btree (import_manifest_id);

CREATE INDEX idx_spricat_unmatched_open ON public.supplier_pricat_unmatched_line USING btree (vendor_profile_id, resolved_at);

CREATE INDEX idx_spricat_unmatched_reason ON public.supplier_pricat_unmatched_line USING btree (reason);

CREATE INDEX idx_sstock_line_ean ON public.supplier_stock_snapshot_line USING btree (vendor_profile_id, article_ean);

CREATE INDEX idx_sstock_line_snapshot ON public.supplier_stock_snapshot_line USING btree (snapshot_id);

CREATE INDEX idx_sstock_snapshot_correlation ON public.supplier_stock_snapshot USING btree (correlation_id);

CREATE INDEX idx_sstock_snapshot_profile_asof ON public.supplier_stock_snapshot USING btree (vendor_profile_id, snapshot_as_of);

CREATE INDEX idx_sstock_snapshot_status ON public.supplier_stock_snapshot USING btree (status);

CREATE INDEX idx_stintent_polling ON public.supplier_transmission_intent USING btree (status_polling_active, last_polled_at);

CREATE INDEX idx_stintent_profile ON public.supplier_transmission_intent USING btree (vendor_profile_id);

CREATE INDEX idx_stintent_purchase_order ON public.supplier_transmission_intent USING btree (purchase_order_id);

CREATE INDEX idx_stintent_state ON public.supplier_transmission_intent USING btree (attempt_state, transmission_intent_id);

CREATE INDEX idx_stline_intent ON public.supplier_transmission_line USING btree (transmission_intent_id, line_number);

CREATE INDEX idx_supplier_invoice_line_invoice ON public.supplier_invoice_line USING btree (supplier_invoice_id);

CREATE INDEX idx_supplier_invoice_profile_date ON public.supplier_invoice USING btree (vendor_profile_id, invoice_date);

CREATE INDEX ix_mktcat_variant_profile_seen ON public.supplier_mktcat_variant USING btree (vendor_profile_id, last_seen_at);

CREATE INDEX ix_mktcat_variant_unresolved ON public.supplier_mktcat_variant USING btree (has_unresolved_images, updated_at);

CREATE INDEX ix_swa_approval_status ON public.supplier_workorder_authorization USING btree (approval_status, updated_at);

CREATE INDEX ix_swa_profile_status ON public.supplier_workorder_authorization USING btree (vendor_profile_id, status);

CREATE INDEX ix_swa_status_polled ON public.supplier_workorder_authorization USING btree (status, last_polled_at);

CREATE UNIQUE INDEX ux_mktcat_sub_profile_event ON public.supplier_mktcat_subscription USING btree (tenant_id, vendor_profile_id, event_name);

CREATE UNIQUE INDEX ux_mktcat_variant_profile_variant ON public.supplier_mktcat_variant USING btree (tenant_id, vendor_profile_id, vendor_variant_id);

CREATE UNIQUE INDEX ux_swa_profile_workorder ON public.supplier_workorder_authorization USING btree (tenant_id, vendor_profile_id, workorder_id);

ALTER TABLE ONLY public.supplier_account
    ADD CONSTRAINT fk_saccount_profile FOREIGN KEY (tenant_id, vendor_profile_id) REFERENCES public.supplier_profile(tenant_id, vendor_profile_id);

ALTER TABLE ONLY public.supplier_auth_config
    ADD CONSTRAINT fk_sauth_profile FOREIGN KEY (tenant_id, vendor_profile_id) REFERENCES public.supplier_profile(tenant_id, vendor_profile_id);

ALTER TABLE ONLY public.supplier_endpoint_binding
    ADD CONSTRAINT fk_sbinding_profile FOREIGN KEY (tenant_id, vendor_profile_id) REFERENCES public.supplier_profile(tenant_id, vendor_profile_id);

ALTER TABLE ONLY public.supplier_endpoint_binding_redaction
    ADD CONSTRAINT fk_sbinding_redaction_binding FOREIGN KEY (tenant_id, binding_id) REFERENCES public.supplier_endpoint_binding(tenant_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.supplier_schedule_lease
    ADD CONSTRAINT fk_slease_binding FOREIGN KEY (tenant_id, binding_id) REFERENCES public.supplier_endpoint_binding(tenant_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.supplier_pricat_entry
    ADD CONSTRAINT fk_spricat_entry_import FOREIGN KEY (tenant_id, import_manifest_id) REFERENCES public.supplier_pricat_import(tenant_id, import_manifest_id);

ALTER TABLE ONLY public.supplier_pricat_unmatched_line
    ADD CONSTRAINT fk_spricat_unmatched_import FOREIGN KEY (tenant_id, import_manifest_id) REFERENCES public.supplier_pricat_import(tenant_id, import_manifest_id);

ALTER TABLE ONLY public.supplier_stock_snapshot_line
    ADD CONSTRAINT fk_sstock_line_snapshot FOREIGN KEY (tenant_id, snapshot_id) REFERENCES public.supplier_stock_snapshot(tenant_id, snapshot_id);

ALTER TABLE ONLY public.supplier_transmission_line
    ADD CONSTRAINT fk_stline_intent FOREIGN KEY (tenant_id, transmission_intent_id) REFERENCES public.supplier_transmission_intent(tenant_id, transmission_intent_id);

ALTER TABLE ONLY public.supplier_invoice_line
    ADD CONSTRAINT supplier_invoice_line_supplier_invoice_id_fkey FOREIGN KEY (tenant_id, supplier_invoice_id) REFERENCES public.supplier_invoice(tenant_id, supplier_invoice_id);

CREATE INDEX ext_product_code_tenant_idx ON public.ext_product_code USING btree (tenant_id);

CREATE INDEX supplier_account_tenant_idx ON public.supplier_account USING btree (tenant_id);

CREATE INDEX supplier_audit_access_tenant_idx ON public.supplier_audit_access USING btree (tenant_id);

CREATE INDEX supplier_auth_config_tenant_idx ON public.supplier_auth_config USING btree (tenant_id);

CREATE INDEX supplier_endpoint_binding_tenant_idx ON public.supplier_endpoint_binding USING btree (tenant_id);

CREATE INDEX supplier_endpoint_binding_redaction_tenant_idx ON public.supplier_endpoint_binding_redaction USING btree (tenant_id);

CREATE INDEX supplier_exchange_audit_tenant_idx ON public.supplier_exchange_audit USING btree (tenant_id);

CREATE INDEX supplier_invoice_tenant_idx ON public.supplier_invoice USING btree (tenant_id);

CREATE INDEX supplier_invoice_line_tenant_idx ON public.supplier_invoice_line USING btree (tenant_id);

CREATE INDEX supplier_pricat_entry_tenant_idx ON public.supplier_pricat_entry USING btree (tenant_id);

CREATE INDEX supplier_pricat_import_tenant_idx ON public.supplier_pricat_import USING btree (tenant_id);

CREATE INDEX supplier_pricat_unmatched_line_tenant_idx ON public.supplier_pricat_unmatched_line USING btree (tenant_id);

CREATE INDEX supplier_profile_tenant_idx ON public.supplier_profile USING btree (tenant_id);

CREATE INDEX supplier_schedule_lease_tenant_idx ON public.supplier_schedule_lease USING btree (tenant_id);

CREATE INDEX supplier_stock_snapshot_tenant_idx ON public.supplier_stock_snapshot USING btree (tenant_id);

CREATE INDEX supplier_stock_snapshot_line_tenant_idx ON public.supplier_stock_snapshot_line USING btree (tenant_id);

CREATE INDEX supplier_transmission_intent_tenant_idx ON public.supplier_transmission_intent USING btree (tenant_id);

CREATE INDEX supplier_transmission_line_tenant_idx ON public.supplier_transmission_line USING btree (tenant_id);

ALTER TABLE public.ext_product_code ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_product_code FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_product_code
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_account ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_account FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_account
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_audit_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_audit_access FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_audit_access
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_auth_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_auth_config FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_auth_config
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_endpoint_binding ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_endpoint_binding FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_endpoint_binding
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_endpoint_binding_redaction ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_endpoint_binding_redaction FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_endpoint_binding_redaction
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_exchange_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_exchange_audit FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_exchange_audit
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_invoice ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_invoice FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_invoice
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_invoice_line ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_invoice_line FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_invoice_line
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_mktcat_subscription ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_mktcat_subscription FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_mktcat_subscription
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_mktcat_variant ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_mktcat_variant FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_mktcat_variant
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_pricat_entry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_pricat_entry FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_pricat_entry
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_pricat_import ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_pricat_import FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_pricat_import
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_pricat_unmatched_line ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_pricat_unmatched_line FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_pricat_unmatched_line
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_profile FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_profile
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_schedule_lease ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_schedule_lease FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_schedule_lease
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_stock_snapshot ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_stock_snapshot FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_stock_snapshot
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_stock_snapshot_line ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_stock_snapshot_line FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_stock_snapshot_line
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_transmission_intent ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_transmission_intent FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_transmission_intent
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_transmission_line ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_transmission_line FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_transmission_line
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_workorder_authorization ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_workorder_authorization FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_workorder_authorization
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());
