-- pos-invoice: Flyway baseline (flattened 2026-09-09 from the previous migration history) with the
-- ADR-0062 tenancy schema folded in. Generated by scripts/db/tenancy/flatten.py from a pg_dump of a
-- database migrated with the retired scripts; the tenancy additions are mechanical and are listed in
-- docs/TENANCY_SCHEMA.md. Global (unscoped) tables: src/main/resources/db/tenancy-global-tables.txt.
--
-- Tenant context: app_current_tenant() reads the session setting app.current_tenant, which the
-- TenantAwareDataSource (pos-tenancy-common, plan WS1) binds per checkout. Until then the owner role
-- carries a transitional default (postgres/init-tenancy.sh) and tests set it per connection.
-- With nothing bound: NULL -> every scoped table reads as empty and refuses inserts (fail closed).

-- Functions are emitted before the tables they reference (pg_dump order); do not validate bodies.
SET check_function_bodies = false;

CREATE OR REPLACE FUNCTION public.app_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$ SELECT NULLIF(current_setting('app.current_tenant', true), '')::uuid $$;

CREATE TABLE public.billing_rules (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    purchase_order_required boolean NOT NULL,
    version integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    invoice_delivery_method character varying(20) NOT NULL,
    invoice_grouping_strategy character varying(30) NOT NULL,
    party_id character varying(36) NOT NULL,
    updated_by character varying(36) NOT NULL,
    payment_terms_code character varying(50) NOT NULL,
    fleet_authorization_required boolean DEFAULT false NOT NULL,
    fleet_supplier_ref character varying(100),
    CONSTRAINT billing_rules_invoice_delivery_method_check CHECK (((invoice_delivery_method)::text = ANY (ARRAY[('EMAIL'::character varying)::text, ('PORTAL'::character varying)::text, ('MAIL'::character varying)::text]))),
    CONSTRAINT billing_rules_invoice_grouping_strategy_check CHECK (((invoice_grouping_strategy)::text = ANY (ARRAY[('PER_WORKORDER'::character varying)::text, ('PER_VEHICLE'::character varying)::text, ('SINGLE_INVOICE'::character varying)::text]))),
    CONSTRAINT billing_rules_payment_terms_code_check CHECK (((payment_terms_code)::text = ANY ((ARRAY['DUE_ON_RECEIPT'::character varying, 'NET_10'::character varying, 'NET_15'::character varying, 'NET_30'::character varying, 'NET_45'::character varying, 'NET_60'::character varying])::text[]))),
    CONSTRAINT ck_billing_rules_fleet_ref CHECK (((fleet_authorization_required = false) OR (fleet_supplier_ref IS NOT NULL)))
);

CREATE TABLE public.deposit_credit (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    deposit_credit_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    source_type character varying(16) NOT NULL,
    source_id uuid NOT NULL,
    order_id uuid NOT NULL,
    party_id character varying(64),
    currency_code character varying(3) DEFAULT 'USD'::character varying NOT NULL,
    original_amount numeric(19,4) NOT NULL,
    remaining_balance numeric(19,4) NOT NULL,
    status character varying(24) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT chk_deposit_original_positive CHECK ((original_amount > (0)::numeric)),
    CONSTRAINT chk_deposit_remaining_range CHECK (((remaining_balance >= (0)::numeric) AND (remaining_balance <= original_amount)))
);

CREATE TABLE public.deposit_credit_application (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    application_id uuid NOT NULL,
    deposit_credit_id uuid NOT NULL,
    invoice_id uuid NOT NULL,
    amount_applied numeric(19,4) NOT NULL,
    applied_at timestamp with time zone NOT NULL,
    CONSTRAINT chk_deposit_application_positive CHECK ((amount_applied > (0)::numeric))
);

CREATE TABLE public.event_outbox (
    id uuid NOT NULL,
    topic character varying(255) NOT NULL,
    record_key character varying(255) NOT NULL,
    payload text NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    published_at timestamp(6) with time zone,
    attempts integer DEFAULT 0 NOT NULL,
    last_error text
);

CREATE TABLE public.ext_customer_party (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    party_id uuid NOT NULL,
    party_type character varying(32) NOT NULL,
    display_name character varying(255),
    status character varying(32) NOT NULL,
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.ext_location (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    location_id uuid NOT NULL,
    name character varying(255),
    active boolean DEFAULT false NOT NULL,
    address_line1 character varying(255),
    address_line2 character varying(255),
    city character varying(255),
    region character varying(64),
    postal_code character varying(32),
    country character varying(8),
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    timezone character varying(64),
    financial_ancestor_ids text DEFAULT ''::text NOT NULL,
    other_ancestor_ids text DEFAULT ''::text NOT NULL
);

CREATE TABLE public.ext_location_parent (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    child_id uuid NOT NULL,
    parent_type character varying(64) NOT NULL,
    parent_id uuid NOT NULL
);

CREATE TABLE public.ext_people_employee (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    employee_id uuid NOT NULL,
    person_id uuid NOT NULL,
    employee_number character varying(64),
    status character varying(20) NOT NULL,
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.ext_workorder (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    workorder_id uuid NOT NULL,
    workorder_number character varying(64),
    status character varying(64),
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    customer_id uuid,
    workorder_created_at timestamp(6) with time zone
);

CREATE TABLE public.invoice_adjustments (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    amount numeric(19,4) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    invoice_id uuid NOT NULL,
    type character varying(20) NOT NULL,
    authorized_by character varying(64) NOT NULL,
    reason character varying(512) NOT NULL,
    external_reference character varying(64),
    CONSTRAINT invoice_adjustments_type_check CHECK (((type)::text = ANY ((ARRAY['DISCOUNT'::character varying, 'FEE'::character varying, 'CORRECTION'::character varying, 'WARRANTY'::character varying])::text[])))
);

CREATE TABLE public.invoice_items (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    line_total numeric(19,4) NOT NULL,
    quantity numeric(19,4) NOT NULL,
    unit_price numeric(19,4) NOT NULL,
    id uuid NOT NULL,
    invoice_id uuid NOT NULL,
    workorder_item_id uuid,
    description character varying(512) NOT NULL,
    type character varying(32)
);

CREATE TABLE public.invoice_line_tax (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    invoice_id uuid NOT NULL,
    line_item_id character varying(64),
    jurisdiction_type character varying(32) NOT NULL,
    jurisdiction_code character varying(64) NOT NULL,
    rate numeric(9,6) NOT NULL,
    taxable_base numeric(19,4) NOT NULL,
    tax_amount numeric(19,4) NOT NULL,
    exempt boolean DEFAULT false NOT NULL,
    exemption_reason_code character varying(32),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.invoice_tax_summary (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    invoice_id uuid NOT NULL,
    jurisdiction_type character varying(32) NOT NULL,
    jurisdiction_code character varying(64) NOT NULL,
    taxable_base numeric(19,4) NOT NULL,
    tax_amount numeric(19,4) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.invoices (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    adjustments_amount numeric(19,4) NOT NULL,
    subtotal numeric(19,4) NOT NULL,
    tax_amount numeric(19,4) NOT NULL,
    total_amount numeric(19,4) NOT NULL,
    version integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    finalized_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    approval_id uuid,
    estimate_id uuid,
    id uuid NOT NULL,
    workorder_id uuid,
    status character varying(20) NOT NULL,
    customer_id character varying(64),
    finalized_by character varying(64),
    invoice_number character varying(64),
    location_id uuid,
    due_date date,
    payment_terms_code character varying(20),
    order_id uuid,
    deposit_source_type character varying(16),
    deposit_source_id uuid,
    gl_entry_id uuid,
    CONSTRAINT invoices_finalized_due_date_check CHECK ((((status)::text <> ALL ((ARRAY['FINALIZED'::character varying, 'POSTED'::character varying])::text[])) OR ((due_date IS NOT NULL) AND (payment_terms_code IS NOT NULL)))),
    CONSTRAINT invoices_status_check CHECK (((status)::text = ANY (ARRAY[('DRAFT'::character varying)::text, ('FINALIZED'::character varying)::text, ('POSTED'::character varying)::text, ('ERROR'::character varying)::text])))
);

CREATE TABLE public.payment_intents (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    authorized_amount numeric(15,2),
    captured_amount numeric(15,2),
    voided_remainder_amount numeric(15,2),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    invoice_id uuid NOT NULL,
    payment_flow character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    gateway_provider character varying(50),
    gateway_reference character varying(100),
    idempotency_key character varying(128) NOT NULL,
    gateway_response text,
    payment_token character varying(255) NOT NULL,
    CONSTRAINT payment_intents_payment_flow_check CHECK (((payment_flow)::text = ANY (ARRAY[('SALE_CAPTURE'::character varying)::text, ('AUTH_ONLY'::character varying)::text]))),
    CONSTRAINT payment_intents_status_check CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('AUTHORIZED'::character varying)::text, ('CAPTURED'::character varying)::text, ('CAPTURE_FAILED'::character varying)::text, ('VOIDED'::character varying)::text, ('EXPIRED'::character varying)::text])))
);

CREATE TABLE public.processed_events (
    event_id character varying(36) NOT NULL,
    tenant_id uuid,
    owner character varying(64) NOT NULL,
    processed_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.receipts (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    reprint_count integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    delivery_method character varying(10),
    delivery_status character varying(10),
    id uuid NOT NULL,
    invoice_id uuid NOT NULL,
    payment_intent_id uuid NOT NULL,
    status character varying(20) NOT NULL,
    template_version character varying(32) NOT NULL,
    reference character varying(64) NOT NULL,
    terminal_id character varying(64) NOT NULL,
    cashier_id character varying(128) NOT NULL,
    last_reprinted_by character varying(128),
    template_id character varying(128) NOT NULL,
    delivery_email_address character varying(256),
    last_reprint_reason character varying(256),
    CONSTRAINT receipts_delivery_method_check CHECK (((delivery_method)::text = ANY (ARRAY[('PRINT'::character varying)::text, ('EMAIL'::character varying)::text]))),
    CONSTRAINT receipts_delivery_status_check CHECK (((delivery_status)::text = ANY (ARRAY[('SUCCESS'::character varying)::text, ('FAILED'::character varying)::text]))),
    CONSTRAINT receipts_status_check CHECK (((status)::text = 'GENERATED'::text))
);

CREATE TABLE public.refund_records (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    amount numeric(19,4) NOT NULL,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    requested_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    invoice_id uuid,
    payment_intent_id uuid,
    status character varying(20) NOT NULL,
    reason character varying(30) NOT NULL,
    requested_by character varying(128) NOT NULL,
    gateway_reference character varying(256),
    notes character varying(1024),
    external_reference character varying(64),
    party_id character varying(64),
    CONSTRAINT refund_records_anchor_check CHECK (((payment_intent_id IS NOT NULL) OR (invoice_id IS NOT NULL) OR (party_id IS NOT NULL))),
    CONSTRAINT refund_records_reason_check CHECK (((reason)::text = ANY (ARRAY[('CUSTOMER_RETURN'::character varying)::text, ('SERVICE_ERROR'::character varying)::text, ('OVERCHARGE'::character varying)::text, ('DAMAGED_GOODS'::character varying)::text, ('GOODWILL'::character varying)::text, ('CHARGEBACK_AVOIDANCE'::character varying)::text, ('FRAUD_PREVENTION'::character varying)::text, ('MANAGER_DISCRETION'::character varying)::text, ('OTHER'::character varying)::text]))),
    CONSTRAINT refund_records_status_check CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('COMPLETED'::character varying)::text, ('FAILED'::character varying)::text])))
);

ALTER TABLE ONLY public.billing_rules
    ADD CONSTRAINT billing_rules_party_id_key UNIQUE (tenant_id, party_id);

ALTER TABLE ONLY public.billing_rules
    ADD CONSTRAINT billing_rules_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.billing_rules
    ADD CONSTRAINT billing_rules_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.deposit_credit_application
    ADD CONSTRAINT deposit_credit_application_pkey PRIMARY KEY (application_id);

ALTER TABLE ONLY public.deposit_credit_application
    ADD CONSTRAINT deposit_credit_application_tenant_key UNIQUE (tenant_id, application_id);

ALTER TABLE ONLY public.deposit_credit
    ADD CONSTRAINT deposit_credit_pkey PRIMARY KEY (deposit_credit_id);

ALTER TABLE ONLY public.deposit_credit
    ADD CONSTRAINT deposit_credit_tenant_key UNIQUE (tenant_id, deposit_credit_id);

ALTER TABLE ONLY public.event_outbox
    ADD CONSTRAINT event_outbox_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ext_customer_party
    ADD CONSTRAINT ext_customer_party_pkey PRIMARY KEY (party_id);

ALTER TABLE ONLY public.ext_customer_party
    ADD CONSTRAINT ext_customer_party_tenant_key UNIQUE (tenant_id, party_id);

ALTER TABLE ONLY public.ext_location_parent
    ADD CONSTRAINT ext_location_parent_pkey PRIMARY KEY (child_id, parent_type);

ALTER TABLE ONLY public.ext_location_parent
    ADD CONSTRAINT ext_location_parent_tenant_key UNIQUE (tenant_id, child_id, parent_type);

ALTER TABLE ONLY public.ext_location
    ADD CONSTRAINT ext_location_pkey PRIMARY KEY (location_id);

ALTER TABLE ONLY public.ext_location
    ADD CONSTRAINT ext_location_tenant_key UNIQUE (tenant_id, location_id);

ALTER TABLE ONLY public.ext_people_employee
    ADD CONSTRAINT ext_people_employee_pkey PRIMARY KEY (employee_id);

ALTER TABLE ONLY public.ext_people_employee
    ADD CONSTRAINT ext_people_employee_tenant_key UNIQUE (tenant_id, employee_id);

ALTER TABLE ONLY public.ext_workorder
    ADD CONSTRAINT ext_workorder_pkey PRIMARY KEY (workorder_id);

ALTER TABLE ONLY public.ext_workorder
    ADD CONSTRAINT ext_workorder_tenant_key UNIQUE (tenant_id, workorder_id);

ALTER TABLE ONLY public.invoice_adjustments
    ADD CONSTRAINT invoice_adjustments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoice_adjustments
    ADD CONSTRAINT invoice_adjustments_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.invoice_items
    ADD CONSTRAINT invoice_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoice_items
    ADD CONSTRAINT invoice_items_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.invoice_line_tax
    ADD CONSTRAINT invoice_line_tax_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoice_line_tax
    ADD CONSTRAINT invoice_line_tax_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.invoice_tax_summary
    ADD CONSTRAINT invoice_tax_summary_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoice_tax_summary
    ADD CONSTRAINT invoice_tax_summary_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.payment_intents
    ADD CONSTRAINT payment_intents_idempotency_key_key UNIQUE (tenant_id, idempotency_key);

ALTER TABLE ONLY public.payment_intents
    ADD CONSTRAINT payment_intents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.payment_intents
    ADD CONSTRAINT payment_intents_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.processed_events
    ADD CONSTRAINT processed_events_pkey PRIMARY KEY (event_id);

ALTER TABLE ONLY public.receipts
    ADD CONSTRAINT receipts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.receipts
    ADD CONSTRAINT receipts_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.receipts
    ADD CONSTRAINT receipts_reference_key UNIQUE (tenant_id, reference);

ALTER TABLE ONLY public.refund_records
    ADD CONSTRAINT refund_records_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.refund_records
    ADD CONSTRAINT refund_records_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.deposit_credit_application
    ADD CONSTRAINT uq_deposit_application_credit_invoice UNIQUE (tenant_id, deposit_credit_id, invoice_id);

ALTER TABLE ONLY public.deposit_credit
    ADD CONSTRAINT uq_deposit_credit_order UNIQUE (tenant_id, order_id);

CREATE INDEX idx_event_outbox_unpublished ON public.event_outbox USING btree (id) WHERE (published_at IS NULL);

CREATE INDEX idx_ext_customer_party_display_name ON public.ext_customer_party USING btree (lower((display_name)::text));

CREATE INDEX idx_ext_location_parent_parent ON public.ext_location_parent USING btree (parent_id, parent_type);

CREATE INDEX idx_ext_workorder_number ON public.ext_workorder USING btree (workorder_number);

CREATE INDEX idx_inv_ext_employee_number ON public.ext_people_employee USING btree (employee_number);

CREATE INDEX idx_invoice_line_tax_invoice ON public.invoice_line_tax USING btree (invoice_id);

CREATE INDEX idx_invoice_tax_summary_invoice ON public.invoice_tax_summary USING btree (invoice_id);

CREATE INDEX idx_processed_events_owner_tenant_event ON public.processed_events USING btree (owner, tenant_id, event_id);

CREATE INDEX ix_deposit_application_invoice ON public.deposit_credit_application USING btree (invoice_id);

CREATE INDEX ix_deposit_credit_source ON public.deposit_credit USING btree (source_type, source_id);

CREATE INDEX ix_deposit_credit_status ON public.deposit_credit USING btree (status);

CREATE UNIQUE INDEX ux_invoice_adjustments_type_external_reference ON public.invoice_adjustments USING btree (tenant_id, type, external_reference) WHERE (external_reference IS NOT NULL);

CREATE UNIQUE INDEX ux_invoices_order_id ON public.invoices USING btree (tenant_id, order_id) WHERE (order_id IS NOT NULL);

CREATE UNIQUE INDEX ux_refund_records_external_reference_active ON public.refund_records USING btree (tenant_id, external_reference) WHERE ((external_reference IS NOT NULL) AND ((status)::text <> 'FAILED'::text));

ALTER TABLE ONLY public.receipts
    ADD CONSTRAINT fk3hmid8b40s5yd0jo2s36684ql FOREIGN KEY (tenant_id, invoice_id) REFERENCES public.invoices(tenant_id, id);

ALTER TABLE ONLY public.invoice_items
    ADD CONSTRAINT fk46ae0lhu1oqs7cv91fn6y9n7w FOREIGN KEY (tenant_id, invoice_id) REFERENCES public.invoices(tenant_id, id);

ALTER TABLE ONLY public.refund_records
    ADD CONSTRAINT fk5g4w2npjrmc4r1ktid7kssfpi FOREIGN KEY (tenant_id, invoice_id) REFERENCES public.invoices(tenant_id, id);

ALTER TABLE ONLY public.payment_intents
    ADD CONSTRAINT fk8d5o0e14e7pi75wj8tiddlcvr FOREIGN KEY (tenant_id, invoice_id) REFERENCES public.invoices(tenant_id, id);

ALTER TABLE ONLY public.deposit_credit_application
    ADD CONSTRAINT fk_deposit_application_credit FOREIGN KEY (tenant_id, deposit_credit_id) REFERENCES public.deposit_credit(tenant_id, deposit_credit_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.invoice_line_tax
    ADD CONSTRAINT fk_invoice_line_tax_invoice FOREIGN KEY (tenant_id, invoice_id) REFERENCES public.invoices(tenant_id, id);

ALTER TABLE ONLY public.invoice_tax_summary
    ADD CONSTRAINT fk_invoice_tax_summary_invoice FOREIGN KEY (tenant_id, invoice_id) REFERENCES public.invoices(tenant_id, id);

ALTER TABLE ONLY public.invoice_adjustments
    ADD CONSTRAINT fkd0x10ud3y581kk2luh2g58jce FOREIGN KEY (tenant_id, invoice_id) REFERENCES public.invoices(tenant_id, id);

ALTER TABLE ONLY public.refund_records
    ADD CONSTRAINT fker3axvi18hhhp3flqraoxg3ay FOREIGN KEY (tenant_id, payment_intent_id) REFERENCES public.payment_intents(tenant_id, id);

ALTER TABLE ONLY public.receipts
    ADD CONSTRAINT fkfbqduvxs5411vrk6du06vwv4s FOREIGN KEY (tenant_id, payment_intent_id) REFERENCES public.payment_intents(tenant_id, id);

CREATE INDEX billing_rules_tenant_idx ON public.billing_rules USING btree (tenant_id);

CREATE INDEX deposit_credit_tenant_idx ON public.deposit_credit USING btree (tenant_id);

CREATE INDEX deposit_credit_application_tenant_idx ON public.deposit_credit_application USING btree (tenant_id);

CREATE INDEX ext_customer_party_tenant_idx ON public.ext_customer_party USING btree (tenant_id);

CREATE INDEX ext_location_tenant_idx ON public.ext_location USING btree (tenant_id);

CREATE INDEX ext_location_parent_tenant_idx ON public.ext_location_parent USING btree (tenant_id);

CREATE INDEX ext_people_employee_tenant_idx ON public.ext_people_employee USING btree (tenant_id);

CREATE INDEX ext_workorder_tenant_idx ON public.ext_workorder USING btree (tenant_id);

CREATE INDEX invoice_items_tenant_idx ON public.invoice_items USING btree (tenant_id);

CREATE INDEX invoice_line_tax_tenant_idx ON public.invoice_line_tax USING btree (tenant_id);

CREATE INDEX invoice_tax_summary_tenant_idx ON public.invoice_tax_summary USING btree (tenant_id);

CREATE INDEX payment_intents_tenant_idx ON public.payment_intents USING btree (tenant_id);

CREATE INDEX receipts_tenant_idx ON public.receipts USING btree (tenant_id);

ALTER TABLE public.billing_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_rules FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.billing_rules
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.deposit_credit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deposit_credit FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.deposit_credit
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.deposit_credit_application ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deposit_credit_application FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.deposit_credit_application
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_customer_party ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_customer_party FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_customer_party
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_location ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_location FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_location
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_location_parent ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_location_parent FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_location_parent
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_people_employee ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_people_employee FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_people_employee
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_workorder ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_workorder FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_workorder
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.invoice_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_adjustments FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.invoice_adjustments
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.invoice_items
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.invoice_line_tax ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_line_tax FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.invoice_line_tax
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.invoice_tax_summary ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_tax_summary FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.invoice_tax_summary
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.invoices
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.payment_intents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_intents FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.payment_intents
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receipts FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.receipts
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.refund_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.refund_records FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.refund_records
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());
