spring:
  application:
    name: image
  datasource:
    url: jdbc:postgresql://localhost:5432/pos_image_db
    username: ${SPRING_DATASOURCE_USERNAME:pos_user}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 0

management:
  server:
    port: 0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org:
      springframework: INFO
    com:
      positivity:
        posimage: INFO
