-- pos-event-receiver: Flyway baseline (flattened 2026-09-09 from the previous migration history) with the
-- ADR-0062 tenancy schema folded in. Generated by scripts/db/tenancy/flatten.py from a pg_dump of a
-- database migrated with the retired scripts; the tenancy additions are mechanical and are listed in
-- docs/TENANCY_SCHEMA.md. Global (unscoped) tables: src/main/resources/db/tenancy-global-tables.txt.
--
-- Tenant context: app_current_tenant() reads the session setting app.current_tenant, which the
-- TenantAwareDataSource (pos-tenancy-common, plan WS1) binds per checkout. Until then the owner role
-- carries a transitional default (postgres/init-tenancy.sh) and tests set it per connection.
-- With nothing bound: NULL -> every scoped table reads as empty and refuses inserts (fail closed).

-- Functions are emitted before the tables they reference (pg_dump order); do not validate bodies.
SET check_function_bodies = false;

CREATE OR REPLACE FUNCTION public.app_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$ SELECT NULLIF(current_setting('app.current_tenant', true), '')::uuid $$;

CREATE TABLE public.emitted_event (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    event_id uuid NOT NULL,
    id character varying(255),
    api_version character varying(255),
    "timestamp" bigint,
    elapsed_ms bigint,
    published_at timestamp without time zone NOT NULL,
    entity_id character varying(64)
);

CREATE TABLE public.event_type (
    id uuid NOT NULL,
    type_code character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    api_version character varying(255) DEFAULT '1'::character varying NOT NULL,
    p50_micros bigint DEFAULT 10000000 NOT NULL,
    p95_micros bigint DEFAULT 10000000 NOT NULL,
    p99_micros bigint DEFAULT 10000000 NOT NULL
);

CREATE TABLE public.preregistered_event (
    id character varying(255) NOT NULL
);

ALTER TABLE ONLY public.emitted_event
    ADD CONSTRAINT emitted_event_pkey PRIMARY KEY (event_id, published_at);

ALTER TABLE ONLY public.emitted_event
    ADD CONSTRAINT emitted_event_tenant_key UNIQUE (tenant_id, event_id, published_at);

ALTER TABLE ONLY public.event_type
    ADD CONSTRAINT event_type_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.preregistered_event
    ADD CONSTRAINT preregistered_event_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.event_type
    ADD CONSTRAINT uk_event_type_type_code UNIQUE (type_code);

CREATE INDEX idx_emitted_event_entity_time ON public.emitted_event USING btree (entity_id, published_at DESC) WHERE (entity_id IS NOT NULL);

CREATE INDEX idx_emitted_event_id ON public.emitted_event USING btree (id);

CREATE INDEX emitted_event_tenant_idx ON public.emitted_event USING btree (tenant_id);

ALTER TABLE public.emitted_event ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emitted_event FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.emitted_event
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());
