-- pos-catalog: Flyway baseline (flattened 2026-09-09 from the previous migration history) with the
-- ADR-0062 tenancy schema folded in. Generated by scripts/db/tenancy/flatten.py from a pg_dump of a
-- database migrated with the retired scripts; the tenancy additions are mechanical and are listed in
-- docs/TENANCY_SCHEMA.md. Global (unscoped) tables: src/main/resources/db/tenancy-global-tables.txt.
--
-- Tenant context: app_current_tenant() reads the session setting app.current_tenant, which the
-- TenantAwareDataSource (pos-tenancy-common, plan WS1) binds per checkout. Until then the owner role
-- carries a transitional default (postgres/init-tenancy.sh) and tests set it per connection.
-- With nothing bound: NULL -> every scoped table reads as empty and refuses inserts (fail closed).

-- Functions are emitted before the tables they reference (pg_dump order); do not validate bodies.
SET check_function_bodies = false;

CREATE OR REPLACE FUNCTION public.app_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$ SELECT NULLIF(current_setting('app.current_tenant', true), '')::uuid $$;

CREATE TABLE public.approval_request (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    resolved_at timestamp(6) with time zone,
    assigned_approver_id uuid NOT NULL,
    id uuid NOT NULL,
    override_id uuid NOT NULL,
    status character varying(32) NOT NULL,
    assignment_strategy character varying(128) NOT NULL,
    CONSTRAINT approval_request_status_check CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('APPROVED'::character varying)::text, ('REJECTED'::character varying)::text])))
);

CREATE TABLE public.catalog_entity (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    description character varying(255),
    name character varying(255)
);

CREATE TABLE public.catalog_entity_non_inventory_products (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    catalog_entity_id uuid NOT NULL,
    non_inventory_products_id uuid NOT NULL
);

CREATE TABLE public.catalog_entity_products (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    catalog_entity_id uuid NOT NULL,
    products_id uuid NOT NULL
);

CREATE TABLE public.catalog_entity_services (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    catalog_entity_id uuid NOT NULL,
    services_id uuid NOT NULL
);

CREATE TABLE public.category (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    name character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.competitorxreference (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    competitor_part_id uuid,
    id uuid NOT NULL,
    part_id uuid
);

CREATE TABLE public.dimensions (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    dimension_value double precision NOT NULL,
    id uuid NOT NULL,
    product_id uuid,
    description character varying(255),
    dimension_type character varying(255),
    unit_of_measure character varying(255),
    CONSTRAINT dimensions_dimension_type_check CHECK (((dimension_type)::text = ANY (ARRAY[('LENGTH'::character varying)::text, ('WIDTH'::character varying)::text, ('HEIGHT'::character varying)::text, ('WEIGHT'::character varying)::text, ('VOLUME'::character varying)::text, ('AREA'::character varying)::text, ('DIAMETER'::character varying)::text, ('CIRCUMFERENCE'::character varying)::text, ('RADIUS'::character varying)::text, ('TEMPERATURE'::character varying)::text, ('TIME'::character varying)::text, ('SPEED'::character varying)::text, ('PRESSURE'::character varying)::text, ('FORCE'::character varying)::text, ('ENERGY'::character varying)::text, ('POWER'::character varying)::text, ('FREQUENCY'::character varying)::text, ('ANGLE'::character varying)::text, ('DATA_SIZE'::character varying)::text, ('CURRENT'::character varying)::text, ('VOLTAGE'::character varying)::text, ('RESISTANCE'::character varying)::text])))
);

CREATE TABLE public.event_outbox (
    id uuid NOT NULL,
    topic character varying(255) NOT NULL,
    record_key character varying(255) NOT NULL,
    payload text NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    published_at timestamp(6) with time zone,
    attempts integer DEFAULT 0 NOT NULL,
    last_error text
);

CREATE TABLE public.ext_inventory_availability (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    aggregate_id uuid NOT NULL,
    stock_item_id character varying(255) NOT NULL,
    location_id uuid,
    on_hand_quantity numeric(19,4) NOT NULL,
    allocated_quantity numeric(19,4) NOT NULL,
    available_to_promise_quantity numeric(19,4) NOT NULL,
    unit_of_measure character varying(32),
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.ext_location (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    location_id uuid NOT NULL,
    name character varying(255),
    active boolean DEFAULT true NOT NULL,
    aggregate_version bigint NOT NULL,
    financial_ancestor_ids text DEFAULT ''::text NOT NULL,
    other_ancestor_ids text DEFAULT ''::text NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.ext_location_parent (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    child_id uuid NOT NULL,
    parent_type character varying(64) NOT NULL,
    parent_id uuid NOT NULL
);

CREATE TABLE public.ext_product_lead_time (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    product_id uuid NOT NULL,
    min_days integer,
    max_days integer,
    display_text character varying(64),
    source character varying(64),
    confidence character varying(32),
    as_of timestamp(6) with time zone,
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.guardrail_policy (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    auto_approval_threshold_percent numeric(10,4) NOT NULL,
    max_discount_percent numeric(10,4) NOT NULL,
    min_margin_percent numeric(10,4) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    scope_id uuid NOT NULL,
    scope character varying(32) NOT NULL,
    CONSTRAINT guardrail_policy_scope_check CHECK (((scope)::text = ANY (ARRAY[('LOCATION'::character varying)::text, ('REGION'::character varying)::text])))
);

CREATE TABLE public.item_cost (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    average_cost numeric(19,4),
    last_cost numeric(19,4),
    qty_on_hand numeric(19,4) NOT NULL,
    standard_cost numeric(19,4),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    item_cost_id uuid NOT NULL,
    item_id uuid NOT NULL
);

CREATE TABLE public.item_cost_audit (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    new_value numeric(19,4),
    old_value numeric(19,4),
    audit_timestamp timestamp(6) with time zone NOT NULL,
    audit_id uuid NOT NULL,
    item_id uuid NOT NULL,
    actor character varying(255) NOT NULL,
    change_source_id character varying(255) NOT NULL,
    change_source_type character varying(255) NOT NULL,
    cost_type_changed character varying(255) NOT NULL,
    reason_code character varying(255),
    CONSTRAINT item_cost_audit_change_source_type_check CHECK (((change_source_type)::text = ANY (ARRAY[('MANUAL'::character varying)::text, ('PURCHASE_ORDER'::character varying)::text]))),
    CONSTRAINT item_cost_audit_cost_type_changed_check CHECK (((cost_type_changed)::text = ANY (ARRAY[('STANDARD'::character varying)::text, ('LAST'::character varying)::text, ('AVERAGE'::character varying)::text])))
);

CREATE TABLE public.labor_guide_import (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    import_manifest_id uuid NOT NULL,
    source_code character varying(32) NOT NULL,
    source_revision character varying(64) NOT NULL,
    expected_chunk_count integer NOT NULL,
    expected_line_count bigint NOT NULL,
    content_checksum character varying(128) NOT NULL,
    chunks_applied integer DEFAULT 0 NOT NULL,
    lines_applied bigint DEFAULT 0 NOT NULL,
    lines_unmapped bigint DEFAULT 0 NOT NULL,
    status character varying(16) NOT NULL,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_lgi_status CHECK (((status)::text = ANY ((ARRAY['APPLYING'::character varying, 'COMPLETE'::character varying, 'INCOMPLETE'::character varying])::text[])))
);

CREATE TABLE public.labor_guide_import_chunk (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    import_manifest_id uuid NOT NULL,
    chunk_sequence integer NOT NULL,
    line_count integer NOT NULL,
    applied_at timestamp with time zone NOT NULL
);

CREATE TABLE public.labor_guide_unmapped_operation (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    source_code character varying(32) NOT NULL,
    provider_op_code character varying(128) NOT NULL,
    last_manifest_id uuid,
    occurrence_count bigint DEFAULT 1 NOT NULL,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL
);

CREATE TABLE public.labor_time_source_policy (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    time_type character varying(24) NOT NULL,
    source_code character varying(32) NOT NULL,
    precedence integer NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    operation_category character varying(32),
    CONSTRAINT ck_ltsp_operation_category CHECK (((operation_category IS NULL) OR ((operation_category)::text = ANY ((ARRAY['REPAIR'::character varying, 'DIAGNOSTIC'::character varying, 'MAINTENANCE'::character varying, 'TIRE_SERVICE'::character varying])::text[])))),
    CONSTRAINT ck_ltsp_time_type CHECK (((time_type)::text = ANY ((ARRAY['RETAIL_FLAT_RATE'::character varying, 'OEM_WARRANTY'::character varying, 'MANUFACTURER_INSTALL'::character varying, 'DURION_STANDARD'::character varying])::text[])))
);

CREATE TABLE public.location_price_override (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    base_price numeric(19,4) NOT NULL,
    cost numeric(19,4),
    discount_percent numeric(10,4) NOT NULL,
    margin_percent numeric(10,4),
    override_price numeric(19,4) NOT NULL,
    approved_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    rejected_at timestamp(6) with time zone,
    resolved_at timestamp(6) with time zone,
    version bigint,
    approved_by_user_id uuid,
    created_by_user_id uuid NOT NULL,
    id uuid NOT NULL,
    location_id uuid NOT NULL,
    product_id uuid NOT NULL,
    rejected_by uuid,
    status character varying(32) NOT NULL,
    rejection_reason_code character varying(128),
    rejection_notes character varying(1024),
    CONSTRAINT location_price_override_status_check CHECK (((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('PENDING_APPROVAL'::character varying)::text, ('REJECTED'::character varying)::text, ('INACTIVE'::character varying)::text])))
);

CREATE TABLE public.non_inventory_product (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    long_description character varying(255),
    name character varying(255),
    short_description character varying(255)
);

CREATE TABLE public.oemxreference (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    oem_part_id uuid,
    part_id uuid
);

CREATE TABLE public.price_book (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    is_default boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint,
    price_book_id uuid NOT NULL,
    scope_id uuid,
    status character varying(16) NOT NULL,
    scope character varying(32) NOT NULL,
    name character varying(255) NOT NULL,
    CONSTRAINT price_book_scope_check CHECK (((scope)::text = ANY (ARRAY[('COMPANY_DEFAULT'::character varying)::text, ('LOCATION'::character varying)::text, ('CUSTOMER_TIER'::character varying)::text]))),
    CONSTRAINT price_book_status_check CHECK (((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('INACTIVE'::character varying)::text])))
);

CREATE TABLE public.price_book_rule (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    priority integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    effective_end_at timestamp(6) with time zone,
    effective_start_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint,
    created_by_user_id uuid NOT NULL,
    price_book_id uuid NOT NULL,
    rule_id uuid NOT NULL,
    target_id uuid,
    target_type character varying(16) NOT NULL,
    condition_type character varying(32) NOT NULL,
    status character varying(32) NOT NULL,
    condition_value character varying(255),
    pricing_logic text NOT NULL,
    CONSTRAINT price_book_rule_condition_type_check CHECK (((condition_type)::text = ANY (ARRAY[('CUSTOMER_TIER'::character varying)::text, ('LOCATION'::character varying)::text, ('NONE'::character varying)::text]))),
    CONSTRAINT price_book_rule_status_check CHECK (((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('INACTIVE'::character varying)::text, ('NOT_APPLICABLE_MISSING_BASE'::character varying)::text]))),
    CONSTRAINT price_book_rule_target_type_check CHECK (((target_type)::text = ANY (ARRAY[('SKU'::character varying)::text, ('CATEGORY'::character varying)::text, ('GLOBAL'::character varying)::text])))
);

CREATE TABLE public.processed_events (
    event_id character varying(36) NOT NULL,
    owner character varying(64) NOT NULL,
    processed_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.product (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    last_state_changed_at timestamp(6) with time zone,
    lifecycle_state_effective_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    category_id uuid,
    id uuid NOT NULL,
    last_state_changed_by uuid,
    manufacturer_id uuid,
    subcategory_id uuid,
    color character varying(255),
    country_of_origin character varying(255),
    description character varying(255),
    lifecycle_override_reason character varying(255),
    lifecycle_state character varying(255) DEFAULT 'ACTIVE'::character varying NOT NULL,
    long_description character varying(255),
    manufacturer_brand character varying(255),
    manufacturer_name character varying(255),
    manufacturer_part_number character varying(255),
    manufacturer_warranty character varying(255),
    material character varying(255),
    name character varying(255),
    product_code character varying(255),
    product_code_type character varying(255),
    short_description character varying(255),
    sku character varying(255),
    status character varying(255) DEFAULT 'ACTIVE'::character varying NOT NULL,
    type character varying(255),
    unit_of_measure character varying(255),
    upc character varying(255),
    warranty character varying(255),
    tracking_level character varying(16) DEFAULT 'NONE'::character varying NOT NULL,
    tread_design_id uuid,
    attributes text,
    specifications text,
    version bigint DEFAULT 0 NOT NULL,
    tread_design_source character varying(10),
    CONSTRAINT ck_product_tread_design_source_paired CHECK (((tread_design_id IS NULL) = (tread_design_source IS NULL))),
    CONSTRAINT product_lifecycle_state_check CHECK (((lifecycle_state)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('INACTIVE'::character varying)::text, ('DISCONTINUED'::character varying)::text]))),
    CONSTRAINT product_product_code_type_check CHECK (((product_code_type)::text = ANY (ARRAY[('UPC'::character varying)::text, ('EAN'::character varying)::text]))),
    CONSTRAINT product_status_check CHECK (((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('INACTIVE'::character varying)::text]))),
    CONSTRAINT product_tracking_level_check CHECK (((tracking_level)::text = ANY (ARRAY[('NONE'::character varying)::text, ('LOT'::character varying)::text, ('SERIAL'::character varying)::text])))
);

CREATE TABLE public.product_code_duplicate_report (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    code_type character varying(32) NOT NULL,
    code_value character varying(255) NOT NULL,
    product_count integer NOT NULL,
    product_ids text NOT NULL,
    detected_at timestamp(6) with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.product_code_duplicate_report IS 'EAN/UPC values carried by more than one product at the time the per-type uniqueness constraint was applied (#1232).';

CREATE TABLE public.product_images (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    product_id uuid NOT NULL,
    image_url character varying(255)
);

CREATE TABLE public.product_msrp (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    amount numeric(19,4) NOT NULL,
    currency character varying(3) NOT NULL,
    effective_end_date date,
    effective_start_date date NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint,
    msrp_id uuid NOT NULL,
    product_id uuid NOT NULL,
    updated_by uuid
);

CREATE TABLE public.product_replacement (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    priority_order integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone,
    effective_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    original_product_id uuid NOT NULL,
    replacement_id uuid NOT NULL,
    replacement_product_id uuid NOT NULL,
    notes character varying(255)
);

CREATE TABLE public.product_uom (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    uom_code character varying(32) NOT NULL,
    uom_type character varying(16) NOT NULL,
    factor_to_base numeric(20,6) NOT NULL,
    precision_scale integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT product_uom_uom_type_check CHECK (((uom_type)::text = ANY (ARRAY[('BASE'::character varying)::text, ('PURCHASE'::character varying)::text, ('PACK'::character varying)::text, ('OTHER'::character varying)::text])))
);

CREATE TABLE public.service (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    long_description character varying(255),
    name character varying(255),
    short_description character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    operation_code character varying(64),
    operation_category character varying(32),
    default_labor_hours numeric(5,1),
    CONSTRAINT ck_service_operation_category CHECK (((operation_category IS NULL) OR ((operation_category)::text = ANY ((ARRAY['REPAIR'::character varying, 'DIAGNOSTIC'::character varying, 'MAINTENANCE'::character varying, 'TIRE_SERVICE'::character varying])::text[]))))
);

CREATE TABLE public.service_labor_standard (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    service_id uuid NOT NULL,
    vehicle_year character varying(16),
    make character varying(64),
    model character varying(64),
    submodel character varying(64),
    engine_code character varying(64),
    aces_vehicle_id bigint,
    labor_hours numeric(5,1) NOT NULL,
    time_type character varying(24) NOT NULL,
    overlap_group character varying(64),
    included_op_codes text[],
    source_code character varying(32) NOT NULL,
    source_revision character varying(64) NOT NULL,
    published_at date,
    import_manifest_id uuid,
    superseded_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    owner_scope character varying(16) DEFAULT 'PLATFORM'::character varying NOT NULL,
    owner_location_id uuid,
    CONSTRAINT ck_sls_owner_scope CHECK ((((owner_scope)::text = ANY ((ARRAY['PLATFORM'::character varying, 'SHOP'::character varying])::text[])) AND ((((owner_scope)::text = 'SHOP'::text) AND (owner_location_id IS NOT NULL)) OR (((owner_scope)::text = 'PLATFORM'::text) AND (owner_location_id IS NULL))))),
    CONSTRAINT ck_sls_time_type CHECK (((time_type)::text = ANY ((ARRAY['RETAIL_FLAT_RATE'::character varying, 'OEM_WARRANTY'::character varying, 'MANUFACTURER_INSTALL'::character varying, 'DURION_STANDARD'::character varying])::text[])))
);

CREATE TABLE public.service_operation_xref (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    service_id uuid NOT NULL,
    source_code character varying(32) NOT NULL,
    provider_op_code character varying(128) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.service_package (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    package_code character varying(64) NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    owner_scope character varying(16) DEFAULT 'PLATFORM'::character varying NOT NULL,
    owner_location_id uuid,
    fleet_party_id uuid,
    package_labor_hours numeric(5,1),
    active boolean DEFAULT true NOT NULL,
    effective_from date,
    effective_to date,
    version bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_svc_pkg_owner_scope CHECK ((((owner_scope)::text = ANY ((ARRAY['PLATFORM'::character varying, 'SHOP'::character varying])::text[])) AND ((((owner_scope)::text = 'SHOP'::text) AND (owner_location_id IS NOT NULL)) OR (((owner_scope)::text = 'PLATFORM'::text) AND (owner_location_id IS NULL))))),
    CONSTRAINT ck_svc_pkg_window CHECK (((effective_to IS NULL) OR (effective_from IS NULL) OR (effective_to >= effective_from)))
);

CREATE TABLE public.service_package_member (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    package_id uuid NOT NULL,
    service_id uuid NOT NULL,
    sequence integer NOT NULL,
    quantity numeric(10,2) DEFAULT 1 NOT NULL,
    required boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_svc_pkg_member_qty CHECK ((quantity > (0)::numeric))
);

CREATE TABLE public.subcategory (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    name character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    category_id uuid NOT NULL
);

CREATE TABLE public.substitution_group (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    name character varying(128) NOT NULL,
    notes character varying(512),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.substitution_group_member (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    group_id uuid NOT NULL,
    product_id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.supplier_article_code (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    supplier_ref character varying(100) NOT NULL,
    product_id uuid NOT NULL,
    supplier_article_code character varying(64) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);

CREATE TABLE public.supplier_price_entry (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    supplier_ref character varying(100) NOT NULL,
    product_id uuid NOT NULL,
    match_method character varying(32) NOT NULL,
    article_ean character varying(64),
    supplier_article_code character varying(64),
    x_reference_code character varying(64),
    buyer_account_number character varying(64) NOT NULL,
    country_code character varying(8) NOT NULL,
    currency character varying(8) NOT NULL,
    suggested_retail_price numeric(19,4),
    gross_price numeric(19,4),
    net_price numeric(19,4),
    tax_rate numeric(9,4),
    recycling_fee numeric(19,4),
    effective_from date NOT NULL,
    source_document_id character varying(255),
    source_document_date date,
    import_manifest_id uuid NOT NULL,
    fetched_at timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT ck_supplier_price_entry_match_method CHECK (((match_method)::text = ANY ((ARRAY['EAN'::character varying, 'UPC_XREFERENCE'::character varying])::text[])))
);

CREATE TABLE public.supplier_price_import (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    import_manifest_id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    supplier_ref character varying(100),
    chunks_applied integer DEFAULT 0 NOT NULL,
    lines_applied integer DEFAULT 0 NOT NULL,
    expected_chunk_count integer,
    expected_line_count integer,
    content_checksum character varying(64),
    status character varying(32) NOT NULL,
    completed_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT ck_supplier_price_import_status CHECK (((status)::text = ANY ((ARRAY['APPLYING'::character varying, 'COMPLETE'::character varying, 'INCOMPLETE'::character varying])::text[])))
);

CREATE TABLE public.supplier_price_import_chunk (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    import_manifest_id uuid NOT NULL,
    chunk_sequence integer NOT NULL,
    lines_applied integer NOT NULL,
    applied_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.tread_design (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    vendor_profile_id uuid NOT NULL,
    supplier_ref character varying(100) NOT NULL,
    vendor_variant_id character varying(100) NOT NULL,
    brand character varying(200),
    tread_design character varying(200),
    tread_design_2 character varying(200),
    product_name character varying(300),
    vehicle_type character varying(100),
    seasonality character varying(100),
    content_hash character varying(64) NOT NULL,
    has_unresolved_images boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    match_state character varying(20) NOT NULL,
    match_state_at timestamp(6) with time zone NOT NULL,
    resolved_by character varying(200),
    resolution_note text,
    defer_until timestamp(6) with time zone
);

CREATE TABLE public.tread_design_image (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    tread_design_id uuid NOT NULL,
    image_type character varying(100),
    image_id bigint,
    content_hash character varying(64),
    source_uri character varying(1000),
    unresolved boolean NOT NULL
);

CREATE TABLE public.tread_design_match_candidate (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    tread_design_id uuid NOT NULL,
    product_id uuid NOT NULL,
    score numeric(5,4) NOT NULL,
    tier character varying(20) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.tread_design_text (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    tread_design_id uuid NOT NULL,
    language_code character varying(16) NOT NULL,
    name character varying(300),
    description text,
    foot_notes text
);

CREATE TABLE public.uom_conversion (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    conversion_factor numeric(20,6) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    created_by character varying(255),
    from_uom_code character varying(255) NOT NULL,
    to_uom_code character varying(255) NOT NULL
);

ALTER TABLE ONLY public.approval_request
    ADD CONSTRAINT approval_request_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.approval_request
    ADD CONSTRAINT approval_request_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.catalog_entity_non_inventory_products
    ADD CONSTRAINT catalog_entity_non_inventory_prod_non_inventory_products_id_key UNIQUE (tenant_id, non_inventory_products_id);

ALTER TABLE ONLY public.catalog_entity
    ADD CONSTRAINT catalog_entity_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.catalog_entity
    ADD CONSTRAINT catalog_entity_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.catalog_entity_products
    ADD CONSTRAINT catalog_entity_products_products_id_key UNIQUE (tenant_id, products_id);

ALTER TABLE ONLY public.catalog_entity_services
    ADD CONSTRAINT catalog_entity_services_services_id_key UNIQUE (tenant_id, services_id);

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.competitorxreference
    ADD CONSTRAINT competitorxreference_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.competitorxreference
    ADD CONSTRAINT competitorxreference_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.dimensions
    ADD CONSTRAINT dimensions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.dimensions
    ADD CONSTRAINT dimensions_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.event_outbox
    ADD CONSTRAINT event_outbox_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ext_inventory_availability
    ADD CONSTRAINT ext_inventory_availability_pkey PRIMARY KEY (aggregate_id);

ALTER TABLE ONLY public.ext_inventory_availability
    ADD CONSTRAINT ext_inventory_availability_tenant_key UNIQUE (tenant_id, aggregate_id);

ALTER TABLE ONLY public.ext_location_parent
    ADD CONSTRAINT ext_location_parent_pkey PRIMARY KEY (child_id, parent_type);

ALTER TABLE ONLY public.ext_location_parent
    ADD CONSTRAINT ext_location_parent_tenant_key UNIQUE (tenant_id, child_id, parent_type);

ALTER TABLE ONLY public.ext_location
    ADD CONSTRAINT ext_location_pkey PRIMARY KEY (location_id);

ALTER TABLE ONLY public.ext_location
    ADD CONSTRAINT ext_location_tenant_key UNIQUE (tenant_id, location_id);

ALTER TABLE ONLY public.ext_product_lead_time
    ADD CONSTRAINT ext_product_lead_time_pkey PRIMARY KEY (product_id);

ALTER TABLE ONLY public.ext_product_lead_time
    ADD CONSTRAINT ext_product_lead_time_tenant_key UNIQUE (tenant_id, product_id);

ALTER TABLE ONLY public.guardrail_policy
    ADD CONSTRAINT guardrail_policy_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.guardrail_policy
    ADD CONSTRAINT guardrail_policy_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.item_cost_audit
    ADD CONSTRAINT item_cost_audit_pkey PRIMARY KEY (audit_id);

ALTER TABLE ONLY public.item_cost_audit
    ADD CONSTRAINT item_cost_audit_tenant_key UNIQUE (tenant_id, audit_id);

ALTER TABLE ONLY public.item_cost
    ADD CONSTRAINT item_cost_item_id_key UNIQUE (tenant_id, item_id);

ALTER TABLE ONLY public.item_cost
    ADD CONSTRAINT item_cost_pkey PRIMARY KEY (item_cost_id);

ALTER TABLE ONLY public.item_cost
    ADD CONSTRAINT item_cost_tenant_key UNIQUE (tenant_id, item_cost_id);

ALTER TABLE ONLY public.labor_guide_import_chunk
    ADD CONSTRAINT labor_guide_import_chunk_import_manifest_id_chunk_sequence_key UNIQUE (tenant_id, import_manifest_id, chunk_sequence);

ALTER TABLE ONLY public.labor_guide_import_chunk
    ADD CONSTRAINT labor_guide_import_chunk_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.labor_guide_import_chunk
    ADD CONSTRAINT labor_guide_import_chunk_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.labor_guide_import
    ADD CONSTRAINT labor_guide_import_pkey PRIMARY KEY (import_manifest_id);

ALTER TABLE ONLY public.labor_guide_import
    ADD CONSTRAINT labor_guide_import_tenant_key UNIQUE (tenant_id, import_manifest_id);

ALTER TABLE ONLY public.labor_guide_unmapped_operation
    ADD CONSTRAINT labor_guide_unmapped_operation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.labor_guide_unmapped_operation
    ADD CONSTRAINT labor_guide_unmapped_operation_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.labor_guide_unmapped_operation
    ADD CONSTRAINT labor_guide_unmapped_operation_source_code_provider_op_code_key UNIQUE (tenant_id, source_code, provider_op_code);

ALTER TABLE ONLY public.labor_time_source_policy
    ADD CONSTRAINT labor_time_source_policy_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.labor_time_source_policy
    ADD CONSTRAINT labor_time_source_policy_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.location_price_override
    ADD CONSTRAINT location_price_override_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.location_price_override
    ADD CONSTRAINT location_price_override_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.non_inventory_product
    ADD CONSTRAINT non_inventory_product_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.non_inventory_product
    ADD CONSTRAINT non_inventory_product_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.oemxreference
    ADD CONSTRAINT oemxreference_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.oemxreference
    ADD CONSTRAINT oemxreference_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.product_code_duplicate_report
    ADD CONSTRAINT pk_product_code_duplicate_report PRIMARY KEY (code_type, code_value);

ALTER TABLE ONLY public.product_code_duplicate_report
    ADD CONSTRAINT product_code_duplicate_report_tenant_key UNIQUE (tenant_id, code_type, code_value);

ALTER TABLE ONLY public.supplier_article_code
    ADD CONSTRAINT pk_supplier_article_code PRIMARY KEY (id);

ALTER TABLE ONLY public.supplier_article_code
    ADD CONSTRAINT supplier_article_code_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.supplier_price_entry
    ADD CONSTRAINT pk_supplier_price_entry PRIMARY KEY (id);

ALTER TABLE ONLY public.supplier_price_entry
    ADD CONSTRAINT supplier_price_entry_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.supplier_price_import
    ADD CONSTRAINT pk_supplier_price_import PRIMARY KEY (import_manifest_id);

ALTER TABLE ONLY public.supplier_price_import
    ADD CONSTRAINT supplier_price_import_tenant_key UNIQUE (tenant_id, import_manifest_id);

ALTER TABLE ONLY public.supplier_price_import_chunk
    ADD CONSTRAINT pk_supplier_price_import_chunk PRIMARY KEY (id);

ALTER TABLE ONLY public.supplier_price_import_chunk
    ADD CONSTRAINT supplier_price_import_chunk_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.tread_design
    ADD CONSTRAINT pk_tread_design PRIMARY KEY (id);

ALTER TABLE ONLY public.tread_design
    ADD CONSTRAINT tread_design_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.tread_design_image
    ADD CONSTRAINT pk_tread_design_image PRIMARY KEY (id);

ALTER TABLE ONLY public.tread_design_image
    ADD CONSTRAINT tread_design_image_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.tread_design_match_candidate
    ADD CONSTRAINT pk_tread_design_match_candidate PRIMARY KEY (id);

ALTER TABLE ONLY public.tread_design_match_candidate
    ADD CONSTRAINT tread_design_match_candidate_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.tread_design_text
    ADD CONSTRAINT pk_tread_design_text PRIMARY KEY (id);

ALTER TABLE ONLY public.tread_design_text
    ADD CONSTRAINT tread_design_text_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.price_book
    ADD CONSTRAINT price_book_pkey PRIMARY KEY (price_book_id);

ALTER TABLE ONLY public.price_book
    ADD CONSTRAINT price_book_tenant_key UNIQUE (tenant_id, price_book_id);

ALTER TABLE ONLY public.price_book_rule
    ADD CONSTRAINT price_book_rule_pkey PRIMARY KEY (rule_id);

ALTER TABLE ONLY public.price_book_rule
    ADD CONSTRAINT price_book_rule_tenant_key UNIQUE (tenant_id, rule_id);

ALTER TABLE ONLY public.processed_events
    ADD CONSTRAINT processed_events_pkey PRIMARY KEY (event_id);

ALTER TABLE ONLY public.product_msrp
    ADD CONSTRAINT product_msrp_pkey PRIMARY KEY (msrp_id);

ALTER TABLE ONLY public.product_msrp
    ADD CONSTRAINT product_msrp_tenant_key UNIQUE (tenant_id, msrp_id);

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.product_replacement
    ADD CONSTRAINT product_replacement_pkey PRIMARY KEY (replacement_id);

ALTER TABLE ONLY public.product_replacement
    ADD CONSTRAINT product_replacement_tenant_key UNIQUE (tenant_id, replacement_id);

ALTER TABLE ONLY public.product_uom
    ADD CONSTRAINT product_uom_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.product_uom
    ADD CONSTRAINT product_uom_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.service_labor_standard
    ADD CONSTRAINT service_labor_standard_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.service_labor_standard
    ADD CONSTRAINT service_labor_standard_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.service_operation_xref
    ADD CONSTRAINT service_operation_xref_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.service_operation_xref
    ADD CONSTRAINT service_operation_xref_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.service_operation_xref
    ADD CONSTRAINT service_operation_xref_source_code_provider_op_code_key UNIQUE (tenant_id, source_code, provider_op_code);

ALTER TABLE ONLY public.service_package_member
    ADD CONSTRAINT service_package_member_package_id_service_id_key UNIQUE (tenant_id, package_id, service_id);

ALTER TABLE ONLY public.service_package_member
    ADD CONSTRAINT service_package_member_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.service_package_member
    ADD CONSTRAINT service_package_member_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.service_package
    ADD CONSTRAINT service_package_package_code_key UNIQUE (tenant_id, package_code);

ALTER TABLE ONLY public.service_package
    ADD CONSTRAINT service_package_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.service_package
    ADD CONSTRAINT service_package_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.service
    ADD CONSTRAINT service_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.service
    ADD CONSTRAINT service_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.subcategory
    ADD CONSTRAINT subcategory_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.subcategory
    ADD CONSTRAINT subcategory_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.substitution_group_member
    ADD CONSTRAINT substitution_group_member_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.substitution_group_member
    ADD CONSTRAINT substitution_group_member_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.substitution_group
    ADD CONSTRAINT substitution_group_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.substitution_group
    ADD CONSTRAINT substitution_group_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.product
    ADD CONSTRAINT uk_product_code_type_value UNIQUE (tenant_id, product_code_type, product_code);

ALTER TABLE ONLY public.product
    ADD CONSTRAINT uk_product_manufacturer_mpn UNIQUE (tenant_id, manufacturer_id, manufacturer_part_number);

ALTER TABLE ONLY public.product
    ADD CONSTRAINT uk_product_sku UNIQUE (tenant_id, sku);

ALTER TABLE ONLY public.product_uom
    ADD CONSTRAINT uk_product_uom_product_code UNIQUE (tenant_id, product_id, uom_code);

ALTER TABLE ONLY public.substitution_group_member
    ADD CONSTRAINT uk_substitution_group_member_product UNIQUE (tenant_id, product_id);

ALTER TABLE ONLY public.supplier_article_code
    ADD CONSTRAINT uk_supplier_article_code_vendor_product UNIQUE (tenant_id, vendor_profile_id, product_id);

ALTER TABLE ONLY public.supplier_price_import_chunk
    ADD CONSTRAINT uk_supplier_price_import_chunk UNIQUE (tenant_id, import_manifest_id, chunk_sequence);

ALTER TABLE ONLY public.tread_design_match_candidate
    ADD CONSTRAINT uk_tread_design_match_candidate_design_product UNIQUE (tenant_id, tread_design_id, product_id);

ALTER TABLE ONLY public.tread_design_text
    ADD CONSTRAINT uk_tread_design_text_design_language UNIQUE (tenant_id, tread_design_id, language_code);

ALTER TABLE ONLY public.tread_design
    ADD CONSTRAINT uk_tread_design_vendor_variant UNIQUE (tenant_id, vendor_profile_id, vendor_variant_id);

ALTER TABLE ONLY public.uom_conversion
    ADD CONSTRAINT uom_conversion_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.uom_conversion
    ADD CONSTRAINT uom_conversion_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.labor_time_source_policy
    ADD CONSTRAINT ux_ltsp_key UNIQUE NULLS NOT DISTINCT (tenant_id, time_type, source_code, operation_category);

CREATE INDEX idx_event_outbox_published_window ON public.event_outbox USING btree (topic, published_at, created_at);

CREATE INDEX idx_event_outbox_unpublished ON public.event_outbox USING btree (published_at, id);

CREATE UNIQUE INDEX idx_ext_inventory_availability_sku_location ON public.ext_inventory_availability USING btree (tenant_id, stock_item_id, location_id);

CREATE INDEX idx_ext_location_parent_parent ON public.ext_location_parent USING btree (parent_id, parent_type);

CREATE INDEX idx_item_cost_audit_item_id ON public.item_cost_audit USING btree (item_id);

CREATE INDEX idx_item_cost_audit_timestamp ON public.item_cost_audit USING btree (audit_timestamp);

CREATE INDEX idx_processed_events_owner ON public.processed_events USING btree (owner, event_id);

CREATE INDEX idx_product_manufacturer_part_number ON public.product USING btree (manufacturer_part_number);

CREATE INDEX idx_product_tread_design ON public.product USING btree (tread_design_id);

CREATE INDEX idx_product_uom_product ON public.product_uom USING btree (product_id);

CREATE INDEX idx_subcategory_category_id ON public.subcategory USING btree (category_id);

CREATE INDEX idx_substitution_group_member_group ON public.substitution_group_member USING btree (group_id);

CREATE INDEX idx_supplier_article_code_product ON public.supplier_article_code USING btree (product_id);

CREATE INDEX idx_supplier_price_entry_import ON public.supplier_price_entry USING btree (import_manifest_id);

CREATE INDEX idx_supplier_price_entry_latest ON public.supplier_price_entry USING btree (product_id, vendor_profile_id, country_code, currency, effective_from);

CREATE INDEX idx_supplier_price_entry_product ON public.supplier_price_entry USING btree (product_id);

CREATE INDEX idx_supplier_price_import_profile ON public.supplier_price_import USING btree (vendor_profile_id);

CREATE INDEX idx_supplier_price_import_status ON public.supplier_price_import USING btree (status);

CREATE INDEX idx_tread_design_brand ON public.tread_design USING btree (brand);

CREATE INDEX idx_tread_design_match_candidate_product ON public.tread_design_match_candidate USING btree (product_id);

CREATE INDEX idx_tread_design_match_state ON public.tread_design USING btree (match_state);

CREATE INDEX ix_lgi_source ON public.labor_guide_import USING btree (source_code, created_at);

CREATE INDEX ix_sls_lookup ON public.service_labor_standard USING btree (service_id, make, model, vehicle_year) WHERE (superseded_at IS NULL);

CREATE INDEX ix_sls_owner ON public.service_labor_standard USING btree (owner_location_id) WHERE ((superseded_at IS NULL) AND (owner_location_id IS NOT NULL));

CREATE INDEX ix_sls_source ON public.service_labor_standard USING btree (source_code, source_revision);

CREATE INDEX ix_sox_service ON public.service_operation_xref USING btree (service_id);

CREATE INDEX ix_svc_pkg_fleet ON public.service_package USING btree (fleet_party_id) WHERE (fleet_party_id IS NOT NULL);

CREATE INDEX ix_svc_pkg_member_package ON public.service_package_member USING btree (package_id, sequence);

CREATE INDEX ix_svc_pkg_member_service ON public.service_package_member USING btree (service_id);

CREATE INDEX ix_svc_pkg_owner ON public.service_package USING btree (owner_location_id) WHERE (owner_location_id IS NOT NULL);

CREATE UNIQUE INDEX ux_service_operation_code ON public.service USING btree (tenant_id, operation_code) WHERE (operation_code IS NOT NULL);

CREATE UNIQUE INDEX ux_sls_active_key ON public.service_labor_standard USING btree (tenant_id, service_id, time_type, COALESCE(owner_location_id, '00000000-0000-0000-0000-000000000000'::uuid), COALESCE(vehicle_year, ''::character varying), COALESCE(make, ''::character varying), COALESCE(model, ''::character varying), COALESCE(submodel, ''::character varying), COALESCE(engine_code, ''::character varying)) WHERE (superseded_at IS NULL);

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fk1mtsbur82frn64de7balymq9s FOREIGN KEY (tenant_id, category_id) REFERENCES public.category(tenant_id, id);

ALTER TABLE ONLY public.product_replacement
    ADD CONSTRAINT fk23q0f9u2whm28m9fs9n99xb FOREIGN KEY (tenant_id, original_product_id) REFERENCES public.product(tenant_id, id);

ALTER TABLE ONLY public.catalog_entity_products
    ADD CONSTRAINT fk476ell5xxschdvutc75nffhja FOREIGN KEY (tenant_id, catalog_entity_id) REFERENCES public.catalog_entity(tenant_id, id);

ALTER TABLE ONLY public.catalog_entity_services
    ADD CONSTRAINT fk49m0dx6jwure5r0j0co8seyge FOREIGN KEY (tenant_id, catalog_entity_id) REFERENCES public.catalog_entity(tenant_id, id);

ALTER TABLE ONLY public.dimensions
    ADD CONSTRAINT fk7tfbgibw9dikxhdt2kklr2gal FOREIGN KEY (tenant_id, product_id) REFERENCES public.product(tenant_id, id);

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fk_product_tread_design FOREIGN KEY (tenant_id, tread_design_id) REFERENCES public.tread_design(tenant_id, id) ON DELETE SET NULL;

ALTER TABLE ONLY public.product_uom
    ADD CONSTRAINT fk_product_uom_product FOREIGN KEY (tenant_id, product_id) REFERENCES public.product(tenant_id, id);

ALTER TABLE ONLY public.subcategory
    ADD CONSTRAINT fk_subcategory_category FOREIGN KEY (tenant_id, category_id) REFERENCES public.category(tenant_id, id);

ALTER TABLE ONLY public.substitution_group_member
    ADD CONSTRAINT fk_substitution_group_member_group FOREIGN KEY (tenant_id, group_id) REFERENCES public.substitution_group(tenant_id, id);

ALTER TABLE ONLY public.substitution_group_member
    ADD CONSTRAINT fk_substitution_group_member_product FOREIGN KEY (tenant_id, product_id) REFERENCES public.product(tenant_id, id);

ALTER TABLE ONLY public.supplier_price_import_chunk
    ADD CONSTRAINT fk_supplier_price_import_chunk_import FOREIGN KEY (tenant_id, import_manifest_id) REFERENCES public.supplier_price_import(tenant_id, import_manifest_id);

ALTER TABLE ONLY public.tread_design_image
    ADD CONSTRAINT fk_tread_design_image_design FOREIGN KEY (tenant_id, tread_design_id) REFERENCES public.tread_design(tenant_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tread_design_match_candidate
    ADD CONSTRAINT fk_tread_design_match_candidate_design FOREIGN KEY (tenant_id, tread_design_id) REFERENCES public.tread_design(tenant_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tread_design_match_candidate
    ADD CONSTRAINT fk_tread_design_match_candidate_product FOREIGN KEY (tenant_id, product_id) REFERENCES public.product(tenant_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tread_design_text
    ADD CONSTRAINT fk_tread_design_text_design FOREIGN KEY (tenant_id, tread_design_id) REFERENCES public.tread_design(tenant_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.price_book_rule
    ADD CONSTRAINT fkaxidnoonhdakivm7t131al1jg FOREIGN KEY (tenant_id, price_book_id) REFERENCES public.price_book(tenant_id, price_book_id);

ALTER TABLE ONLY public.product_replacement
    ADD CONSTRAINT fkbm7akqsv7no4vmqcsskekeg7c FOREIGN KEY (tenant_id, replacement_product_id) REFERENCES public.product(tenant_id, id);

ALTER TABLE ONLY public.oemxreference
    ADD CONSTRAINT fke1e54dmkk79ij6eld0f2mdyt0 FOREIGN KEY (tenant_id, part_id) REFERENCES public.product(tenant_id, id);

ALTER TABLE ONLY public.catalog_entity_non_inventory_products
    ADD CONSTRAINT fkfawtw55yxh23ywfe0ahses16r FOREIGN KEY (tenant_id, non_inventory_products_id) REFERENCES public.non_inventory_product(tenant_id, id);

ALTER TABLE ONLY public.competitorxreference
    ADD CONSTRAINT fkfw2853b0whcpyw6br2rq64hkp FOREIGN KEY (tenant_id, part_id) REFERENCES public.product(tenant_id, id);

ALTER TABLE ONLY public.oemxreference
    ADD CONSTRAINT fkgmcb0x8hrpajoiq638668tj5e FOREIGN KEY (tenant_id, oem_part_id) REFERENCES public.product(tenant_id, id);

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT fki8jnqq05sk5nkma3pfp3ylqrt FOREIGN KEY (tenant_id, product_id) REFERENCES public.product(tenant_id, id);

ALTER TABLE ONLY public.catalog_entity_non_inventory_products
    ADD CONSTRAINT fkitorsfib7wj1ihj1y7v06gsdm FOREIGN KEY (tenant_id, catalog_entity_id) REFERENCES public.catalog_entity(tenant_id, id);

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fkku369nri8u3s17uom8or57trs FOREIGN KEY (tenant_id, subcategory_id) REFERENCES public.subcategory(tenant_id, id);

ALTER TABLE ONLY public.product_msrp
    ADD CONSTRAINT fkm2hp6orjpe4idnqs7le7uuenp FOREIGN KEY (tenant_id, product_id) REFERENCES public.product(tenant_id, id);

ALTER TABLE ONLY public.catalog_entity_products
    ADD CONSTRAINT fkol0slx2skww65mmbtr82wp8n0 FOREIGN KEY (tenant_id, products_id) REFERENCES public.product(tenant_id, id);

ALTER TABLE ONLY public.catalog_entity_services
    ADD CONSTRAINT fkpvoe5tma4j9xfu10rw1j397tx FOREIGN KEY (tenant_id, services_id) REFERENCES public.service(tenant_id, id);

ALTER TABLE ONLY public.competitorxreference
    ADD CONSTRAINT fkscuc2tre171k4o6iy0fbxiim3 FOREIGN KEY (tenant_id, competitor_part_id) REFERENCES public.product(tenant_id, id);

ALTER TABLE ONLY public.labor_guide_import_chunk
    ADD CONSTRAINT labor_guide_import_chunk_import_manifest_id_fkey FOREIGN KEY (tenant_id, import_manifest_id) REFERENCES public.labor_guide_import(tenant_id, import_manifest_id);

ALTER TABLE ONLY public.service_labor_standard
    ADD CONSTRAINT service_labor_standard_service_id_fkey FOREIGN KEY (tenant_id, service_id) REFERENCES public.service(tenant_id, id);

ALTER TABLE ONLY public.service_operation_xref
    ADD CONSTRAINT service_operation_xref_service_id_fkey FOREIGN KEY (tenant_id, service_id) REFERENCES public.service(tenant_id, id);

ALTER TABLE ONLY public.service_package_member
    ADD CONSTRAINT service_package_member_package_id_fkey FOREIGN KEY (tenant_id, package_id) REFERENCES public.service_package(tenant_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.service_package_member
    ADD CONSTRAINT service_package_member_service_id_fkey FOREIGN KEY (tenant_id, service_id) REFERENCES public.service(tenant_id, id);

CREATE INDEX approval_request_tenant_idx ON public.approval_request USING btree (tenant_id);

CREATE INDEX catalog_entity_tenant_idx ON public.catalog_entity USING btree (tenant_id);

CREATE INDEX catalog_entity_non_inventory_products_tenant_idx ON public.catalog_entity_non_inventory_products USING btree (tenant_id);

CREATE INDEX catalog_entity_products_tenant_idx ON public.catalog_entity_products USING btree (tenant_id);

CREATE INDEX catalog_entity_services_tenant_idx ON public.catalog_entity_services USING btree (tenant_id);

CREATE INDEX category_tenant_idx ON public.category USING btree (tenant_id);

CREATE INDEX competitorxreference_tenant_idx ON public.competitorxreference USING btree (tenant_id);

CREATE INDEX dimensions_tenant_idx ON public.dimensions USING btree (tenant_id);

CREATE INDEX ext_location_tenant_idx ON public.ext_location USING btree (tenant_id);

CREATE INDEX ext_location_parent_tenant_idx ON public.ext_location_parent USING btree (tenant_id);

CREATE INDEX ext_product_lead_time_tenant_idx ON public.ext_product_lead_time USING btree (tenant_id);

CREATE INDEX guardrail_policy_tenant_idx ON public.guardrail_policy USING btree (tenant_id);

CREATE INDEX item_cost_tenant_idx ON public.item_cost USING btree (tenant_id);

CREATE INDEX item_cost_audit_tenant_idx ON public.item_cost_audit USING btree (tenant_id);

CREATE INDEX labor_guide_import_tenant_idx ON public.labor_guide_import USING btree (tenant_id);

CREATE INDEX labor_guide_import_chunk_tenant_idx ON public.labor_guide_import_chunk USING btree (tenant_id);

CREATE INDEX labor_guide_unmapped_operation_tenant_idx ON public.labor_guide_unmapped_operation USING btree (tenant_id);

CREATE INDEX labor_time_source_policy_tenant_idx ON public.labor_time_source_policy USING btree (tenant_id);

CREATE INDEX location_price_override_tenant_idx ON public.location_price_override USING btree (tenant_id);

CREATE INDEX non_inventory_product_tenant_idx ON public.non_inventory_product USING btree (tenant_id);

CREATE INDEX oemxreference_tenant_idx ON public.oemxreference USING btree (tenant_id);

CREATE INDEX price_book_tenant_idx ON public.price_book USING btree (tenant_id);

CREATE INDEX price_book_rule_tenant_idx ON public.price_book_rule USING btree (tenant_id);

CREATE INDEX product_tenant_idx ON public.product USING btree (tenant_id);

CREATE INDEX product_code_duplicate_report_tenant_idx ON public.product_code_duplicate_report USING btree (tenant_id);

CREATE INDEX product_images_tenant_idx ON public.product_images USING btree (tenant_id);

CREATE INDEX product_msrp_tenant_idx ON public.product_msrp USING btree (tenant_id);

CREATE INDEX product_replacement_tenant_idx ON public.product_replacement USING btree (tenant_id);

CREATE INDEX product_uom_tenant_idx ON public.product_uom USING btree (tenant_id);

CREATE INDEX service_operation_xref_tenant_idx ON public.service_operation_xref USING btree (tenant_id);

CREATE INDEX service_package_tenant_idx ON public.service_package USING btree (tenant_id);

CREATE INDEX service_package_member_tenant_idx ON public.service_package_member USING btree (tenant_id);

CREATE INDEX subcategory_tenant_idx ON public.subcategory USING btree (tenant_id);

CREATE INDEX substitution_group_tenant_idx ON public.substitution_group USING btree (tenant_id);

CREATE INDEX substitution_group_member_tenant_idx ON public.substitution_group_member USING btree (tenant_id);

CREATE INDEX supplier_article_code_tenant_idx ON public.supplier_article_code USING btree (tenant_id);

CREATE INDEX supplier_price_entry_tenant_idx ON public.supplier_price_entry USING btree (tenant_id);

CREATE INDEX supplier_price_import_tenant_idx ON public.supplier_price_import USING btree (tenant_id);

CREATE INDEX supplier_price_import_chunk_tenant_idx ON public.supplier_price_import_chunk USING btree (tenant_id);

CREATE INDEX tread_design_tenant_idx ON public.tread_design USING btree (tenant_id);

CREATE INDEX tread_design_image_tenant_idx ON public.tread_design_image USING btree (tenant_id);

CREATE INDEX tread_design_match_candidate_tenant_idx ON public.tread_design_match_candidate USING btree (tenant_id);

CREATE INDEX tread_design_text_tenant_idx ON public.tread_design_text USING btree (tenant_id);

CREATE INDEX uom_conversion_tenant_idx ON public.uom_conversion USING btree (tenant_id);

ALTER TABLE public.approval_request ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.approval_request FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.approval_request
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.catalog_entity ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_entity FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.catalog_entity
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.catalog_entity_non_inventory_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_entity_non_inventory_products FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.catalog_entity_non_inventory_products
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.catalog_entity_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_entity_products FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.catalog_entity_products
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.catalog_entity_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_entity_services FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.catalog_entity_services
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.category ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.category FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.category
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.competitorxreference ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competitorxreference FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.competitorxreference
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.dimensions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dimensions FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.dimensions
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_inventory_availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_inventory_availability FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_inventory_availability
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_location ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_location FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_location
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_location_parent ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_location_parent FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_location_parent
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_product_lead_time ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_product_lead_time FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_product_lead_time
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.guardrail_policy ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guardrail_policy FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.guardrail_policy
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.item_cost ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.item_cost FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.item_cost
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.item_cost_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.item_cost_audit FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.item_cost_audit
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.labor_guide_import ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.labor_guide_import FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.labor_guide_import
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.labor_guide_import_chunk ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.labor_guide_import_chunk FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.labor_guide_import_chunk
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.labor_guide_unmapped_operation ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.labor_guide_unmapped_operation FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.labor_guide_unmapped_operation
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.labor_time_source_policy ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.labor_time_source_policy FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.labor_time_source_policy
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.location_price_override ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.location_price_override FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.location_price_override
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.non_inventory_product ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.non_inventory_product FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.non_inventory_product
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.oemxreference ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oemxreference FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.oemxreference
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.price_book ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_book FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.price_book
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.price_book_rule ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_book_rule FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.price_book_rule
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.product ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.product
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.product_code_duplicate_report ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_code_duplicate_report FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.product_code_duplicate_report
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.product_images
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.product_msrp ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_msrp FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.product_msrp
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.product_replacement ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_replacement FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.product_replacement
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.product_uom ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_uom FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.product_uom
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.service ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.service
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.service_labor_standard ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_labor_standard FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.service_labor_standard
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.service_operation_xref ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_operation_xref FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.service_operation_xref
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.service_package ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_package FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.service_package
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.service_package_member ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_package_member FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.service_package_member
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.subcategory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subcategory FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.subcategory
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.substitution_group ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.substitution_group FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.substitution_group
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.substitution_group_member ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.substitution_group_member FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.substitution_group_member
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_article_code ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_article_code FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_article_code
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_price_entry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_price_entry FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_price_entry
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_price_import ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_price_import FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_price_import
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.supplier_price_import_chunk ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_price_import_chunk FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.supplier_price_import_chunk
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.tread_design ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tread_design FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.tread_design
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.tread_design_image ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tread_design_image FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.tread_design_image
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.tread_design_match_candidate ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tread_design_match_candidate FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.tread_design_match_candidate
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.tread_design_text ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tread_design_text FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.tread_design_text
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.uom_conversion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.uom_conversion FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.uom_conversion
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());
