-- Phase 5.3 follow-up: add remaining mapped entity columns for pos-catalog.

ALTER TABLE IF EXISTS location_price_override
    ADD COLUMN IF NOT EXISTS location_id UUID,
    ADD COLUMN IF NOT EXISTS product_id UUID,
    ADD COLUMN IF NOT EXISTS base_price NUMERIC(19, 4),
    ADD COLUMN IF NOT EXISTS cost NUMERIC(19, 4),
    ADD COLUMN IF NOT EXISTS override_price NUMERIC(19, 4),
    ADD COLUMN IF NOT EXISTS discount_percent NUMERIC(10, 4),
    ADD COLUMN IF NOT EXISTS margin_percent NUMERIC(10, 4),
    ADD COLUMN IF NOT EXISTS status VARCHAR(64),
    ADD COLUMN IF NOT EXISTS created_by_user_id UUID,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS approved_by_user_id UUID,
    ADD COLUMN IF NOT EXISTS rejected_by UUID,
    ADD COLUMN IF NOT EXISTS rejection_reason_code VARCHAR(128),
    ADD COLUMN IF NOT EXISTS rejection_notes VARCHAR(1024);

ALTER TABLE IF EXISTS product_replacement
    ADD COLUMN IF NOT EXISTS replacement_id UUID,
    ADD COLUMN IF NOT EXISTS priority_order INTEGER,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS uom_conversion
    ADD COLUMN IF NOT EXISTS from_uom_code VARCHAR(255),
    ADD COLUMN IF NOT EXISTS to_uom_code VARCHAR(255),
    ADD COLUMN IF NOT EXISTS conversion_factor NUMERIC(20, 6),
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS guardrail_policy
    ADD COLUMN IF NOT EXISTS scope VARCHAR(64),
    ADD COLUMN IF NOT EXISTS scope_id UUID,
    ADD COLUMN IF NOT EXISTS min_margin_percent NUMERIC(10, 4),
    ADD COLUMN IF NOT EXISTS max_discount_percent NUMERIC(10, 4),
    ADD COLUMN IF NOT EXISTS auto_approval_threshold_percent NUMERIC(10, 4),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS price_book
    ADD COLUMN IF NOT EXISTS price_book_id UUID,
    ADD COLUMN IF NOT EXISTS name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS scope VARCHAR(64),
    ADD COLUMN IF NOT EXISTS scope_id UUID,
    ADD COLUMN IF NOT EXISTS is_default BOOLEAN,
    ADD COLUMN IF NOT EXISTS status VARCHAR(64),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS product_msrp
    ADD COLUMN IF NOT EXISTS msrp_id UUID,
    ADD COLUMN IF NOT EXISTS amount NUMERIC(19, 4),
    ADD COLUMN IF NOT EXISTS currency VARCHAR(3),
    ADD COLUMN IF NOT EXISTS effective_start_date DATE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_by UUID;

ALTER TABLE IF EXISTS price_book_rule
    ADD COLUMN IF NOT EXISTS rule_id UUID,
    ADD COLUMN IF NOT EXISTS target_type VARCHAR(64),
    ADD COLUMN IF NOT EXISTS target_id UUID,
    ADD COLUMN IF NOT EXISTS pricing_logic TEXT,
    ADD COLUMN IF NOT EXISTS condition_type VARCHAR(64),
    ADD COLUMN IF NOT EXISTS condition_value VARCHAR(255),
    ADD COLUMN IF NOT EXISTS priority INTEGER,
    ADD COLUMN IF NOT EXISTS effective_start_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS status VARCHAR(64),
    ADD COLUMN IF NOT EXISTS created_by_user_id UUID,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
