package com.positivity.nhtsa.internal.entity;

import com.positivity.shared.id.UUIDv7Id;
import com.positivity.tenancy.TenantGlobal;
import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

@Data
@Entity
@TenantGlobal(
        reason = "vehicle reference data shared by every tenant (ADR-0062 section 5, db/tenancy-global-tables.txt)")
@EntityListeners(AuditingEntityListener.class)
public class Make {
    @Id
    @GeneratedValue
    @UUIDv7Id
    @Column(columnDefinition = "UUID")
    private UUID id;

    /**
     * vPIC's own numeric id for this row (#2454): the id vPIC's dependent lookups take in their path, which
     * the local UUID cannot stand in for. {@code null} when the row did not come from vPIC, or was cached
     * before this column existed; such a row is served from cache and has no vPIC parent to refresh from.
     */
    @Column(name = "nhtsa_id")
    private Long nhtsaId;

    private String name;

    /**
     * The manufacturers vPIC pairs this make with (#2471). A make is one row per vPIC Make_ID; several
     * manufacturers can build it, so the link is many-to-many ({@code make_manufacturer}). Eager: the id list is
     * part of the response.
     */
    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(
            name = "make_manufacturer",
            joinColumns = @JoinColumn(name = "make_id"),
            inverseJoinColumns = @JoinColumn(name = "manufacturer_id"))
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private Set<Manufacturer> manufacturers = new HashSet<>();

    private LocalDateTime cacheTimestamp;
    // Getters and setters are generated by Lombok's @Data annotation
}
