# POS Order Service
spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/pos_order_db
    username: ${SPRING_DATASOURCE_USERNAME:pos_user}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
 
server:
  port: 0

management:
  server:
    port: 0
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com:
      positivity:
        order: INFO
    org:
      springframework:
        web: INFO
      hibernate: INFO
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
