# POS Order Service
spring:
  application:
    name: order
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 0
  tomcat:
    max-http-header-size: 65536

management:
  server:
    port: 0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    com:
      positivity:
        order: INFO
      netflix:
        discovery:
          shared:
            resolver:
              aws:
                ConfigClusterResolver: WARN
    org:
      springframework:
        web: INFO
      hibernate: INFO
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  default-produces-media-type: application/json
