package com.positivity.workorder.internal.entity;

import com.positivity.shared.id.UUIDv7Id;
import com.positivity.workorder.internal.enums.EstimateStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.persistence.UniqueConstraint;
import java.math.BigDecimal;
import java.time.Clock;
import java.time.Instant;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

@Entity
@Table(name = "estimate", uniqueConstraints = @UniqueConstraint(columnNames = {"locationId", "estimateNumber"}))
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EntityListeners(AuditingEntityListener.class)
public class Estimate {
    @Id
    @GeneratedValue
    @UUIDv7Id
    @Column(columnDefinition = "UUID")
    private UUID id;

    @Column(unique = false) // Uniqueness enforced at DB level with composite constraint
    private String estimateNumber; // Human-readable identifier (e.g., EST-2024-1001)

    private UUID locationId; // Reference to Location (previously shopId)
    private UUID vehicleId; // Reference to Vehicle
    private UUID customerId; // Reference to Customer

    @Enumerated(EnumType.STRING)
    @Builder.Default
    private EstimateStatus status = EstimateStatus.DRAFT;

    private String currencyUomId; // Currency code (e.g., 'USD')
    private UUID taxRegionId; // Reference to tax region

    private String createdByUserId; // Username who created the estimate (from JWT via SecurityContextHelper)

    @SuppressWarnings("java:S1450") // JPA column; getter/setter generated by Lombok @Data
    @CreatedDate
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(nullable = false)
    private Instant updatedAt;

    private LocalDateTime approvedAt;
    private LocalDateTime declinedAt;
    private LocalDateTime expiresAt;

    // CAP:003 Issue #168 - Submit for Approval tracking
    private LocalDateTime submittedAt; // When estimate was submitted for customer approval
    private String submittedBy; // User who submitted estimate for approval

    @Column(nullable = false, updatable = false)
    private String createdById; // User who created the estimate
    // Configuration reference for approval method
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "approval_configuration_id")
    @ToString.Exclude
    private ApprovalConfiguration approvalConfiguration;

    @Transient
    public UUID getApprovalConfigurationId() {
        return approvalConfiguration != null ? approvalConfiguration.getId() : null;
    }

    @Transient
    public void setApprovalConfigurationId(UUID approvalConfigurationId) {
        this.approvalConfiguration =
                approvalConfigurationId != null ? new ApprovalConfiguration(approvalConfigurationId) : null;
    }

    @Column(columnDefinition = "UUID")
    private UUID appointmentId; // Reference to source appointment (Story #65 CAP:140)

    // Notes or reason for decline
    private String declineReason;

    // Approved by (customer UUID who approved the estimate)
    private UUID approvedBy;

    // Customer signature capture for approval
    @Column(length = 100000)
    private String signatureData; // Base64-encoded signature image

    private String signatureMimeType; // MIME type (e.g., image/png)
    private String signerName; // Name of person who signed
    private String approvalNotes; // Additional notes at approval time

    // Purchase order tracking (CAP:092 Story #98)
    @Column(length = 100)
    private String purchaseOrderNumber; // PO number when approval requires it

    // Financial tracking for approval invalidation
    private BigDecimal subtotal;
    private BigDecimal taxAmount;
    private BigDecimal total;

    // Version tracking for estimate revisions
    @Builder.Default
    private Integer version = 1;

    // CRM reference IDs — immutable point-in-time snapshot (CAP-094 Story #93)
    @Column(length = 36, updatable = false)
    private String crmPartyId;

    @Column(length = 36, updatable = false)
    private String crmVehicleId;

    @Builder.Default
    @Column(columnDefinition = "TEXT", updatable = false)
    @Convert(converter = StringListJsonConverter.class)
    private List<String> crmContactIds = new ArrayList<>();

    /**
     * Check if estimate can be transitioned to approved state.
     */
    public boolean canApprove() {
        return status == EstimateStatus.PENDING_APPROVAL;
    }

    /**
     * Check if estimate can be transitioned to declined state.
     */
    public boolean canDecline() {
        return status == EstimateStatus.DRAFT
                || status == EstimateStatus.PENDING_APPROVAL
                || status == EstimateStatus.APPROVED;
    }

    /**
     * Check if estimate can be reopened (transitioned from declined to draft).
     */
    public boolean canReopen(int configuredExpiryDays) {
        return canReopen(configuredExpiryDays, LocalDateTime.now(Clock.systemUTC()));
    }

    /**
     * Check if estimate can be reopened using the provided reference time.
     */
    public boolean canReopen(int configuredExpiryDays, LocalDateTime referenceTime) {
        if (status != EstimateStatus.DECLINED || declinedAt == null) {
            return false;
        }
        LocalDateTime expiryDate = declinedAt.plusDays(configuredExpiryDays);
        return !referenceTime.isAfter(expiryDate);
    }

    public Estimate(UUID id) {
        this.id = id;
    }
}
