package com.positivity.workorder.internal.entity;

import com.positivity.shared.id.UUIDv7Generator;
import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "estimate", uniqueConstraints = @UniqueConstraint(columnNames = { "locationId", "estimateNumber" }))
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Estimate {
    @Id
    @Column(columnDefinition = "UUID")
    private UUID id;

    @Column(unique = false) // Uniqueness enforced at DB level with composite constraint
    private String estimateNumber; // Human-readable identifier (e.g., EST-2024-1001)

    private UUID locationId; // Reference to Location (previously shopId)
    private UUID vehicleId; // Reference to Vehicle
    private UUID customerId; // Reference to Customer

    @Enumerated(EnumType.STRING)
    @Builder.Default
    private EstimateStatus status = EstimateStatus.DRAFT;

    private String currencyUomId; // Currency code (e.g., 'USD')
    private UUID taxRegionId; // Reference to tax region

    private UUID createdByUserId; // User who created the estimate
    @SuppressWarnings("java:S1450") // JPA column; getter/setter generated by Lombok @Data
    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;
    private LocalDateTime approvedAt;
    private LocalDateTime declinedAt;
    private LocalDateTime expiresAt;

    // CAP:003 Issue #168 - Submit for Approval tracking
    private LocalDateTime submittedAt; // When estimate was submitted for customer approval
    private String submittedBy; // User who submitted estimate for approval

    @Column(nullable = false, updatable = false)
    private String createdById; // User who created the estimate
    // Configuration reference for approval method
    private UUID approvalConfigurationId;

    // Notes or reason for decline
    private String declineReason;

    // Approved by (service advisor or system user ID)
    private String approvedBy;

    // Customer signature capture for approval
    @Column(length = 100000)
    private String signatureData; // Base64-encoded signature image
    private String signatureMimeType; // MIME type (e.g., image/png)
    private String signerName; // Name of person who signed
    private String approvalNotes; // Additional notes at approval time

    // Purchase order tracking (CAP:092 Story #98)
    @Column(length = 100)
    private String purchaseOrderNumber; // PO number when approval requires it

    // Financial tracking for approval invalidation
    private BigDecimal subtotal;
    private BigDecimal taxAmount;
    private BigDecimal total;

    // Version tracking for estimate revisions
    @Builder.Default
    private Integer version = 1;

    // Legacy field for backward compatibility
    /**
     * @deprecated Use {@link #locationId}. This legacy field will be removed after
     *             all callers migrate off shopId.
     */
    @SuppressWarnings("java:S1133")
    @Deprecated(since = "0.1.0", forRemoval = true)
    @Transient
    private Long shopId;

    @PrePersist
    protected void prePersist() {
        if (id == null) {
            id = UUIDv7Generator.generate();
        }
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    /**
     * Check if estimate can be transitioned to approved state.
     */
    public boolean canApprove() {
        return status == EstimateStatus.PENDING_APPROVAL;
    }

    /**
     * Check if estimate can be transitioned to declined state.
     */
    public boolean canDecline() {
        return status == EstimateStatus.PENDING_APPROVAL || status == EstimateStatus.APPROVED;
    }

    /**
     * Check if estimate can be reopened (transitioned from declined to draft).
     */
    public boolean canReopen(int configuredExpiryDays) {
        if (status != EstimateStatus.DECLINED || declinedAt == null) {
            return false;
        }
        LocalDateTime expiryDate = declinedAt.plusDays(configuredExpiryDays);
        return LocalDateTime.now().isBefore(expiryDate);
    }
}
