package com.positivity.workorder.internal.entity;

import com.positivity.shared.id.UUIDv7Id;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import java.time.Instant;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Read-only pick-list replica fed by {@code inventory.pick-list.updated} facts on
 * {@code inventory.events.v1} (ADR-0044 §6, #901).
 *
 * <p>pos-inventory owns these facts; nothing in this module may write the table except the event
 * consumer. Serves the pick-flow read path previously answered by the retired
 * {@code InventoryPickClient}.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "ext_pick_list")
public class ExtPickListReplica {

    @Id
    @Column(name = "pick_list_id", nullable = false)
    private UUID pickListId;

    @Column(name = "workorder_id")
    private UUID workorderId;

    @Column(name = "status", length = 64)
    private String status;

    @Column(name = "priority", nullable = false)
    private int priority;

    @Column(name = "due_at")
    private Instant dueAt;

    @Column(name = "pick_list_created_at")
    private Instant pickListCreatedAt;

    @Column(name = "aggregate_version", nullable = false)
    private long aggregateVersion;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * Explicit dependency hook for the ArchUnit UUIDv7 rule: the primary key is the owner's
     * UUIDv7 pick list id, generated by pos-inventory.
     */
    @Transient
    public Class<?> uuidv7Dependency() {
        return UUIDv7Id.class;
    }
}
