package com.positivity.workorder.internal.entity;

import com.positivity.shared.id.UUIDv7Id;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import java.time.Instant;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Read-only pick-task replica fed by {@code inventory.pick-task.updated} facts on
 * {@code inventory.events.v1}; {@code quantityConsumed} accumulates from
 * {@code inventory.consumption.recorded} facts (ADR-0044 §6, #901).
 *
 * <p>pos-inventory owns these facts; nothing in this module may write the table except the event
 * consumer.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "ext_pick_task")
public class ExtPickTaskReplica {

    @Id
    @Column(name = "pick_task_id", nullable = false)
    private UUID pickTaskId;

    @Column(name = "pick_list_id")
    private UUID pickListId;

    @Column(name = "workorder_id")
    private UUID workorderId;

    @Column(name = "sku_id")
    private UUID skuId;

    @Column(name = "location_id")
    private UUID locationId;

    @Column(name = "quantity_required", nullable = false)
    private int quantityRequired;

    @Column(name = "quantity_picked", nullable = false)
    private int quantityPicked;

    @Column(name = "quantity_consumed", nullable = false)
    private int quantityConsumed;

    @Column(name = "status", length = 64)
    private String status;

    @Column(name = "sort_order", nullable = false)
    private int sortOrder;

    @Column(name = "aggregate_version", nullable = false)
    private long aggregateVersion;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * Explicit dependency hook for the ArchUnit UUIDv7 rule: the primary key is the owner's
     * UUIDv7 pick task id, generated by pos-inventory.
     */
    @Transient
    public Class<?> uuidv7Dependency() {
        return UUIDv7Id.class;
    }
}
