-- pos-tax: Flyway baseline (flattened 2026-09-09 from the previous migration history) with the
-- ADR-0062 tenancy schema folded in. Generated by scripts/db/tenancy/flatten.py from a pg_dump of a
-- database migrated with the retired scripts; the tenancy additions are mechanical and are listed in
-- docs/TENANCY_SCHEMA.md. Global (unscoped) tables: src/main/resources/db/tenancy-global-tables.txt.
--
-- Tenant context: app_current_tenant() reads the session setting app.current_tenant, which the
-- TenantAwareDataSource (pos-tenancy-common, plan WS1) binds per checkout. Until then the owner role
-- carries a transitional default (postgres/init-tenancy.sh) and tests set it per connection.
-- With nothing bound: NULL -> every scoped table reads as empty and refuses inserts (fail closed).

-- Functions are emitted before the tables they reference (pg_dump order); do not validate bodies.
SET check_function_bodies = false;

CREATE OR REPLACE FUNCTION public.app_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$ SELECT NULLIF(current_setting('app.current_tenant', true), '')::uuid $$;

CREATE TABLE public.exemption_certificate (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    customer_id character varying(100) NOT NULL,
    state_scope character varying(10),
    reason_code character varying(32) NOT NULL,
    certificate_number character varying(100),
    effective_from date NOT NULL,
    expires_at date,
    status character varying(16) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.tax_provider_transaction (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    reference_id uuid NOT NULL,
    reference_type character varying(32),
    provider character varying(64) NOT NULL,
    status character varying(16) NOT NULL,
    external_transaction_id character varying(128),
    attempts integer DEFAULT 0 NOT NULL,
    last_error character varying(1024),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

ALTER TABLE ONLY public.exemption_certificate
    ADD CONSTRAINT exemption_certificate_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.exemption_certificate
    ADD CONSTRAINT exemption_certificate_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.tax_provider_transaction
    ADD CONSTRAINT tax_provider_transaction_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tax_provider_transaction
    ADD CONSTRAINT tax_provider_transaction_tenant_key UNIQUE (tenant_id, id);

CREATE INDEX idx_exemption_certificate_customer ON public.exemption_certificate USING btree (customer_id, status, effective_from);

CREATE INDEX idx_tax_provider_transaction_status ON public.tax_provider_transaction USING btree (status);

CREATE UNIQUE INDEX ux_tax_provider_transaction_reference ON public.tax_provider_transaction USING btree (tenant_id, reference_id);

CREATE INDEX exemption_certificate_tenant_idx ON public.exemption_certificate USING btree (tenant_id);

ALTER TABLE public.exemption_certificate ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exemption_certificate FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.exemption_certificate
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.tax_provider_transaction ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tax_provider_transaction FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.tax_provider_transaction
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());
