spring:
  application:
    name: pos-vehicle-inventory
  datasource:
    url: jdbc:postgresql://localhost:5432/pos_vehicle_inventory_db
    username: pos_user
    password: pos_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 0

management:
  server:
    port: 0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org:
      springframework: INFO
    com:
      positivity:
        vehicle: INFO
