-- pos-customer: Flyway baseline (flattened 2026-09-09 from the previous migration history) with the
-- ADR-0062 tenancy schema folded in. Generated by scripts/db/tenancy/flatten.py from a pg_dump of a
-- database migrated with the retired scripts; the tenancy additions are mechanical and are listed in
-- docs/TENANCY_SCHEMA.md. Global (unscoped) tables: src/main/resources/db/tenancy-global-tables.txt.
--
-- Tenant context: app_current_tenant() reads the session setting app.current_tenant, which the
-- TenantAwareDataSource (pos-tenancy-common, plan WS1) binds per checkout. Until then the owner role
-- carries a transitional default (postgres/init-tenancy.sh) and tests set it per connection.
-- With nothing bound: NULL -> every scoped table reads as empty and refuses inserts (fail closed).

-- Functions are emitted before the tables they reference (pg_dump order); do not validate bodies.
SET check_function_bodies = false;

CREATE OR REPLACE FUNCTION public.app_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$ SELECT NULLIF(current_setting('app.current_tenant', true), '')::uuid $$;

CREATE TABLE public.commercial_party (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    party_type smallint NOT NULL,
    status smallint NOT NULL,
    tier smallint NOT NULL,
    tier_manual_override boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    tier_assigned_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    customer_id uuid NOT NULL,
    parent_party_id uuid,
    billing_terms_id character varying(255),
    customer_number character varying(255) NOT NULL,
    display_name character varying(255),
    legal_name character varying(255) NOT NULL,
    primary_address character varying(255),
    tax_id character varying(255),
    tier_assigned_by character varying(255),
    br_po_required boolean,
    br_tax_exempt boolean,
    br_credit_hold boolean,
    br_auto_pay_enabled boolean,
    br_payment_terms character varying(100),
    br_credit_limit numeric(19,4),
    br_currency character varying(3),
    br_invoice_delivery_method character varying(50),
    br_billing_address_id uuid,
    br_discount_policy_ref character varying(200),
    modified_by character varying(255),
    account_marketing_opt_out boolean DEFAULT false NOT NULL,
    account_marketing_opt_out_at timestamp(6) with time zone,
    lifecycle_stage character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT commercial_party_lifecycle_stage_chk CHECK (((lifecycle_stage)::text = ANY ((ARRAY['PROSPECT'::character varying, 'ACTIVE'::character varying, 'DORMANT'::character varying])::text[]))),
    CONSTRAINT commercial_party_party_type_check CHECK (((party_type >= 0) AND (party_type <= 2))),
    CONSTRAINT commercial_party_status_check CHECK (((status >= 0) AND (status <= 3))),
    CONSTRAINT commercial_party_tier_check CHECK (((tier >= 0) AND (tier <= 5)))
);

CREATE SEQUENCE public.commercial_party_customer_number_seq
    START WITH 1209047103196
    INCREMENT BY 1
    MINVALUE 1209047103196
    MAXVALUE 2821109907455
    CACHE 1;

CREATE TABLE public.communication_preference (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint NOT NULL,
    party_id uuid NOT NULL,
    preference_id uuid NOT NULL,
    email_preference character varying(20),
    marketing_preference character varying(20),
    phone_preference character varying(20),
    sms_preference character varying(20),
    update_source character varying(20),
    preferences_note character varying(1000),
    marketing_email_consent character varying(20) DEFAULT 'UNSET'::character varying NOT NULL,
    marketing_sms_consent character varying(20) DEFAULT 'UNSET'::character varying NOT NULL,
    opt_out_reason character varying(30),
    opt_out_at timestamp(6) with time zone,
    quiet_hours_start time without time zone,
    quiet_hours_end time without time zone,
    max_marketing_sends_per_month integer,
    CONSTRAINT comm_pref_marketing_email_consent_chk CHECK (((marketing_email_consent)::text = ANY ((ARRAY['OPT_IN'::character varying, 'OPT_OUT'::character varying, 'UNSET'::character varying])::text[]))),
    CONSTRAINT comm_pref_marketing_sms_consent_chk CHECK (((marketing_sms_consent)::text = ANY ((ARRAY['OPT_IN'::character varying, 'OPT_OUT'::character varying, 'UNSET'::character varying])::text[]))),
    CONSTRAINT comm_pref_opt_out_reason_chk CHECK (((opt_out_reason IS NULL) OR ((opt_out_reason)::text = ANY ((ARRAY['NOT_INTERESTED'::character varying, 'TOO_FREQUENT'::character varying, 'NEVER_SIGNED_UP'::character varying, 'CONTENT_NOT_RELEVANT'::character varying, 'LEGAL_DNC'::character varying, 'OTHER'::character varying])::text[]))))
);

CREATE TABLE public.consent_event (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    consent_event_id uuid NOT NULL,
    party_id uuid NOT NULL,
    channel character varying(20) NOT NULL,
    old_value character varying(20) NOT NULL,
    new_value character varying(20) NOT NULL,
    reason character varying(30),
    source character varying(30) NOT NULL,
    actor character varying(255),
    occurred_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT consent_event_channel_chk CHECK (((channel)::text = ANY ((ARRAY['EMAIL'::character varying, 'SMS'::character varying])::text[]))),
    CONSTRAINT consent_event_new_value_chk CHECK (((new_value)::text = ANY ((ARRAY['OPT_IN'::character varying, 'OPT_OUT'::character varying, 'UNSET'::character varying])::text[]))),
    CONSTRAINT consent_event_old_value_chk CHECK (((old_value)::text = ANY ((ARRAY['OPT_IN'::character varying, 'OPT_OUT'::character varying, 'UNSET'::character varying])::text[]))),
    CONSTRAINT consent_event_source_chk CHECK (((source)::text = ANY ((ARRAY['CSR'::character varying, 'SELF_SERVICE'::character varying, 'UNSUBSCRIBE_LINK'::character varying, 'IMPORT'::character varying, 'API'::character varying, 'SYSTEM'::character varying])::text[])))
);

CREATE TABLE public.consent_flag (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    flag_value boolean,
    preference_id uuid NOT NULL,
    flag_name character varying(100) NOT NULL
);

CREATE TABLE public.contact_role_assignment (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    is_primary boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    contact_id uuid NOT NULL,
    customer_account_id uuid NOT NULL,
    role_name character varying(50) NOT NULL,
    CONSTRAINT contact_role_assignment_role_name_check CHECK (((role_name)::text = ANY (ARRAY[('BILLING'::character varying)::text, ('PAYMENT_AUTHORIZER'::character varying)::text, ('OPERATIONS'::character varying)::text, ('PRIMARY_BUSINESS_CONTACT'::character varying)::text, ('TECHNICAL'::character varying)::text])))
);

CREATE TABLE public.customer_interaction (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    interaction_id uuid NOT NULL,
    party_id uuid NOT NULL,
    contact_id uuid,
    type character varying(30) NOT NULL,
    channel character varying(20),
    direction character varying(20) NOT NULL,
    campaign_id uuid,
    campaign_code character varying(100),
    subject character varying(255),
    summary character varying(1000),
    body character varying(4000),
    actor character varying(255),
    source_workorder_id character varying(64),
    source_event_id character varying(64),
    occurred_at timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT customer_interaction_channel_chk CHECK (((channel IS NULL) OR ((channel)::text = ANY ((ARRAY['EMAIL'::character varying, 'SMS'::character varying])::text[])))),
    CONSTRAINT customer_interaction_direction_chk CHECK (((direction)::text = ANY ((ARRAY['OUTBOUND'::character varying, 'INBOUND'::character varying])::text[]))),
    CONSTRAINT customer_interaction_type_chk CHECK (((type)::text = ANY ((ARRAY['CAMPAIGN_SEND'::character varying, 'EMAIL'::character varying, 'SMS'::character varying, 'CALL'::character varying, 'FOLLOW_UP'::character varying, 'NOTE'::character varying, 'WORKORDER_NOTE'::character varying])::text[])))
);

CREATE TABLE public.customer_vehicle (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    customer_id uuid NOT NULL,
    vin character varying(255)
);

CREATE TABLE public.event_outbox (
    id uuid NOT NULL,
    topic character varying(255) NOT NULL,
    record_key character varying(255) NOT NULL,
    payload text NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    published_at timestamp(6) with time zone,
    attempts integer DEFAULT 0 NOT NULL,
    last_error text
);

CREATE TABLE public.ext_organization_postal_address (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    organization_id uuid NOT NULL,
    line1 character varying(255),
    line2 character varying(255),
    city character varying(120),
    region character varying(120),
    postal_code character varying(20),
    country_code character varying(2),
    address_updated_at timestamp(6) with time zone,
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.ext_people_contact_person (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    person_id uuid NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    preferred_name character varying(255),
    primary_email character varying(255),
    contact_points text,
    person_created_at timestamp(6) with time zone,
    person_updated_at timestamp(6) with time zone,
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    address_line1 character varying(255),
    address_line2 character varying(255),
    address_city character varying(120),
    address_region character varying(120),
    address_postal_code character varying(20),
    address_country_code character varying(2)
);

CREATE TABLE public.ext_vehicle (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    vehicle_id uuid NOT NULL,
    account_id uuid NOT NULL,
    vin character varying(17) NOT NULL,
    vin_normalized character varying(17) NOT NULL,
    unit_number character varying(255),
    description text,
    license_plate character varying(50),
    license_plate_jurisdiction character varying(50),
    model_year integer,
    make character varying(255),
    model character varying(255),
    "trim" character varying(255),
    is_active boolean NOT NULL,
    vehicle_created_at timestamp(6) with time zone,
    vehicle_updated_at timestamp(6) with time zone,
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.ext_vehicle_care_preference (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    vehicle_id uuid NOT NULL,
    service_interval_months integer,
    preference_updated_at timestamp(6) with time zone,
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.follow_up_task (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    task_id uuid NOT NULL,
    party_id uuid NOT NULL,
    vehicle_id uuid,
    type character varying(40) NOT NULL,
    due_date date,
    assigned_to character varying(255),
    status character varying(20) NOT NULL,
    source_workorder_id character varying(64),
    source_event_id character varying(64),
    reason character varying(500),
    outcome character varying(500),
    notes character varying(2000),
    booked_workorder_id uuid,
    booked_appointment_id uuid,
    closed_at timestamp(6) with time zone,
    closed_by character varying(255),
    created_by character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT follow_up_task_outcome_chk CHECK ((((status)::text = 'OPEN'::text) OR (outcome IS NOT NULL))),
    CONSTRAINT follow_up_task_status_chk CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'DONE'::character varying, 'DISMISSED'::character varying])::text[]))),
    CONSTRAINT follow_up_task_type_chk CHECK (((type)::text = ANY ((ARRAY['DECLINED_SERVICE_FOLLOWUP'::character varying, 'SERVICE_DUE_REMINDER'::character varying, 'FLEET_CHECKIN'::character varying, 'CAMPAIGN_RESPONSE'::character varying, 'GENERAL'::character varying])::text[])))
);

CREATE TABLE public.inquiry (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    inquiry_id uuid NOT NULL,
    channel character varying(20) NOT NULL,
    audience_type character varying(20) NOT NULL,
    contact_name character varying(200) NOT NULL,
    organization_name character varying(200),
    email character varying(320),
    phone character varying(40),
    vehicle_of_interest character varying(300),
    service_of_interest character varying(300),
    message character varying(2000),
    campaign_code character varying(100),
    status character varying(20) NOT NULL,
    party_id uuid,
    assigned_to character varying(255),
    resolution_note character varying(1000),
    submitted_from character varying(64),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT inquiry_audience_type_chk CHECK (((audience_type)::text = ANY ((ARRAY['COMMERCIAL'::character varying, 'INDIVIDUAL'::character varying])::text[]))),
    CONSTRAINT inquiry_channel_chk CHECK (((channel)::text = ANY ((ARRAY['WEB_FORM'::character varying, 'PHONE'::character varying, 'WALK_IN'::character varying, 'EMAIL'::character varying, 'REFERRAL'::character varying, 'CAMPAIGN'::character varying])::text[]))),
    CONSTRAINT inquiry_contactable_chk CHECK (((email IS NOT NULL) OR (phone IS NOT NULL))),
    CONSTRAINT inquiry_converted_party_chk CHECK ((((status)::text <> 'CONVERTED'::text) OR (party_id IS NOT NULL))),
    CONSTRAINT inquiry_status_chk CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'CONTACTED'::character varying, 'CONVERTED'::character varying, 'CLOSED'::character varying])::text[])))
);

CREATE TABLE public.merge_audit (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    contacts_transferred integer,
    external_ids_merged integer,
    vehicles_transferred integer,
    merged_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    merge_audit_id uuid NOT NULL,
    merged_by_user_id uuid NOT NULL,
    source_party_id uuid NOT NULL,
    survivor_party_id uuid NOT NULL,
    merge_reason character varying(1000) NOT NULL
);

CREATE TABLE public.party_alias (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    source_party_id uuid NOT NULL,
    target_party_id uuid NOT NULL
);

CREATE TABLE public.party_external_identifier (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    party_id uuid NOT NULL,
    identifier_value character varying(255),
    system_name character varying(255) NOT NULL
);

CREATE TABLE public.party_note (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    note_id uuid NOT NULL,
    party_id uuid NOT NULL,
    source_event_id character varying(64) NOT NULL,
    source_workorder_id character varying(64),
    note_type character varying(100),
    note_text character varying(2000)
);

CREATE TABLE public.party_relationship (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    effective_end_date date,
    effective_start_date date NOT NULL,
    is_primary_billing_contact boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    created_by uuid,
    from_party_id uuid NOT NULL,
    party_relationship_id uuid NOT NULL,
    to_person_id uuid NOT NULL,
    updated_by uuid
);

CREATE TABLE public.party_relationship_role (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    party_relationship_id uuid NOT NULL,
    role_type character varying(255) NOT NULL,
    CONSTRAINT party_relationship_role_role_type_check CHECK (((role_type)::text = ANY (ARRAY[('APPROVER'::character varying)::text, ('BILLING'::character varying)::text, ('PRIMARY_CONTACT'::character varying)::text, ('DRIVER'::character varying)::text, ('TECHNICAL'::character varying)::text])))
);

CREATE TABLE public.party_tag (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    tag_id uuid NOT NULL,
    name character varying(100) NOT NULL,
    category character varying(100),
    color character varying(20),
    active boolean DEFAULT true NOT NULL,
    created_by character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.party_tag_assignment (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    assignment_id uuid NOT NULL,
    party_id uuid NOT NULL,
    tag_id uuid NOT NULL,
    assigned_by character varying(255),
    assigned_at timestamp(6) with time zone NOT NULL,
    source character varying(20) NOT NULL,
    CONSTRAINT party_tag_assignment_source_chk CHECK (((source)::text = ANY ((ARRAY['MANUAL'::character varying, 'CAMPAIGN'::character varying, 'IMPORT'::character varying, 'RULE'::character varying])::text[])))
);

CREATE TABLE public.person_party (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    status smallint NOT NULL,
    tier smallint NOT NULL,
    tier_manual_override boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    tier_assigned_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    customer_id uuid NOT NULL,
    person_id uuid NOT NULL,
    preferred_contact_method character varying(20) NOT NULL,
    customer_number character varying(255) NOT NULL,
    primary_address character varying(255),
    tier_assigned_by character varying(255),
    modified_by character varying(255),
    lifecycle_stage character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT person_party_lifecycle_stage_chk CHECK (((lifecycle_stage)::text = ANY ((ARRAY['PROSPECT'::character varying, 'ACTIVE'::character varying, 'DORMANT'::character varying])::text[]))),
    CONSTRAINT person_party_preferred_contact_method_check CHECK (((preferred_contact_method)::text = ANY (ARRAY[('EMAIL'::character varying)::text, ('PHONE_CALL'::character varying)::text, ('SMS'::character varying)::text, ('NONE'::character varying)::text]))),
    CONSTRAINT person_party_status_check CHECK (((status >= 0) AND (status <= 3))),
    CONSTRAINT person_party_tier_check CHECK (((tier >= 0) AND (tier <= 5)))
);

CREATE TABLE public.processed_events (
    event_id character varying(36) NOT NULL,
    owner character varying(64) NOT NULL,
    processed_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.processing_log (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    processed_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    correlation_id character varying(36),
    event_id character varying(36) NOT NULL,
    status character varying(40) NOT NULL,
    event_type character varying(100) NOT NULL,
    failure_reason character varying(500),
    CONSTRAINT processing_log_status_check CHECK (((status)::text = ANY (ARRAY[('SUCCESS'::character varying)::text, ('SKIPPED_DUPLICATE'::character varying)::text, ('SCHEMA_VALIDATION_FAILED'::character varying)::text, ('BUSINESS_RULE_VIOLATION'::character varying)::text])))
);

CREATE TABLE public.promotion_counter (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    total_usage_count integer NOT NULL,
    version bigint,
    counter_id uuid NOT NULL,
    promotion_id uuid NOT NULL
);

CREATE TABLE public.promotion_redemption (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    discount_amount numeric(38,2) NOT NULL,
    recorded_over_limit boolean,
    created_at timestamp(6) with time zone NOT NULL,
    redemption_timestamp timestamp(6) without time zone,
    customer_id uuid NOT NULL,
    invoice_id uuid,
    promotion_id uuid NOT NULL,
    promotion_redemption_id uuid NOT NULL,
    workorder_id uuid NOT NULL,
    discount_type character varying(30) NOT NULL,
    promotion_code character varying(255) NOT NULL,
    recorded_by character varying(255),
    status character varying(30) NOT NULL,
    campaign_code character varying(100),
    CONSTRAINT promotion_redemption_status_check CHECK (((status)::text = ANY (ARRAY[('RECORDED'::character varying)::text, ('RECORDED_OVER_LIMIT'::character varying)::text])))
);

CREATE TABLE public.segment (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    segment_id uuid NOT NULL,
    name character varying(150) NOT NULL,
    description character varying(1000),
    audience_type character varying(20) NOT NULL,
    type character varying(20) NOT NULL,
    predicate text,
    active boolean DEFAULT true NOT NULL,
    created_by character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT segment_audience_type_chk CHECK (((audience_type)::text = ANY ((ARRAY['COMMERCIAL'::character varying, 'INDIVIDUAL'::character varying])::text[]))),
    CONSTRAINT segment_predicate_shape_chk CHECK (((((type)::text = 'DYNAMIC'::text) AND (predicate IS NOT NULL)) OR (((type)::text = 'STATIC'::text) AND (predicate IS NULL)))),
    CONSTRAINT segment_type_chk CHECK (((type)::text = ANY ((ARRAY['STATIC'::character varying, 'DYNAMIC'::character varying])::text[])))
);

CREATE TABLE public.segment_member (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    segment_member_id uuid NOT NULL,
    segment_id uuid NOT NULL,
    party_id uuid NOT NULL,
    contact_id uuid,
    added_by character varying(255),
    added_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.service_history (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    service_history_id uuid NOT NULL,
    party_id uuid NOT NULL,
    vehicle_id uuid,
    source_workorder_id uuid NOT NULL,
    workorder_number character varying(64),
    completed_at timestamp(6) with time zone NOT NULL,
    amount numeric(19,2),
    source_event_id character varying(64) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.suppression_entry (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    suppression_id uuid NOT NULL,
    channel character varying(20) NOT NULL,
    address_hash character varying(64) NOT NULL,
    address_hint character varying(120),
    party_id uuid,
    reason character varying(30) NOT NULL,
    source character varying(30) NOT NULL,
    created_by character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT suppression_entry_channel_chk CHECK (((channel)::text = ANY ((ARRAY['EMAIL'::character varying, 'SMS'::character varying])::text[]))),
    CONSTRAINT suppression_entry_reason_chk CHECK (((reason)::text = ANY ((ARRAY['HARD_BOUNCE'::character varying, 'SPAM_COMPLAINT'::character varying, 'LEGAL_DNC'::character varying, 'MANUAL'::character varying, 'UNSUBSCRIBE_LINK'::character varying])::text[]))),
    CONSTRAINT suppression_entry_source_chk CHECK (((source)::text = ANY ((ARRAY['CSR'::character varying, 'SELF_SERVICE'::character varying, 'UNSUBSCRIBE_LINK'::character varying, 'IMPORT'::character varying, 'API'::character varying, 'SYSTEM'::character varying])::text[])))
);

ALTER TABLE ONLY public.commercial_party
    ADD CONSTRAINT commercial_party_customer_number_key UNIQUE (tenant_id, customer_number);

ALTER TABLE ONLY public.commercial_party
    ADD CONSTRAINT commercial_party_pkey PRIMARY KEY (customer_id);

ALTER TABLE ONLY public.commercial_party
    ADD CONSTRAINT commercial_party_tenant_key UNIQUE (tenant_id, customer_id);

ALTER TABLE ONLY public.communication_preference
    ADD CONSTRAINT communication_preference_party_id_key UNIQUE (tenant_id, party_id);

ALTER TABLE ONLY public.communication_preference
    ADD CONSTRAINT communication_preference_pkey PRIMARY KEY (preference_id);

ALTER TABLE ONLY public.communication_preference
    ADD CONSTRAINT communication_preference_tenant_key UNIQUE (tenant_id, preference_id);

ALTER TABLE ONLY public.consent_event
    ADD CONSTRAINT consent_event_pkey PRIMARY KEY (consent_event_id);

ALTER TABLE ONLY public.consent_event
    ADD CONSTRAINT consent_event_tenant_key UNIQUE (tenant_id, consent_event_id);

ALTER TABLE ONLY public.consent_flag
    ADD CONSTRAINT consent_flag_pkey PRIMARY KEY (preference_id, flag_name);

ALTER TABLE ONLY public.consent_flag
    ADD CONSTRAINT consent_flag_tenant_key UNIQUE (tenant_id, preference_id, flag_name);

ALTER TABLE ONLY public.contact_role_assignment
    ADD CONSTRAINT contact_role_assignment_pkey PRIMARY KEY (contact_id, customer_account_id, role_name);

ALTER TABLE ONLY public.contact_role_assignment
    ADD CONSTRAINT contact_role_assignment_tenant_key UNIQUE (tenant_id, contact_id, customer_account_id, role_name);

ALTER TABLE ONLY public.customer_interaction
    ADD CONSTRAINT customer_interaction_pkey PRIMARY KEY (interaction_id);

ALTER TABLE ONLY public.customer_interaction
    ADD CONSTRAINT customer_interaction_tenant_key UNIQUE (tenant_id, interaction_id);

ALTER TABLE ONLY public.event_outbox
    ADD CONSTRAINT event_outbox_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ext_organization_postal_address
    ADD CONSTRAINT ext_organization_postal_address_pkey PRIMARY KEY (organization_id);

ALTER TABLE ONLY public.ext_organization_postal_address
    ADD CONSTRAINT ext_organization_postal_address_tenant_key UNIQUE (tenant_id, organization_id);

ALTER TABLE ONLY public.ext_people_contact_person
    ADD CONSTRAINT ext_people_contact_person_pkey PRIMARY KEY (person_id);

ALTER TABLE ONLY public.ext_people_contact_person
    ADD CONSTRAINT ext_people_contact_person_tenant_key UNIQUE (tenant_id, person_id);

ALTER TABLE ONLY public.ext_vehicle_care_preference
    ADD CONSTRAINT ext_vehicle_care_preference_pkey PRIMARY KEY (vehicle_id);

ALTER TABLE ONLY public.ext_vehicle_care_preference
    ADD CONSTRAINT ext_vehicle_care_preference_tenant_key UNIQUE (tenant_id, vehicle_id);

ALTER TABLE ONLY public.ext_vehicle
    ADD CONSTRAINT ext_vehicle_pkey PRIMARY KEY (vehicle_id);

ALTER TABLE ONLY public.ext_vehicle
    ADD CONSTRAINT ext_vehicle_tenant_key UNIQUE (tenant_id, vehicle_id);

ALTER TABLE ONLY public.follow_up_task
    ADD CONSTRAINT follow_up_task_pkey PRIMARY KEY (task_id);

ALTER TABLE ONLY public.follow_up_task
    ADD CONSTRAINT follow_up_task_tenant_key UNIQUE (tenant_id, task_id);

ALTER TABLE ONLY public.inquiry
    ADD CONSTRAINT inquiry_pkey PRIMARY KEY (inquiry_id);

ALTER TABLE ONLY public.inquiry
    ADD CONSTRAINT inquiry_tenant_key UNIQUE (tenant_id, inquiry_id);

ALTER TABLE ONLY public.merge_audit
    ADD CONSTRAINT merge_audit_pkey PRIMARY KEY (merge_audit_id);

ALTER TABLE ONLY public.merge_audit
    ADD CONSTRAINT merge_audit_tenant_key UNIQUE (tenant_id, merge_audit_id);

ALTER TABLE ONLY public.party_alias
    ADD CONSTRAINT party_alias_pkey PRIMARY KEY (source_party_id);

ALTER TABLE ONLY public.party_alias
    ADD CONSTRAINT party_alias_tenant_key UNIQUE (tenant_id, source_party_id);

ALTER TABLE ONLY public.party_external_identifier
    ADD CONSTRAINT party_external_identifier_pkey PRIMARY KEY (party_id, system_name);

ALTER TABLE ONLY public.party_external_identifier
    ADD CONSTRAINT party_external_identifier_tenant_key UNIQUE (tenant_id, party_id, system_name);

ALTER TABLE ONLY public.party_note
    ADD CONSTRAINT party_note_pkey PRIMARY KEY (note_id);

ALTER TABLE ONLY public.party_note
    ADD CONSTRAINT party_note_tenant_key UNIQUE (tenant_id, note_id);

ALTER TABLE ONLY public.party_relationship
    ADD CONSTRAINT party_relationship_pkey PRIMARY KEY (party_relationship_id);

ALTER TABLE ONLY public.party_relationship
    ADD CONSTRAINT party_relationship_tenant_key UNIQUE (tenant_id, party_relationship_id);

ALTER TABLE ONLY public.party_relationship_role
    ADD CONSTRAINT party_relationship_role_pkey PRIMARY KEY (party_relationship_id, role_type);

ALTER TABLE ONLY public.party_relationship_role
    ADD CONSTRAINT party_relationship_role_tenant_key UNIQUE (tenant_id, party_relationship_id, role_type);

ALTER TABLE ONLY public.party_tag_assignment
    ADD CONSTRAINT party_tag_assignment_pkey PRIMARY KEY (assignment_id);

ALTER TABLE ONLY public.party_tag_assignment
    ADD CONSTRAINT party_tag_assignment_tenant_key UNIQUE (tenant_id, assignment_id);

ALTER TABLE ONLY public.party_tag
    ADD CONSTRAINT party_tag_pkey PRIMARY KEY (tag_id);

ALTER TABLE ONLY public.party_tag
    ADD CONSTRAINT party_tag_tenant_key UNIQUE (tenant_id, tag_id);

ALTER TABLE ONLY public.person_party
    ADD CONSTRAINT person_party_customer_number_key UNIQUE (tenant_id, customer_number);

ALTER TABLE ONLY public.person_party
    ADD CONSTRAINT person_party_person_id_key UNIQUE (tenant_id, person_id);

ALTER TABLE ONLY public.person_party
    ADD CONSTRAINT person_party_pkey PRIMARY KEY (customer_id);

ALTER TABLE ONLY public.person_party
    ADD CONSTRAINT person_party_tenant_key UNIQUE (tenant_id, customer_id);

ALTER TABLE ONLY public.processed_events
    ADD CONSTRAINT processed_events_pkey PRIMARY KEY (event_id);

ALTER TABLE ONLY public.processing_log
    ADD CONSTRAINT processing_log_event_id_key UNIQUE (tenant_id, event_id);

ALTER TABLE ONLY public.processing_log
    ADD CONSTRAINT processing_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.processing_log
    ADD CONSTRAINT processing_log_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.promotion_counter
    ADD CONSTRAINT promotion_counter_pkey PRIMARY KEY (counter_id);

ALTER TABLE ONLY public.promotion_counter
    ADD CONSTRAINT promotion_counter_tenant_key UNIQUE (tenant_id, counter_id);

ALTER TABLE ONLY public.promotion_counter
    ADD CONSTRAINT promotion_counter_promotion_id_key UNIQUE (tenant_id, promotion_id);

ALTER TABLE ONLY public.promotion_redemption
    ADD CONSTRAINT promotion_redemption_pkey PRIMARY KEY (promotion_redemption_id);

ALTER TABLE ONLY public.promotion_redemption
    ADD CONSTRAINT promotion_redemption_tenant_key UNIQUE (tenant_id, promotion_redemption_id);

ALTER TABLE ONLY public.segment_member
    ADD CONSTRAINT segment_member_pkey PRIMARY KEY (segment_member_id);

ALTER TABLE ONLY public.segment_member
    ADD CONSTRAINT segment_member_tenant_key UNIQUE (tenant_id, segment_member_id);

ALTER TABLE ONLY public.segment
    ADD CONSTRAINT segment_pkey PRIMARY KEY (segment_id);

ALTER TABLE ONLY public.segment
    ADD CONSTRAINT segment_tenant_key UNIQUE (tenant_id, segment_id);

ALTER TABLE ONLY public.service_history
    ADD CONSTRAINT service_history_pkey PRIMARY KEY (service_history_id);

ALTER TABLE ONLY public.service_history
    ADD CONSTRAINT service_history_tenant_key UNIQUE (tenant_id, service_history_id);

ALTER TABLE ONLY public.suppression_entry
    ADD CONSTRAINT suppression_entry_pkey PRIMARY KEY (suppression_id);

ALTER TABLE ONLY public.suppression_entry
    ADD CONSTRAINT suppression_entry_tenant_key UNIQUE (tenant_id, suppression_id);

ALTER TABLE ONLY public.contact_role_assignment
    ADD CONSTRAINT uk_primary_role_per_account UNIQUE (tenant_id, customer_account_id, role_name, is_primary);

ALTER TABLE ONLY public.party_tag_assignment
    ADD CONSTRAINT uq_party_tag_assignment UNIQUE (tenant_id, party_id, tag_id);

ALTER TABLE ONLY public.promotion_redemption
    ADD CONSTRAINT uq_promotion_workorder UNIQUE (tenant_id, promotion_id, workorder_id);

ALTER TABLE ONLY public.segment_member
    ADD CONSTRAINT uq_segment_member UNIQUE (tenant_id, segment_id, party_id);

ALTER TABLE ONLY public.suppression_entry
    ADD CONSTRAINT uq_suppression_channel_address UNIQUE (tenant_id, channel, address_hash);

CREATE INDEX idx_comm_pref_party ON public.communication_preference USING btree (party_id);

CREATE INDEX idx_commercial_party_lifecycle ON public.commercial_party USING btree (lifecycle_stage);

CREATE INDEX idx_consent_event_occurred ON public.consent_event USING btree (occurred_at);

CREATE INDEX idx_consent_event_party ON public.consent_event USING btree (party_id, occurred_at DESC);

CREATE INDEX idx_contact_role_account ON public.contact_role_assignment USING btree (customer_account_id);

CREATE INDEX idx_contact_role_contact ON public.contact_role_assignment USING btree (contact_id);

CREATE INDEX idx_contact_role_role ON public.contact_role_assignment USING btree (role_name);

CREATE INDEX idx_cust_ext_person_last_name ON public.ext_people_contact_person USING btree (last_name);

CREATE INDEX idx_cust_ext_person_primary_email ON public.ext_people_contact_person USING btree (primary_email);

CREATE INDEX idx_customer_interaction_campaign ON public.customer_interaction USING btree (campaign_id);

CREATE INDEX idx_customer_interaction_party ON public.customer_interaction USING btree (party_id, occurred_at DESC);

CREATE INDEX idx_event_outbox_published_window ON public.event_outbox USING btree (topic, created_at) WHERE (published_at IS NOT NULL);

CREATE INDEX idx_event_outbox_unpublished ON public.event_outbox USING btree (id) WHERE (published_at IS NULL);

CREATE INDEX idx_ext_vehicle_account ON public.ext_vehicle USING btree (account_id);

CREATE INDEX idx_ext_vehicle_vin_normalized ON public.ext_vehicle USING btree (vin_normalized);

CREATE INDEX idx_follow_up_task_assignee ON public.follow_up_task USING btree (assigned_to, status);

CREATE INDEX idx_follow_up_task_party ON public.follow_up_task USING btree (party_id, status);

CREATE INDEX idx_follow_up_task_queue ON public.follow_up_task USING btree (status, due_date);

CREATE INDEX idx_inquiry_campaign ON public.inquiry USING btree (campaign_code) WHERE (campaign_code IS NOT NULL);

CREATE INDEX idx_inquiry_party ON public.inquiry USING btree (party_id);

CREATE INDEX idx_inquiry_source_window ON public.inquiry USING btree (submitted_from, created_at) WHERE (submitted_from IS NOT NULL);

CREATE INDEX idx_inquiry_status ON public.inquiry USING btree (status, created_at DESC);

CREATE INDEX idx_merge_audit_merged_at ON public.merge_audit USING btree (merged_at);

CREATE INDEX idx_merge_audit_source ON public.merge_audit USING btree (source_party_id);

CREATE INDEX idx_merge_audit_survivor ON public.merge_audit USING btree (survivor_party_id);

CREATE INDEX idx_party_note_party_id ON public.party_note USING btree (party_id);

CREATE INDEX idx_party_rel_from_party ON public.party_relationship USING btree (from_party_id);

CREATE INDEX idx_party_rel_primary_billing ON public.party_relationship USING btree (from_party_id, is_primary_billing_contact);

CREATE INDEX idx_party_rel_to_person ON public.party_relationship USING btree (to_person_id);

CREATE INDEX idx_party_tag_assignment_party ON public.party_tag_assignment USING btree (party_id);

CREATE INDEX idx_party_tag_assignment_tag ON public.party_tag_assignment USING btree (tag_id);

CREATE INDEX idx_party_tag_category ON public.party_tag USING btree (category);

CREATE INDEX idx_person_party_lifecycle ON public.person_party USING btree (lifecycle_stage);

CREATE INDEX idx_processed_events_owner_event ON public.processed_events USING btree (owner, event_id);

CREATE INDEX idx_promotion_redemption_campaign_code ON public.promotion_redemption USING btree (campaign_code) WHERE (campaign_code IS NOT NULL);

CREATE INDEX idx_segment_audience_type ON public.segment USING btree (audience_type);

CREATE INDEX idx_segment_member_segment ON public.segment_member USING btree (segment_id);

CREATE INDEX idx_service_history_party ON public.service_history USING btree (party_id, completed_at DESC);

CREATE INDEX idx_service_history_vehicle ON public.service_history USING btree (vehicle_id, completed_at DESC);

CREATE INDEX idx_suppression_lookup ON public.suppression_entry USING btree (channel, address_hash);

CREATE INDEX idx_suppression_party ON public.suppression_entry USING btree (party_id);

CREATE UNIQUE INDEX uq_customer_interaction_source_event ON public.customer_interaction USING btree (tenant_id, source_event_id) WHERE (source_event_id IS NOT NULL);

CREATE UNIQUE INDEX uq_follow_up_task_source_event ON public.follow_up_task USING btree (tenant_id, source_event_id) WHERE (source_event_id IS NOT NULL);

CREATE UNIQUE INDEX uq_party_note_source_event ON public.party_note USING btree (tenant_id, source_event_id) WHERE (source_event_id IS NOT NULL);

CREATE UNIQUE INDEX uq_party_tag_name ON public.party_tag USING btree (tenant_id, lower((name)::text));

CREATE UNIQUE INDEX uq_segment_name ON public.segment USING btree (tenant_id, lower((name)::text));

CREATE UNIQUE INDEX uq_service_history_source_event ON public.service_history USING btree (tenant_id, source_event_id);

ALTER TABLE ONLY public.party_external_identifier
    ADD CONSTRAINT fk4t0ae53m82e4t1b16b2auoqxj FOREIGN KEY (tenant_id, party_id) REFERENCES public.commercial_party(tenant_id, customer_id);

ALTER TABLE ONLY public.party_relationship_role
    ADD CONSTRAINT fk89bwlqs1fhtw1s8ndpf3kf2lr FOREIGN KEY (tenant_id, party_relationship_id) REFERENCES public.party_relationship(tenant_id, party_relationship_id);

ALTER TABLE ONLY public.party_relationship
    ADD CONSTRAINT fkftk9y006ra70wvp6kiipg3e5l FOREIGN KEY (tenant_id, to_person_id) REFERENCES public.person_party(tenant_id, customer_id);

ALTER TABLE ONLY public.consent_flag
    ADD CONSTRAINT fkloc4qn5pey3x2xm25jb1icc4q FOREIGN KEY (tenant_id, preference_id) REFERENCES public.communication_preference(tenant_id, preference_id);

ALTER TABLE ONLY public.party_relationship
    ADD CONSTRAINT fkno0x9fk035wa0dmacpe7dw83k FOREIGN KEY (tenant_id, from_party_id) REFERENCES public.commercial_party(tenant_id, customer_id);

ALTER TABLE ONLY public.commercial_party
    ADD CONSTRAINT fkqnadyw5cth6b002hcsauif0ic FOREIGN KEY (tenant_id, parent_party_id) REFERENCES public.commercial_party(tenant_id, customer_id);

ALTER TABLE ONLY public.party_tag_assignment
    ADD CONSTRAINT party_tag_assignment_tag_fk FOREIGN KEY (tenant_id, tag_id) REFERENCES public.party_tag(tenant_id, tag_id);

ALTER TABLE ONLY public.segment_member
    ADD CONSTRAINT segment_member_segment_fk FOREIGN KEY (tenant_id, segment_id) REFERENCES public.segment(tenant_id, segment_id);

CREATE INDEX commercial_party_tenant_idx ON public.commercial_party USING btree (tenant_id);

CREATE INDEX communication_preference_tenant_idx ON public.communication_preference USING btree (tenant_id);

CREATE INDEX consent_event_tenant_idx ON public.consent_event USING btree (tenant_id);

CREATE INDEX consent_flag_tenant_idx ON public.consent_flag USING btree (tenant_id);

CREATE INDEX contact_role_assignment_tenant_idx ON public.contact_role_assignment USING btree (tenant_id);

CREATE INDEX customer_vehicle_tenant_idx ON public.customer_vehicle USING btree (tenant_id);

CREATE INDEX ext_organization_postal_address_tenant_idx ON public.ext_organization_postal_address USING btree (tenant_id);

CREATE INDEX ext_people_contact_person_tenant_idx ON public.ext_people_contact_person USING btree (tenant_id);

CREATE INDEX ext_vehicle_tenant_idx ON public.ext_vehicle USING btree (tenant_id);

CREATE INDEX ext_vehicle_care_preference_tenant_idx ON public.ext_vehicle_care_preference USING btree (tenant_id);

CREATE INDEX inquiry_tenant_idx ON public.inquiry USING btree (tenant_id);

CREATE INDEX merge_audit_tenant_idx ON public.merge_audit USING btree (tenant_id);

CREATE INDEX party_alias_tenant_idx ON public.party_alias USING btree (tenant_id);

CREATE INDEX party_external_identifier_tenant_idx ON public.party_external_identifier USING btree (tenant_id);

CREATE INDEX party_relationship_tenant_idx ON public.party_relationship USING btree (tenant_id);

CREATE INDEX party_relationship_role_tenant_idx ON public.party_relationship_role USING btree (tenant_id);

CREATE INDEX party_tag_assignment_tenant_idx ON public.party_tag_assignment USING btree (tenant_id);

CREATE INDEX person_party_tenant_idx ON public.person_party USING btree (tenant_id);

CREATE INDEX processing_log_tenant_idx ON public.processing_log USING btree (tenant_id);

CREATE INDEX promotion_counter_tenant_idx ON public.promotion_counter USING btree (tenant_id);

CREATE INDEX promotion_redemption_tenant_idx ON public.promotion_redemption USING btree (tenant_id);

CREATE INDEX segment_member_tenant_idx ON public.segment_member USING btree (tenant_id);

CREATE INDEX suppression_entry_tenant_idx ON public.suppression_entry USING btree (tenant_id);

ALTER TABLE public.commercial_party ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commercial_party FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.commercial_party
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.communication_preference ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.communication_preference FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.communication_preference
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.consent_event ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consent_event FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.consent_event
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.consent_flag ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consent_flag FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.consent_flag
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.contact_role_assignment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_role_assignment FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.contact_role_assignment
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.customer_interaction ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_interaction FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.customer_interaction
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.customer_vehicle ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_vehicle FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.customer_vehicle
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_organization_postal_address ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_organization_postal_address FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_organization_postal_address
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_people_contact_person ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_people_contact_person FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_people_contact_person
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_vehicle ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_vehicle FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_vehicle
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_vehicle_care_preference ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_vehicle_care_preference FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_vehicle_care_preference
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.follow_up_task ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follow_up_task FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.follow_up_task
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.inquiry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiry FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.inquiry
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.merge_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.merge_audit FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.merge_audit
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.party_alias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.party_alias FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.party_alias
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.party_external_identifier ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.party_external_identifier FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.party_external_identifier
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.party_note ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.party_note FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.party_note
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.party_relationship ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.party_relationship FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.party_relationship
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.party_relationship_role ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.party_relationship_role FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.party_relationship_role
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.party_tag ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.party_tag FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.party_tag
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.party_tag_assignment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.party_tag_assignment FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.party_tag_assignment
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.person_party ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.person_party FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.person_party
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.processing_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.processing_log FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.processing_log
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.promotion_counter ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotion_counter FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.promotion_counter
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.promotion_redemption ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotion_redemption FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.promotion_redemption
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.segment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.segment FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.segment
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.segment_member ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.segment_member FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.segment_member
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.service_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_history FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.service_history
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.suppression_entry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppression_entry FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.suppression_entry
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());
