-- pos-vehicle-reference-carapi: Flyway baseline (flattened 2026-09-09 from the previous migration history) with the
-- ADR-0062 tenancy schema folded in. Generated by scripts/db/tenancy/flatten.py from a pg_dump of a
-- database migrated with the retired scripts; the tenancy additions are mechanical and are listed in
-- docs/TENANCY_SCHEMA.md. Global (unscoped) tables: src/main/resources/db/tenancy-global-tables.txt.
--
-- Tenant context: app_current_tenant() reads the session setting app.current_tenant, which the
-- TenantAwareDataSource (pos-tenancy-common, plan WS1) binds per checkout. Until then the owner role
-- carries a transitional default (postgres/init-tenancy.sh) and tests set it per connection.
-- With nothing bound: NULL -> every scoped table reads as empty and refuses inserts (fail closed).

-- Functions are emitted before the tables they reference (pg_dump order); do not validate bodies.
SET check_function_bodies = false;

CREATE OR REPLACE FUNCTION public.app_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$ SELECT NULLIF(current_setting('app.current_tenant', true), '')::uuid $$;

CREATE TABLE public.car_api_make (
    id uuid NOT NULL,
    make_id uuid,
    make_name character varying(255),
    cache_timestamp timestamp without time zone
);

CREATE TABLE public.car_api_model (
    id uuid NOT NULL,
    model_id uuid,
    model_name character varying(255),
    make_id uuid,
    cache_timestamp timestamp without time zone
);

ALTER TABLE ONLY public.car_api_make
    ADD CONSTRAINT car_api_make_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.car_api_model
    ADD CONSTRAINT car_api_model_pkey PRIMARY KEY (id);

CREATE INDEX idx_car_api_model_make_id ON public.car_api_model USING btree (make_id);

ALTER TABLE ONLY public.car_api_model
    ADD CONSTRAINT fk_car_api_model_make FOREIGN KEY (make_id) REFERENCES public.car_api_make(id);
