package com.positivity.vehiclefitment.entity;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

@Data
@Entity
public class Make {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    @ManyToOne
    private Manufacturer manufacturer; // Reference to the Manufacturer entity
    private LocalDateTime cacheTimestamp;
    // Getters and setters are generated by Lombok's @Data annotation
}

