-- Phase 5.3 follow-up: add remaining mapped entity columns for pos-workorder.

ALTER TABLE IF EXISTS audit_events
    ADD COLUMN IF NOT EXISTS entity_type VARCHAR(255),
    ADD COLUMN IF NOT EXISTS entity_id UUID,
    ADD COLUMN IF NOT EXISTS event_type VARCHAR(255),
    ADD COLUMN IF NOT EXISTS event_timestamp TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS user_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS details TEXT;

ALTER TABLE IF EXISTS substitute_link
    ADD COLUMN IF NOT EXISTS product_id UUID,
    ADD COLUMN IF NOT EXISTS substitute_part_id UUID,
    ADD COLUMN IF NOT EXISTS substitute_type VARCHAR(64),
    ADD COLUMN IF NOT EXISTS is_auto_suggest BOOLEAN,
    ADD COLUMN IF NOT EXISTS priority INTEGER,
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN,
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(255),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS version INTEGER;

ALTER TABLE IF EXISTS approval_record
    ADD COLUMN IF NOT EXISTS resolution_status VARCHAR(64),
    ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS resolved_by VARCHAR(255),
    ADD COLUMN IF NOT EXISTS exception_reason TEXT,
    ADD COLUMN IF NOT EXISTS approval_note TEXT;

ALTER TABLE IF EXISTS substitute_audit
    ADD COLUMN IF NOT EXISTS audit_id UUID,
    ADD COLUMN IF NOT EXISTS operation VARCHAR(255),
    ADD COLUMN IF NOT EXISTS payload_before TEXT,
    ADD COLUMN IF NOT EXISTS payload_after TEXT,
    ADD COLUMN IF NOT EXISTS actor_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS timestamp TIMESTAMPTZ;

ALTER TABLE IF EXISTS workorder_labor_entry
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS work_order_snapshots
    ADD COLUMN IF NOT EXISTS status VARCHAR(64),
    ADD COLUMN IF NOT EXISTS captured_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS captured_by VARCHAR(255),
    ADD COLUMN IF NOT EXISTS snapshot_type VARCHAR(255),
    ADD COLUMN IF NOT EXISTS snapshot_data TEXT,
    ADD COLUMN IF NOT EXISTS reason TEXT;

ALTER TABLE IF EXISTS workorder_part_usage_event
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS estimate_item
    ADD COLUMN IF NOT EXISTS item_type VARCHAR(64),
    ADD COLUMN IF NOT EXISTS description VARCHAR(500),
    ADD COLUMN IF NOT EXISTS quantity NUMERIC(19, 4),
    ADD COLUMN IF NOT EXISTS unit_price NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS line_total NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS tax_code VARCHAR(50),
    ADD COLUMN IF NOT EXISTS product_id UUID,
    ADD COLUMN IF NOT EXISTS service_id UUID,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS created_by_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS deleted BOOLEAN,
    ADD COLUMN IF NOT EXISTS approval_status VARCHAR(64),
    ADD COLUMN IF NOT EXISTS approval_method_used VARCHAR(100),
    ADD COLUMN IF NOT EXISTS approval_proof_id UUID,
    ADD COLUMN IF NOT EXISTS rejection_reason VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS approval_notes VARCHAR(1000);

ALTER TABLE IF EXISTS workorder_part_adjustment_event
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS technician_assignment
    ADD COLUMN IF NOT EXISTS technician_id UUID,
    ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS assigned_by TEXT,
    ADD COLUMN IF NOT EXISTS reassignment_reason TEXT,
    ADD COLUMN IF NOT EXISTS notes TEXT,
    ADD COLUMN IF NOT EXISTS current BOOLEAN,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS idempotency_keys
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS estimate
    ADD COLUMN IF NOT EXISTS estimate_number VARCHAR(255),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS created_by_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS signature_data VARCHAR(100000),
    ADD COLUMN IF NOT EXISTS purchase_order_number VARCHAR(100);

ALTER TABLE IF EXISTS workorder_part_substitution
    ADD COLUMN IF NOT EXISTS substitution_id UUID,
    ADD COLUMN IF NOT EXISTS original_product_id UUID,
    ADD COLUMN IF NOT EXISTS substitute_product_id UUID,
    ADD COLUMN IF NOT EXISTS selected_by VARCHAR(255),
    ADD COLUMN IF NOT EXISTS selected_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS pricing_snapshot TEXT;

ALTER TABLE IF EXISTS estimate_snapshot
    ADD COLUMN IF NOT EXISTS status VARCHAR(64),
    ADD COLUMN IF NOT EXISTS snapshot_data TEXT,
    ADD COLUMN IF NOT EXISTS captured_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS captured_by_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS notes VARCHAR(500);
