-- Service-position assignment and single-current-technician enforcement (#1983, #1984, #1985).
--
-- Three things land together because they are one rule expressed at three levels: a workorder holds
-- at most one service position and a position holds at most one open workorder; a workorder has at
-- most one current technician; and both facts keep an append-only history saying who changed them,
-- when and why.
--
-- The constraints are partial UNIQUE INDEXes rather than application checks. Both rules were
-- previously enforced only by a read-then-write in Java, which two concurrent requests pass
-- together: neither sees the other's uncommitted row, so both "free" answers are correct at the
-- moment they are read and both writes land. Postgres deciding between them is the only version of
-- this that actually holds.
--
-- ADR-0062: every table here is tenant-scoped, under row-level security, and every unique index
-- leads with tenant_id, so the constraints are per tenant.

-- ---------------------------------------------------------------------------
-- 1. HOLD joins the resource types.
-- ---------------------------------------------------------------------------
-- A hold position is the site's parking lot: a workorder parked there carries
-- resource_type = 'HOLD' with resource_id = its own location_id, which is what makes a hold
-- site-scoped without a table of its own. It is the one type excluded from the occupancy index
-- below, because a lot has no capacity limit.
ALTER TABLE public.workorder DROP CONSTRAINT IF EXISTS workorder_resource_type_check;
ALTER TABLE public.workorder ADD CONSTRAINT workorder_resource_type_check
    CHECK (resource_type IS NULL OR resource_type IN ('BAY', 'MOBILE_UNIT', 'HOLD'));

COMMENT ON COLUMN public.workorder.resource_type IS
    'Kind of service position resource_id names: BAY and MOBILE_UNIT are pos-location aggregates and '
    'hold one open workorder each; HOLD is the site parking lot (resource_id = location_id) and has no '
    'capacity limit (#1984).';

-- ---------------------------------------------------------------------------
-- 2. Service-position history.
-- ---------------------------------------------------------------------------
CREATE TABLE public.service_position_assignment (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id bigint NOT NULL,
    workorder_id uuid NOT NULL,
    resource_type character varying(32) NOT NULL,
    resource_id uuid NOT NULL,
    location_id uuid,
    assigned_at timestamp(6) without time zone NOT NULL,
    assigned_by text NOT NULL,
    released_at timestamp(6) without time zone,
    released_by text,
    reason text,
    current boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT service_position_assignment_resource_type_check
        CHECK (resource_type IN ('BAY', 'MOBILE_UNIT', 'HOLD'))
);

COMMENT ON TABLE public.service_position_assignment IS
    'Append-only history of the service positions a workorder has occupied (#1983). The workorder row '
    'says where the job is now; this says how it got there. Closed rows are never deleted.';

ALTER TABLE public.service_position_assignment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_position_assignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.service_position_assignment
    ADD CONSTRAINT service_position_assignment_pkey PRIMARY KEY (id);

-- Tenant-scoped uniqueness on the surrogate key, the shape every other table in this module uses:
-- it is what lets a tenant-scoped foreign key reference this row by (tenant_id, id).
ALTER TABLE ONLY public.service_position_assignment
    ADD CONSTRAINT service_position_assignment_tenant_key UNIQUE (tenant_id, id);

-- ADR-0062: the foreign key carries tenant_id so a row can never reference another tenant's
-- workorder, matching how technician_assignment references it.
ALTER TABLE ONLY public.service_position_assignment
    ADD CONSTRAINT service_position_assignment_workorder_fkey
    FOREIGN KEY (tenant_id, workorder_id) REFERENCES public.workorder(tenant_id, id);

CREATE INDEX service_position_assignment_tenant_idx
    ON public.service_position_assignment USING btree (tenant_id);

-- The two read paths: "where is this workorder now" and "what is this workorder's history".
CREATE INDEX service_position_assignment_workorder_idx
    ON public.service_position_assignment USING btree (tenant_id, workorder_id, assigned_at DESC);

CREATE UNIQUE INDEX service_position_assignment_one_current_uniq
    ON public.service_position_assignment (tenant_id, workorder_id)
    WHERE current;

ALTER TABLE public.service_position_assignment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_position_assignment FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.service_position_assignment
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

-- ---------------------------------------------------------------------------
-- 3. Resolve existing double-booked positions, then forbid them.
-- ---------------------------------------------------------------------------
-- Nothing enforced occupancy before this migration, so an alpha seed can hold several open
-- workorders on one bay. Creating the index on that data would fail and leave the module unbootable,
-- so the duplicates are resolved first, exactly as the story requires: the earliest-created claim
-- keeps the position and every later one is moved to its site's hold position — parked, visible, and
-- nobody's assignment silently deleted. A duplicate with no location_id has no lot to be parked in,
-- so it is simply unplaced; unset is always allowed.
--
-- "Open" here is Workorder.isLocked() in SQL, and has to be: a plain
-- status NOT IN ('COMPLETED','CANCELLED') would treat a reopened workorder as closed and leave a
-- live claim behind for the index to reject.
WITH ranked AS (
    SELECT id,
           tenant_id,
           location_id,
           row_number() OVER (
               PARTITION BY tenant_id, resource_type, resource_id
               ORDER BY created_at, id
           ) AS claim_rank
    FROM public.workorder
    WHERE resource_id IS NOT NULL
      AND resource_type IN ('BAY', 'MOBILE_UNIT')
      AND (status IS NULL OR status <> 'CANCELLED')
      AND (status IS NULL OR status <> 'COMPLETED' OR is_reopened IS TRUE)
)
UPDATE public.workorder w
SET resource_type = CASE WHEN ranked.location_id IS NULL THEN NULL ELSE 'HOLD' END,
    resource_id   = ranked.location_id
FROM ranked
WHERE w.id = ranked.id
  AND w.tenant_id = ranked.tenant_id
  AND ranked.claim_rank > 1;

-- One open workorder per exclusive position, per tenant. HOLD is excluded: the parking lot takes as
-- many as fit. The open predicate mirrors Workorder.isLocked() and
-- WorkorderRepository.findOpenOccupantsOfPosition — the application check produces the 409 naming the
-- occupant, this index produces the same refusal for two assigns that race past that check. They
-- must keep agreeing; changing one without the other reintroduces the 500 this index exists to avoid.
CREATE UNIQUE INDEX workorder_open_position_uniq
    ON public.workorder (tenant_id, resource_type, resource_id)
    WHERE resource_id IS NOT NULL
      AND resource_type IN ('BAY', 'MOBILE_UNIT')
      AND (status IS NULL OR status <> 'CANCELLED')
      AND (status IS NULL OR status <> 'COMPLETED' OR is_reopened IS TRUE);

-- ---------------------------------------------------------------------------
-- 4. Seed the position history from the placements that already exist.
-- ---------------------------------------------------------------------------
-- Without this every workorder currently in a bay would read back with an empty history and a
-- current position that no row accounts for, and the first release would have nothing to close. The
-- synthesized row is honest about what is known: the placement is real, its actor and reason are not
-- recorded anywhere, so they say so rather than inventing a user.
INSERT INTO public.service_position_assignment (
    tenant_id, workorder_id, resource_type, resource_id, location_id,
    assigned_at, assigned_by, reason, current, created_at, updated_at)
SELECT w.tenant_id,
       w.id,
       w.resource_type,
       w.resource_id,
       w.location_id,
       COALESCE(w.updated_at, w.created_at, now()) AT TIME ZONE 'UTC',
       'system:migration',
       'Placement that predates service-position history (#1983)',
       TRUE,
       COALESCE(w.created_at, now()),
       now()
FROM public.workorder w
WHERE w.resource_id IS NOT NULL
  AND w.resource_type IS NOT NULL
  AND (w.status IS NULL OR w.status <> 'CANCELLED')
  AND (w.status IS NULL OR w.status <> 'COMPLETED' OR w.is_reopened IS TRUE);

-- ---------------------------------------------------------------------------
-- 5. Resolve existing multi-current technicians, then forbid them.
-- ---------------------------------------------------------------------------
-- assignTechnician closed the previous row and inserted a new one in the application only, so a
-- raced pair of assigns could leave two current rows behind. The latest assigned_at wins — it is the
-- most recent statement of intent — and the losers are closed rather than deleted, because the
-- history is append-only and a closed row is still the record that the technician was once on the
-- job. unassigned_at is stamped from the winner's assigned_at so the timeline reads correctly.
WITH ranked AS (
    SELECT id,
           tenant_id,
           workorder_id,
           row_number() OVER (
               PARTITION BY tenant_id, workorder_id
               ORDER BY assigned_at DESC, id DESC
           ) AS recency_rank,
           max(assigned_at) OVER (PARTITION BY tenant_id, workorder_id) AS winner_assigned_at
    FROM public.technician_assignment
    WHERE current
)
UPDATE public.technician_assignment t
SET current = FALSE,
    unassigned_at = COALESCE(t.unassigned_at, ranked.winner_assigned_at),
    reassignment_reason = COALESCE(
        t.reassignment_reason,
        'Closed by migration: the workorder had more than one current technician (#1985)')
FROM ranked
WHERE t.id = ranked.id
  AND t.tenant_id = ranked.tenant_id
  AND ranked.recency_rank > 1;

-- One current technician per workorder, per tenant. The application refuses a second assign with 409
-- TECHNICIAN_ALREADY_ASSIGNED; this is what makes the rule true when two assigns race that check.
CREATE UNIQUE INDEX technician_assignment_one_current_uniq
    ON public.technician_assignment (tenant_id, workorder_id)
    WHERE current;
