spring:
  application:
    name: documents

server:
  port: ${SERVER_PORT:8092}
  tomcat:
    max-http-header-size: 65536

documents:
  pdf:
    max-input-characters: 1000000
    template-base-path: classpath:/templates
    max-table-rows: 200

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

pos:
  events:
    base-url: ${POS_EVENTS_BASE_URL:http://pos-event-receiver:8080}
    api-secret: ${POS_EVENTS_API_SECRET:}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  default-produces-media-type: application/json

logging:
  level:
    com:
      netflix:
        discovery:
          shared:
            resolver:
              aws:
                ConfigClusterResolver: WARN
