logging:
  level:
    root: INFO
    org:
      springframework: INFO
    com:
      positivity:
        events: INFO

      netflix:
        discovery:
          shared:
            resolver:
              aws:
                ConfigClusterResolver: WARN