package com.positivity.bulkloader.internal.enums;

public enum DomainType {
    CATALOG_PRODUCT,
    INVENTORY_STOCK_COUNT,
    LOCATION,
    CUSTOMER,
    COMMERCIAL_CUSTOMER,
    PERSON,
    BASE_PRICE,
    VEHICLE,
    VEHICLE_FITMENT,
    STORAGE_LOCATION,
    BAY,
    MOBILE_UNIT,
    STAFFING_ASSIGNMENT,
    PUTAWAY_RULE,
    CYCLE_COUNT_PLAN,
    SECURITY_ROLE,
    SECURITY_ROLE_PERMISSION,
    SECURITY_USER,
    USER_PERSON_LINK,
    MECHANIC_SKILL
}
