-- pos-bulk-loader: Flyway baseline (flattened 2026-09-09 from the previous migration history) with the
-- ADR-0062 tenancy schema folded in. Generated by scripts/db/tenancy/flatten.py from a pg_dump of a
-- database migrated with the retired scripts; the tenancy additions are mechanical and are listed in
-- docs/TENANCY_SCHEMA.md. Global (unscoped) tables: src/main/resources/db/tenancy-global-tables.txt.
--
-- Tenant context: app_current_tenant() reads the session setting app.current_tenant, which the
-- TenantAwareDataSource (pos-tenancy-common, plan WS1) binds per checkout. Until then the owner role
-- carries a transitional default (postgres/init-tenancy.sh) and tests set it per connection.
-- With nothing bound: NULL -> every scoped table reads as empty and refuses inserts (fail closed).

-- Functions are emitted before the tables they reference (pg_dump order); do not validate bodies.
SET check_function_bodies = false;

CREATE OR REPLACE FUNCTION public.app_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$ SELECT NULLIF(current_setting('app.current_tenant', true), '')::uuid $$;

CREATE TABLE public.batch_job_execution (
    job_execution_id bigint NOT NULL,
    version bigint,
    job_instance_id bigint NOT NULL,
    create_time timestamp(6) without time zone NOT NULL,
    start_time timestamp(6) without time zone DEFAULT NULL::timestamp without time zone,
    end_time timestamp(6) without time zone DEFAULT NULL::timestamp without time zone,
    status character varying(10),
    exit_code character varying(2500),
    exit_message character varying(2500),
    last_updated timestamp(6) without time zone
);

CREATE TABLE public.batch_job_execution_context (
    job_execution_id bigint NOT NULL,
    short_context character varying(2500) NOT NULL,
    serialized_context text
);

CREATE TABLE public.batch_job_execution_params (
    job_execution_id bigint NOT NULL,
    parameter_name character varying(100) NOT NULL,
    parameter_type character varying(100) NOT NULL,
    parameter_value character varying(2500),
    identifying character(1) NOT NULL
);

CREATE SEQUENCE public.batch_job_execution_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE public.batch_job_instance (
    job_instance_id bigint NOT NULL,
    version bigint,
    job_name character varying(100) NOT NULL,
    job_key character varying(32) NOT NULL
);

CREATE SEQUENCE public.batch_job_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE public.batch_step_execution (
    step_execution_id bigint NOT NULL,
    version bigint NOT NULL,
    step_name character varying(100) NOT NULL,
    job_execution_id bigint NOT NULL,
    create_time timestamp(6) without time zone NOT NULL,
    start_time timestamp(6) without time zone DEFAULT NULL::timestamp without time zone,
    end_time timestamp(6) without time zone DEFAULT NULL::timestamp without time zone,
    status character varying(10),
    commit_count bigint,
    read_count bigint,
    filter_count bigint,
    write_count bigint,
    read_skip_count bigint,
    write_skip_count bigint,
    process_skip_count bigint,
    rollback_count bigint,
    exit_code character varying(2500),
    exit_message character varying(2500),
    last_updated timestamp(6) without time zone
);

CREATE TABLE public.batch_step_execution_context (
    step_execution_id bigint NOT NULL,
    short_context character varying(2500) NOT NULL,
    serialized_context text
);

CREATE SEQUENCE public.batch_step_execution_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE public.bulk_load_column_mapping (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    job_id uuid NOT NULL,
    source_column character varying(500) NOT NULL,
    target_field character varying(500) NOT NULL,
    confidence double precision,
    overridden_by_user boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.bulk_load_job (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    operator_id character varying(255) NOT NULL,
    location_id uuid,
    file_name character varying(500) NOT NULL,
    original_file_path character varying(1000),
    domain_type character varying(50) NOT NULL,
    status character varying(50) NOT NULL,
    total_rows bigint,
    processed_rows bigint DEFAULT 0,
    success_count bigint DEFAULT 0,
    failure_count bigint DEFAULT 0,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.bulk_load_record_audit (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    job_id uuid NOT NULL,
    entity_type character varying(100),
    entity_id uuid,
    row_number bigint,
    review_status character varying(50) DEFAULT 'PENDING'::character varying NOT NULL,
    reason_codes jsonb,
    original_values jsonb,
    corrected_values jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tus_upload (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    job_id uuid NOT NULL,
    operator_id character varying(255) NOT NULL,
    file_name character varying(500) NOT NULL,
    total_size bigint NOT NULL,
    upload_offset bigint DEFAULT 0 NOT NULL,
    completed boolean DEFAULT false NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.batch_job_execution_context
    ADD CONSTRAINT batch_job_execution_context_pkey PRIMARY KEY (job_execution_id);

ALTER TABLE ONLY public.batch_job_execution
    ADD CONSTRAINT batch_job_execution_pkey PRIMARY KEY (job_execution_id);

ALTER TABLE ONLY public.batch_job_instance
    ADD CONSTRAINT batch_job_instance_pkey PRIMARY KEY (job_instance_id);

ALTER TABLE ONLY public.batch_step_execution_context
    ADD CONSTRAINT batch_step_execution_context_pkey PRIMARY KEY (step_execution_id);

ALTER TABLE ONLY public.batch_step_execution
    ADD CONSTRAINT batch_step_execution_pkey PRIMARY KEY (step_execution_id);

ALTER TABLE ONLY public.bulk_load_column_mapping
    ADD CONSTRAINT bulk_load_column_mapping_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.bulk_load_column_mapping
    ADD CONSTRAINT bulk_load_column_mapping_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.bulk_load_job
    ADD CONSTRAINT bulk_load_job_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.bulk_load_job
    ADD CONSTRAINT bulk_load_job_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.bulk_load_record_audit
    ADD CONSTRAINT bulk_load_record_audit_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.bulk_load_record_audit
    ADD CONSTRAINT bulk_load_record_audit_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.batch_job_instance
    ADD CONSTRAINT job_inst_un UNIQUE (job_name, job_key);

ALTER TABLE ONLY public.tus_upload
    ADD CONSTRAINT tus_upload_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tus_upload
    ADD CONSTRAINT tus_upload_tenant_key UNIQUE (tenant_id, id);

CREATE INDEX idx_bulk_load_column_mapping_job_id ON public.bulk_load_column_mapping USING btree (job_id);

CREATE UNIQUE INDEX idx_bulk_load_job_one_active_per_operator ON public.bulk_load_job USING btree (tenant_id, operator_id) WHERE ((status)::text <> ALL ((ARRAY['COMPLETED'::character varying, 'CANCELLED'::character varying, 'FAILED'::character varying, 'PARTIAL'::character varying])::text[]));

CREATE INDEX idx_bulk_load_job_operator_id ON public.bulk_load_job USING btree (operator_id);

CREATE INDEX idx_bulk_load_job_status ON public.bulk_load_job USING btree (status);

CREATE INDEX idx_bulk_load_record_audit_job_id ON public.bulk_load_record_audit USING btree (job_id);

CREATE INDEX idx_bulk_load_record_audit_review_status ON public.bulk_load_record_audit USING btree (review_status);

CREATE INDEX idx_tus_upload_expires_at ON public.tus_upload USING btree (expires_at) WHERE (completed = false);

CREATE INDEX idx_tus_upload_job_id ON public.tus_upload USING btree (job_id);

ALTER TABLE ONLY public.bulk_load_column_mapping
    ADD CONSTRAINT bulk_load_column_mapping_job_id_fkey FOREIGN KEY (tenant_id, job_id) REFERENCES public.bulk_load_job(tenant_id, id);

ALTER TABLE ONLY public.bulk_load_record_audit
    ADD CONSTRAINT bulk_load_record_audit_job_id_fkey FOREIGN KEY (tenant_id, job_id) REFERENCES public.bulk_load_job(tenant_id, id);

ALTER TABLE ONLY public.batch_job_execution_context
    ADD CONSTRAINT job_exec_ctx_fk FOREIGN KEY (job_execution_id) REFERENCES public.batch_job_execution(job_execution_id);

ALTER TABLE ONLY public.batch_job_execution_params
    ADD CONSTRAINT job_exec_params_fk FOREIGN KEY (job_execution_id) REFERENCES public.batch_job_execution(job_execution_id);

ALTER TABLE ONLY public.batch_step_execution
    ADD CONSTRAINT job_exec_step_fk FOREIGN KEY (job_execution_id) REFERENCES public.batch_job_execution(job_execution_id);

ALTER TABLE ONLY public.batch_job_execution
    ADD CONSTRAINT job_inst_exec_fk FOREIGN KEY (job_instance_id) REFERENCES public.batch_job_instance(job_instance_id);

ALTER TABLE ONLY public.batch_step_execution_context
    ADD CONSTRAINT step_exec_ctx_fk FOREIGN KEY (step_execution_id) REFERENCES public.batch_step_execution(step_execution_id);

ALTER TABLE ONLY public.tus_upload
    ADD CONSTRAINT tus_upload_job_id_fkey FOREIGN KEY (tenant_id, job_id) REFERENCES public.bulk_load_job(tenant_id, id) ON DELETE CASCADE;

CREATE INDEX bulk_load_column_mapping_tenant_idx ON public.bulk_load_column_mapping USING btree (tenant_id);

CREATE INDEX bulk_load_record_audit_tenant_idx ON public.bulk_load_record_audit USING btree (tenant_id);

CREATE INDEX tus_upload_tenant_idx ON public.tus_upload USING btree (tenant_id);

ALTER TABLE public.bulk_load_column_mapping ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bulk_load_column_mapping FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.bulk_load_column_mapping
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.bulk_load_job ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bulk_load_job FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.bulk_load_job
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.bulk_load_record_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bulk_load_record_audit FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.bulk_load_record_audit
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.tus_upload ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tus_upload FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.tus_upload
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());
