spring:
  application:
    name: shop-manager
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    out-of-order: ${SPRING_FLYWAY_OUT_OF_ORDER:false}
  cloud:
    discovery:
      enabled: true
  boot:
    admin:
      client:
        enabled: true

server:
  port: 0

management:
  server:
    port: 0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org:
      springframework: INFO
    com:
      positivity:
        shop: INFO

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

pos:
  crm:
    customer-base-url: ${POS_CRM_CUSTOMER_BASE_URL:http://localhost:8080/v1/customers}
    vehicle-base-url: ${POS_CRM_VEHICLE_BASE_URL:http://localhost:8080/v1/vehicles}
    connect-timeout-ms: ${POS_CRM_CONNECT_TIMEOUT_MS:200}
    read-timeout-ms: ${POS_CRM_READ_TIMEOUT_MS:2000}
