package com.positivity.location.internal.entity;

import com.positivity.shared.id.UUIDv7Id;
import com.positivity.tenancy.TenantContext;
import com.positivity.tenancy.TenantGlobal;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import java.time.Instant;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Idempotency log for replica consumers (ADR-0044 §4): one row per applied envelope, keyed by the
 * envelope's {@code eventId} and written in the same transaction as the replica update, so
 * redelivery is harmless.
 *
 * <p>{@code owner} is the producing domain (e.g. {@code vehicle}); reconciliation-manifest window
 * scans filter on it so one owner's manifest math never sees another owner's eventIds.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@TenantGlobal(
        reason = "consumer idempotency ledger keyed by eventId, deduplicated across tenants; the tenant the fact"
                + " was applied under is carried as data for per-tenant reconciliation (db/tenancy-global-tables.txt)")
@Table(name = "processed_events")
public class ProcessedEvent {

    @Id
    @Column(name = "event_id", nullable = false, updatable = false, length = 36)
    private String eventId;

    @Column(name = "owner", nullable = false, updatable = false, length = 64)
    private String owner;

    @Column(name = "processed_at", nullable = false)
    private Instant processedAt;

    /**
     * Tenant the fact was applied under (ADR-0062 §3), stamped from the tenant bound to the thread
     * when the row is persisted — the tenant the record interceptor read from the message header.
     * Reconciliation-manifest window scans filter on it so one tenant's manifest math never sees
     * another tenant's eventIds; a row recorded with no tenant bound belongs to no manifest. Carried
     * as data, never as a discriminator: the table is global and the eventId key deduplicates across
     * tenants.
     */
    @Column(name = "tenant_id", updatable = false)
    private UUID tenantId;

    @PrePersist
    void stampTenantFromContext() {
        if (tenantId == null) {
            tenantId = TenantContext.current().orElse(null);
        }
    }

    /**
     * Explicit dependency hook for the ArchUnit UUIDv7 rule: the eventId key IS a UUIDv7,
     * generated by the producing module's envelope factory, stored as its string form.
     */
    @Transient
    public Class<?> uuidv7Dependency() {
        return UUIDv7Id.class;
    }
}
