#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

MVNW="./mvnw"
PROFILE="openapi"
PHASE="verify"
SKIP_FLAGS=(-DskipTests -DskipITs)
MODULE_TIMEOUT_SECONDS=420
DRY_RUN=false
AGGREGATE_OPENAPI=true
AGGREGATE_OUTPUT="pos-api-gateway/docs/openapi-aggregate.yaml"

usage() {
  cat <<'EOF'
Generate openapi.yaml for modules configured with springdoc-openapi-maven-plugin.

Usage:
  scripts/generate-openapi.sh [options] [module...]

Options:
  --profile <name>   Maven profile to activate (default: openapi)
  --phase <phase>    Maven phase/goal to run (default: verify)
                     Note: verify ensures post-integration-test runs (spring-boot:stop).
  --timeout <sec>    Per-module timeout in seconds (default: 420, use 0 to disable)
  --aggregate-output <path>
                     Aggregate OpenAPI output path relative to repo root
                     (default: pos-api-gateway/docs/openapi-aggregate.yaml)
  --no-aggregate     Skip aggregate OpenAPI generation step
  --run-tests        Do not skip tests
  --dry-run          Print commands without executing
  -h, --help         Show this help

Examples:
  scripts/generate-openapi.sh
  scripts/generate-openapi.sh pos-price pos-tax
  scripts/generate-openapi.sh --profile openapi --phase verify
EOF
}

MODULES=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      PROFILE="$2"
      shift 2
      ;;
    --phase)
      PHASE="$2"
      shift 2
      ;;
    --run-tests)
      SKIP_FLAGS=()
      shift
      ;;
    --timeout)
      MODULE_TIMEOUT_SECONDS="$2"
      shift 2
      ;;
    --aggregate-output)
      AGGREGATE_OUTPUT="$2"
      shift 2
      ;;
    --no-aggregate)
      AGGREGATE_OPENAPI=false
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    pos-*)
      MODULES+=("$1")
      shift
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ ! -x "$MVNW" ]]; then
  echo "Cannot find executable Maven wrapper at $MVNW" >&2
  exit 1
fi

discover_modules() {
  if command -v rg >/dev/null 2>&1; then
    rg -l '<outputFileName>openapi.yaml</outputFileName>' pos-*/pom.xml \
      | sort \
      | sed 's#/pom.xml$##'
    return
  fi

  grep -l '<outputFileName>openapi.yaml</outputFileName>' pos-*/pom.xml 2>/dev/null \
    | sort \
    | sed 's#/pom.xml$##'
}

module_has_openapi() {
  local module="$1"
  if [[ ! -f "$module/pom.xml" ]]; then
    return 1
  fi

  if command -v rg >/dev/null 2>&1; then
    rg -q '<outputFileName>openapi.yaml</outputFileName>' "$module/pom.xml"
    return
  fi

  grep -q '<outputFileName>openapi.yaml</outputFileName>' "$module/pom.xml"
}

generate_aggregate_openapi() {
  local output_file="$1"
  shift
  local modules=("$@")

  if ! command -v python3 >/dev/null 2>&1; then
    echo "WARN: python3 not found; skipping aggregate OpenAPI generation." >&2
    return 0
  fi

  python3 - "$ROOT_DIR" "$output_file" "${modules[@]}" <<'PY'
import os
import sys
from pathlib import Path

try:
    import yaml  # type: ignore
except Exception:
    print("ERROR: PyYAML is required for aggregate OpenAPI generation (python package 'yaml').", file=sys.stderr)
    sys.exit(1)


def encode_json_pointer(segment: str) -> str:
    return segment.replace("~", "~0").replace("/", "~1")


def relative_posix_path(from_path: Path, to_path: Path) -> str:
    return os.path.relpath(to_path, start=from_path.parent).replace(os.sep, "/")


root_dir = Path(sys.argv[1]).resolve()
output_arg = Path(sys.argv[2])
modules = sys.argv[3:]

output_path = output_arg if output_arg.is_absolute() else (root_dir / output_arg)

specs = []
for module in modules:
    spec_path = root_dir / module / "openapi.yaml"
    if not spec_path.is_file():
        continue
    with spec_path.open("r", encoding="utf-8") as f:
        spec = yaml.safe_load(f)
    if not isinstance(spec, dict):
        continue
    if not isinstance(spec.get("paths"), dict):
        continue
    specs.append((module, spec_path, spec))

if not specs:
    print("WARN: No module openapi.yaml files found; aggregate file not generated.", file=sys.stderr)
    sys.exit(0)

first_info = specs[0][2].get("info") if isinstance(specs[0][2].get("info"), dict) else {}
aggregate = {
    "openapi": "3.0.3",
    "info": {
        "title": "Durion POS Aggregated API",
        "version": str(first_info.get("version", "1.0.0")),
        "description": "Aggregated OpenAPI index referencing module-level specs generated by scripts/generate-openapi.sh",
    },
    "paths": {},
    "tags": [],
    "x-aggregated-modules": [module for module, _, _ in specs],
}

seen_paths = set()
duplicate_paths = []

for module, spec_path, spec in specs:
    aggregate["tags"].append({"name": module, "description": f"Operations served by {module}"})
    for path_key in sorted(spec["paths"].keys()):
        if path_key in seen_paths:
            duplicate_paths.append({"path": path_key, "module": module})
            continue
        seen_paths.add(path_key)
        ref = relative_posix_path(output_path, spec_path) + "#/paths/" + encode_json_pointer(path_key)
        aggregate["paths"][path_key] = {"$ref": ref}

if duplicate_paths:
    aggregate["x-duplicate-paths-skipped"] = duplicate_paths

output_path.parent.mkdir(parents=True, exist_ok=True)
with output_path.open("w", encoding="utf-8") as f:
    yaml.safe_dump(aggregate, f, sort_keys=False, allow_unicode=False)

print(f"Generated aggregate OpenAPI: {output_path}")
print(f"Indexed paths: {len(aggregate['paths'])}")
print(f"Modules included: {len(specs)}")
if duplicate_paths:
    print(f"Duplicate paths skipped: {len(duplicate_paths)}")
PY
}

if [[ ${#MODULES[@]} -eq 0 ]]; then
  mapfile -t MODULES < <(discover_modules)
fi

if [[ ${#MODULES[@]} -eq 0 ]]; then
  echo "No modules found with <outputFileName>openapi.yaml</outputFileName>."
  exit 0
fi

echo "Profile: $PROFILE"
echo "Phase:   $PHASE"
if [[ "$MODULE_TIMEOUT_SECONDS" -gt 0 ]]; then
  echo "Timeout: ${MODULE_TIMEOUT_SECONDS}s per module"
else
  echo "Timeout: disabled"
fi
if [[ ${#SKIP_FLAGS[@]} -eq 0 ]]; then
  echo "Tests:   enabled"
else
  echo "Tests:   skipped (${SKIP_FLAGS[*]})"
fi
echo "Modules: ${MODULES[*]}"
if [[ "$AGGREGATE_OPENAPI" == true ]]; then
  echo "Aggregate output: $AGGREGATE_OUTPUT"
else
  echo "Aggregate output: disabled"
fi
echo

JMX_PORT=9119
CURRENT_MODULE=""

kill_port_if_held() {
  local port="$1"
  local pid
  pid=$(lsof -ti tcp:"$port" 2>/dev/null || true)
  if [[ -n "$pid" ]]; then
    echo "  WARNING: port $port held by PID $pid — killing before start..." >&2
    kill "$pid" 2>/dev/null || true
    local i
    for i in 1 2 3; do
      sleep 1
      lsof -ti tcp:"$port" >/dev/null 2>&1 || break
    done
  fi
}

stop_spring_boot() {
  local module="$1"
  echo "  Attempting spring-boot:stop for $module..." >&2
  if "$MVNW" -pl "$module" -P"$PROFILE" spring-boot:stop -q 2>/dev/null; then
    echo "  spring-boot:stop succeeded for $module." >&2
  else
    echo "  spring-boot:stop failed or not applicable; falling back to port kill." >&2
    kill_port_if_held "$JMX_PORT"
  fi
}

cleanup_current_module() {
  if [[ -n "$CURRENT_MODULE" ]]; then
    echo >&2
    echo "Interrupted — cleaning up $CURRENT_MODULE..." >&2
    stop_spring_boot "$CURRENT_MODULE"
    CURRENT_MODULE=""
  fi
}

trap 'cleanup_current_module' INT TERM EXIT

FAILED_MODULES=()

for module in "${MODULES[@]}"; do
  if ! module_has_openapi "$module"; then
    echo "Skipping $module (no openapi.yaml output configured in pom.xml)"
    continue
  fi

  kill_port_if_held "$JMX_PORT"
  CURRENT_MODULE="$module"

  cmd=("$MVNW" "-pl" "$module" "-am" "-P$PROFILE" "${SKIP_FLAGS[@]}" "$PHASE")
  echo "==> $module"
  echo "${cmd[*]}"
  if [[ "$DRY_RUN" == false ]]; then
    module_status=0
    if [[ "$MODULE_TIMEOUT_SECONDS" -gt 0 ]]; then
      if command -v timeout >/dev/null 2>&1; then
        timeout --foreground "${MODULE_TIMEOUT_SECONDS}" "${cmd[@]}" || module_status=$?
        if [[ "$module_status" -eq 124 ]]; then
          echo "ERROR: Timed out after ${MODULE_TIMEOUT_SECONDS}s while generating OpenAPI for $module." >&2
          echo "This usually indicates Spring Boot failed to start or startup never reached readiness." >&2
          stop_spring_boot "$module"
        elif [[ "$module_status" -ne 0 ]]; then
          echo "ERROR: OpenAPI generation failed for $module (exit code: $module_status)." >&2
          stop_spring_boot "$module"
        fi
      else
        echo "WARN: 'timeout' command not found; running without timeout for $module." >&2
        "${cmd[@]}" || { module_status=$?; stop_spring_boot "$module"; }
      fi
    else
      "${cmd[@]}" || { module_status=$?; stop_spring_boot "$module"; }
    fi

    if [[ "$module_status" -ne 0 ]]; then
      FAILED_MODULES+=("$module:$module_status")
      echo "Continuing to next module..." >&2
    fi
  fi
  CURRENT_MODULE=""
  echo
done

if [[ ${#FAILED_MODULES[@]} -gt 0 ]]; then
  echo "OpenAPI generation completed with failures:"
  for failed in "${FAILED_MODULES[@]}"; do
    echo "  - $failed"
  done
  exit 1
fi

if [[ "$AGGREGATE_OPENAPI" == true ]]; then
  echo "Generating aggregate OpenAPI..."
  if ! generate_aggregate_openapi "$AGGREGATE_OUTPUT" "${MODULES[@]}"; then
    echo "ERROR: Failed to generate aggregate OpenAPI file." >&2
    exit 1
  fi
fi

echo "OpenAPI generation completed successfully."
