#!/bin/bash
# Quick Reference - Version Management Commands
# Run: bash scripts/quick-reference.sh

echo "🚀 DURION POSITIVITY BACKEND - VERSION MANAGEMENT QUICK REFERENCE"
echo "=================================================================="
echo ""

echo "📋 MOST COMMON COMMANDS:"
echo ""
echo "  Preview patch bump (0.1.0 → 0.1.1-SNAPSHOT):"
echo "    ./scripts/update-version.sh patch"
echo ""
echo "  Bump minor version and commit:"
echo "    ./scripts/update-version.sh minor --commit"
echo ""
echo "  Bump major version and commit:"
echo "    ./scripts/update-version.sh major --commit"
echo ""

echo "📊 MANUAL MAVEN COMMANDS:"
echo ""
echo "  Check current version:"
echo "    ./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout"
echo ""
echo "  Set specific version:"
echo "    ./mvnw versions:set -DnewVersion=0.2.0-SNAPSHOT -DprocessAllModules"
echo ""
echo "  Check dependency updates:"
echo "    ./mvnw versions:display-dependency-updates"
echo ""

echo "🔄 RELEASE WORKFLOW:"
echo ""
echo "  1. Bump version:"
echo "     ./scripts/update-version.sh minor --commit"
echo ""
echo "  2. Create release tag:"
echo "     git tag v0.2.0"
echo ""
echo "  3. Push changes and tags:"
echo "     git push origin main --tags"
echo ""

echo "❌ TROUBLESHOOTING:"
echo ""
echo "  Undo all version changes:"
echo "    git checkout pom.xml **/pom.xml"
echo ""
echo "  Make script executable:"
echo "    chmod +x scripts/update-version.sh"
echo ""

echo "📚 LEARN MORE:"
echo ""
echo "  - Full guide:        docs/VERSION_MANAGEMENT.md"
echo "  - Script docs:       scripts/README.md"
echo "  - Maven Plugin docs: https://www.mojohaus.org/versions/"
echo ""
