package com.positivity.inventory.internal.controller;

import com.positivity.events.EmitEvent;
import com.positivity.inventory.internal.config.PickListService;
import com.positivity.inventory.internal.dto.picklist.ConfirmPickTaskRequest;
import com.positivity.inventory.internal.dto.picklist.CreatePickListRequest;
import com.positivity.inventory.internal.dto.picklist.PickListResponse;
import com.positivity.inventory.internal.dto.picklist.PickTaskResponse;
import com.positivity.inventory.internal.dto.picklist.UpdatePickListStatusRequest;
import com.positivity.inventory.internal.enums.PickListStatus;
import com.positivity.inventory.internal.security.InventoryPermissionRegistry;
import com.positivity.shared.error.ApiError;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import java.net.URI;
import java.util.List;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/v1/inventory/pick-lists")
@RequiredArgsConstructor
@Tag(name = "Pick Lists", description = "Pick list and pick task management endpoints")
public class PickListController {

    private final PickListService pickListService;

    @PostMapping
    @EmitEvent(id = "INVENTORY_PICK_LIST_CREATE", apiVersion = "1")
    @io.swagger.v3.oas.annotations.security.SecurityRequirement(
            name = "bearerAuth",
            scopes = {"inventory:pick_list:create"})
    @PreAuthorize("hasAuthority('" + InventoryPermissionRegistry.PICK_LIST_CREATE + "')")
    @Operation(
            operationId = "createPickList",
            summary = "Create pick list",
            description = """
                    Creates a pick list for a workorder in DRAFT status; pick tasks are not generated by this call \
                    — they are attached by the pick-list generation flow, and releasePickList later opens the list \
                    for execution.
                    Use this tool to start pick planning for a workorder; do not use releasePickList, which only \
                    transitions an existing list to READY_TO_PICK, and do not use updatePickListStatus for \
                    creation even though it tolerates unknown ids.
                    Preconditions: none are checked — the workorder id is not validated against the workorder \
                    service.
                    Required inputs: workorderId (UUID); dueAt (ISO-8601 instant), priority (non-negative integer, \
                    default 0) and reservationId (UUID) are optional.
                    Emits an INVENTORY_PICK_LIST_CREATE event; no ledger entries or allocations are written.
                    Returns 201 with the created pick list, and 400 when workorderId is missing or priority is \
                    negative.
                    """,
            tags = {"Pick Lists"})
    @ApiResponse(
            responseCode = "201",
            description = "Pick list created",
            content =
                    @Content(mediaType = "application/json", schema = @Schema(implementation = PickListResponse.class)))
    @ApiResponse(
            responseCode = "400",
            description = "Validation failure",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    @ApiResponse(
            responseCode = "403",
            description = "User lacks required pick list authority",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    public ResponseEntity<PickListResponse> createPickList(
            @io.swagger.v3.oas.annotations.parameters.RequestBody(
                            description = "The workorder to pick for, with optional due time, priority and backing"
                                    + " reservation.",
                            required = true,
                            content =
                                    @Content(
                                            mediaType = "application/json",
                                            examples = @ExampleObject(name = "Pick list for a workorder", value = """
                                                                    {"workorderId":"018f0a1b-2c3d-7e4f-8a9b-0c1d2e3f4a10",
                                                                     "dueAt":"2026-08-20T09:30:00Z",
                                                                     "priority":5,
                                                                     "reservationId":"018f0a1b-2c3d-7e4f-8a9b-0c1d2e3f4a11"}
                                                                    """)))
                    @Valid
                    @RequestBody
                    CreatePickListRequest request) {
        PickListResponse response = pickListService.createPickList(request);
        return ResponseEntity.created(URI.create("/v1/inventory/pick-lists/" + response.getPickListId()))
                .body(response);
    }

    @GetMapping("/{pickListId}")
    @io.swagger.v3.oas.annotations.security.SecurityRequirement(
            name = "bearerAuth",
            scopes = {"inventory:pick_list:view"})
    @PreAuthorize("hasAuthority('" + InventoryPermissionRegistry.PICK_LIST_VIEW + "')")
    @Operation(
            operationId = "getPickList",
            summary = "Get pick list",
            description = """
                    Returns one pick list header with its workorder linkage, lifecycle status, priority and due \
                    timestamp.
                    Use this tool when the pickListId is already known; use listPickListsForWorkorder instead to \
                    find lists by workorder, and listPickTasksForPickList for the list's tasks.
                    Preconditions: the pick list must exist.
                    Required inputs: pickListId (UUID) path parameter; there is no request body.
                    No events are emitted and no state changes; this is a read-only projection.
                    Returns 404 when no pick list exists for the supplied id.
                    """,
            tags = {"Pick Lists"})
    @ApiResponse(
            responseCode = "200",
            description = "Pick list returned",
            content =
                    @Content(mediaType = "application/json", schema = @Schema(implementation = PickListResponse.class)))
    @ApiResponse(
            responseCode = "403",
            description = "User lacks required pick list authority",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    @ApiResponse(
            responseCode = "404",
            description = "Pick list not found",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    public ResponseEntity<PickListResponse> getPickList(
            @Parameter(description = "Pick list identifier", required = true) @PathVariable UUID pickListId) {
        return ResponseEntity.ok(pickListService.getPickList(pickListId));
    }

    @GetMapping
    @io.swagger.v3.oas.annotations.security.SecurityRequirement(
            name = "bearerAuth",
            scopes = {"inventory:pick_list:view"})
    @PreAuthorize("hasAuthority('" + InventoryPermissionRegistry.PICK_LIST_VIEW + "')")
    @Operation(
            operationId = "listPickListsForWorkorder",
            summary = "List pick lists for workorder",
            description = """
                    Returns every pick list linked to a workorder.
                    Use this tool to find a workorder's pick lists and their statuses; use getPickList instead \
                    when the pickListId is already known.
                    Preconditions: none; an unknown workorderId simply yields an empty array.
                    Required inputs: workorderId (UUID) as a query parameter; there is no request body.
                    No events are emitted and no state changes; this is a read-only projection.
                    Returns 200 with an empty array when the workorder has no pick lists.
                    """,
            tags = {"Pick Lists"})
    @ApiResponse(
            responseCode = "200",
            description = "Pick lists returned",
            content =
                    @Content(
                            mediaType = "application/json",
                            array = @ArraySchema(schema = @Schema(implementation = PickListResponse.class))))
    @ApiResponse(
            responseCode = "400",
            description = "Invalid workorder identifier",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    @ApiResponse(
            responseCode = "403",
            description = "User lacks required pick list authority",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    public ResponseEntity<List<PickListResponse>> getPickListsForWorkorder(
            @Parameter(description = "Workorder identifier", required = true) @RequestParam UUID workorderId) {
        return ResponseEntity.ok(pickListService.getPickListsForWorkorder(workorderId));
    }

    @PostMapping("/{pickListId}/release")
    @EmitEvent(id = "INVENTORY_PICK_LIST_RELEASE", apiVersion = "1")
    @io.swagger.v3.oas.annotations.security.SecurityRequirement(
            name = "bearerAuth",
            scopes = {"inventory:pick_list:execute"})
    @PreAuthorize("hasAuthority('" + InventoryPermissionRegistry.PICK_LIST_EXECUTE + "')")
    @Operation(
            operationId = "releasePickList",
            summary = "Release pick list",
            description = """
                    Releases a pick list by setting its status to READY_TO_PICK so its pick tasks can be executed.
                    Use this tool when planning is done and picking should start, then confirm each task with \
                    confirmPickTask; do not use updatePickListStatus for release — it applies any status without \
                    this operation's intent.
                    Preconditions: the pick list must exist; no prior-status guard is enforced, so releasing an \
                    already released or completed list simply re-applies READY_TO_PICK.
                    Required inputs: pickListId (UUID) path parameter; there is no request body.
                    Emits an INVENTORY_PICK_LIST_RELEASE event; no ledger entries are written.
                    Returns 404 when no pick list exists for the supplied id.
                    """,
            tags = {"Pick Lists"})
    @ApiResponse(
            responseCode = "200",
            description = "Pick list released",
            content =
                    @Content(mediaType = "application/json", schema = @Schema(implementation = PickListResponse.class)))
    @ApiResponse(
            responseCode = "403",
            description = "User lacks required pick list authority",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    @ApiResponse(
            responseCode = "404",
            description = "Pick list not found",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    public ResponseEntity<PickListResponse> releasePickList(
            @Parameter(description = "Pick list identifier", required = true) @PathVariable UUID pickListId) {
        return ResponseEntity.ok(pickListService.releasePickList(pickListId));
    }

    @PostMapping("/{pickListId}/tasks/{taskId}/confirm")
    @EmitEvent(id = "INVENTORY_PICK_TASK_CONFIRM", apiVersion = "1")
    @io.swagger.v3.oas.annotations.security.SecurityRequirement(
            name = "bearerAuth",
            scopes = {"inventory:pick_list:execute"})
    @PreAuthorize("hasAuthority('" + InventoryPermissionRegistry.PICK_LIST_EXECUTE + "')")
    @Operation(
            operationId = "confirmPickTask",
            summary = "Confirm pick task",
            description = """
                    Confirms one pick task against scanned data, marking it PICKED with the quantity picked and \
                    the lot the units were taken from; when every task on the list is PICKED the pick list flips \
                    to COMPLETED.
                    Use this tool once per physical pick; do not use confirmPickingList on the pickingLists path, \
                    which is an unimplemented stub that always returns 501, and do not use consumePickedItems \
                    until after confirmation — consumption posts the stock decrement, while confirmation posts no \
                    ledger entries.
                    Preconditions: the pick task must exist and belong to the pick list; for a LOT-tracked SKU the \
                    lot must be keyed and resolve to an existing ACTIVE lot.
                    Required inputs: pickListId and taskId (UUIDs) as path parameters, plus scannedSkuId (UUID), \
                    scannedLocationId (UUID) and quantityPicked (positive, at most the task's required quantity); \
                    lotNumber is required for LOT-tracked SKUs, ignored for untracked ones, and overrides the \
                    task's advisory suggestedLotNumber.
                    Emits an INVENTORY_PICK_TASK_CONFIRM event; the resolved pickedLotId is stored on the task and \
                    travels to the consumption posting.
                    Returns 404 when the pick list or task is unknown or the task belongs to another list, 422 \
                    with PICK_SCAN_MISMATCH when scannedSkuId differs from the task's product, 422 with \
                    LOT_NUMBER_REQUIRED, LOT_UNKNOWN or LOT_NOT_AVAILABLE for lot failures, and 400 when \
                    quantityPicked exceeds the required quantity.
                    """,
            tags = {"Pick Lists"})
    @ApiResponse(
            responseCode = "200",
            description = "Pick task confirmed",
            content =
                    @Content(mediaType = "application/json", schema = @Schema(implementation = PickTaskResponse.class)))
    @ApiResponse(
            responseCode = "400",
            description = "Validation failure",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    @ApiResponse(
            responseCode = "403",
            description = "User lacks required pick task authority",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    @ApiResponse(
            responseCode = "404",
            description = "Pick list or pick task not found",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    @ApiResponse(
            responseCode = "422",
            description = "Pick confirmation failed business validation",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    public ResponseEntity<PickTaskResponse> confirmPickTask(
            @Parameter(description = "Pick list identifier", required = true) @PathVariable UUID pickListId,
            @Parameter(description = "Pick task identifier", required = true) @PathVariable UUID taskId,
            @io.swagger.v3.oas.annotations.parameters.RequestBody(
                            required = true,
                            description = "Scanned SKU, scanned location, quantity picked and, for LOT-tracked"
                                    + " SKUs, the lot the units were taken from.",
                            content =
                                    @Content(
                                            mediaType = "application/json",
                                            schema = @Schema(implementation = ConfirmPickTaskRequest.class),
                                            examples =
                                                    @ExampleObject(name = "Confirm a lot-tracked pick", value = """
                                                                    {"scannedSkuId":"018f0a1b-2c3d-7e4f-8a9b-0c1d2e3f4a01",
                                                                     "scannedLocationId":"018f0a1b-2c3d-7e4f-8a9b-0c1d2e3f4a02",
                                                                     "quantityPicked":12,
                                                                     "lotNumber":"LOT-2026-A"}
                                                                    """)))
                    @Valid
                    @RequestBody
                    ConfirmPickTaskRequest request) {
        return ResponseEntity.ok(pickListService.confirmPickTask(
                pickListId,
                taskId,
                request.getScannedSkuId(),
                request.getScannedLocationId(),
                request.getQuantityPicked(),
                request.getLotNumber()));
    }

    @GetMapping("/{pickListId}/tasks")
    @io.swagger.v3.oas.annotations.security.SecurityRequirement(
            name = "bearerAuth",
            scopes = {"inventory:pick_list:view"})
    @PreAuthorize("hasAuthority('" + InventoryPermissionRegistry.PICK_LIST_VIEW + "')")
    @Operation(
            operationId = "listPickTasksForPickList",
            summary = "List pick tasks for pick list",
            description = """
                    Returns the pick tasks of a pick list with their status, quantities, suggested location and \
                    lot fields.
                    Use this tool to drive a picking screen after releasePickList; use getPickList instead for the \
                    list header only.
                    Preconditions: none are enforced — an unknown pickListId yields an empty array rather than a \
                    404.
                    Required inputs: pickListId (UUID) path parameter; there is no request body.
                    No events are emitted and no state changes; this is a read-only projection.
                    Returns 200 with an empty array when the pick list has no tasks or does not exist.
                    """,
            tags = {"Pick Lists"})
    @ApiResponse(
            responseCode = "200",
            description = "Pick tasks returned",
            content =
                    @Content(
                            mediaType = "application/json",
                            array = @ArraySchema(schema = @Schema(implementation = PickTaskResponse.class))))
    @ApiResponse(
            responseCode = "403",
            description = "User lacks required pick list authority",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    @ApiResponse(
            responseCode = "404",
            description = "Pick list not found",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    public ResponseEntity<List<PickTaskResponse>> getPickTasksForPickList(
            @Parameter(description = "Pick list identifier", required = true) @PathVariable UUID pickListId) {
        return ResponseEntity.ok(pickListService.getPickTasksForPickList(pickListId));
    }

    @PatchMapping("/{pickListId}/status")
    @EmitEvent(id = "INVENTORY_PICK_LIST_STATUS_UPDATE", apiVersion = "1")
    @io.swagger.v3.oas.annotations.security.SecurityRequirement(
            name = "bearerAuth",
            scopes = {"inventory:pick_list:execute"})
    @PreAuthorize("hasAuthority('" + InventoryPermissionRegistry.PICK_LIST_EXECUTE + "')")
    @Operation(
            operationId = "updatePickListStatus",
            summary = "Update pick list status",
            description = """
                    Applies a lifecycle status (DRAFT, READY_TO_PICK, IN_PROGRESS, COMPLETED or CANCELLED) to a \
                    pick list.
                    Use this tool for manual status corrections; do not use it in place of releasePickList, the \
                    intended release transition, or cancelPickList, the intended cancel.
                    Preconditions: none are enforced — no transition rules apply, and an unknown pickListId is not \
                    rejected: a new pick list row is created under that id with the requested status.
                    Required inputs: pickListId (UUID) path parameter and status in the body.
                    Emits an INVENTORY_PICK_LIST_STATUS_UPDATE event; no ledger entries are written and task \
                    statuses are not touched.
                    Returns 400 when status is missing; it never returns 404 because an unknown id upserts a new \
                    row.
                    """,
            tags = {"Pick Lists"})
    @ApiResponse(
            responseCode = "200",
            description = "Pick list status updated",
            content =
                    @Content(mediaType = "application/json", schema = @Schema(implementation = PickListResponse.class)))
    @ApiResponse(
            responseCode = "400",
            description = "Validation failure",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    @ApiResponse(
            responseCode = "403",
            description = "User lacks required pick list authority",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    @ApiResponse(
            responseCode = "404",
            description = "Pick list not found",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    public ResponseEntity<PickListResponse> updatePickListStatus(
            @Parameter(description = "Pick list identifier", required = true) @PathVariable UUID pickListId,
            @io.swagger.v3.oas.annotations.parameters.RequestBody(
                            required = true,
                            description = "The target lifecycle status to apply to the pick list.",
                            content =
                                    @Content(
                                            mediaType = "application/json",
                                            schema = @Schema(implementation = UpdatePickListStatusRequest.class),
                                            examples =
                                                    @ExampleObject(
                                                            name = "Mark in progress",
                                                            value = "{\"status\":\"IN_PROGRESS\"}")))
                    @Valid
                    @RequestBody
                    UpdatePickListStatusRequest request) {
        PickListStatus status = request.getStatus();
        if (status == null) {
            throw new IllegalArgumentException("status is required");
        }
        return ResponseEntity.ok(pickListService.updatePickListStatus(pickListId, status));
    }

    @DeleteMapping("/{pickListId}")
    @EmitEvent(id = "INVENTORY_PICK_LIST_CANCEL", apiVersion = "1")
    @io.swagger.v3.oas.annotations.security.SecurityRequirement(
            name = "bearerAuth",
            scopes = {"inventory:pick_list:execute"})
    @PreAuthorize("hasAuthority('" + InventoryPermissionRegistry.PICK_LIST_EXECUTE + "')")
    @Operation(
            operationId = "cancelPickList",
            summary = "Cancel pick list",
            description = """
                    Cancels a pick list by setting its status to CANCELLED; individual task statuses are left \
                    unchanged.
                    Use this tool to abandon picking for a workorder; do not use cancelReservation, which releases \
                    the reservation and its allocations — cancelling a pick list neither releases allocations nor \
                    writes ledger entries.
                    Preconditions: none are enforced; cancelling an unknown pick list is a silent no-op.
                    Required inputs: pickListId (UUID) path parameter; there is no request body.
                    Emits an INVENTORY_PICK_LIST_CANCEL event; no ledger entries are written.
                    Returns 204 even when the pick list does not exist, because the cancel is then a no-op.
                    """,
            tags = {"Pick Lists"})
    @ApiResponse(responseCode = "204", description = "Pick list cancelled")
    @ApiResponse(
            responseCode = "403",
            description = "User lacks required pick list authority",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    @ApiResponse(
            responseCode = "404",
            description = "Pick list not found",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    public ResponseEntity<Void> cancelPickList(
            @Parameter(description = "Pick list identifier", required = true) @PathVariable UUID pickListId) {
        pickListService.cancelPickList(pickListId);
        return ResponseEntity.noContent().build();
    }
}
