-- pos-order: Flyway baseline (flattened 2026-09-09 from the previous migration history) with the
-- ADR-0062 tenancy schema folded in. Generated by scripts/db/tenancy/flatten.py from a pg_dump of a
-- database migrated with the retired scripts; the tenancy additions are mechanical and are listed in
-- docs/TENANCY_SCHEMA.md. Global (unscoped) tables: src/main/resources/db/tenancy-global-tables.txt.
--
-- Tenant context: app_current_tenant() reads the session setting app.current_tenant, which the
-- TenantAwareDataSource (pos-tenancy-common, plan WS1) binds per checkout. Until then the owner role
-- carries a transitional default (postgres/init-tenancy.sh) and tests set it per connection.
-- With nothing bound: NULL -> every scoped table reads as empty and refuses inserts (fail closed).

-- Functions are emitted before the tables they reference (pg_dump order); do not validate bodies.
SET check_function_bodies = false;

CREATE OR REPLACE FUNCTION public.app_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$ SELECT NULLIF(current_setting('app.current_tenant', true), '')::uuid $$;

CREATE TABLE public.approval_record (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    record_id uuid NOT NULL,
    price_override_id uuid NOT NULL,
    reviewer_user_id uuid NOT NULL,
    reviewer_role character varying(255) NOT NULL,
    action character varying(255) NOT NULL,
    comments character varying(2000),
    action_timestamp timestamp without time zone NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    reviewer_ip_address character varying(255)
);

CREATE TABLE public.cash_movement (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    movement_id uuid NOT NULL,
    session_id uuid NOT NULL,
    movement_type character varying(16) NOT NULL,
    amount numeric(19,4) NOT NULL,
    reason character varying(500) NOT NULL,
    clerk_id character varying(255) NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.event_outbox (
    id uuid NOT NULL,
    topic character varying(255) NOT NULL,
    record_key character varying(255) NOT NULL,
    payload text NOT NULL,
    created_at timestamp without time zone NOT NULL,
    published_at timestamp without time zone,
    attempts integer DEFAULT 0 NOT NULL,
    last_error text
);

CREATE TABLE public.ext_billing_rules (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    party_id uuid NOT NULL,
    payment_terms character varying(100),
    credit_limit numeric(19,4),
    credit_hold boolean,
    po_required boolean,
    aggregate_version bigint NOT NULL,
    synced_at timestamp without time zone NOT NULL
);

CREATE TABLE public.ext_customer (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    party_id uuid NOT NULL,
    status character varying(64) NOT NULL,
    display_name character varying(255),
    aggregate_version bigint NOT NULL,
    synced_at timestamp without time zone NOT NULL,
    party_type character varying(32),
    requirements_met boolean DEFAULT false NOT NULL
);

CREATE TABLE public.ext_estimate (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    estimate_id uuid NOT NULL,
    estimate_number character varying(64),
    status character varying(40),
    customer_id uuid,
    vehicle_id uuid,
    location_id uuid,
    aggregate_version bigint NOT NULL,
    synced_at timestamp without time zone NOT NULL
);

CREATE TABLE public.ext_estimate_line (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    item_id uuid NOT NULL,
    estimate_id uuid NOT NULL,
    item_type character varying(16),
    description character varying(512),
    quantity numeric(19,4),
    unit_price numeric(19,4),
    line_total numeric(19,4),
    product_id uuid,
    service_id uuid,
    approval_status character varying(32),
    deleted boolean
);

CREATE TABLE public.ext_inventory_availability (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    aggregate_id uuid NOT NULL,
    stock_item_id character varying(255) NOT NULL,
    location_id uuid,
    on_hand_quantity numeric(19,4) NOT NULL,
    allocated_quantity numeric(19,4) NOT NULL,
    available_to_promise_quantity numeric(19,4) NOT NULL,
    unit_of_measure character varying(32),
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.ext_location (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    location_id uuid NOT NULL,
    code character varying(64),
    name character varying(255),
    active boolean NOT NULL,
    address_line1 character varying(255),
    address_line2 character varying(255),
    city character varying(128),
    region character varying(64),
    postal_code character varying(32),
    country character varying(8),
    aggregate_version bigint NOT NULL,
    synced_at timestamp without time zone NOT NULL,
    financial_ancestor_ids text DEFAULT ''::text NOT NULL,
    other_ancestor_ids text DEFAULT ''::text NOT NULL
);

CREATE TABLE public.ext_location_parent (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    child_id uuid NOT NULL,
    parent_type character varying(64) NOT NULL,
    parent_id uuid NOT NULL
);

CREATE TABLE public.ext_product (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    product_id uuid NOT NULL,
    sku character varying(255),
    name character varying(500),
    active boolean NOT NULL,
    tracking_level character varying(32),
    aggregate_version bigint NOT NULL,
    synced_at timestamp without time zone NOT NULL,
    base_uom character varying(32)
);

CREATE TABLE public.ext_product_code (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    product_id uuid NOT NULL,
    code_type character varying(16),
    code character varying(64),
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.ext_product_uom (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    product_id uuid NOT NULL,
    uom_code character varying(32) NOT NULL,
    uom_type character varying(16),
    factor_to_base numeric(20,6) NOT NULL,
    precision_scale integer NOT NULL
);

CREATE TABLE public.ext_supplier_article_code (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    id uuid NOT NULL,
    supplier_ref character varying(100) NOT NULL,
    vendor_profile_id uuid NOT NULL,
    product_id uuid NOT NULL,
    supplier_article_code character varying(64) NOT NULL,
    aggregate_version bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.ext_vehicle (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    vehicle_id uuid NOT NULL,
    account_id uuid NOT NULL,
    active boolean NOT NULL,
    aggregate_version bigint NOT NULL,
    synced_at timestamp without time zone NOT NULL
);

CREATE TABLE public.ext_workorder (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    workorder_id uuid NOT NULL,
    workorder_number character varying(64),
    status character varying(40),
    customer_id uuid,
    vehicle_id uuid,
    shop_id uuid,
    invoice_id uuid,
    aggregate_version bigint NOT NULL,
    synced_at timestamp without time zone NOT NULL
);

CREATE TABLE public.ext_workorder_line (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    line_id uuid NOT NULL,
    workorder_id uuid NOT NULL,
    line_kind character varying(16) NOT NULL,
    product_id uuid,
    description character varying(512),
    quantity numeric(19,4),
    unit_price numeric(19,4),
    line_total numeric(19,4),
    declined boolean,
    returnable boolean
);

CREATE TABLE public.order_line_serial (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    order_line_id uuid NOT NULL,
    serial_index integer NOT NULL,
    serial_number character varying(128) NOT NULL
);

CREATE TABLE public.order_number_sequence (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    location_id uuid NOT NULL,
    period character varying(4) NOT NULL,
    next_value bigint NOT NULL
);

CREATE TABLE public.order_payment_record (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    payment_record_id uuid NOT NULL,
    order_id uuid NOT NULL,
    record_type character varying(16) NOT NULL,
    payment_intent_id uuid,
    refund_id uuid,
    method_type character varying(32) NOT NULL,
    amount numeric(19,4) NOT NULL,
    reference character varying(128),
    occurred_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone NOT NULL
);

CREATE TABLE public.order_status_history (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    history_id uuid NOT NULL,
    order_id uuid NOT NULL,
    from_status character varying(64),
    to_status character varying(64) NOT NULL,
    actor character varying(255) NOT NULL,
    reason character varying(500),
    transitioned_at timestamp without time zone NOT NULL
);

CREATE TABLE public.price_override (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    override_id uuid NOT NULL,
    order_id uuid NOT NULL,
    order_line_id uuid NOT NULL,
    product_id uuid NOT NULL,
    original_price numeric(19,4) NOT NULL,
    override_price numeric(19,4) NOT NULL,
    reason_code character varying(255) NOT NULL,
    justification character varying(2000),
    status character varying(255) NOT NULL,
    requested_by_user_id uuid NOT NULL,
    approved_by_user_id uuid,
    rejected_by_user_id uuid,
    rejection_reason character varying(1000),
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    updated_by character varying(255) NOT NULL,
    approved_at timestamp without time zone,
    rejected_at timestamp without time zone,
    applied_at timestamp without time zone,
    requires_approval boolean NOT NULL,
    affects_commission boolean DEFAULT false NOT NULL,
    idempotency_key character varying(128)
);

CREATE TABLE public.processed_events (
    event_id character varying(36) NOT NULL,
    tenant_id uuid,
    owner character varying(64) NOT NULL,
    processed_at timestamp without time zone NOT NULL
);

CREATE TABLE public.purchase_order (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    purchase_order_id uuid NOT NULL,
    po_number character varying(255) NOT NULL,
    vendor_id uuid NOT NULL,
    status character varying(255) NOT NULL,
    version_number integer NOT NULL,
    currency character varying(255) NOT NULL,
    subtotal_minor bigint NOT NULL,
    tax_minor bigint NOT NULL,
    grand_total_minor bigint NOT NULL,
    open_balance_minor bigint,
    ship_to_location_id uuid,
    payment_terms_id character varying(255),
    po_date date,
    expected_delivery_date date,
    requested_by character varying(255),
    comment character varying(255),
    approver_id character varying(255),
    approval_timestamp timestamp(6) with time zone,
    approval_notes character varying(255),
    created_by character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    supplier_ref character varying(100),
    transmission_state character varying(32) DEFAULT 'NOT_TRANSMITTED'::character varying NOT NULL,
    transmission_intent_id uuid,
    vendor_document_id character varying(255),
    supplier_order_number character varying(255),
    transmission_rejection_reason character varying(64),
    transmission_vendor_reason character varying(1024),
    transmission_requested_at timestamp(6) with time zone,
    transmission_observed_at timestamp(6) with time zone,
    transmission_count integer DEFAULT 0 NOT NULL,
    transmitted_version_number integer,
    CONSTRAINT purchase_order_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'APPROVED'::character varying, 'PARTIALLY_RECEIVED'::character varying, 'FULLY_RECEIVED'::character varying, 'CLOSED'::character varying, 'CANCELLED'::character varying])::text[])))
);

CREATE TABLE public.purchase_order_line (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    line_id uuid NOT NULL,
    purchase_order_id uuid NOT NULL,
    line_number integer NOT NULL,
    sku_id uuid,
    description character varying(255) NOT NULL,
    quantity_decimal numeric(18,6) NOT NULL,
    unit_cost_minor bigint NOT NULL,
    line_total_minor bigint NOT NULL,
    tax_minor bigint,
    tax_code_id character varying(255),
    gl_account_id character varying(255),
    open_quantity_decimal numeric(18,6),
    document_uom character varying(32),
    document_quantity numeric(18,6),
    conversion_factor numeric(20,6),
    created_at timestamp(6) with time zone NOT NULL
);

CREATE SEQUENCE public.purchase_order_number_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE public.purchase_order_transmission_event (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    event_id uuid NOT NULL,
    purchase_order_id uuid NOT NULL,
    transmission_intent_id uuid,
    event_type character varying(64) NOT NULL,
    status character varying(32),
    vendor_document_id character varying(255),
    supplier_order_number character varying(255),
    vendor_reason character varying(1024),
    despatch_date date,
    estimated_delivery_date date,
    observed_at timestamp(6) with time zone NOT NULL,
    recorded_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.register_session (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    session_id uuid NOT NULL,
    version bigint NOT NULL,
    terminal_id character varying(255) NOT NULL,
    location_id uuid,
    opened_by_clerk_id character varying(255) NOT NULL,
    status character varying(16) NOT NULL,
    opening_float numeric(19,4) NOT NULL,
    counted_cash numeric(19,4),
    theoretical_cash numeric(19,4),
    over_short numeric(19,4),
    variance_approved boolean DEFAULT false NOT NULL,
    variance_approved_by character varying(255),
    closed_by_clerk_id character varying(255),
    opened_at timestamp with time zone NOT NULL,
    closing_started_at timestamp with time zone,
    closed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.return_order (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    return_order_id uuid NOT NULL,
    version bigint NOT NULL,
    original_order_id uuid NOT NULL,
    original_order_number character varying(255),
    location_id uuid,
    customer_id uuid,
    original_invoice_id uuid,
    refund_method character varying(24) NOT NULL,
    status character varying(24) NOT NULL,
    reason_code character varying(64),
    total_refund numeric(19,4) NOT NULL,
    creation_idempotency_key character varying(128),
    approved_by_user_id uuid,
    approved_at timestamp with time zone,
    rejection_reason character varying(2000),
    failure_reason character varying(2000),
    returned_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    updated_by character varying(255) NOT NULL
);

CREATE TABLE public.return_order_line (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    return_line_id uuid NOT NULL,
    return_order_id uuid NOT NULL,
    original_order_line_id uuid NOT NULL,
    item_sku character varying(255) NOT NULL,
    return_qty integer NOT NULL,
    condition_code character varying(16) NOT NULL,
    line_refund numeric(19,4) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT chk_return_qty_positive CHECK ((return_qty > 0))
);

CREATE TABLE public.return_order_line_serial (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    return_line_id uuid NOT NULL,
    serial_index integer NOT NULL,
    serial_number character varying(128) NOT NULL
);

CREATE TABLE public.sales_order (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    order_id uuid NOT NULL,
    clerk_id character varying(255) NOT NULL,
    terminal_id character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    subtotal numeric(19,4) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    updated_by character varying(255) NOT NULL,
    cancellation_reason character varying(255),
    work_order_id uuid,
    cancellation_idempotency_key character varying(255),
    version bigint DEFAULT 0 NOT NULL,
    order_number character varying(64),
    location_id uuid,
    label character varying(255),
    creation_idempotency_key character varying(128),
    customer_id uuid,
    vehicle_id uuid,
    customer_validation_status character varying(32),
    discount_total numeric(19,4) DEFAULT 0 NOT NULL,
    tax_total numeric(19,4) DEFAULT 0 NOT NULL,
    grand_total numeric(19,4) DEFAULT 0 NOT NULL,
    tax_stale boolean DEFAULT false NOT NULL,
    general_note character varying(2000),
    order_discount_type character varying(16),
    order_discount_value numeric(19,4),
    order_discount_reason_code character varying(64),
    quote_expires_at timestamp without time zone,
    invoice_id uuid,
    invoice_number character varying(64),
    checkout_idempotency_key character varying(128),
    amount_paid numeric(19,4) DEFAULT 0 NOT NULL,
    balance_due numeric(19,4),
    session_id uuid,
    deposit_source_type character varying(16),
    deposit_source_id uuid
);

CREATE TABLE public.sales_order_line (
    tenant_id uuid DEFAULT public.app_current_tenant() NOT NULL,
    order_line_id uuid NOT NULL,
    order_id uuid NOT NULL,
    item_sku character varying(255) NOT NULL,
    item_description character varying(255) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(19,4) NOT NULL,
    fulfillment_status character varying(255) NOT NULL,
    price_source character varying(255) NOT NULL,
    reason_code character varying(255),
    source_type character varying(255),
    source_id character varying(255),
    source_line_id character varying(255),
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    client_line_uuid uuid,
    discount_percent numeric(5,2),
    discount_amount numeric(19,4) DEFAULT 0 NOT NULL,
    line_subtotal numeric(19,4) DEFAULT 0 NOT NULL,
    tax_amount numeric(19,4) DEFAULT 0 NOT NULL,
    line_total numeric(19,4) DEFAULT 0 NOT NULL,
    customer_note character varying(1000),
    internal_note character varying(1000),
    pricing_breakdown text,
    returnable boolean,
    reservation_id uuid,
    backorder_id uuid
);

ALTER TABLE ONLY public.approval_record
    ADD CONSTRAINT approval_record_pkey PRIMARY KEY (record_id);

ALTER TABLE ONLY public.approval_record
    ADD CONSTRAINT approval_record_tenant_key UNIQUE (tenant_id, record_id);

ALTER TABLE ONLY public.cash_movement
    ADD CONSTRAINT cash_movement_pkey PRIMARY KEY (movement_id);

ALTER TABLE ONLY public.cash_movement
    ADD CONSTRAINT cash_movement_tenant_key UNIQUE (tenant_id, movement_id);

ALTER TABLE ONLY public.event_outbox
    ADD CONSTRAINT event_outbox_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ext_billing_rules
    ADD CONSTRAINT ext_billing_rules_pkey PRIMARY KEY (party_id);

ALTER TABLE ONLY public.ext_billing_rules
    ADD CONSTRAINT ext_billing_rules_tenant_key UNIQUE (tenant_id, party_id);

ALTER TABLE ONLY public.ext_customer
    ADD CONSTRAINT ext_customer_pkey PRIMARY KEY (party_id);

ALTER TABLE ONLY public.ext_customer
    ADD CONSTRAINT ext_customer_tenant_key UNIQUE (tenant_id, party_id);

ALTER TABLE ONLY public.ext_estimate_line
    ADD CONSTRAINT ext_estimate_line_pkey PRIMARY KEY (item_id);

ALTER TABLE ONLY public.ext_estimate_line
    ADD CONSTRAINT ext_estimate_line_tenant_key UNIQUE (tenant_id, item_id);

ALTER TABLE ONLY public.ext_estimate
    ADD CONSTRAINT ext_estimate_pkey PRIMARY KEY (estimate_id);

ALTER TABLE ONLY public.ext_estimate
    ADD CONSTRAINT ext_estimate_tenant_key UNIQUE (tenant_id, estimate_id);

ALTER TABLE ONLY public.ext_inventory_availability
    ADD CONSTRAINT ext_inventory_availability_pkey PRIMARY KEY (aggregate_id);

ALTER TABLE ONLY public.ext_inventory_availability
    ADD CONSTRAINT ext_inventory_availability_tenant_key UNIQUE (tenant_id, aggregate_id);

ALTER TABLE ONLY public.ext_location_parent
    ADD CONSTRAINT ext_location_parent_pkey PRIMARY KEY (child_id, parent_type);

ALTER TABLE ONLY public.ext_location_parent
    ADD CONSTRAINT ext_location_parent_tenant_key UNIQUE (tenant_id, child_id, parent_type);

ALTER TABLE ONLY public.ext_location
    ADD CONSTRAINT ext_location_pkey PRIMARY KEY (location_id);

ALTER TABLE ONLY public.ext_location
    ADD CONSTRAINT ext_location_tenant_key UNIQUE (tenant_id, location_id);

ALTER TABLE ONLY public.ext_product_code
    ADD CONSTRAINT ext_product_code_pkey PRIMARY KEY (product_id);

ALTER TABLE ONLY public.ext_product_code
    ADD CONSTRAINT ext_product_code_tenant_key UNIQUE (tenant_id, product_id);

ALTER TABLE ONLY public.ext_product
    ADD CONSTRAINT ext_product_pkey PRIMARY KEY (product_id);

ALTER TABLE ONLY public.ext_product
    ADD CONSTRAINT ext_product_tenant_key UNIQUE (tenant_id, product_id);

ALTER TABLE ONLY public.ext_product_uom
    ADD CONSTRAINT ext_product_uom_pkey PRIMARY KEY (product_id, uom_code);

ALTER TABLE ONLY public.ext_product_uom
    ADD CONSTRAINT ext_product_uom_tenant_key UNIQUE (tenant_id, product_id, uom_code);

ALTER TABLE ONLY public.ext_vehicle
    ADD CONSTRAINT ext_vehicle_pkey PRIMARY KEY (vehicle_id);

ALTER TABLE ONLY public.ext_vehicle
    ADD CONSTRAINT ext_vehicle_tenant_key UNIQUE (tenant_id, vehicle_id);

ALTER TABLE ONLY public.ext_workorder_line
    ADD CONSTRAINT ext_workorder_line_pkey PRIMARY KEY (line_id);

ALTER TABLE ONLY public.ext_workorder_line
    ADD CONSTRAINT ext_workorder_line_tenant_key UNIQUE (tenant_id, line_id);

ALTER TABLE ONLY public.ext_workorder
    ADD CONSTRAINT ext_workorder_pkey PRIMARY KEY (workorder_id);

ALTER TABLE ONLY public.ext_workorder
    ADD CONSTRAINT ext_workorder_tenant_key UNIQUE (tenant_id, workorder_id);

ALTER TABLE ONLY public.order_line_serial
    ADD CONSTRAINT order_line_serial_pkey PRIMARY KEY (order_line_id, serial_index);

ALTER TABLE ONLY public.order_line_serial
    ADD CONSTRAINT order_line_serial_tenant_key UNIQUE (tenant_id, order_line_id, serial_index);

ALTER TABLE ONLY public.order_number_sequence
    ADD CONSTRAINT order_number_sequence_pkey PRIMARY KEY (location_id, period);

ALTER TABLE ONLY public.order_number_sequence
    ADD CONSTRAINT order_number_sequence_tenant_key UNIQUE (tenant_id, location_id, period);

ALTER TABLE ONLY public.order_payment_record
    ADD CONSTRAINT order_payment_record_pkey PRIMARY KEY (payment_record_id);

ALTER TABLE ONLY public.order_payment_record
    ADD CONSTRAINT order_payment_record_tenant_key UNIQUE (tenant_id, payment_record_id);

ALTER TABLE ONLY public.order_status_history
    ADD CONSTRAINT order_status_history_pkey PRIMARY KEY (history_id);

ALTER TABLE ONLY public.order_status_history
    ADD CONSTRAINT order_status_history_tenant_key UNIQUE (tenant_id, history_id);

ALTER TABLE ONLY public.ext_supplier_article_code
    ADD CONSTRAINT pk_ext_supplier_article_code PRIMARY KEY (id);

ALTER TABLE ONLY public.ext_supplier_article_code
    ADD CONSTRAINT ext_supplier_article_code_tenant_key UNIQUE (tenant_id, id);

ALTER TABLE ONLY public.price_override
    ADD CONSTRAINT price_override_pkey PRIMARY KEY (override_id);

ALTER TABLE ONLY public.price_override
    ADD CONSTRAINT price_override_tenant_key UNIQUE (tenant_id, override_id);

ALTER TABLE ONLY public.processed_events
    ADD CONSTRAINT processed_events_pkey PRIMARY KEY (event_id);

ALTER TABLE ONLY public.purchase_order_line
    ADD CONSTRAINT purchase_order_line_pkey PRIMARY KEY (line_id);

ALTER TABLE ONLY public.purchase_order_line
    ADD CONSTRAINT purchase_order_line_tenant_key UNIQUE (tenant_id, line_id);

ALTER TABLE ONLY public.purchase_order
    ADD CONSTRAINT purchase_order_pkey PRIMARY KEY (purchase_order_id);

ALTER TABLE ONLY public.purchase_order
    ADD CONSTRAINT purchase_order_tenant_key UNIQUE (tenant_id, purchase_order_id);

ALTER TABLE ONLY public.purchase_order
    ADD CONSTRAINT purchase_order_po_number_key UNIQUE (tenant_id, po_number);

ALTER TABLE ONLY public.purchase_order_transmission_event
    ADD CONSTRAINT purchase_order_transmission_event_pkey PRIMARY KEY (event_id);

ALTER TABLE ONLY public.purchase_order_transmission_event
    ADD CONSTRAINT purchase_order_transmission_event_tenant_key UNIQUE (tenant_id, event_id);

ALTER TABLE ONLY public.register_session
    ADD CONSTRAINT register_session_pkey PRIMARY KEY (session_id);

ALTER TABLE ONLY public.register_session
    ADD CONSTRAINT register_session_tenant_key UNIQUE (tenant_id, session_id);

ALTER TABLE ONLY public.return_order
    ADD CONSTRAINT return_order_creation_idempotency_key_key UNIQUE (tenant_id, creation_idempotency_key);

ALTER TABLE ONLY public.return_order_line
    ADD CONSTRAINT return_order_line_pkey PRIMARY KEY (return_line_id);

ALTER TABLE ONLY public.return_order_line
    ADD CONSTRAINT return_order_line_tenant_key UNIQUE (tenant_id, return_line_id);

ALTER TABLE ONLY public.return_order_line_serial
    ADD CONSTRAINT return_order_line_serial_pkey PRIMARY KEY (return_line_id, serial_index);

ALTER TABLE ONLY public.return_order_line_serial
    ADD CONSTRAINT return_order_line_serial_tenant_key UNIQUE (tenant_id, return_line_id, serial_index);

ALTER TABLE ONLY public.return_order
    ADD CONSTRAINT return_order_pkey PRIMARY KEY (return_order_id);

ALTER TABLE ONLY public.return_order
    ADD CONSTRAINT return_order_tenant_key UNIQUE (tenant_id, return_order_id);

ALTER TABLE ONLY public.sales_order_line
    ADD CONSTRAINT sales_order_line_pkey PRIMARY KEY (order_line_id);

ALTER TABLE ONLY public.sales_order_line
    ADD CONSTRAINT sales_order_line_tenant_key UNIQUE (tenant_id, order_line_id);

ALTER TABLE ONLY public.sales_order
    ADD CONSTRAINT sales_order_pkey PRIMARY KEY (order_id);

ALTER TABLE ONLY public.sales_order
    ADD CONSTRAINT sales_order_tenant_key UNIQUE (tenant_id, order_id);

ALTER TABLE ONLY public.ext_supplier_article_code
    ADD CONSTRAINT uk_ext_supplier_article_code_ref_product UNIQUE (tenant_id, supplier_ref, product_id);

ALTER TABLE ONLY public.price_override
    ADD CONSTRAINT uk_price_override_idempotency_key UNIQUE (tenant_id, idempotency_key);

CREATE INDEX idx_approval_record_price_override_id ON public.approval_record USING btree (price_override_id);

CREATE INDEX idx_event_outbox_unpublished ON public.event_outbox USING btree (published_at, id);

CREATE INDEX idx_ext_estimate_line_estimate ON public.ext_estimate_line USING btree (estimate_id);

CREATE UNIQUE INDEX idx_ext_inventory_availability_sku_location ON public.ext_inventory_availability USING btree (tenant_id, stock_item_id, location_id);

CREATE INDEX idx_ext_inventory_availability_updated_at ON public.ext_inventory_availability USING btree (updated_at DESC);

CREATE INDEX idx_ext_location_parent_parent ON public.ext_location_parent USING btree (parent_id, parent_type);

CREATE INDEX idx_ext_product_code_lookup ON public.ext_product_code USING btree (code_type, code);

CREATE INDEX idx_ext_product_sku ON public.ext_product USING btree (sku);

CREATE INDEX idx_ext_supplier_article_code_product ON public.ext_supplier_article_code USING btree (product_id);

CREATE INDEX idx_ext_vehicle_account ON public.ext_vehicle USING btree (account_id);

CREATE INDEX idx_ext_workorder_line_workorder ON public.ext_workorder_line USING btree (workorder_id);

CREATE INDEX idx_order_payment_record_intent ON public.order_payment_record USING btree (payment_intent_id);

CREATE INDEX idx_order_payment_record_order ON public.order_payment_record USING btree (order_id);

CREATE INDEX idx_order_status_history_order_id ON public.order_status_history USING btree (order_id);

CREATE INDEX idx_po_transmission_event_order ON public.purchase_order_transmission_event USING btree (purchase_order_id, observed_at);

CREATE INDEX idx_price_override_order_id ON public.price_override USING btree (order_id);

CREATE INDEX idx_price_override_order_line_id ON public.price_override USING btree (order_line_id);

CREATE INDEX idx_purchase_order_line_order ON public.purchase_order_line USING btree (purchase_order_id);

CREATE INDEX idx_purchase_order_line_sku ON public.purchase_order_line USING btree (sku_id);

CREATE INDEX idx_purchase_order_transmission_intent ON public.purchase_order USING btree (transmission_intent_id);

CREATE INDEX idx_purchase_order_vendor_status ON public.purchase_order USING btree (vendor_id, status);

CREATE INDEX idx_sales_order_clerk_status ON public.sales_order USING btree (clerk_id, status);

CREATE INDEX idx_sales_order_line_order_id ON public.sales_order_line USING btree (order_id);

CREATE INDEX idx_sales_order_terminal_status ON public.sales_order USING btree (terminal_id, status);

CREATE INDEX ix_cash_movement_session ON public.cash_movement USING btree (session_id);

CREATE INDEX ix_register_session_terminal ON public.register_session USING btree (terminal_id);

CREATE INDEX ix_return_line_order ON public.return_order_line USING btree (return_order_id);

CREATE INDEX ix_return_line_original ON public.return_order_line USING btree (original_order_line_id);

CREATE INDEX ix_return_order_original ON public.return_order USING btree (original_order_id);

CREATE INDEX ix_return_order_status ON public.return_order USING btree (status);

CREATE INDEX ix_sales_order_session ON public.sales_order USING btree (session_id);

CREATE UNIQUE INDEX uk_sales_order_creation_idem_key ON public.sales_order USING btree (tenant_id, creation_idempotency_key);

CREATE UNIQUE INDEX uk_sales_order_line_client_uuid ON public.sales_order_line USING btree (tenant_id, order_id, client_line_uuid);

CREATE UNIQUE INDEX uk_sales_order_order_number ON public.sales_order USING btree (tenant_id, order_number);

CREATE UNIQUE INDEX ux_register_session_one_active_per_terminal ON public.register_session USING btree (tenant_id, terminal_id) WHERE ((status)::text <> 'CLOSED'::text);

CREATE UNIQUE INDEX ux_sales_order_checkout_key ON public.sales_order USING btree (tenant_id, checkout_idempotency_key) WHERE (checkout_idempotency_key IS NOT NULL);

ALTER TABLE ONLY public.approval_record
    ADD CONSTRAINT fk_approval_record_price_override FOREIGN KEY (tenant_id, price_override_id) REFERENCES public.price_override(tenant_id, override_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.cash_movement
    ADD CONSTRAINT fk_cash_movement_session FOREIGN KEY (tenant_id, session_id) REFERENCES public.register_session(tenant_id, session_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.order_line_serial
    ADD CONSTRAINT fk_order_line_serial_line FOREIGN KEY (tenant_id, order_line_id) REFERENCES public.sales_order_line(tenant_id, order_line_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.order_status_history
    ADD CONSTRAINT fk_order_status_history_order FOREIGN KEY (tenant_id, order_id) REFERENCES public.sales_order(tenant_id, order_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.price_override
    ADD CONSTRAINT fk_price_override_order FOREIGN KEY (tenant_id, order_id) REFERENCES public.sales_order(tenant_id, order_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.price_override
    ADD CONSTRAINT fk_price_override_order_line FOREIGN KEY (tenant_id, order_line_id) REFERENCES public.sales_order_line(tenant_id, order_line_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.return_order_line
    ADD CONSTRAINT fk_return_line_order FOREIGN KEY (tenant_id, return_order_id) REFERENCES public.return_order(tenant_id, return_order_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.return_order_line_serial
    ADD CONSTRAINT fk_return_line_serial_line FOREIGN KEY (tenant_id, return_line_id) REFERENCES public.return_order_line(tenant_id, return_line_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.sales_order_line
    ADD CONSTRAINT fk_sales_order_line_order FOREIGN KEY (tenant_id, order_id) REFERENCES public.sales_order(tenant_id, order_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.purchase_order_line
    ADD CONSTRAINT purchase_order_line_purchase_order_id_fkey FOREIGN KEY (tenant_id, purchase_order_id) REFERENCES public.purchase_order(tenant_id, purchase_order_id);

ALTER TABLE ONLY public.purchase_order_transmission_event
    ADD CONSTRAINT purchase_order_transmission_event_purchase_order_id_fkey FOREIGN KEY (tenant_id, purchase_order_id) REFERENCES public.purchase_order(tenant_id, purchase_order_id);

CREATE INDEX approval_record_tenant_idx ON public.approval_record USING btree (tenant_id);

CREATE INDEX cash_movement_tenant_idx ON public.cash_movement USING btree (tenant_id);

CREATE INDEX ext_billing_rules_tenant_idx ON public.ext_billing_rules USING btree (tenant_id);

CREATE INDEX ext_customer_tenant_idx ON public.ext_customer USING btree (tenant_id);

CREATE INDEX ext_estimate_tenant_idx ON public.ext_estimate USING btree (tenant_id);

CREATE INDEX ext_estimate_line_tenant_idx ON public.ext_estimate_line USING btree (tenant_id);

CREATE INDEX ext_location_tenant_idx ON public.ext_location USING btree (tenant_id);

CREATE INDEX ext_location_parent_tenant_idx ON public.ext_location_parent USING btree (tenant_id);

CREATE INDEX ext_product_tenant_idx ON public.ext_product USING btree (tenant_id);

CREATE INDEX ext_product_code_tenant_idx ON public.ext_product_code USING btree (tenant_id);

CREATE INDEX ext_product_uom_tenant_idx ON public.ext_product_uom USING btree (tenant_id);

CREATE INDEX ext_supplier_article_code_tenant_idx ON public.ext_supplier_article_code USING btree (tenant_id);

CREATE INDEX ext_vehicle_tenant_idx ON public.ext_vehicle USING btree (tenant_id);

CREATE INDEX ext_workorder_tenant_idx ON public.ext_workorder USING btree (tenant_id);

CREATE INDEX ext_workorder_line_tenant_idx ON public.ext_workorder_line USING btree (tenant_id);

CREATE INDEX order_line_serial_tenant_idx ON public.order_line_serial USING btree (tenant_id);

CREATE INDEX order_number_sequence_tenant_idx ON public.order_number_sequence USING btree (tenant_id);

CREATE INDEX order_payment_record_tenant_idx ON public.order_payment_record USING btree (tenant_id);

CREATE INDEX order_status_history_tenant_idx ON public.order_status_history USING btree (tenant_id);

CREATE INDEX price_override_tenant_idx ON public.price_override USING btree (tenant_id);

CREATE INDEX purchase_order_tenant_idx ON public.purchase_order USING btree (tenant_id);

CREATE INDEX purchase_order_line_tenant_idx ON public.purchase_order_line USING btree (tenant_id);

CREATE INDEX purchase_order_transmission_event_tenant_idx ON public.purchase_order_transmission_event USING btree (tenant_id);

CREATE INDEX return_order_tenant_idx ON public.return_order USING btree (tenant_id);

CREATE INDEX return_order_line_tenant_idx ON public.return_order_line USING btree (tenant_id);

CREATE INDEX return_order_line_serial_tenant_idx ON public.return_order_line_serial USING btree (tenant_id);

ALTER TABLE public.approval_record ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.approval_record FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.approval_record
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.cash_movement ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cash_movement FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.cash_movement
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_billing_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_billing_rules FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_billing_rules
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_customer ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_customer FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_customer
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_estimate ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_estimate FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_estimate
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_estimate_line ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_estimate_line FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_estimate_line
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_inventory_availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_inventory_availability FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_inventory_availability
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_location ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_location FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_location
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_location_parent ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_location_parent FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_location_parent
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_product ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_product FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_product
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_product_code ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_product_code FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_product_code
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_product_uom ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_product_uom FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_product_uom
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_supplier_article_code ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_supplier_article_code FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_supplier_article_code
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_vehicle ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_vehicle FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_vehicle
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_workorder ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_workorder FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_workorder
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.ext_workorder_line ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ext_workorder_line FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ext_workorder_line
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.order_line_serial ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_line_serial FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.order_line_serial
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.order_number_sequence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_number_sequence FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.order_number_sequence
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.order_payment_record ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_payment_record FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.order_payment_record
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.order_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_status_history FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.order_status_history
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.price_override ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_override FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.price_override
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.purchase_order ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_order FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.purchase_order
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.purchase_order_line ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_order_line FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.purchase_order_line
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.purchase_order_transmission_event ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_order_transmission_event FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.purchase_order_transmission_event
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.register_session ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.register_session FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.register_session
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.return_order ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.return_order FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.return_order
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.return_order_line ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.return_order_line FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.return_order_line
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.return_order_line_serial ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.return_order_line_serial FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.return_order_line_serial
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.sales_order ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_order FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.sales_order
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());

ALTER TABLE public.sales_order_line ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_order_line FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.sales_order_line
    USING (tenant_id = public.app_current_tenant())
    WITH CHECK (tenant_id = public.app_current_tenant());
