package com.positivity.customer.internal.controller;

import com.positivity.bulkingest.AbstractBulkIngestController;
import com.positivity.bulkingest.BulkIngestRequest;
import com.positivity.bulkingest.BulkIngestResponse;
import com.positivity.bulkingest.BulkIngestResult;
import com.positivity.customer.internal.dto.CommercialBulkIngestRecord;
import com.positivity.customer.internal.dto.CreateCommercialAccountRequest;
import com.positivity.customer.internal.dto.CreatePartyRelationshipRequest;
import com.positivity.customer.internal.dto.CreatePersonRequest;
import com.positivity.customer.internal.enums.ContactPointType;
import com.positivity.customer.internal.enums.PartyRelationshipRole;
import com.positivity.customer.internal.enums.PreferredContactMethod;
import com.positivity.customer.internal.security.CrmPermissionRegistry;
import com.positivity.customer.service.PartyRelationshipService;
import com.positivity.customer.service.PartyService;
import com.positivity.customer.service.PersonService;
import com.positivity.events.EmitEvent;
import com.positivity.security.common.SecurityContextHelper;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import java.time.Clock;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.jspecify.annotations.NonNull;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.util.StringUtils;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@io.swagger.v3.oas.annotations.security.SecurityRequirement(
        name = "bearerAuth",
        scopes = {CrmPermissionRegistry.PARTY_CREATE})
@RequestMapping("/v1/customer/commercial")
@RequiredArgsConstructor
@Slf4j
@PreAuthorize("hasAuthority('" + CrmPermissionRegistry.PARTY_CREATE + "')")
@Tag(name = "Commercial Bulk Ingest API", description = "Bulk import commercial account records")
public class CommercialBulkIngestController extends AbstractBulkIngestController<CommercialBulkIngestRecord> {

    private final PartyService partyService;
    private final PersonService personService;
    private final PartyRelationshipService partyRelationshipService;
    private final Clock clock;

    @Override
    @io.swagger.v3.oas.annotations.Operation(
            operationId = "bulkIngestCommercialAccounts",
            summary = "Bulk Ingest Commercial Account Records",
            description = """
                        Imports a batch of commercial account records, creating each one through the same path as \
                        createCrmCommercialAccount and reporting a per-row success or failure result without aborting \
                        the batch.
                        Use this tool for migrations and file imports of commercial fleets; individual customers go \
                        through bulkIngestCustomers instead.
                        Preconditions: none beyond authorization; rows that fail are reported with errorCode \
                        COMMERCIAL_INGEST_FAILED while the rest of the batch proceeds.
                        Required inputs: jobId (UUID), locationId (UUID), and a non-empty records list where each \
                        record has legalName (max 255); displayName defaults to the legal name, and taxId and \
                        billingTermsId are optional; when contactFirstName and contactLastName are both present, a \
                        primary contact person is created (canonical identity lands in pos-people-contact, with \
                        contactEmail/contactPhone as its contact points) and attached with the PRIMARY_CONTACT role \
                        effective today.
                        Customer numbers are always generated by the service; supplied numbers cannot be preserved, \
                        and rows are not deduplicated, so re-running a batch creates duplicate accounts.
                        Account creation and contact attachment are separate transactions: a row whose contact step \
                        fails is reported as failed even though its account may already exist.
                        Emits a CUSTOMER_COMMERCIAL_BULK_INGEST event, and each successful row publishes a \
                        party-changed customer fact.
                        Returns 200 with per-row results including failures, and 400 when jobId, locationId, or the \
                        records list is missing or empty.
                        """)
    @PostMapping("/bulk-ingest")
    @PreAuthorize("hasAuthority('" + CrmPermissionRegistry.PARTY_CREATE + "')")
    @EmitEvent(id = "CUSTOMER_COMMERCIAL_BULK_INGEST", apiVersion = "1")
    public ResponseEntity<BulkIngestResponse> bulkIngest(
            @io.swagger.v3.oas.annotations.parameters.RequestBody(
                            description = "The ingest job envelope with the batch of commercial account records"
                                    + " to import.",
                            required = true,
                            content =
                                    @io.swagger.v3.oas.annotations.media.Content(
                                            mediaType = "application/json",
                                            examples =
                                                    @io.swagger.v3.oas.annotations.media.ExampleObject(
                                                            name = "Single-account batch with primary contact",
                                                            value = """
                                                        {"jobId":"018f0a1b-2c3d-7e4f-8a9b-0c1d2e3f4a70",
                                                         "locationId":"018f0a1b-2c3d-7e4f-8a9b-0c1d2e3f4a71",
                                                         "records":[
                                                           {"legalName":"Piedmont Freight Carriers LLC",
                                                            "displayName":"Piedmont Freight",
                                                            "taxId":"27-4481203",
                                                            "billingTermsId":"NET-30",
                                                            "contactFirstName":"Dale",
                                                            "contactLastName":"Whitfield",
                                                            "contactEmail":"dale@piedmont.example.com"}]}
                                                        """)))
                    @Valid
                    @RequestBody
                    @NonNull
                    BulkIngestRequest<CommercialBulkIngestRecord> request) {
        return super.bulkIngest(request);
    }

    @Override
    protected BulkIngestResponse processRecords(@NonNull BulkIngestRequest<CommercialBulkIngestRecord> request) {
        UUID userId = null;
        if (StringUtils.hasText(request.getOperatorId())) {
            try {
                userId = UUID.fromString(request.getOperatorId());
            } catch (IllegalArgumentException _) {
                log.warn(
                        "operatorId '{}' is not a valid UUID; falling back to security context",
                        request.getOperatorId());
            }
        }
        if (userId == null) {
            userId = SecurityContextHelper.getCurrentUserIdAsUuid().orElse(null);
        }

        List<BulkIngestResult> results = new ArrayList<>();
        int successCount = 0;
        int failureCount = 0;

        for (int i = 0; i < request.getRecords().size(); i++) {
            CommercialBulkIngestRecord ingestRecord = request.getRecords().get(i);
            try {
                var accountResponse = partyService.createCommercialAccount(toCreateAccountRequest(ingestRecord));
                UUID partyId = UUID.fromString(accountResponse.getPartyId());

                if (hasContact(ingestRecord)) {
                    attachPrimaryContact(partyId, ingestRecord, userId);
                }

                results.add(BulkIngestResult.builder()
                        .rowIndex(i)
                        .entityId(partyId)
                        .success(true)
                        .build());
                successCount++;
            } catch (Exception exception) {
                log.warn("Failed to ingest commercial record at row {}: {}", i, exception.getMessage(), exception);
                results.add(BulkIngestResult.builder()
                        .rowIndex(i)
                        .success(false)
                        .errorCode("COMMERCIAL_INGEST_FAILED")
                        .errorMessage(errorMessage(exception))
                        .build());
                failureCount++;
            }
        }

        return BulkIngestResponse.builder()
                .totalSubmitted(request.getRecords().size())
                .successCount(successCount)
                .failureCount(failureCount)
                .results(results)
                .build();
    }

    private CreateCommercialAccountRequest toCreateAccountRequest(@NonNull CommercialBulkIngestRecord ingestRecord) {
        // CommercialParty requires a displayName at flush; fall back to the legal
        // name so a name-only record does not fail on persist.
        String displayName = StringUtils.hasText(ingestRecord.getDisplayName())
                ? ingestRecord.getDisplayName()
                : ingestRecord.getLegalName();
        return CreateCommercialAccountRequest.builder()
                .legalName(ingestRecord.getLegalName())
                .displayName(displayName)
                .taxId(ingestRecord.getTaxId())
                .billingTermsId(ingestRecord.getBillingTermsId())
                .build();
    }

    private boolean hasContact(@NonNull CommercialBulkIngestRecord ingestRecord) {
        return StringUtils.hasText(ingestRecord.getContactFirstName())
                && StringUtils.hasText(ingestRecord.getContactLastName());
    }

    private void attachPrimaryContact(
            @NonNull UUID partyId, @NonNull CommercialBulkIngestRecord ingestRecord, UUID userId) {
        CreatePersonRequest createPersonRequest = new CreatePersonRequest();
        createPersonRequest.setFirstName(ingestRecord.getContactFirstName());
        createPersonRequest.setLastName(ingestRecord.getContactLastName());
        createPersonRequest.setPreferredContactMethod(
                StringUtils.hasText(ingestRecord.getContactEmail())
                        ? PreferredContactMethod.EMAIL
                        : PreferredContactMethod.PHONE_CALL);
        if (StringUtils.hasText(ingestRecord.getContactEmail())) {
            createPersonRequest.setEmails(List.of(CreatePersonRequest.EmailInput.builder()
                    .value(ingestRecord.getContactEmail())
                    .isPrimary(true)
                    .build()));
        }
        if (StringUtils.hasText(ingestRecord.getContactPhone())) {
            createPersonRequest.setPhones(List.of(CreatePersonRequest.PhoneInput.builder()
                    .value(ingestRecord.getContactPhone())
                    .type(ContactPointType.PHONE_MOBILE)
                    .isPrimary(true)
                    .build()));
        }

        var personResponse = personService.createPerson(createPersonRequest, userId);

        partyRelationshipService.createRelationship(
                partyId,
                CreatePartyRelationshipRequest.builder()
                        .personId(personResponse.getPersonId())
                        .roles(Set.of(PartyRelationshipRole.PRIMARY_CONTACT))
                        .effectiveStartDate(LocalDate.now(clock))
                        .build(),
                userId);
    }

    private String errorMessage(@NonNull Exception exception) {
        String message = exception.getMessage();
        return message == null || message.isBlank() ? "Commercial ingest failed" : message;
    }
}
