security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}

eureka:
  instance:
    appname: api-gateway
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

logging:
  level:
    com:
      netflix:
        discovery:
          shared:
            resolver:
              aws:
                ConfigClusterResolver: WARN
