#!/usr/bin/env bash
# Script to apply Story Authoring Agent updates to GitHub issues  
# Generated by Story Authoring Agent for clarification resolution
set -euo pipefail

REPO="louisburroughs/durion-positivity-backend"
ORIGIN_ISSUE="169"
CLAR_ISSUE="305"

echo "==================================="
echo "Story Authoring Agent Update Script"
echo "==================================="
echo ""
echo "Task: Integrate clarification responses from issue #${CLAR_ISSUE} into issue #${ORIGIN_ISSUE}"
echo ""

# Check if gh CLI is authenticated
if ! gh auth status >/dev/null 2>&1; then
    echo "ERROR: gh CLI is not authenticated."
    echo "Please run: gh auth login"
    exit 1
fi

echo "Step 1: Fetching current issue #${ORIGIN_ISSUE} body..."
TEMP_DIR="/tmp/story-work-${ORIGIN_ISSUE}"
mkdir -p "$TEMP_DIR"
CURRENT_BODY="${TEMP_DIR}/current.md"
UPDATED_BODY="${TEMP_DIR}/updated.md"

gh issue view "$ORIGIN_ISSUE" -R "$REPO" --json body -q .body > "$CURRENT_BODY"
echo "✓ Current issue body fetched"
echo ""

echo "Step 2: Checking if issue has Open Questions section..."
if grep -q "## Open Questions" "$CURRENT_BODY"; then
    echo "✓ Open Questions section found - will be removed"
    HAS_OPEN_QUESTIONS=true
else
    echo "⚠ No Open Questions section found"
    HAS_OPEN_QUESTIONS=false
fi
echo ""

echo "Step 3: Applying clarification updates..."
echo ""
echo "⚠️  MANUAL UPDATE REQUIRED ⚠️"
echo ""
echo "The current issue body has been saved to: $CURRENT_BODY"
echo ""
echo "Please manually apply the following changes to the story:"
echo ""
echo "1. Remove the 'STOP: Clarification required' line (if present)"
echo "2. Remove the 'Open Questions' section"
echo "3. Add Business Rules for:"
echo "   - BR-SNAPSHOT-1: Immutable Snapshot Requirement"
echo "   - BR-LEGAL-1: Legal Terms Policy Configuration"
echo "   - BR-LEGAL-2: Missing Legal Terms Handling"
echo "4. Update Functional Behavior to describe snapshot creation and policy enforcement"
echo "5. Add Data Requirements for:"
echo "   - EstimateSummarySnapshot"
echo "   - LegalTermsConfiguration"
echo "   - MissingLegalTermsPolicy"
echo "6. Add Acceptance Criteria:"
echo "   - AC-SNAPSHOT-1: Immutable Snapshot Created"
echo "   - AC-LEGAL-1: Legal Terms Included When Configured"
echo "   - AC-LEGAL-2: Policy Mode - FAIL"
echo "   - AC-LEGAL-3: Policy Mode - USE_DEFAULTS"
echo "   - AC-LEGAL-4: Policy Configuration"
echo "   - AC-LEGAL-5: Audit Trail Captured"
echo "7. Update Audit & Observability section"
echo ""
echo "Refer to: .story-work/issue-169-update-summary.md for detailed content"
echo ""
echo "After manual updates, save the result to: $UPDATED_BODY"
echo ""
read -p "Press Enter when you have completed the manual updates..."

if [ ! -f "$UPDATED_BODY" ]; then
    echo "ERROR: Updated issue body not found at: $UPDATED_BODY"
    echo "Please save your updated content there and run this script again."
    exit 1
fi

echo ""
echo "Step 4: Updating issue #${ORIGIN_ISSUE} body..."
gh issue edit "$ORIGIN_ISSUE" -R "$REPO" --body-file "$UPDATED_BODY"
echo "✓ Issue body updated"
echo ""

echo "Step 5: Updating labels on issue #${ORIGIN_ISSUE}..."
# Remove blocking label
gh issue edit "$ORIGIN_ISSUE" -R "$REPO" \
    --remove-label "blocked:clarification" || true

# Add needs-review label  
gh issue edit "$ORIGIN_ISSUE" -R "$REPO" \
    --add-label "status:needs-review"
echo "✓ Labels updated"
echo ""

echo "Step 6: Adding resolution comment to issue #${ORIGIN_ISSUE}..."
gh issue comment "$ORIGIN_ISSUE" -R "$REPO" --body "## Clarification Resolution Complete

All clarification questions from issue #${CLAR_ISSUE} have been reviewed and integrated into this story.

### Decision Integrated:
**Missing Terms & Conditions Policy**: Use immutable snapshots; if legal terms are missing, handle gracefully per configurable policy (fail or use defaults) with clear documentation.

### Story Updates:
- Business Rule added: Immutable Snapshot Requirement (BR-SNAPSHOT-1)
- Business Rule added: Legal Terms Policy Configuration (BR-LEGAL-1)
- Business Rule added: Missing Legal Terms Handling (BR-LEGAL-2)
- Functional Behavior updated to specify snapshot creation and policy enforcement
- Data Requirements extended with EstimateSummarySnapshot, LegalTermsConfiguration, and MissingLegalTermsPolicy entities
- Acceptance Criteria added for snapshot creation, legal terms handling, and policy configuration (AC-SNAPSHOT-1, AC-LEGAL-1 through AC-LEGAL-5)
- Audit & Observability updated for snapshot and policy events

**Status**: Ready for domain agent review and development planning.

---
*Updated by Story Authoring Agent - $(date -u +'%Y-%m-%dT%H:%M:%SZ')*"
echo "✓ Comment added"
echo ""

echo "Step 7: Closing clarification issue #${CLAR_ISSUE}..."
gh issue close "$CLAR_ISSUE" -R "$REPO" --reason completed --comment "## Clarification Complete

Clarification has been provided and successfully integrated into the origin story (issue #${ORIGIN_ISSUE}).

The Story Authoring Agent has updated the origin story with:
- Immutable snapshot requirement for estimate summaries
- Configurable policy for handling missing legal terms (FAIL or USE_DEFAULTS)
- Comprehensive data model for snapshots, legal terms configuration, and policy management
- Complete acceptance criteria covering all policy scenarios
- Audit trail requirements for compliance and traceability

The origin story is now unblocked and ready for review.

---
*Closed by Story Authoring Agent - $(date -u +'%Y-%m-%dT%H:%M:%SZ')*"
echo "✓ Clarification issue closed"
echo ""

echo "==================================="
echo "✓ All updates applied successfully"
echo "==================================="
echo ""
echo "Summary:"
echo "  - Issue #${ORIGIN_ISSUE}: Updated body, labels changed to status:needs-review"
echo "  - Issue #${CLAR_ISSUE}: Closed as completed"
echo ""
echo "Next steps:"
echo "  1. Domain agents should review the updated story"
echo "  2. If approved, change label to status:ready-for-dev"
echo "  3. Begin development implementation"
