#!/usr/bin/env bash
# Script to apply Story Authoring Agent updates to GitHub issues
# Generated by Story Authoring Agent for clarification resolution
set -euo pipefail

REPO="louisburroughs/durion-positivity-backend"
ORIGIN_ISSUE="194"
CLAR_ISSUE="326"

echo "==================================="
echo "Story Authoring Agent Update Script"
echo "==================================="
echo ""
echo "Task: Integrate clarification responses from issue #${CLAR_ISSUE} into issue #${ORIGIN_ISSUE}"
echo ""

# Check if gh CLI is authenticated
if ! gh auth status >/dev/null 2>&1; then
    echo "ERROR: gh CLI is not authenticated."
    echo "Please run: gh auth login"
    exit 1
fi

# Verify the updated issue body file exists
AFTER_FILE=".story-work/work/${ORIGIN_ISSUE}/after.md"
if [ ! -f "$AFTER_FILE" ]; then
    echo "ERROR: Updated issue body not found at: $AFTER_FILE"
    exit 1
fi

echo "Step 1: Updating issue #${ORIGIN_ISSUE} body..."
gh issue edit "$ORIGIN_ISSUE" -R "$REPO" --body-file "$AFTER_FILE"
echo "✓ Issue body updated"
echo ""

echo "Step 2: Updating labels on issue #${ORIGIN_ISSUE}..."
# Remove blocking and draft labels
gh issue edit "$ORIGIN_ISSUE" -R "$REPO" \
    --remove-label "blocked:clarification" \
    --remove-label "status:draft" \
    --remove-label "risk:financial-inference" || true

# Add needs-review label
gh issue edit "$ORIGIN_ISSUE" -R "$REPO" \
    --add-label "status:needs-review"
echo "✓ Labels updated"
echo ""

echo "Step 3: Adding resolution comment to issue #${ORIGIN_ISSUE}..."
gh issue comment "$ORIGIN_ISSUE" -R "$REPO" --body "## Clarification Resolution Complete

All clarification questions from issue #${CLAR_ISSUE} have been reviewed and integrated into this story.

### Decisions Integrated:
1. **Inter-Domain Contract**: Product validation via replicated cache with synchronous fallback (24hr TTL default)
2. **Product Lifecycle Handling**: Configurable behavior (default: flag for manual review)
3. **Historical Data Policy**: Read-only with controlled correction mechanisms (superseding records, prospective adjustments, or exceptional overrides with full audit trail)
4. **Timezone Handling**: Configurable timezone interpretation (default: store local time)

### Story Updates:
- Business Rules BR3-BR9 added with all clarified policies
- Data schema extended (supersededMsrpId, correctionReasonCode, productDiscontinued fields)
- New MSRPAuditLog entity for full audit trail
- Acceptance Criteria AC6-AC10 added for historical corrections, cache behavior, product discontinuation, and timezone handling
- Configuration Requirements table added

**Status**: Ready for domain agent review and development planning.

---
*Updated by Story Authoring Agent - $(date -u +'%Y-%m-%dT%H:%M:%SZ')*"
echo "✓ Comment added"
echo ""

echo "Step 4: Closing clarification issue #${CLAR_ISSUE}..."
gh issue close "$CLAR_ISSUE" -R "$REPO" --reason completed --comment "## Clarification Complete

All clarifications have been provided and successfully integrated into the origin story (issue #${ORIGIN_ISSUE}).

The Story Authoring Agent has updated the origin story with:
- Resolved inter-domain contracts
- Clarified product lifecycle handling
- Comprehensive historical data policy with audit requirements
- Timezone configuration options

The origin story is now unblocked and ready for review.

---
*Closed by Story Authoring Agent - $(date -u +'%Y-%m-%dT%H:%M:%SZ')*"
echo "✓ Clarification issue closed"
echo ""

echo "==================================="
echo "✓ All updates applied successfully"
echo "==================================="
echo ""
echo "Summary:"
echo "  - Issue #${ORIGIN_ISSUE}: Updated body, labels changed to status:needs-review"
echo "  - Issue #${CLAR_ISSUE}: Closed as completed"
echo ""
echo "Next steps:"
echo "  1. Domain agents should review the updated story"
echo "  2. If approved, change label to status:ready-for-dev"
echo "  3. Begin development implementation"
